### ISSUE TITLE
onedrive Failed to query available drives: HTTP error 401 (401 Unauthorized)

### ISSUE THREAD

**Issue by Jayjjjjj** [ncw/rclone#2861] opened 2018-12-23 10:15 UTC
#### What is the problem you are having with rclone?
While I copied token from cmd,it shows

>  Failed to query available drives: HTTP error 401 (401 Unauthorized) returned body: "{\r\n  \"error\": {\r\n    \"code\": \"InvalidAuthenticationToken\",\r\n    \"message\": \"Access token validation failure.\",\r\n    \"innerError\": {\r\n      \"request-id\": \"08d8d81a-1ee8-4618-ac75-eddecca234b5\",\r\n      \"date\": \"2018-12-23T09:54:32\"\r\n    }\r\n  }\r\n}"

But i could successfully add onedrive on 
Windows 7,64bit
rclone v1.41
- os/arch: windows/amd64
- go version: go1.10.
I tried to change the account on microsoft,but it still occurs.

#### What is your rclone version (output from `rclone version`)
rclone v1.45-039-g5babf2dc-beta
- os/arch: linux/amd64
- go version: go1.11.4
#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
CentOS7.6,64bit
####  Which cloud storage system are you using? (eg Google Drive)
OneDrive
#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone config

**Comment by ncw** [comment] 2018-12-26 16:44
Have you tried copying the config file from the Windows box?  Find out where it is with `rclone config file` then copy it to the remote machine and try that?

I suspect something went wrong with the cut and paste.  The onedrive tokens are very long and overflow paste buffers on macOS at least.

**Comment by Jayjjjjj** [comment] 2018-12-27 12:13
I have tried to copy it from windows which can successfully add onedrive,but it still occurs.
I use putty 0.70 64bit on windows.I noticed that some /r/n is in the pasted tokens,so i use np++ to replace all of them with ''. It didnt change anything.

**Comment by Jayjjjjj** [comment] 2018-12-27 12:13
> Have you tried copying the config file from the Windows box? Find out where it is with `rclone config file` then copy it to the remote machine and try that?
> 
> I suspect something went wrong with the cut and paste. The onedrive tokens are very long and overflow paste buffers on macOS at least.

I have tried to copy it from windows which can successfully add onedrive,but it still occurs.
I use putty 0.70 64bit on windows.I noticed that some /r/n is in the pasted tokens,so i use np++ to replace all of them with ''. It didnt change anything.

**Comment by Jayjjjjj** [comment] 2018-12-27 12:16
It is in C:\Users\Jay\.config\rclone
I use WIN7.

**Comment by guoxiangke** [comment] 2019-01-25 23:11
ubuntu@VM-0-6-ubuntu:~/rclone-v1.45-linux-amd64$ rclone version
rclone v1.45
- os/arch: linux/amd64
- go version: go1.11.2

when I copy onedrive token from my local mac to remote server.
same 401 error, I tried copy local config to remote
&it's need refresh, also need copy token , then the same error .

**Comment by cmfarias** [comment] 2019-02-11 20:50
Use auto config?
 * Say Y if not sure
 * Say N if you are working on a remote or headless machine
y) Yes
n) No
y/n> n
For this to work, you will need rclone available on a machine that has a web browser available.
Execute the following on your machine:
	rclone authorize "onedrive"

Be sure both version of rclone are the same on both machines, the source where rclone without web browser is, and the later wich has a web browser  autorize rclone!!!

I have this early and not post a comment before, sorry about that.

I my case I run with this two different rclone versions:

Machine with no web browser, only rclone app:

rclone v1.46
- os/arch: linux/amd64
- go version: go1.11.5

Machine with web browser to authorize rclone:

rclone v1.43.1
- os/arch: linux/amd64
- go version: go1.11

As You can also notice, machine with web browser authorize rclone give us a token, then back in the former and paste it, gives us that error!!!

Please let me know if I'm wrong!

Thanks in advance...

cmf.

**Comment by ncw** [comment] 2019-02-12 12:38
We switched over to using the graph API in v1.44 so the tokens will be incompatible between v1.43.1 and v1.46.  I think this explains the issue probably.

So you need the same version of rclone in each place.

**Comment by Cnly** [comment] 2019-03-13 10:56
I'm closing this for now as this issue seems to have been caused by inconsistent versions of rclone used in different places. Please feel free to re-open if you have another opinion. :)

**Closed by Cnly** 2019-03-13 10:56 UTC
Labels: Remote: One Drive
