### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by microbug** [ncw/rclone#960] opened 2016-12-17 21:02 UTC
A scheduler for the bandwidth limit would be great. Example: when doing large uploads on my home internet connection with limited bandwidth, I'd like to use all the bandwidth in the middle of the night and less the rest of the time.

**Comment by ncw** [comment] 2016-12-21 20:14
I think this is a duplicate of #221 - can you add your support to that issue please.

You can also use SIGUSR2 to turn the bwlimit on and off in the mean time.

**Closed by ncw** 2016-12-21 20:14 UTC
Labels: duplicate
