### ISSUE TITLE
[BUG] onedrive not accepting spaces on folder names.

### ISSUE THREAD

**Issue by chmercesmoreira** [ncw/rclone#1296] opened 2017-03-29 22:26 UTC
> What is your rclone version (eg output from `rclone -V`)
`rclone v1.36`
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
`Linux carlos-pc 4.10.6-1-MANJARO #1 SMP PREEMPT Sun Mar 26 19:17:24 UTC 2017 x86_64 GNU/Linux`
> Which cloud storage system are you using? (eg Google Drive)
`OneDrive`
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
This bug is reproducible using any command that contain one folder with spaces, example:
```
$ rclone lsd onedrive:'/Plex/TV Shows/'
2017/03/28 16:55:37 directory not found
```
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
$ rclone lsd onedrive:'/Plex/TV Shows/' -vv
2017/03/29 19:24:46 DEBUG : rclone: Version "v1.36" starting with parameters ["rclone" "lsd" "onedrive:/Plex/TV Shows/" "-vv"]
2017/03/29 19:24:48 INFO  : One drive root 'Plex/TV Shows': Modify window is 1s
2017/03/29 19:24:48 directory not found
```
And to prove that this folder actually exists:
```
$ rclone lsd onedrive:'/Plex/' -vv
2017/03/29 19:25:32 DEBUG : rclone: Version "v1.36" starting with parameters ["rclone" "lsd" "onedrive:/Plex/" "-vv"]
2017/03/29 19:25:34 INFO  : One drive root 'Plex': Modify window is 1s
2017/03/29 19:25:34 DEBUG : One drive root 'Plex': Reading ""
2017/03/29 19:25:34 DEBUG : One drive root 'Plex': Finished reading ""
          -1 2017-03-27 23:17:06         2 Animes
          -1 2017-03-28 03:27:48         7 Movies 2D
          -1 2017-03-28 03:27:48         2 Movies 3D
          -1 2017-03-26 18:36:43         3 TV Shows
2017/03/29 19:25:34 DEBUG : Go routines at exit 6
2017/03/29 19:25:34 DEBUG : rclone: Version "v1.36" finishing with parameters ["rclone" "lsd" "onedrive:/Plex/" "-vv"]
```

More informations about this bug:
https://forum.rclone.org/t/directory-not-found-even-though-it-exists
https://forum.rclone.org/t/oddity-with-one-drive-and-spaces-in-folder-names

**Comment by ncw** [comment] 2017-03-30 09:52
I haven't quite managed to replicate your exact problem, but there is clearly something weird going on!

```
$ rclone copy -v Dir onedrive:Dir
2017/03/30 10:40:36 INFO  : One drive root 'Dir': Modify window is 1s
2017/03/30 10:40:36 INFO  : One drive root 'Dir': Waiting for checks to finish
2017/03/30 10:40:36 INFO  : One drive root 'Dir': Waiting for transfers to finish
2017/03/30 10:40:37 INFO  : Sub Dir/test.txt: Copied (new)
2017/03/30 10:40:37 INFO  : 
Transferred:      6 Bytes (3 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            1
Elapsed time:        1.9s
$ rclone lsd onedrive:'/Dir/'
          -1 2017-03-30 09:40:38         0 Sub Dir
          -1 2017-03-30 09:40:39         1 Sub+Dir
```

If I run the integration tests they fail with lots of errors like this

```
	            	expected: []string{"file name.txt"}
	            	received: []string{"file+name.txt"}
```

So this indicates that something has changed at OneDrive, since I ran the integration tests for the 1.36 release and they worked fine then.

Needs more investigation!

 @yonjah - have you got time to look at this?

**Comment by yonjah** [comment] 2017-03-30 11:23
I'm looking at it now

**Comment by yonjah** [comment] 2017-03-30 14:42
OK I think i figured it out.
But it is really weird the only reason for this happening now is onedrive changing their api.
Unless the old code base used an old go version but I also tested this issue with old version of rclone (1.35) and I can reproduce this issue.

It seems like all the escape methods for path are using `net/url` `QueryEscape` instead of `PathEscape`
`QueryEscape` escapes spaces as '+' which onedirve interprets as literal '+' path escape is escaping them as '%20' which seems to be working fine.

Unfortunately  `PathEscape` is only available in go 1.8
I'll submit a pull request with the changes to onedrive but this will not work without go 1.8 and I assume before upgrading go full integration tests needs to be done on all remotes which is probably somehting that someone with more experience in the code base should be doing

**Comment by ncw** [comment] 2017-03-30 16:35
@yonjah excellent work finding the problem :-)

go1.8 is not a problem - rclone builds with go1.8 normally.  However I'm trying to keep it working with pre go1.8 too.

What we need for this is a backported PathEscape for pre go1.8.  It is possible get the equivalent of path escape with a bit of trickery using a url.URL I think...  Something like this: https://play.golang.org/p/IPYL2oINdD would be a backwards compatible way of doing it.

**Comment by yonjah** [comment] 2017-03-31 03:23
OK I'll try and see if I can do the changes this weekend

**Comment by yonjah** [comment] 2017-03-31 06:59
On a side note - https://github.com/OneDrive/onedrive-api-docs/issues/555 deployed two days ago :speak_no_evil:

**Comment by ncw** [comment] 2017-03-31 12:21
@yonjah that is surely related - well spotted!

**Comment by yonjah** [comment] 2017-03-31 16:18
I made the changes so it wont use 1.8 api.
But when I run the integration tests one test fails for taking too long.
I tried running the test without the changes and I'm getting the same failure.
I'm not sure if this is something else that changed with OneDrive or just something specific
to my machine.

**Comment by aas2234** [comment] 2017-04-06 02:42
I am having the same issue since last week as well. When can we expect a fix? This is effectively doubling up my space requirement for the backup on onedrive making rclone pretty much unusable.

**Comment by yonjah** [comment] 2017-04-06 02:57
@aas2234 This has been fixed in the referenced pull request -
https://github.com/ncw/rclone/issues/1299

ncw has been a bit less active than usual this month so I'm not sure when he'll have the time to check it properly. but it might take a bit longer for the merge to happen.

if you think its worth it you can pull the changes and build rclone locally (I've been running the fixed version for a few days now and didn't notice any issues) but it still not fully tested so you might prefer to wait for the next release.

**Comment by chmercesmoreira** [comment] 2017-04-06 03:44
@yonjah 
Hey yonjah, what are the steps to build rclone with your changes?
I have already cloned the repo and applied your pull request locally, what should I do now?
Obs: I have already configured the GOPATH.

**Comment by yonjah** [comment] 2017-04-06 03:52
@chmercesmoreira  if you followed the instructions here to setup your development environment - 
https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md
in `rclone` repo main folder you can run -
`go run rclone.go --help`
and see if it works.
You can also run any other `rclone` command the same way. their will be a small delay to run the build but it is not very noticeable.
You can also run a proper build by running `go build` in the same path which will create the `rclone` binary on the same path

**Comment by chmercesmoreira** [comment] 2017-04-06 03:56
Have you created a particular fork with this change already? If so, please can you give me the link so that I can build it the easy way. (I'm not a git/go expert). Anyway, if you can't do it I will wait for the next official update of rclone.

**Comment by yonjah** [comment] 2017-04-06 04:00
@chmercesmoreira in that case it might be better to wait.

**Comment by chmercesmoreira** [comment] 2017-04-06 04:01
@yonjah 
No problem, thank you anyway.

**Comment by ncw** [comment] 2017-04-10 14:23
Sorry have been away - back now!  Will merge the PR soon and post a beta here for you all to try.

**Closed** 2017-04-10 14:50 UTC
Labels: bug, Remote: One Drive

**Comment by ncw** [comment] 2017-04-10 14:51
Please find the beta with this fix in here

https://beta.rclone.org/v1.36-21-ge3a4132/ (uploaded in 15-30 mins)

**Comment by aas2234** [comment] 2017-04-11 00:53
Thanks! Will give it a go :)

**Comment by aas2234** [comment] 2017-04-11 06:41
@ncw : The fix works fine, thanks for the quick turnaround!

**Comment by traynier** [comment] 2017-04-11 09:12
Thanks, working for me! You might want to consider an official release of 1.36.1, as looking at the milestones I guess 1.37 is a while away, and onedrive is effectively broken without this fix.

**Comment by ncw** [comment] 2017-04-11 10:08
Thanks for testing.

@traynier thanks for the suggestion - I will mull it over...

**Comment by aas2234** [comment] 2017-04-14 03:55
Thanks @ncw. I do agree that a minor release with this fix would be great!

**Comment by thettenhausen** [comment] 2017-09-07 20:18
I am having a related issue:

```
$ rclone lsd "onedrive:/Videos/TV Shows/Game Of Thrones/"
          -1 2017-05-02 00:45:22        11 Season 1
          -1 2017-05-02 00:52:29         2 Season 2
          -1 2017-05-02 02:12:42        10 Season 3
          -1 2017-05-02 06:21:47        20 Season 4
          -1 2017-09-07 18:44:46        15 Season 5
          -1 2017-09-07 18:44:41        11 Season 6
          -1 2017-08-28 10:16:39        11 Season 7
```

That looks fine, no problem with any of the space so far. This next one though fails (and yes, there are files in there):
`
$ rclone lsd "onedrive:/Videos/TV Shows/Game Of Thrones/Season 5"`

Since you did it above for a similar case I tried -vv as well:

```
$ rclone lsd "onedrive:/Videos/TV Shows/Game Of Thrones/Season 5" -vv
2017/09/07 16:09:52 DEBUG : rclone: Version "v1.37" starting with parameters ["rclone" "lsd" "onedrive:/Videos/TV Shows/Game Of Thrones/Season 5" "-vv"]
2017/09/07 16:09:53 INFO  : One drive root 'Videos/TV Shows/Game Of Thrones/Season 5': Modify window is 1s
2017/09/07 16:09:53 DEBUG : Go routines at exit 5
2017/09/07 16:09:53 DEBUG : rclone: Version "v1.37" finishing with parameters ["rclone" "lsd" "onedrive:/Videos/TV Shows/Game Of Thrones/Season 5" "-vv"]
```

Anything else I can try?

**Comment by yonjah** [comment] 2017-09-08 01:00
@thettenhausen if your looking for files listed under the directory you should use `ls` and not `lsd`
try running your second listing with `rclone ls`

**Comment by thettenhausen** [comment] 2017-09-08 08:46
@yonjah Oh my... it seems it was too late at night. You are right. I obviously was confused and found this thread and thought it applied. Sorry.
