### ISSUE TITLE
Fails when file is blocked by Google Drive as malware, despite downloading it

### ISSUE THREAD

**Issue by Fabian42** [ncw/rclone#2338] opened 2018-06-04 21:34 UTC
#### What is the problem you are having with rclone?
When having a file that Google Drive claims to be malware on Google Drive, it sometimes can be downloaded, sometimes not. But rclone gives a negative console output and feedback to programs in both cases.

Link to the RCloneSync issue (closed, because it's really an RClone issue): https://github.com/cjnaz/RCloneSync/issues/19#issuecomment-394171221
There you can also find a link to the underlying Google Drive bug report, but since I would not expect it to be fixed soon, also it can happen again at any time, so RClone should work around it.
On the Google Drive bug report, you can find download links for the two affected files.

#### What is your rclone version (eg output from `rclone -V`)
rclone v1.41-076-g2b332bceβ
- os/arch: linux/amd64
- go version: go1.10.1

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Debian, 64bit

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone sync drive: /home/fabian/drive`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
Too long to be included completely. But the important parts are in the log without `-vv` anyway:
```2018/06/04 20:51:32 ERROR : programs/titanium/de.robv.android.xposed.installer-de4f0dc569f96dbcc5668d40fa76040b.apk.bz2: Failed to copy: failed to open source object: open file failed: googleapi: Error 403: This file has been identified as malware or spam and cannot be downloaded., cannotDownloadAbusiveFile
2018/06/04 20:53:21 ERROR : Local file system at /home/fabian/drive: not deleting files as there were IO errors
2018/06/04 20:53:21 ERROR : Local file system at /home/fabian/drive: not deleting directories as there were IO errors
2018/06/04 20:53:21 ERROR : Attempt 1/3 failed with 1 errors and: failed to open source object: open file failed: googleapi: Error 403: This file has been identified as malware or spam and cannot be downloaded., cannotDownloadAbusiveFile
2018/06/04 20:53:30 ERROR : programs/titanium/de.robv.android.xposed.installer-de4f0dc569f96dbcc5668d40fa76040b.apk.bz2: Failed to copy: failed to open source object: open file failed: googleapi: Error 403: This file has been identified as malware or spam and cannot be downloaded., cannotDownloadAbusiveFile
2018/06/04 20:55:00 ERROR : Local file system at /home/fabian/drive: not deleting files as there were IO errors
2018/06/04 20:55:00 ERROR : Local file system at /home/fabian/drive: not deleting directories as there were IO errors
2018/06/04 20:55:00 ERROR : Attempt 2/3 failed with 1 errors and: failed to open source object: open file failed: googleapi: Error 403: This file has been identified as malware or spam and cannot be downloaded., cannotDownloadAbusiveFile
2018/06/04 20:55:07 ERROR : programs/titanium/de.robv.android.xposed.installer-de4f0dc569f96dbcc5668d40fa76040b.apk.bz2: Failed to copy: failed to open source object: open file failed: googleapi: Error 403: This file has been identified as malware or spam and cannot be downloaded., cannotDownloadAbusiveFile
2018/06/04 20:56:30 ERROR : Local file system at /home/fabian/drive: not deleting files as there were IO errors
2018/06/04 20:56:30 ERROR : Local file system at /home/fabian/drive: not deleting directories as there were IO errors
2018/06/04 20:56:30 ERROR : Attempt 3/3 failed with 1 errors and: failed to open source object: open file failed: googleapi: Error 403: This file has been identified as malware or spam and cannot be downloaded., cannotDownloadAbusiveFile
2018/06/04 20:56:30 Failed to sync: failed to open source object: open file failed: googleapi: Error 403: This file has been identified as malware or spam and cannot be downloaded., cannotDownloadAbusiveFile```

**Comment by ncw** [comment] 2018-06-05 08:37
What we did with Dropbox which has a similar problem is if we detect this sort of error we wrap it in a  `fserrors.NoRetryError(err)` which will mean that rclone won't treat this as a reason to retry the sync.

Here is the relevant dropbox code:

https://github.com/ncw/rclone/blob/ba43acb6aa703ed64b4c9671b36d31354bbd9f5b/backend/dropbox/dropbox.go#L859-L876

This could be adapted to the equivalent place in the drive backend

https://github.com/ncw/rclone/blob/ba43acb6aa703ed64b4c9671b36d31354bbd9f5b/backend/drive/drive.go#L1528-L1559

This would mean type asserting the error to a `googleapi.Error` in the if clause at line 1556 and looking for the cause.

Fancy having a go?

**Comment by ncw** [comment] 2018-06-05 08:45
Actually maybe it would be better to do #2317 which has a solution for downloading the files without generating the error?

BTW are you saying that the file is downloaded correctly even though there is an error? I would have thought rclone would abort when it got the error.

**Comment by Fabian42** [comment] 2018-06-05 08:58
It seems to do it sometimes. I haven't tested too much and most of the
tests I did were with RCloneSync, which does more than just a simple copy,
so I'm not too sure. I can try a few times more today.

**Comment by Fabian42** [comment] 2018-06-10 19:07
I just did some tests and it never successfully downloaded the file. I don't know what happened before, but I can't get it to work now.

**Comment by ncw** [comment] 2018-06-10 20:47
@Fabian42 thanks for testing.

#2317 has been done now which provides the `--drive-acknowledge-abuse` flag which will allow these files to be downloaded.

Find it in [the latest beta](https://beta.rclone.org) (to be released in 1.42).

I think this is a good solution for this issue, so I'm going to close it now.

**Closed by ncw** 2018-06-10 20:47 UTC

**Comment by nagualcode** [comment] 2018-08-30 19:05
--drive-acknowledge-abuse  should be default behavior... Thank you 👍

**Comment by ncw** [comment] 2018-08-31 18:59
@nagualcode There are google guidelines which say it shouldn't be!  However if you use [the latest beta](https://beta.rclone.org) you can set it in your config file in the advanced section.

**Comment by hardrocksr** [comment] 2020-09-24 16:44
I'm getting a very similar but more specific error message from gdrive. Maybe they've updated their policies since then. 

"Failed to sync: failed to open source object: open file failed: googleapi: Error 403: Only the owner can download abusive files., cannotDownloadAbusiveFile"

I'm using the --drive-acknowledge-abuse but still getting this error. Are there any new flags we can pass?

**Comment by ncw** [comment] 2020-09-25 10:16
The docs don't appear to have changed

https://developers.google.com/drive/api/v3/reference/files/get#acknowledgeAbuse

Can you check with `-vv --dump headers` that rclone is adding the `?acknowledgeAbuse` flag into the URL of the GET request?

Assuming it is, then I guess this must be a policy update.

**Comment by bad1dea** [comment] 2021-01-19 12:50
> 
> 
> The docs don't appear to have changed
> 
> https://developers.google.com/drive/api/v3/reference/files/get#acknowledgeAbuse
> 
> Can you check with `-vv --dump headers` that rclone is adding the `?acknowledgeAbuse` flag into the URL of the GET request?
> 
> Assuming it is, then I guess this must be a policy update.

I've tested this, with a known file that is flagged, the flag is being sent properly in the headers, what seems to be an issue is when you are using an SA to copy/sync, it is refusing to download the file, however when you are copy/sync from authenticated user it works.

Not sure how that logic works, as SA is considered owner from member lists.

I'm not sure how to supply logs without having to sanitize urls/headers - if there's another way to generate log without identifying urls I'd be happy to post.
