### ISSUE TITLE
Remote deletions not happening on Amazon drive

### ISSUE THREAD

**Issue by isaiah36** [ncw/rclone#573] opened 2016-07-08 17:22 UTC
When filing an issue, please include the following information if
possible as well as a description of the problem.

> What is your rclone version (eg output from `rclone -V`) 1.29

> Which OS you are using and how many bits (eg Windows 7, 64 bit) Ubuntu 16 (64 bit)

> Which cloud storage system are you using? (eg Google Drive) Amazon

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`) sync

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

Files are not being deleted from the Amazon drive after transfers are completed.  

Some files, with newly edited meta tags, are being modified but their older versions are not showing up in the Trash as they used to.  This is not a problem as such.  I am reporting it in case it is an unintended behavior.

**Comment by ncw** [comment] 2016-07-09 09:39
Note that if there were IO errors in the sync, then rclone won't delete files.  rclone will log `Not deleting files as there were IO errors`.

The API doesn't give control over which files end up in the trash or not, so if something has changed about which files end up in the trash then amazon have changed something most likely.

Did updated files used to end up in the trash - I don't remember testing that?

**Comment by isaiah36** [comment] 2016-07-09 15:26
Yes, updated files used to go in the trash.  Or, was it renamed files?  A seed of doubt has entered my mind now, because I can't remember for sure whether file name changes and file size changes both caused older versions to be sent to trash, or only the former.  I sorted the files by 'Date Modified' to confirm the updates had taken place.  Whatever rclone does it does consistently so I don't worry about it now.

It is the same I/O error every time being caused by a directory called 'lost+found' which puts up a 'Permission denied' because it is reserved by the file system.  I have added an external drive and mounted it as a sub directory, hence this issue.  Is there a way to exclude that directory from the sync?

Thanks, NCW!

**Comment by ncw** [comment] 2016-07-13 15:28
Sure - check out the [filters page](http://rclone.org/filtering/).  `--exclude /path/to/lost+found/**` is probably what you want.  Check using `rclone ls` with the filter first.

**Comment by isaiah36** [comment] 2016-07-13 18:23
That should fix it.  Thank you!

**Comment by isaiah36** [comment] 2016-07-14 11:18
Today's log still has 'Not deleting files as there were IO errors'
I may have placed the exclude flag in the wrong place.  This is the exact command I am using
'/usr/sbin/rclone sync --exclude /home/isaiahsellassie/Music/JAZZ/lost+found/** /home/isaiahsellassie/Music Adrive:Music'
Perhaps I should try it without the trailing slash and asterisks.  Or, put the exclude flag after the sync paths.

**Comment by ncw** [comment] 2016-07-14 11:37
It doesn't matter where you put the `--exclude` flag.

Note that you don't repeat the path in the remote in the exclude, so you want something like this.  (I should have said it needed the relative path from the root of the sync.)  I'd put it in quotes too as it contains shell metacharacters `*`.

    /usr/sbin/rclone sync --exclude "/JAZZ/lost+found/**" /home/isaiahsellassie/Music Adrive:Music

You can test whether it is working with the `ls` commands which obey excludes in the same way, eg

    /usr/sbin/rclone ls --exclude "/JAZZ/lost+found/**" /home/isaiahsellassie/Music

Or if you decided you never wanted a directory called `lost+found` wherever it was found then you could use `--exclude "lost+found/**"`

**Comment by isaiah36** [comment] 2016-07-14 12:43
I did a --dry-run -v with the corrected command, and it concluded without an IO error.  It did report, 'Attempt 3/3 failed with 1 errors' at the end but I don't know what that refers to.

I'll find out if remote deletes are working again after cron runs the sync as usual tonight.  I have deleted a folder completely as it happens.

Thank you kindly, sir!

**Comment by ncw** [comment] 2016-07-14 13:09
It should have left a log for that error that will give you a clue as to what happened. You can use the - - log-file option to save the log somewhere. 

You need to track down that last error or it won't do the remote deletions.

**Comment by isaiah36** [comment] 2016-07-14 13:49
So, if I add --log-file will it default to my home directory?  or, should I follow it with an explicit path and file name?

**Comment by ncw** [comment] 2016-07-14 14:01
A full path is safest

**Comment by isaiah36** [comment] 2016-07-14 16:08
I have attached the log.  The uploads occurred but remote deletions did not.  It is still trying to open the JAZZ/lost+found directory.

[rclone-log.txt](https://github.com/ncw/rclone/files/364234/rclone-log.txt)

**Comment by isaiah36** [comment] 2016-07-25 16:18
Is there a fix in the offing, Nick?

**Comment by ncw** [comment] 2016-07-27 18:18
We need to stop it looking in the `lost+found` directory - any IO errors will stop remote deletions.

Which command line did you use with that log?  Did it have the `--exclude "/JAZZ/lost+found/**"` in it?  I'm pretty sure that should work.

**Comment by isaiah36** [comment] 2016-07-27 22:54
Yes, that was it exactly.  I thought it should be without the slash and asterisks at the end but I followed your instructions.

**Comment by ncw** [comment] 2016-07-28 09:31
The first slash roots it to the start of filesystem hierarchy.  The `/**` means this directory and anything under it which is quite important.

I see what the problem is now - you need to upgrade rclone - the feature I'm trying to use was only put in 1.30.

I suggest you upgrade to the latest rclone 1.32 and try again.

**Comment by isaiah36** [comment] 2016-07-28 17:46
I did the upgrade yesterday, and sure enough, when I look at the log email from cron, the problem is solved!  It is no longer trying to open the excluded directory, and deletions are being completed.

THANK YOU!

**Comment by isaiah36** [comment] 2016-07-29 14:23
The only thing it needs now is the ability to delete empty folders.

**Comment by ncw** [comment] 2016-07-29 15:22
Excellent! Deleting empty folders is #100 so I'll close this one.

**Closed by ncw** 2016-07-29 15:22 UTC
