### ISSUE TITLE
OSX - failed to authenticate decrypted block

### ISSUE THREAD

**Issue by remusb** [ncw/rclone#1517] opened 2017-07-03 21:40 UTC
Hi,

I've just installed rclone on macOS after having some other issues on Ubuntu (unrelated to rclone). I don't really know if I had the same issue or not on Ubuntu but here's what I have:

- Used rclone sync to upload media files on Google Drive on Ubuntu 16.04
- Using rclone now in macOS to play some of those media files encrypted on Google Drive causes almost immediate aborts in playback (log file attached)
- the config file was copied as is from one system to another and there's no chance of mismatch in passwords since the filenames and the way the issue happens (file names are decrypted ok, some playback does happen, I can at least see a frame or 2 opening, a text file can be read just fine remotely)
- downloaded encrypted files on my local drive, mounted them locally just to rule out any remote issue but the same thing happens
- I've tried my best to troubleshoot and read all the other relevant issues but couldn't match to something similar on my scenario

At this point I suspect something is with `fuse for macOS` (3.6.0) but I don't really have any evidence of that just yet (will look at what they can log out).

```
2017/07/04 00:21:31 DEBUG : test.clip.convert.1080p.mkv: ReadFileHandle.seek from 738807808 to 738807808
2017/07/04 00:21:31 ERROR : test.clip.convert.1080p.mkv: ReadFileHandle.Read error: low level retry 10/10: failed to authenticate decrypted block - bad password?
2017/07/04 00:21:31 DEBUG : test.clip.convert.1080p.mkv: ReadFileHandle.seek from 738807808 to 738807808
2017/07/04 00:21:31 ERROR : test.clip.convert.1080p.mkv: ReadFileHandle.Read error: failed to authenticate decrypted block - bad password?
2017/07/04 00:21:31 DEBUG : test.clip.convert.1080p.mkv (r): >Read: read=-1, err=failed to authenticate decrypted block - bad password?
2017/07/04 00:21:31 DEBUG : fuse: -> [ID=0x2] Read error=EIO: failed to authenticate decrypted block - bad password?
```

> What is your rclone version (eg output from `rclone -V`)
rclone v1.36-231-g575e779bβ
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
macOS Sierra
> Which cloud storage system are you using? (eg Google Drive)
Google Drive / local
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone mount --log-level DEBUG --dump-headers --debug-fuse --allow-other --log-file=rclone.log local-crypt: ~/Mounts/Local
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
Attached
[rclone.txt](https://github.com/ncw/rclone/files/1120578/rclone.txt)

**Comment by ncw** [comment] 2017-07-04 08:59
What happens when you use `rclone copy` to copy one of the offending videos from the crypt remote back to your local machine?  Do you see the same `failed to authenticate decrypted block - bad password?` errors?

Do you see the errors with mount on the ubuntu machine?

Which version of rclone did you use to upload the data?

Have you tried using `rclone cryptcheck` to check the checksums of a local copy?

**Comment by remusb** [comment] 2017-07-04 09:25
Hi @ncw 

The rclone used on Ubuntu is the latest release version which is the first used on mac too and led me to try the latest beta. I think the Ubuntu part can be left out of the mix (either way, that one was wiped out). 
I attempted to upload a new file on the current setup (remote Google Drive) and it has the same issues so definitely not: password issue or rclone version issue.

Later Edit: Ok, I actually tried it with the local crypt to copy from a local decrypted version to the local encrypted mount and when starting a playback from the local unencrypted mount it works. Seems like I need to do some more testing to pinpoint the cause and it does seem to involve the remotte (Google Drive) somehow.

**Comment by ncw** [comment] 2017-07-04 11:24
OK we need to pinpoint what is causing the problem.

It sounds like the problem is intermittent so you might need to repeat it a few times.

Can you use `rclone copy` on your mac to copy a file from the encrypted remote and see if you get the same error - that will tell us whether it is FUSE or not.

**Comment by remusb** [comment] 2017-07-04 12:35
Should have considered trying to mount directly rclone to GDrive (plexdrive sits in front for caching). Mounting directly rclone to GDrive works, there's no more disconnects. Seems I have to shift my troubleshooting in plexdrive. Thanks

**Comment by ncw** [comment] 2017-07-07 10:02
OK no worries, I'll close this for the moment then.

**Closed by ncw** 2017-07-07 10:02 UTC
