### ISSUE TITLE
Filename handling leaks too much info

### ISSUE THREAD

**Issue by chbm** [ncw/rclone#666] opened 2016-08-31 23:01 UTC
The encrypted path parts methods leaks information about the structure, is susceptible to collision attacks, is hard to secure as path names are constrained in size and the algorithms used are constrained by the sync validation requirements.  As a side disadvantage it's also hard to use on blob storage systems which don't follow unixy path rules. 

I propose using a directory file and nameless blobs. The directory file can be treated as a normal blob and retain more meta information about the file. It also declouples local and remote storage features (think OS X resources). 

I was working on a similar project and have an implementation of the directory scheme at
https://github.com/chbm/securetomb/blob/master/lib/securetomb/fileset.rb
It's basically a sqlite DB which gets changed locally and then synced to the remote.

**Comment by ncw** [comment] 2016-09-05 19:29
I think this is a duplicate of #637 where discussion of a higher security file name encryption is ongoing.  I'd appreciate your input there - thanks

**Closed** 2016-09-19 17:31 UTC
Labels: duplicate
