### ISSUE TITLE
onedrive for business: fails to copy file with specific file name

### ISSUE THREAD

**Issue by masoud919** [ncw/rclone#2859] opened 2018-12-22 15:51 UTC
#### What is the problem you are having with rclone?
```
Failed to copy: generalException: General exception while processing
```
Fails to copy a file named "2016_06_01_000002_create_oauth_access_tokens_table.php"
If I change the file name to "2016_06_01_000002_create_oauth_xxxxxx_tokens_table.php" it works with no problems (changing "**access**" to "**xxxxxx**")

#### What is your rclone version (output from `rclone version`)
Tested with 1.45 stable and the latest beta as follows:
rclone v1.45-037-gdf1faa9a-beta
os/arch: windows/amd64
go version: go1.11

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
OneDrive Business

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
```
./rclone copy "d:\2016_06_01_000002_create_oauth_access_tokens_table.php" onedrive:"" -vv
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
2018/12/23 02:19:34 DEBUG : rclone: Version "v1.45-037-gdf1faa9a-beta" starting with parameters ["D:\\Apps\\rclone-v1.45-037-gdf1faa9a-beta-windows-amd64\\rclone.exe" "copy" "d:\\2016_06_01_000002_create_oauth_access_tokens_table.php" "onedrive:" "-vv"]
2018/12/23 02:19:34 DEBUG : Using config file from "C:\\Users\\masou\\.config\\rclone\\rclone.conf"
2018/12/23 02:19:34 DEBUG : One drive root '': Token expired but no uploads in progress - doing nothing
2018/12/23 02:19:37 DEBUG : Keeping previous permissions for config file: -rw-rw-rw-
2018/12/23 02:19:37 DEBUG : onedrive: Saved new token in config file
2018/12/23 02:19:38 DEBUG : 2016_06_01_000002_create_oauth_access_tokens_table.php: Couldn't find file - need to transfer
2018/12/23 02:19:38 DEBUG : 2016_06_01_000002_create_oauth_access_tokens_table.php: Starting multipart upload
2018/12/23 02:19:39 DEBUG : 2016_06_01_000002_create_oauth_access_tokens_table.php: Uploading segment 0/925 size 925
2018/12/23 02:19:39 DEBUG : 2016_06_01_000002_create_oauth_access_tokens_table.php: Cancelling multipart upload: generalException: General exception while processing
2018/12/23 02:19:39 NOTICE: 2016_06_01_000002_create_oauth_access_tokens_table.php: Failed to cancel multipart upload: generalException: General exception while processing
2018/12/23 02:19:39 ERROR : 2016_06_01_000002_create_oauth_access_tokens_table.php: Failed to copy: generalException: General exception while processing
2018/12/23 02:19:39 ERROR : Attempt 1/3 failed with 1 errors and: generalException: General exception while processing
2018/12/23 02:19:39 DEBUG : 2016_06_01_000002_create_oauth_access_tokens_table.php: Couldn't find file - need to transfer
2018/12/23 02:19:39 DEBUG : 2016_06_01_000002_create_oauth_access_tokens_table.php: Starting multipart upload
2018/12/23 02:19:41 DEBUG : 2016_06_01_000002_create_oauth_access_tokens_table.php: Uploading segment 0/925 size 925
2018/12/23 02:19:41 DEBUG : 2016_06_01_000002_create_oauth_access_tokens_table.php: Cancelling multipart upload: generalException: General exception while processing
2018/12/23 02:19:41 NOTICE: 2016_06_01_000002_create_oauth_access_tokens_table.php: Failed to cancel multipart upload: generalException: General exception while processing
2018/12/23 02:19:41 ERROR : 2016_06_01_000002_create_oauth_access_tokens_table.php: Failed to copy: generalException: General exception while processing
2018/12/23 02:19:41 ERROR : Attempt 2/3 failed with 1 errors and: generalException: General exception while processing
2018/12/23 02:19:41 DEBUG : 2016_06_01_000002_create_oauth_access_tokens_table.php: Couldn't find file - need to transfer
2018/12/23 02:19:41 DEBUG : 2016_06_01_000002_create_oauth_access_tokens_table.php: Starting multipart upload
2018/12/23 02:19:42 DEBUG : 2016_06_01_000002_create_oauth_access_tokens_table.php: Uploading segment 0/925 size 925
2018/12/23 02:19:42 DEBUG : 2016_06_01_000002_create_oauth_access_tokens_table.php: Cancelling multipart upload: generalException: General exception while processing
2018/12/23 02:19:42 NOTICE: 2016_06_01_000002_create_oauth_access_tokens_table.php: Failed to cancel multipart upload: generalException: General exception while processing
2018/12/23 02:19:42 ERROR : 2016_06_01_000002_create_oauth_access_tokens_table.php: Failed to copy: generalException: General exception while processing
2018/12/23 02:19:42 ERROR : Attempt 3/3 failed with 1 errors and: generalException: General exception while processing
2018/12/23 02:19:42 Failed to copy: generalException: General exception while processing
```

**Comment by masoud919** [comment] 2018-12-23 00:34
BTW, I can manually upload the file from the OneDrive Business web portal, it happens only with the API.

**Comment by Cnly** [comment] 2018-12-29 07:55
I've been able to reproduce this. Since there's a similar weird [problem](https://github.com/ncw/rclone/issues/2720) with OneDrive Personal, I tend to think it's some bug in their backend. Also, the error is a response for the request `PUT /personal/XXX/_api/v2.0/drives/XXX/items/XXX/uploadSession?guid=...` whose URL is actually given by the remote, so there doesn't seem to be a workaround.

Maybe the only thing that can be done is to report and wait for a fix.

**Comment by ncw** [comment] 2018-12-29 23:47
> > Where have you been reporting onedrive bugs BTW?
> 
> I've been reporting them here https://github.com/OneDrive/onedrive-api-docs/issues
> 
> Hard to tell from the repo name right? ;)

;-)  Yes, [I reported a bug there](https://github.com/OneDrive/onedrive-api-docs/issues/543) before and it got fixed!  That was another score for rclone's integration tests!

> > Do you want to report this one?
> 
> Sure, I'll report that.

Can you link it back here when you have? Thanks!

**Comment by Cnly** [comment] 2019-01-01 14:47
I've opened the issue here: https://github.com/OneDrive/onedrive-api-docs/issues/968

**Comment by Cnly** [comment] 2019-02-28 02:11
Update from upstream:

> This issue should now be resolved - please let us know if you're still seeing issues.

**Comment by ncw** [comment] 2019-02-28 11:16
It is fixed in my tests :-)  I'll close this now - thanks @Cnly for reporting it upstream

**Closed by ncw** 2019-02-28 11:16 UTC
Labels: Remote: One Drive, bug
