### ISSUE TITLE
Windows Mount

### ISSUE THREAD

**Issue by duczz** [ncw/rclone#1149] opened 2017-02-18 11:19 UTC
> What is your rclone version (eg output from `rclone -V`)
Newest

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10
> Which cloud storage system are you using? (eg Google Drive)
ACD GDrive

Currently is it not possible to mount rclone drives on Windows, is it planed or exists a ~date?

Thank you

**Comment by ncw** [comment] 2017-02-18 12:43
This is a duplicate of #1018 - can you add your support to that issue please.

**Closed by ncw** 2017-02-18 12:43 UTC
Labels: duplicate
