### ISSUE TITLE
[Feature Request] VFS - cache files opened in read mode

### ISSUE THREAD

**Issue by ghost** [ncw/rclone#2458] opened 2018-08-10 21:15 UTC
Sorry for my bad english.
VFS does not cache files opened in read mode except in "--vfs-cachemode full".
The problem is that in full mode, --vfs-read-chunk-size is not applied and the entire file is downloaded.
It would be great if the VFS caches read mode file without full mode. (adding vfs-cachemode readwrite?)

**Comment by ncw** [comment] 2018-08-11 09:53
I see what you mean.

The VFS cache was designed to be as simple as possible and even then it is really quite complicated!

At the moment in `--vfs-cache-mode full` when you open a file for read, it will download the entire file before returning any of it.

What I would like to do is make the file readable while it is downloading.

To go further would mean changing the design to be like the backend cache and we have that already.

**Comment by ncw** [comment] 2018-08-11 13:28
I see what you mean.

The VFS cache was designed to be as simple as possible to enable `rclone mount` to be compatible with more programs and even then it is really quite complicated!

At the moment in `--vfs-cache-mode full` when you open a file for read, it will download the entire file before returning any of it.

What I would like to do is make the file readable while it is downloading.

To go further would mean changing the design to be like the backend cache and load in chunks.

So if you want to enable that functionality then I suggest you use the cache backend which does exactly that.

**Comment by 2cpu** [comment] 2018-08-18 01:47
Thank you for reply. For my testing, cache backend adds about 1 second to seek time. I tested both in the cloud and locally.
So where multiple seek operation occurs when open file(container, media formats), it takes more than 10 seconds.
Thats the reason I want to use VFS.

**Comment by ncw** [comment] 2018-08-18 09:49
@2cpu - I see!  I'll leave this open as an enhancement request

**Comment by dcpu** [comment] 2018-08-27 10:44
I recreated github account to make pull request.
https://github.com/ncw/rclone/pull/2493
fixed the issue. I am using cache backend now.

**Comment by dcpu** [comment] 2018-09-03 23:50
I think now this issue can be closed. But I cant do it myself because I have deleted my previous account. Thank you for great work!

**Comment by ncw** [comment] 2018-09-04 10:09
@dcpu Thank you for fixing the issue in the cache - I'll close this one now.

**Closed by ncw** 2018-09-04 10:09 UTC
Labels: enhancement
