### ISSUE TITLE
Rclone size now fails when directory name contains the fullwidth-solidus character (／)

### ISSUE THREAD

**Issue by YenForYang** [ncw/rclone#1519] opened 2017-07-07 11:52 UTC
Using the latest beta (tested on both Windows 64bit and Linux-amd64) with Google Drive--

rclone size "GD:.../sometext／sometext...／..." 

gives the error (with debug on, specific paths are replaced with ellipses)

2017/07/07 06:44:18 DEBUG : rclone: Version "v1.36-241-g92294a4aβ" starting with parameters ["rclone" "size" "GD:.../sometext／sometext...／..." "-vv"]
2017/07/07 06:44:21 INFO  : Google drive root '.../sometext／sometext...／...': Modify window is 1ms
2017/07/07 06:44:22 ERROR : : error listing: directory not found
2017/07/07 06:44:22 Failed to size: directory not found

Note I've confirmed that removing the fullwidth-solidus character produces no error, and this issue did not occur until recently (i.e. I don't recall having an issue in v1.35, maybe(?) even earlier versions of 1.36). I've also tested the command with the "--local-no-unicode-normalization" flag, which produced the same error).

**Comment by ncw** [comment] 2017-07-07 13:15
rclone now translates the full width solidus into a / for google drive.  Are you saying you've got names with the full width solidus in?

If you rename them to be a / then does it fix it?

**Comment by YenForYang** [comment] 2017-07-08 16:18
Well, long ago I switched from using slash to fullwidth solidus in file/folder names (for the sake of having valid file/folder names and directory functionality in rclone).

So does rclone now interprets all fullwidth solidus characters as a regular slash? Is there any way I could turn this functionality off? 

I've got a lot (tons and tons) of files/folders with fullwidth solidus characters instead of slashes. I actually very much prefer the solidus to the normal slash in directory/file names in Drive, since slashes are forbidden characters in windows/linux directories/files.

**Comment by YenForYang** [comment] 2017-07-29 17:00
Just realized that the size command is not the only command affected--if I want to list a directory (that has the solidus character) with lsd it fails as well, so all subfolders under the folder also are not reachable.

**Comment by ncw** [comment] 2017-07-30 09:00
Can you rename the files on drive (using the web interface) to turn the full width solidus into `/`?  Drive files are allowed to have `/` in them which is the root cause of this change.

**Comment by ncw** [comment] 2017-09-25 15:22
I'm going to close this as it is working as expected and there is an easy workaround - just rename the files on drive.

**Closed by ncw** 2017-09-25 15:22 UTC
Labels: bug, Remote: Drive

**Comment by YenForYang** [comment] 2017-10-15 22:52
Coming back to the issue---there are actually many cases in which I want the solidus character rather than the slash. The slash can't be used in filenames in Windows, Linux, etc.; the solidus character **can**, which actually was _the_ reason I switched in the first place. 

Unfortunately renaming thousands of files is not an easy workaround, for not only is that thousands of files of renaming but also I would have to rename them back if I were to download the files. 

If this can't be fixed, perhaps I could somehow use an older version of rclone? What was the latest version of rclone that didn't have this implemented, and is it functional enough to not cause other issues with GDrive?

**Comment by YenForYang** [comment] 2017-10-31 13:52
Is there any way I could get this issue re-opened? I apologize since this issue appears to something that only I have been having, but it's been creating some serious struggles for me. 

(If rclone had a batch "find and replace characters in names" command I probably would have bit the bullet and changed all my '／' characters to '＼' -- perhaps it should be a feature implemented in rclone?)

**Comment by ncw** [comment] 2018-09-04 10:18
@ext4 I like your suggestion of a flag (which can also be stored in the config), say `--drive-no-name-transaction`

This could disable `fullwidth solidus -> /` on upload.

What should happen on download?  Google files can have `/`  in which isn't valid in any filesystem! Rclone could do the translation  `/ -> fullwidth solidus`  but that will cause problems with syncing.

I think the only solution on download would be to skip files with `/` in on download?

If you like that idea then I'll re-open this and we can implement - maybe you'd like to help?

**Comment by ncw** [comment] 2018-09-11 07:07
@ext4 wrote
> Anyway, I'd be more than happy to try give this a shot at the weekend.

I think what you've specified is perfect and I'd be very happy to receive a PR with that in :-)

If you put what you wrote in the [drive docs](https://github.com/ncw/rclone/blob/master/docs/content/drive.md) that would be good too!
