### ISSUE TITLE
panic: close of closed channel (Backblaze B2)

### ISSUE THREAD

**Issue by GrahamCobb** [ncw/rclone#592] opened 2016-07-18 16:27 UTC
rclone crashed when Backblaze returned "storage cap exceeded" errors (see log below).

Obviously this is a minor problem -- the sync was not going to get any further anyway -- but I am guessing you would prefer not to have a crash and a backtrace.

> What is your rclone version (eg output from `rclone -V`)

The special version of 1.32 supplied after my other issue report.

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Debian testing, 64

> Which cloud storage system are you using? (eg Google Drive)

Backblaze B2

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone sync --delete-after /nas/backup/DAR-archive/novatech/ b2:XXXXXX/rclone/nas/backup/DAR-archive/novatech/

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

...many stats deleted...
2016/07/16 06:25:06 
Transferred:   24.484 GBytes (904.506 kBytes/s)
Errors:                 6
Checks:                38
Transferred:           30
Elapsed time:   7h53m3.5s
Transferring:
 *                      DARsystemFull.28.dar.gpg: 39% done. avg:  268.1, cur:  759.5 kByte/s. ETA: 19m38s
 *                      DARsystemFull.31.dar.gpg: 66% done. avg:  290.6, cur: 3855.9 kByte/s. ETA: 2m9s
 *                      DARsystemFull.35.dar.gpg: 46% done. avg:  256.4, cur:    0.0 kByte/s. ETA: 0s
 *                      DARsystemFull.38.dar.gpg: 80% done. avg:  311.4, cur: 3446.8 kByte/s. ETA: 1m24s

2016/07/16 06:25:10 DARsystemFull.31.dar.gpg: Failed to copy: Cannot upload files, storage cap exceeded. See the Caps & Alerts page to increase your cap. (403 storage_cap_exceeded)
2016/07/16 06:25:25 DARsystemFull.35.dar.gpg: Failed to copy: Cannot upload files, storage cap exceeded. See the Caps & Alerts page to increase your cap. (403 storage_cap_exceeded)
2016/07/16 06:25:26 DARsystemFull.28.dar.gpg: Failed to copy: failed to get upload URL: Cannot upload files, storage cap exceeded. See the Caps & Alerts page to increase your cap. (403 storage_cap_exceeded)
panic: close of closed channel

goroutine 49 [running]:
panic(0x868a20, 0xc42034fb90)
	/home/ncw/Code/go/src/runtime/panic.go:500 +0x1a1
github.com/ncw/rclone/fs.(*syncCopyMove).processError(0xc4203c0000, 0xb100c0, 0xc420376c00)
	/home/ncw/Code/go/src/github.com/ncw/rclone/fs/sync.go:186 +0xa8
github.com/ncw/rclone/fs.(*syncCopyMove).pairCopier(0xc4203c0000, 0xc42049c480, 0xb186e0, 0xc4200eeb00, 0xc4203c0088)
	/home/ncw/Code/go/src/github.com/ncw/rclone/fs/sync.go:236 +0x2bb
created by github.com/ncw/rclone/fs.(*syncCopyMove).startTransfers
	/home/ncw/Code/go/src/github.com/ncw/rclone/fs/sync.go:319 +0x108

**Comment by ncw** [comment] 2016-07-18 22:10
Thanks for posting that.

I can see the problem (it is a new bit of code) - I'll fix it for the next release.

The problem is that it got more than one Fatal Error and signaled it more than once in here

```go
// This checks the types of errors returned while copying files
func (s *syncCopyMove) processError(err error) {
	if err == nil {
		return
	}
	s.errorMu.Lock()
	defer s.errorMu.Unlock()
	switch {
	case IsFatalError(err):
		close(s.abort)
		s.fatalErr = err
	case IsNoRetryError(err):
		s.noRetryErr = err
	default:
		s.err = err
	}
}
```

**Comment by ncw** [comment] 2016-08-18 18:03
That is fixed in this beta: http://pub.rclone.org/v1.32-23-gb5faaf7%CE%B2/

and will be in the v1.33 release.

Thanks for reporting.

Nick

**Closed** 2016-08-18 18:03 UTC
Labels: bug, Remote: Backblaze B2
