### ISSUE TITLE
OSX file name encoding causes problems with non-ascii characters

### ISSUE THREAD

**Issue by jkrinke** [ncw/rclone#463] opened 2016-04-29 16:04 UTC
rclone has a problem when filenames contain non-ascii characters.

I have a large number of files and directories on ACD that contain non-ascii characters (umlauts). During sync, rclone always copies all files with such characters from ACD to the local filesystem. It seems that rclone does not find the files in the local directory and therefore copies them, overwriting the current file.  The same happens again if the same sync command is issued as soon as the previous one finished.

> What is your rclone version (eg output from `rclone -V`)

rclone 1.29

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

OSX 10.11.4

> Which cloud storage system are you using? (eg Google Drive)

ACD

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone sync <ACD> <local>

**Comment by ncw** [comment] 2016-04-29 17:01
I think this is a duplicate of #451

I've borrowed a mac from work for the weekend and I'll see if I can fix it!

**Comment by ncw** [comment] 2016-05-02 10:40
I have fixed this now.  Here is a beta for you to try.  Please re-open the ticket if you have any problems with it!

http://pub.rclone.org/v1.29-16-g8b2f6fa%CE%B2/

**Closed by ncw** 2016-05-02 10:40 UTC
Labels: bug

**Comment by jkrinke** [comment] 2016-05-05 17:18
It seems to have fixed the issue. Thanks a lot!
