### ISSUE TITLE
B2 401 expired_auth_token 

### ISSUE THREAD

**Issue by Safari77** [ncw/rclone#366] opened 2016-02-22 10:24 UTC
When filing an issue, please include the following information if
possible as well as a description of the problem.

After a long time of uploading, I get error 401.

> What is your rclone version (eg output from `rclone -V`)
v1.27

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux Fedora 22

> Which cloud storage system are you using? (eg Google Drive)
B2

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync /some/dir backblaze:foo

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

x: Failed to copy: Failed to upload: Authorization token has expired (401 expired_auth_token)

rclone could automatically get new token.

**Comment by ncw** [comment] 2016-02-22 13:36
Thanks for reporting this.  This is a duplicate of #310 which is scheduled for the next release so I'm going to close this one - if you'd like to follow the other ticket you'll get notifications about its progress.

You have provided the actual error message though which is super helpful - thanks.

**Closed by ncw** 2016-02-22 13:36 UTC
Labels: duplicate
