### ISSUE TITLE
hubic: error authenticating swift connection: failed to get credentials: 401

### ISSUE THREAD

**Issue by do11** [ncw/rclone#1741] opened 2017-10-14 20:58 UTC
hubic remote authenticated and worked yesterday, but today is reporting 401 error.

> What is your rclone version (eg output from `rclone -V`)

```
rclone v1.38
- os/arch: linux/amd64
- go version: go1.9
```

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

`CentOS release 6.9 (Final)`

> Which cloud storage system are you using? (eg Google Drive)

`hubic`

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

```
# rclone lsd hubic:
2017/10/14 23:47:11 Failed to create file system for "hubic:": error authenticating swift connection: failed to get credentials: 401
```

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
# rclone -vv lsd hubic:
2017/10/14 23:55:12 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2017/10/14 23:55:12 DEBUG : rclone: Version "v1.38" starting with parameters ["rclone" "-vv" "lsd" "hubic:"]
2017/10/14 23:55:13 Failed to create file system for "hubic:": error authenticating swift connection: failed to get credentials: 401
```

**Comment by do11** [comment] 2017-10-14 22:35
Update. I was copy-pasted output of token request into `rclone.conf`, but it contains `"expires_in":21600` instead of `"expiry":"2017-10-15T07:31:07.232721654+03:00"`. When I added `"expiry"` dated by past, rclone successfully re-authenticated.

**Comment by ncw** [comment] 2017-10-15 20:34
> Update. I was copy-pasted output of token request into rclone.conf, but it contains "expires_in":21600 instead of "expiry":"2017-10-15T07:31:07.232721654+03:00". When I added "expiry" dated by past, rclone successfully re-authenticated.

Well spotted!

I haven't seen that in oauth before - I wonder if it is Hubic experimenting with something?

Refreshing the token (with `rclone config` and editing the remote, not changing any values but saying yes to refresh the token) probably would have fixed it too.

Let me know if you see it again...

**Comment by ncw** [comment] 2017-11-29 13:49
I had this too.  It was caused by hubic wanting me to change my password which I did at hubic.com - then I refreshed the token and all was well.

I'm going to close this issue now since I haven't seen any other reports of it.

**Closed by ncw** 2017-11-29 13:49 UTC

**Comment by loran34** [comment] 2017-11-29 21:48
I have the same issue. I changed my password, refreshed the token and got the following error : 

```
2017/11/29 22:47:11 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2017/11/29 22:47:11 DEBUG : rclone: Version "v1.38" starting with parameters ["rclone" "-vv" "lsd" "hubic-documents:default"]
2017/11/29 22:47:11 Failed to create file system for "hubic-documents:default": error authenticating swift connection: failed to get credentials: 401
```

rclone version (eg output from rclone -V)
```
rclone v1.38
- os/arch: linux/amd64
- go version: go1.9
```

OS 
`Ubuntu 16.04 LTS`

**Comment by ncw** [comment] 2017-11-30 11:16
@loran34 wrote:
> I have the same issue. I changed my password, refreshed the token and got the following error :

I find refreshing the token using `rclone config`, editing the remote, saying no to editing anything, then saying yes to refresh the token works for me.  Is that what you did?

**Comment by asez73** [comment] 2017-12-01 20:18
Hello,
Just to mentionned that I had the same problem and solved it as you proposed: refreshing the token.
It happened 2 weeks ago and again today... Same problem, same solution...

**Comment by loran34** [comment] 2017-12-01 20:36
Yes, that's what I did. I also tried to delete the remote and create a new one. I just got the same error.
