### ISSUE TITLE
encryption & deduplication

### ISSUE THREAD

**Issue by outbackdingo** [ncw/rclone#324] opened 2016-01-26 21:02 UTC
What would be nice is to see dataset encryption and deduplication, therefor securing and lowering the overall disk usage

**Comment by klauspost** [comment] 2016-01-27 09:36
Have a look at [restic](https://github.com/restic/restic), it has a fully encrypted destination and deduplication. That may suit your immediate need better.

**Comment by klauspost** [comment] 2016-01-27 09:51
Duplicate of #219

**Closed by klauspost** 2016-01-27 09:51 UTC
