### ISSUE TITLE
Error when copying from Dropbox remote to S3

### ISSUE THREAD

**Issue by NumberedThought** [ncw/rclone#1823] opened 2017-11-14 21:07 UTC
Version of rclone:
rclone v1.38-052-gf60e2a7aβ
- os/arch: linux/amd64
- go version: go1.9.2

Description:  Error seems to occur when copying from a dropbox remote to any other remote.  I suspect it's a read error from the source side.  Error occurs more frequently when the file to copy is large (in excess of 10GB)  Attempting to copy to a crypt remote error occurs much more frequently

error with debug:  Copy from dropbox remote to s3 remote

2017/11/14 20:56:52 ERROR : FILENAME: Failed to copy: MultipartUpload: upload multipart failed
        upload id: jieiXUa2_G8EJ7fSqxUu.pZWbhrl4Mog8_LHwjWnUK2DWPsFG5r9ql5Vw758g2a2SwCsLH3fy6U5rF6_XJc9p9AO8LUxA76W49zbOlO6eK3SKYsNI8.s8dr5bnBXzfv7
caused by: ReadRequestBody: read multipart upload data failed
caused by: unexpected EOF

**Comment by ncw** [comment] 2017-11-15 09:34
> I suspect it's a read error from the source side

Yes that is what it looks like to me too.

That error looks like it comes from the S3 SDK Multipart upload code and it looks like it was reading on the file handle but it was closed unexpectedly.

This will have been caused by dropbox closing the handle for some reason.

Can you download those big files to the local disk from dropbox?

**Comment by ncw** [comment] 2017-12-12 12:59
I'm going to close this now since I haven't heard from you.  Please reopen if you can reproduce the problem.

**Closed by ncw** 2017-12-12 12:59 UTC

**Comment by mchristiansen23** [comment] 2018-01-19 14:49
I am experiencing this same issue when copying large files.  How can I help troubleshoot and/or get a fix?

**Comment by ncw** [comment] 2018-01-19 15:58
@mchristiansen23 open a new issue with full details of what you are trying to do, the command line of rclone and a log with `-vv` would be an excellent start :-)
