### ISSUE TITLE
onedrive  Failed to query available drives: HTTP error 401 (401 Unauthorized) returned body:

### ISSUE THREAD

**Issue by guoxiangke** [ncw/rclone#2682] opened 2018-10-22 10:00 UTC
#### What is the problem you are having with rclone?
onedrive both Business&Personal can't save config on my ec2 ubuntu server

2018/10/22 09:56:25 ERROR : Failed to save new token in config file: section '1drive' not found
Choose a number from below, or type in an existing value
 1 / OneDrive Personal or Business
   \ "onedrive"
 2 / Root Sharepoint site
   \ "sharepoint"
 3 / Type in driveID
   \ "driveid"
 4 / Type in SiteID
   \ "siteid"
 5 / Search a Sharepoint site
   \ "search"
Your choice> 1
2018/10/22 09:56:26 Failed to query available drives: HTTP error 401 (401 Unauthorized) returned body: "{\r\n  \"error\": {\r\n    \"code\": \"InvalidAuthenticationToken\",\r\n    \"message\": \"Access token validation failure.\",\r\n    \"innerError\": {\r\n      \"request-id\": \"6aac2975-ef49-4f9c-bd01-59e4d9122045\",\r\n      \"date\": \"2018-10-22T09:56:26\"\r\n    }\r\n  }\r\n}"

#### What is your rclone version (output from `rclone version`)

rclone version
rclone v1.44
- os/arch: linux/amd64
- go version: go1.11.1

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

uname -a
Linux ip-172-31-14-114 4.15.0-1021-aws #21-Ubuntu SMP Tue Aug 28 10:23:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

####  Which cloud storage system are you using? (eg Google Drive)
onedrive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone config

**Comment by guoxiangke** [comment] 2018-10-22 12:07
beta also failed, the same error!
rclone v1.44-006-gc5ac96e9-beta
- os/arch: linux/amd64
- go version: go1.11.1

**Comment by Cnly** [comment] 2018-10-24 13:05
Hi, I saw your another issue #2684 which was opened 46 minutes after this one. Can you still reproduce this problem? Or can we consider it some kind of temporary error? I can't reproduce this on my side.

**Comment by Cnly** [comment] 2018-11-04 10:32
@guoxiangke since we don't hear updates from you, I'll assume this is just a temporary problem and close the issue. Please feel free to re-open it if you find anything wrong!

**Closed** 2018-11-04 10:33 UTC
Labels: Remote: One Drive, can't reproduce

**Comment by Jayjjjjj** [comment] 2018-12-23 10:06
hello？I also meet this problem.
 rclone v1.45-039-g5babf2dc-beta
- os/arch: linux/amd64
- go version: go1.11.4
I copied rclone.conf from Win which could successfully add onedrive.
**My remote server runs CentOS7.6.**
while I tried to mount onedrive ,it showed 
Failed to query available drives: HTTP error 401 (401 Unauthorized) returned body: "{\r\n  \"error\": {\r\n    \"code\": \"InvalidAuthenticationToken\",\r\n    \"message\": \"Access token validation failure.\",\r\n    \"innerError\": {\r\n      \"request-id\": \"08d8d81a-1ee8-4618-ac75-eddecca234b5\",\r\n      \"date\": \"2018-12-23T09:54:32\"\r\n    }\r\n  }\r\n}".

**Comment by Cnly** [comment] 2019-01-04 08:51
@nandrasg Can you move over to https://github.com/ncw/rclone/issues/2861 and provide some more details for your case including the version of rclone you're using and what you're trying to do? Thanks.

**Comment by guoxiangke** [comment] 2019-01-25 23:21
![untitled](https://user-images.githubusercontent.com/1160703/51778083-f7c1be00-213a-11e9-8d3a-86f07b327e25.gif)

**Comment by idealclover** [comment] 2019-02-16 09:26
Same problem.

**Comment by Cnly** [comment] 2019-02-18 04:02
For everyone still bugged by this problem please ensure that you're using the same version of rclone in each place. You can check the version of rclone by running `rclone -V`. If you're using the same version of rclone but the version number is < 1.44, please also update them to the latest release.

**Comment by lumengde123** [comment] 2024-02-05 15:43
I also got this error. 

Note1: Make sure Windows and server have the same rclone version。My Windows and CentOS are both rclone v1.65.2, which is the same.

Note 2: The access_token generated after authorization by [rclone authorize "onedrive"] is different every time, so make sure the one you copy is the latest.

Note 3: In this step I chose 4,  Vnet Group (cn) and Microsoft both have office 365 activities, I belong to Global, but I chose (cn), which led to my mistake. Re-select 1 and I succeeded
```shell
Press Enter for the default (global).
  1/Microsoft Cloud Global
    \(global)
  2/Microsoft Cloud for US Government
    \(us)
  3/Microsoft Cloud Germany
    \(de)
  4/Azure and Office 365 operated by Vnet Group in China
    \(cn)
region> 1
```

Then I successfully solved the problem. If subsequent netizens also have such an error, you can check to see if there is a wrong choice in any step that leads to this error....
