### ISSUE TITLE
Notices and strange information

### ISSUE THREAD

**Issue by oliveriojnn** [ncw/rclone#1694] opened 2017-09-19 16:23 UTC
You know how to tell the reason told WARNING? Why do they happen? Is it normal or a mistake?

Log complete: https://gist.github.com/oliveriojnn/98cf9030dc2769942dfa276161d5144a

2017/09/19 13:14:06 NOTICE: **Local file system at /srv/Storage1: Replacing invalid UTF-8 characters in** "EDITORA/ILUSTRAS/VIVER VALORES 2017/FUNDAMENTAL/2 ANO/MAT/VVMAT2F_084_CRIAN\xc7AS.psd"

2017/09/19 13:14:08 NOTICE: EDITORA/ILUSTRAS/VIVER VALORES 2017/FUNDAMENTAL/4 ANO/MAT/VVMAT4F_301_BALANÇA.psd: **Duplicate object found in source - ignoring**

2017/09/19 13:14:31 INFO  : BANCO DE ILUSTRAS/VIVER VALORES 2017/PROJETOS/FUNDAMENTAL/3F/VVETI3F/VVETI3F.xlsx: Copied (**replaced existing**)

These warnings and information are always showing that the copy runs from Google Drive to local server (Ubuntu 16.04.3). Even if there are no new files or modifications at the source.

**Comment by ncw** [comment] 2017-10-02 16:03
This was caused by a bug which is now fixed

https://beta.rclone.org/v1.38-012-g00fe6d95/ (uploaded in 15-30 mins)

Running `rclone dedupe` on your drive is recommended to remove the "Duplicate object" messages.

**Closed by ncw** 2017-10-02 16:03 UTC
