### ISSUE TITLE
Copy to gdrive with gdocs conversion

### ISSUE THREAD

**Issue by dav1303** [ncw/rclone#2046] opened 2018-02-04 08:22 UTC
Hi

In some cases users want to let Microsoft Office because of ans oldest version or not want to pay for a new license.

Is it possible to add à flag to launch the conversion of an office
Document to is équivalent un gdocs when making a copy ?

Regards

**Comment by B4dM4n** [comment] 2018-02-06 14:35
This sounds like a good idea and would complete document handling for drive.

The problem is that rclone can't verify the checksum or size when doing server side conversions. You would have to run it with `--ignore-size` to upload files.
It should nevertheless be possible to implement this feature.

I suggest `--drive-import-formats` as a new parameter to specify the wanted conversions. By default this has to be disabled, because the document conversion is not lossless and can not be reverted.

The `--drive-formats` should probably be renamed to `--drive-export-formats` to make the difference between both clearer.

**Comment by dav1303** [comment] 2018-02-16 21:47
@B4dM4n Did you plan to integrate this feature ?

**Comment by B4dM4n** [comment] 2018-02-19 11:18
Yes, I'm working on this (see [B4dM4n/rclone#drive_import_formats](https://github.com/B4dM4n/rclone/tree/drive_import_formats))
It should be working already, but I would like to implement some tests to verify this.

@ncw I would like to add some tests to `drive_test.go` but I know it is generated from `gen_tests.go`. Any advice how I could add something like `TestInternal` to run before `TestFinalise`?

**Comment by dav1303** [comment] 2018-02-21 10:13
Hi

Please let me know when your test are fine on your side and i can also test
myself.

Regards

**Comment by dav1303** [comment] 2018-03-03 11:07
@B4dM4n have you finish your tests ?

Can i help you on tests ?

**Comment by dav1303** [comment] 2018-05-01 06:41
Hello

Some news around that enhancement ?

Thanks

**Comment by B4dM4n** [comment] 2018-07-27 23:33
@dav1303 
Sorry for the delay, but I didn't have time in the last weeks to work on this issue.

The problem I'm facing is mapping the real filename to a Google document name and back to a real filename for copy and sync to work properly.
I think I found a solution and will try to implement it in time for rclone v1.43.

**Comment by dav1303** [comment] 2018-07-28 12:29
Hi
No problem 
Take your time i'll just want to follow.
Regards

**Comment by B4dM4n** [comment] 2018-09-01 15:33
There has been progress for this issue:
#2479 is a work in progress rewrite of the drive documents handling. 
If anyone wants to help testing the new implementation, there is a beta branch containing the changes: 
https://beta.rclone.org/branch/v1.42-162-g6a66967c-drive-documents/

**Keep in mind this is not tested thoroughly yet and therefore be considered experimental.**

Please post any feedback in #2479. Updated releases will also be anounced there.

**Comment by B4dM4n** [comment] 2018-10-04 19:53
#2479 has been merged lately.

This feature can be used since https://beta.rclone.org/v1.43-112-ga20fae03-beta/, the [latest beta](https://beta.rclone.org/) and in v1.44

**Closed by B4dM4n** 2018-10-04 19:53 UTC
Labels: Remote: Drive, enhancement
