### ISSUE TITLE
acd: Transfers stalling when copying from ACD to crypted ACD

### ISSUE THREAD

**Issue by simonetm** [ncw/rclone#902] opened 2016-11-21 16:31 UTC
For some reason my transfer kept stalling out while copying to an encrypted drive as seen in the picture below. Another user also reported the issue when transferring to an encrypted remote on google drive.

> What is your rclone version (eg output from `rclone -V`)
rclone v1.34-23-gc41b67eβ

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
CentOS 7 64bit

> Which cloud storage system are you using? (eg Google Drive)
Amazon Cloud Drive although another person using google reported the same issue

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy remote:/stuff encryptedremote:/stuff

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
rclone -v copy /tmp amazon:tmp
2016/11/21 16:29:20 rclone: Version "v1.34-23-gc41b67eβ" starting with parameters ["rclone" "-v" "copy" "/tmp" "amazon:tmp"]
2016/11/21 16:29:21 amazon drive root 'tmp': Modify window not supported
2016/11/21 16:29:21 amazon drive root 'tmp': Reading ""
2016/11/21 16:29:21 amazon drive root 'tmp': Finished reading ""
2016/11/21 16:29:21 amazon drive root 'tmp': Waiting for checks to finish
2016/11/21 16:29:21 amazon drive root 'tmp': Waiting for transfers to finish
2016/11/21 16:29:21
rclone -v copy /tmp crypt:tmp
2016/11/21 16:29:58 rclone: Version "v1.34-23-gc41b67eβ" starting with parameters ["rclone" "-v" "copy" "/tmp" "crypt:tmp"]
2016/11/21 16:29:59 Encrypted amazon drive root 'Crypt/hm38iondlmn90pvq0fn7aghs3g': Modify window not supported
2016/11/21 16:29:59 amazon drive root 'Crypt/hm38iondlmn90pvq0fn7aghs3g': Reading ""
2016/11/21 16:29:59 amazon drive root 'Crypt/hm38iondlmn90pvq0fn7aghs3g': Finished reading ""
2016/11/21 16:29:59 Encrypted amazon drive root 'Crypt/hm38iondlmn90pvq0fn7aghs3g': Waiting for checks to finish
2016/11/21 16:29:59 Encrypted amazon drive root 'Crypt/hm38iondlmn90pvq0fn7aghs3g': Waiting for transfers to finish
2016/11/21 16:29:59
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        1.2s
2016/11/21 16:29:59 Go routines at exit 10

![rclone](https://cloud.githubusercontent.com/assets/1960740/20490861/fb35b778-afd4-11e6-8c23-238c2ae5f237.JPG)

**Comment by ncw** [comment] 2016-11-24 16:48
I think this is unlikely to be an rclone problem.  Did your internet connection go to pieces at that moment?  Or maybe Amazon had a problem.

Can you reproduce the problem?

**Comment by simonetm** [comment] 2016-11-24 18:53
Yes multiple times. Other users all so have reported the issue with Google
Drive which makes me think it's not just specific to Amazon.

**Comment by ncw** [comment] 2017-01-20 08:42
This has also been discussed [on the forum](https://forum.rclone.org/t/rclone-stalls-on-acd-upload-done-0-bytes-s-eta-0s-and-must-be-restarted/727/12)

I think the problem is copying from ACD to ACD so I'll change the title in a moment.

I'll try to replicate!

**Comment by ncw** [comment] 2017-01-20 16:06
I think I've worked out what is happening here.  I managed to reproduce it once, and it gave me enough of a clue.

Can you try this beta please and let me know how you get on:

http://beta.rclone.org/v1.35-41-g2abfae2/ (uploaded in 15-30 mins)

Thanks

Nick

**Comment by peixotorms** [comment] 2017-02-07 17:48
I'm facing the same exact issue with uploading large files to Google Drive (60GB). It starts uploading fine and when it gets to around 25% it starts dropping the speed until I get 0 Bytes/s, ETA: 1778029h59m31.770010624s ...

**Comment by ncw** [comment] 2017-02-08 10:35
@peixotorms it is probably some kind of networking problem.  If it happens again use netstat to work out where rclone is connecting to and then use traceroute to see what the path looks like to those IPs.

**Comment by ncw** [comment] 2017-02-14 11:18
I'm going to close this now as the issue is fixed by 2abfae283cd6128cf36bb31bffad1c818e82bbb4

**Closed by ncw** 2017-02-14 11:18 UTC
Labels: bug, Remote: Crypt

**Comment by akang6** [comment] 2017-05-20 22:42
I am having the same issue. I'm running on OS X using SFTP over the local network using version 1.36.

![screenshot 2017-05-20 18 41 12](https://cloud.githubusercontent.com/assets/588620/26279822/162f9bf8-3d8c-11e7-9b10-1aaa64b5ec14.png)
