### ISSUE TITLE
Manage folders

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#100] opened 2015-08-16 14:18 UTC
Some of rclones remote fs do understand the concept of folders, eg
- drive
- local
- dropbox

Make an optional interfaces (eg `Mkdir`, `Rmdir`) for these FS to manage the creation and deletion of folders.  This would enable empty folders, and deletion of empty folders on sync.

**Comment by mullenkamp** [comment] 2015-08-26 16:09
I just noticed this issue when I sync to drive. I would definitely like to have folders deleted in addition to the contained files. 
Thanks a lot for the copy program, it's the most reliable I've used so far for google drive.

**Comment by ncw** [comment] 2015-08-26 20:35
@mullenkamp thanks for the vote of confidence! I can see a plan coming together for this.

**Comment by austinginder** [comment] 2015-09-11 12:46
Been using Rclone regularly for the past few months. Works solid. There are a good number of empty directories left in my Dropbox. This would be awesome if it was built in with the sync command.

**Comment by memeplex** [comment] 2015-12-28 01:04
This is specially important for synchronizing databases (for example, a git repo) which may:

1. require an empty directory to be there.
2. leave behind a large number of empty directories.

**Comment by Wowfunhappy** [comment] 2016-02-03 17:04
Is there any chance that this will be prioritized in the near-ish future?

The longer that I use rclone to sync the contents of my local hard drive with ACD, the more of a problem this is becoming. As files naturally get reorganized and moved around, more and more empty folders pile up on ACD. An aesthetic problem, perhaps, but it's becoming difficult to actually find the files I want, and there's no way to programmatically find and delete the empty folders short of completely deleting the remote copy and re-uploading from scratch, which would take literal months over my internet connection.

Rclone is still useful for creating remote backups should my local hard drive fail, but it's a lot less useful than it once was.

**Comment by ncw** [comment] 2016-02-10 17:57
I think what I might do for this is just delete empty folders on the destination at the end of the sync.

This is relatively straight forward and will satisfy nearly all cases, except for that of syncing an empty directory.

**Comment by cento79** [comment] 2016-02-10 20:07
I think it'll be a useful workaround. I'd go for a dedicated switch to enable the deletion so that people actually wanting empty folders will not be affected. BTW, great job: I synced almost 700GB in less that 3 days; I used to use rsync before and it kept crashing every few GBs. Excellent tool.

**Comment by dav1303** [comment] 2016-02-10 20:54
Sure adding a parameter to let user choose what he wants to do

- Delete empty folders or not delete

**Comment by Wowfunhappy** [comment] 2016-02-10 21:33
Deleting empty folders would definitely solve the problem for my use case.

**Comment by mcrisc** [comment] 2016-02-16 11:31
I agree with @cento79: a switch to enable deletion would be a good solution. Started using rclone a few days ago. Good tool! Congrats!

**Comment by winternet-studio** [comment] 2016-04-07 09:35
I definitely also vote for a switch to enable folder deletion.

**Comment by calisro** [comment] 2016-04-21 17:02
I am for folder deletion but I would rather see rclone delete a folder when asked to rather than delete the contents of a directory and then the empty directory.  The reason that I have for this:

In my use case, I use drive to store home camera data (videos/jpgs) from my home's automation.  I store everything in directories sort of like this:

/cams/<cameraname>/2016-02-01
/cams/<cameraname>/2016-02-02
/cams/<cameraname>/2016-02-03
/cams/<cameraname>/2016-02-04
/cams/<cameraname>/2016-02-05

etc.  So daily folders for each camera.  In the GUI, when I send a folder to the trash, it literally sends the folder to the trash and if I were to try to purge that folder or even restore that folder it would be VERY simply to do.  i.e. select the folder and restore/delete depending on my wishes.

IF I perform the deletes via RCLONE, I send up with tens of thousands of individual files contained in those folders.  Good luck trying to restore them. and there is no method available in amazon cloud drive to 'purge trash' (It needs to be done in batches of 1000 and takes a long time).

It would be more efficient to have rclone delete the contents depending on what you specify.  Like this:

This could delete individual files
rclone -delete robacd:/cams/playroom/2016-03-29/* 
OR
rclone -delete robacd:/cams/playroom/2016-03-29/

This could delete the FOLDER itself (no trailing slash and/or no star)
rclone -delete robacd:/cams/playroom/2016-03-29

Thanks for the great tool.

**Comment by Wowfunhappy** [comment] 2016-04-23 15:25
Perhaps this should be split into two separate tickets? I think that properly managing folders is clearly the ideal long-term goal, but it would be great if rclone could simply delete empty folders in the interim.

**Comment by kardapoltsev** [comment] 2016-05-11 06:36
+1 for deleting empty directories.

**Comment by rtg20** [comment] 2016-05-16 19:19
I too would like empty directories to be deleted. In the meantime, does anyone have a good script for accomplishing the deletion under Windows? Perhaps a Powershell that I can run immediately after rclone?

**Comment by rtg20** [comment] 2016-05-16 19:23
...ok I found one:

gci -R . | where { $_.PSISContainer -and @( $_ | gci ).Count -eq 0 } | ri

reference: http://stackoverflow.com/questions/7831286/how-to-delete-empty-folders-using-windows-command-prompt

**Comment by prashant-mandhare04** [comment] 2016-05-30 14:39
+1 for not leaving empty directories behind.... it's indeed very troublesome over long period of sync

**Comment by Wowfunhappy** [comment] 2016-07-19 15:01
Any chance this could get added to the 1.34 milestone? It's been sitting in "soon" for six months now. :)

**Comment by mclassdesigns** [comment] 2016-09-03 09:27
Empty directories are also not being deleted on OneDrive. Otherwise, amazing tool!

**Comment by peixotorms** [comment] 2016-09-07 16:14
+1 for this, please.

**Comment by ponyesteves** [comment] 2016-09-08 02:09
+1 for this feature! Great tool

**Comment by memeplex** [comment] 2016-09-08 03:49
Please add a thumbs up instead of replying +1. This way the developer will be aware of the number of votes for the feature and less likely to close the issue to further comments. Also interested subscribers won't receive uninteresting comments.

**Comment by scriptzteam** [comment] 2016-10-07 11:28
what about we will have something in rclone like this:

`rclone move ...` will got option `rclone move --delete ...` possible?

**Comment by lynndixon** [comment] 2016-10-14 04:53
I would really like to see the ability of files to be deleted from the destination via sync when they are no longer on the source.  I added my thumbs up as well.

**Comment by ncw** [comment] 2016-10-28 16:29
I wrote a little script to delete all empty dirs under a remote: http://pub.rclone.org/rclone-delete-empty-dirs.py3

Run it with python3.

Use the --dry-run flag with it first to see what it does.

It isn't very efficient but should get the job done. You may need to run it more than once if you have empty directories within other directories that only have empty directories in.

I'll probably integrate the logic into rclone into a new command, maybe `rclone rmdirs` or something like that.

**Comment by lanrat** [comment] 2016-10-28 16:50
I can't access http://pub.rclone.org/rclone-delete-empty-dirs.py3 it gives a 404.

**Comment by cemsbr** [comment] 2016-10-29 06:58
The lsd command in the script of @nsw fails for me. Executing it outside the script gives the message `level value not supported`.

**Comment by calisro** [comment] 2016-10-31 18:15
I wish I would have saw the python script... but for anyone else wanting a work around.  Here is a pure bash one.  It uses a rclone mount and then deletes from acd directly. 

/data/Media is a rclone mount I created.

TMPFILE=/tmp/somefile

find /data/Media2/Videos  -type d -empty | sed 's/\/data\/Media2/rclone  rmdir robacd-crypt:/' | xargs -0 echo| tee $TMPFILE
bash -x $TMPFILE
rm -f $TMPFILE

**Comment by ShapeShifter499** [comment] 2016-11-03 12:25
New to this issue...    

Shouldn't there be a 1:1 sync option?   ANY changes on source leads to a mirrored change on remote?   

For example, I remove a directory completely on source and next time I run rclone sync it removes that directory on remote.  But if a directory is empty on source it gets created as a empty directory on remote.

**Comment by calisro** [comment] 2016-11-03 13:54
@ShapeShifter499  That is the way the 'sync' option works.  The only caveat is there are issues handling directories right now which will get taken care of at some point.

**Comment by ShapeShifter499** [comment] 2016-11-03 17:03
@calisro Maybe I should file a new issue then?  ACD sync doesn't delete files or folders on remote when source changes.

**Comment by ncw** [comment] 2016-11-06 16:42
@lanrat that download works for me - try again!

@cemsbr 
> The lsd command in the script of @ncw fails for me. Executing it outside the script gives the message level value not supported.

That indicates you are using an old version of rclone - you'll need to upgrade.

**Comment by cemsbr** [comment] 2016-11-08 23:13
I used 1.33. I'm waiting 1.34 to available in Archlinux.

**Comment by nrk666** [comment] 2016-11-19 23:40
This python script seems to have some logic problems, I think relating to the root cause. I had some directories nested with empty directories and it tried to delete the top level directory (with nothing inside it but and empty directory) before deleting the empty directory inside itself, then error'd out with "Directory Not Empty" which was true. Wow, even I think that sentence is impossible to follow. 

acd:FOLDER
           - SomeFolder
                     - Some Other Folder (empty)

The python script tried to delete "SomeFolder" before deleting "Some Other Folder" and caused an error because "SomeFolder" was not empty (which was true). 

I ran "python3 <script> acd:FOLDER".

**Comment by cemsbr** [comment] 2016-11-21 20:28
With version 1.34-DEV, it fails the same way as my previous post.

**Comment by ncw** [comment] 2016-11-27 11:53
I've made a new `rclone rmdirs` command which will delete any empty directories (in a nested way) from a remote.

You can try it in this beta: http://beta.rclone.org/v1.34-25-gf3365dd/ (uploaded in 15-30 mins)

Use it like this

    rclone rmdirs --dry-run remote:

When happy then do

    rclone rmdirs remote:

**Comment by ncw** [comment] 2016-11-27 18:45
Oops messed up the build: try http://beta.rclone.org/v1.34-30-g943a093/ (uploaded in 15-30 mins)

**Comment by ncw** [comment] 2016-11-28 14:58
Third time lucky: http://beta.rclone.org/v1.34-36-g539853d/

**Comment by philip-ulrich** [comment] 2016-11-30 04:46
So this seems to address removing empty folders, but I am noticing that the files and folders not on my local and on my remote aren't being removed on sync. If it matters, my remote is B2. Is this a limitation of their object storage?

**Comment by cemsbr** [comment] 2016-11-30 12:39
Worked for me. Took 27 minutes in the first run for dropbox. After running for the first time, total objects and size are still the same, but a dry run doesn't show anything left.

**Comment by calisro** [comment] 2016-12-05 14:16
When using rmdirs, I am seeing errors that hte directories are not found.  

2016/12/05 09:07:40 .unionfs/Pictures/Downloaded Albums/lindasnotepad: Failed to rmdir: directory not found
2016/12/05 09:07:40 Attempt 1/3 failed with 1 errors and: directory not found
2016/12/05 09:08:27 

I don't have anything else running deleting the directories.

**Comment by ncw** [comment] 2016-12-06 12:18
@calisro I can confirm that.  Should be easy to fix - will post a beta here!

**Comment by ncw** [comment] 2016-12-06 15:17
@calisro I've fixed that in http://beta.rclone.org/v1.34-51-gcb9f1ee/ (uploaded in 15-30 mins)

**Comment by Wowfunhappy** [comment] 2016-12-06 15:22
Is there any reason to not do rmdirs automatically and the end of a sync?

Correct me if I'm wrong, but empty directories can't be created with rclone to begin with, so the only way an empty directory could appear is if it's contents were deleted, in which case we probably want the empty directory removed as well.

**Comment by calisro** [comment] 2016-12-06 16:26
@ncw Seems better now.  Thanks.

**Comment by Wowfunhappy** [comment] 2016-12-07 22:29
Whereas the older beta worked beautifully for me, the newer one seems to not actually be deleting my empty folders...

**Comment by tuanjr** [comment] 2016-12-08 21:56
(Sorry for my english bad)
i really love this soft, only problem that it can't delete empty folder after sync
i tried rclone rmdir but failed
but i have many many empty folder like that: /folder1/folder2(empty)/folder3(empty)

**Comment by Fmstrat** [comment] 2016-12-11 22:09
Does rmdirs remove ALL empty directories? Or just empty directories that do not exist in the source? The latter is what I think is really required as there are many, many use cases where empty directories are required.

**Comment by Wowfunhappy** [comment] 2016-12-19 02:07
@fmstrat rmdirs removes all empty directories. Rclone doesn't really support empty directories atm—empty directories on source won't get synced to begin with. NCW has stated that he intends to support empty directories at some point, but rmdirs was added as an easy stop-gap.

**Comment by karan** [comment] 2016-12-27 02:26
`rmdirs` fails for me now:

```
2016/12/26 18:23:02 Failed to rmdirs: directory not empty: []*drive.ChildReference{(*drive.ChildReference)(0xc420664000), (*drive.ChildReference)(0xc420664080), (*drive.ChildReference)(0xc420664100), (*drive.ChildReference)(0xc420664480)}
```

It used to work until last week with `v1.34-36-g539853dβ`. Then it stopped working so I updated the binary. I'm on the latest beta version: 

```
$ rclone --version
rclone v1.34-75-gcbfec0dβ
```

The remote is a folder in Google Drive, and I have confirmed that it is empty.

**Comment by dendenis82** [comment] 2016-12-27 14:30
if for the first: rmdirs remote:
then               sync local: remote:

will last line add again all empty folders(which is needed by some software) to remote?

**Comment by eharris** [comment] 2016-12-30 11:05
I agree that preserving empty folders is necessary in some cases, and the interim solution of optionally deleting all empty directories is a reasonable temporary workaround.

One of the issues mentioned as an explanation of why directories aren't already handled properly was that some backends don't have any concept of them, and this resulted in a common interface that also disregarded them.

Even for backends that don't support the concept of folders, I don't think there should be any reason why they can't be tracked and emulated properly by the rclone code for those backends.  Just a couple of possibilities that come immediately to mind:

1. Creating a placeholder file (like somedir/._empty_) that is otherwise ignored by rclone except to mark that a directory exists.  Potential collisions can be avoided by making the name of the placeholder file configurable per storage destination.  For destinations that support some form of metadata tagging of files, they could also be explicitly marked with that somehow to remove any possible ambiguity.

2. Creating a special file under the parent directory of any empty directories that contains a list of all the empty directories under it.  Again, this special file would be ignored by other normal operations.  This one has the possible benefit that the file may only be needed in the parent of the lowest level of a chain of otherwise empty directories, as the file itself would mark the tree above that as existing.  However that might complicate the implementation enough not to be worth it.

**Comment by Wowfunhappy** [comment] 2017-01-04 20:55
> Creating a placeholder file (like somedir/._empty_) that is otherwise ignored by rclone except to mark that a directory exists.

In the event that such invisible placeholder files will not interfere with your use case, you can do this yourself with Bash. Before running rclone, cd into your directory and type:
`find . -type d -empty -exec touch {}/.keep \;`
[Source](http://cavaliercoder.com/blog/recursively-create-gitkeep-files.html)

NCW has said in the past he'd prefer not to create/store rclone-specific files on remotes, and I generally agree with this approach. It's easy enough to tell rclone to ignore a given file, but what about other programs? What about users going through the remote's native web interface?

**Comment by gordan-bobic** [comment] 2017-01-07 15:50
I don't think there is any disadvantage to keeping rclone specifics on remotes if the directories are encrypted because there is nothing else directly compatible with rclone's encryption (e.g. ecryptfs and encfs).

**Comment by Wowfunhappy** [comment] 2017-01-07 16:49
If you're using Crypt, I agree, but that's only a subset of use cases.

**Comment by calisro** [comment] 2017-01-07 16:58
I wouldn't agree.  it would screw up file counts.  and "crypt" isn't propietery to rclone.  Files shouldn't store metadata and shouldn't be directory placeholders.  just my two cents. :)

**Comment by gordan-bobic** [comment] 2017-01-07 17:56
It is proprietary in the sense that there is no other software that can decrypt the files and file names. There is nothing stopping you from using the same library to implement a codec of your own that can read them, but it is proprietary in the sense that no other similar software can decode the data (e.g. ecryptfs or encfs).

**Comment by calisro** [comment] 2017-01-07 18:28
Look up the word proprietary.  It is ownership.  crypt isn't proprietery.  It is opensource.  And its used in many tools.  Anyone can write code to decrypt the data. This is off-topic though.

**Comment by gordan-bobic** [comment] 2017-01-07 18:35
OK, then:
s/proprietary/incompatible with all other currently available stackable file system encryption methods/

**Comment by kazeuraki** [comment] 2017-01-16 10:44
https://github.com/ncw/rclone/issues/100#issuecomment-269259482
Same with this guy. 
`Failed to rmdirs: directory not empty: (*drive.ChildReference)(0xc420664480)}`
Empty folder A in folder B (dont have any file, just empty folder)

**Comment by balazer** [comment] 2017-01-16 22:12
@ncw, rmdirs is working well for me in v1.35-33-g47ebd07 with Google Drive.  Thank you!

One thing I noticed is that the command line help says 
> rmdirs          Remove any empty directoryies under the path.
But the command will remove the path itself also, not just the directories under the path.  Also 'directories' is misspelled.

**Comment by balazer** [comment] 2017-01-16 23:40
@ncw, using rmdirs in rclone v1.35-33-g47ebd07 I'm experiencing the same `Failed to rmdirs: directory not empty` errors as others.  The directory appears to be empty.

The problem is that the directory contained an item that had been moved to the trash.  Once the item is deleted from the trash, then rmdirs works without errors.

**Comment by Stele77** [comment] 2017-03-11 17:07
Hey, i am just a noob, so i dont know about the technical backgrounds.. But Rclone not syncing empty folders is sadly a deal breaker for my usecase: Backup of my NAS-Shares to ACD. 
This messes up my folder structure, and is even more sad IMHO, because RClone works so flawless otherwise. 
I understand from this or other issue tickets, that many others would want to auto delete empty dirs, but others like me would need them to be synced.

IMHO it would be a viable solution to offer a switch, to let the users decide, how they want to handle this.

I think i am not alone with my workflow need for exact backup, and it otherwise breaks the purpose of this ingenious tool. And it es even more annoying, because new users and noobs like me will struggle, and many wont find the answer here. So everyone not so tech savy and geeky has a problem.. 

Just my 2 cents..

PS: Just saw another user opening a new ticket on the same problem: 
https://github.com/ncw/rclone/issues/1228

**Comment by Fmstrat** [comment] 2017-03-12 11:41
@Stele77 An easy way for this not to be a deal-breaker:

    find /tmp/A -type d -empty -printf "mkdir -p \"%p\";chown %u:%g \"%p\";chmod %m \"%p\"\n" > /tmp/A/rclone-restore-empty-directories.sh;

Run that before you backup to ACD. It's a one-liner that makes a script to restore your empty directories with ownership and permission. It will backup to ACD, so if you ever have to restore, you just run it after the restore completes.

Of course, replace `/tmp/A` with your backup folder.

**Comment by ncw** [comment] 2017-03-13 11:31
I've put this issue on the 1.37 milestone since all the pieces are in place now :-)

**Comment by vesper8** [comment] 2017-03-29 04:29
couldn't we have some enhanced functionality in combination with --delete-excluded so that an rmdir on exlcluded directories is attempted in each folder?

rmdirs could be removing empty directories that i don't want to remove, i only want to remove the ones that are listed in my excluded-filter

**Comment by mehargags** [comment] 2017-04-02 06:02
sorry to nudge this thread, but I needed an urgent help to sync all my directory strcuture to Google Drive.
Have also opened a new thread  [Sync subdirectories recursively excluding some](url=https://forum.rclone.org/t/sync-subdirectories-recursively-excluding-some/1574)

I have a deep directory structure with 1000s of images inside 100s of subdirectories to be sync'd recursively to my Google Drive, but leaving out ./cache and ./thumbnails directory.

## Issue #1 rClone does not copy subdirectories
`rclone sync /synctest/images GDrive:/images`
this ... only sync files in the dir specified
Why is it not sync'ng and creating the directory structure ? What arguments need to be passed to sync all subdir recursive?

## issue #2 How to exclude certain directories
is this right ?
`rclone sync /synctest/images GDrive:/images --exclude "/thumbnails/**"`

I read you can make and load and exclusion file... but if I only need to exclude one or two directories, what will be the right parameter to pass ?

Thanks

**Comment by RolluS** [comment] 2017-04-08 08:34
@mehargags you should open your own issue for subdir, or go to the community forum to have help about exclusion.

Back to the folder issue/feature: I like to work either on the web interface of my cloud provider, or, on a mounted remote.
In the mounted remote, deleting empty folder is as simple as run `find -type d -empty - delete` !

BTW, when moving files from a remote to another one, empty folder are not cleaned.

**Comment by ncw** [comment] 2017-04-10 11:21
@RolluS note that you can delete empty directories with `rclone rmdirs` now (note extra s).

https://rclone.org/commands/rclone_rmdirs/

**Comment by ncw** [comment] 2017-08-09 22:10
Here is a beta which should fix the problem and delete empty directories.  It does this after the sync phase provided there were no IO errors.

https://beta.rclone.org/v1.37-082-g265fb8a5/ (uploaded in 15-30 mins)

Let me know if you find any problems with it!

**Closed** 2017-08-09 22:10 UTC
Labels: enhancement

**Comment by netinial** [comment] 2017-09-18 15:42
I confirm that there are still same issue for GDrive, (leaving empty folders.)

**Comment by winternet-studio** [comment] 2017-09-20 17:28
If anyone is interested in a PHP script that will ensure an exact copy by removing folders on the destination that no longer exist in the source I have posted one here: https://github.com/ncw/rclone/issues/1642#issuecomment-330922123

**Comment by temporaryMan1233** [comment] 2017-11-19 13:35
What's the current progress on syncing empty folders?

**Comment by adrianog** [comment] 2017-12-11 15:27
@ncw why is this the case: "provided there were no IO errors"?

Should we not (attempt to) remove directories from destination regardless, if they are not in the source, irrespective of previous IO errors?

**Comment by ncw** [comment] 2017-12-12 09:09
@adrianog "IO errors" can mean the source was read wrong.  If you read an empty directory incorrectly in the source, you don't want to delete  stuff in the destination.  The same logic doesn't quite apply for source directories, but I'd like to keep the logic the same, as in "IO errors" mean no deletions.

**Comment by archon810** [comment] 2019-08-03 22:08
https://rclone.org/bugs/ refers to this ticket and should probably be updated.

**Comment by ncw** [comment] 2019-08-04 10:28
> https://rclone.org/bugs/ refers to this ticket and should probably be updated.

Well spotted!  I haven't looked at that bugs page for years!

**Comment by trademark18** [comment] 2020-11-06 16:01
Is there a workaround for this?  In my use case I recursively process files in each directory, then when it's empty, I'd like to delete the "folder" on IBM COS.  I've tried various versions of `rmdirs` or `rmdir` and nothing at all seems to delete that "folder" on the ICOS console.  Any info on how to run a command to delete the "folder" on ICOS would be appreciated.

**Comment by ncw** [comment] 2020-11-06 17:40
> Is there a workaround for this? In my use case I recursively process files in each directory, then when it's empty, I'd like to delete the "folder" on IBM COS. I've tried various versions of `rmdirs` or `rmdir` and nothing at all seems to delete that "folder" on the ICOS console. Any info on how to run a command to delete the "folder" on ICOS would be appreciated.

I suspect that there is a 0 sized directory marker object that rclone is ignoring.

You should find that `rclone purge icos:bucket/path/to/folder` will remove it. However be careful with purge - it really will delete everything!

**Comment by trademark18** [comment] 2020-11-06 18:43
@ncw Thanks for the tip.  I tried it and sadly I got the same result.  Oddly I'm not having this issue on a "Standard" bucket, but only on "Smart Tier" buckets.  Maybe those are different under the hood?

**Comment by ncw** [comment] 2020-11-09 12:34
> @ncw Thanks for the tip. I tried it and sadly I got the same result. Oddly I'm not having this issue on a "Standard" bucket, but only on "Smart Tier" buckets. Maybe those are different under the hood?

I remembered wrong - sorry! The S3 backend doesn't support Purge. I suspect this directory was created with something other than rclone - is that correct?

**Comment by trademark18** [comment] 2020-11-16 14:12
@ncw Yes, the directories were created by an Aspera upload.

**Comment by ncw** [comment] 2020-11-16 14:42
> @ncw Yes, the directories were created by an Aspera upload.

What will have happened is that "directory markers" have been created. These are empty files with names like `dir/`. Rclone doesn't deal with these properly at the moment.

If you would like to make a new issue @trademark18 then we can get `rclone purge` to remove them fairly easily which would be a step forward.
