### ISSUE TITLE
Certain files consistently failing to upload to Amazon Cloud Drive.

### ISSUE THREAD

**Issue by Wowfunhappy** [ncw/rclone#183] opened 2015-10-30 03:56 UTC
Hi! I'm trying to use rclone to back up a huge (500GB+) folder with tons of different files to Amazon Cloud Drive. It's working pretty well, but a couple of files seem to be consistently failing to upload. They'll get to around 70-90%, and then fail with the error:

<date> <time> <file-path>: Failed to copy: Post https://content-na.drive.amazonaws.com/cdproxy/nodes?suppress=deduplication: read tcp 172.16.51.149:52885->54.210.227.73:443: read: no route to host

After the error, rclone simply ignores the problem-files and moves on to others. However, it tries again every time I re-run the program (aka after I need to reboot the computer), and always fails on the same files with the same error.

There's nothing overly special about the problem files as far as I can tell, except that they all seem to be among the larger files I'm trying to back up (2GB+).

Thanks a lot, and please let me know if you need any more information!

**Comment by ncw** [comment] 2015-10-30 08:16
Files bigger than 2gb is suspicious...

Which OS are you using and is  it 32 or 64 bit?

Do any files bigger than 2gb transfer Ok? 

"no route to host" is a very odd error and normally only caused by networking problems. I wonder if your Nat gateway or ISP gave up at 2gb for some reason.

What is the make/model of your router/gateway and who is your isp? 

I'll try to reproduce but if you could answer the above that would be very helpful. 

Thanks

Nick

**Comment by klauspost** [comment] 2015-10-30 09:04
Are you on wireless network? "no route to host" indicates that the connection was dropped somewhere.

I have uploaded many 10+GB files, so it isn't a general problem.

**Comment by ncw** [comment] 2015-10-30 10:54
@klauspost I tried uploading a 5GB file with both a 32 bit and 64 bit version of rclone and both worked fine.

@Wowfunhappy My top suspect would be your ISP killing the connection for some shaping reasons or the NAT box blowing up (just because!).

Unfortunately ACD doesn't have chunked upload either so we can't avoid the very large single TCP connection.

**Comment by Wowfunhappy** [comment] 2015-10-30 12:24
I'm using a college wifi network, so I suppose that could be the problem. However, I've been able to upload 5 GB files without problems.

**Comment by Wowfunhappy** [comment] 2015-10-30 12:28
Oops, forgot to mention, I'm using OS X El Capitan, which is 64-bit. College gets internet from Time Warner Cable.

**Comment by klauspost** [comment] 2015-10-30 12:37
Wireless disconnects can happen for very short intervals, even if coverage is generally good.

If you don't want it to happen, wired network is the way to go. 

As a side-note, rclone will automatically retry the interrupted files up to 3 times, after it has tried transferring all files, so if you just leave it running, they should be uploaded at some point.

**Comment by Wowfunhappy** [comment] 2015-10-30 12:44
But why would the connection always be dropped when trying to upload the exact same files? This has happened at least five times now.

And while these are among the larger files I'm trying to upload, I've uploaded larger ones without problems.

I'm going to try using a wired connection later today to see if it make a difference.

**Comment by Wowfunhappy** [comment] 2015-10-31 00:17
Ethernet fixed the issue, so somehow or other this appears to have been a problem on my end. Sorry, and thanks for your help!

**Comment by ncw** [comment] 2015-11-01 20:53
Glad we got to the bottom of it and thanks for your help working it out. In future Amazon have said they will do a better API for uploading files, but until then you'll have to stick to the Ethernet!

**Closed by ncw** 2015-11-01 20:53 UTC
