### ISSUE TITLE
onedrive for business: implement quickXorHash

### ISSUE THREAD

**Issue by edkedk** [ncw/rclone#2262] opened 2018-04-18 19:13 UTC
Onedrive for Business only supports quickXorHash as a checksumming method but rclone does not implement that yet.
Also, documentation should mention that only Onedrive Personal supports SHA1.

#### What is the problem you are having with rclone?

No hashes on Onedrive for Business

#### What is your rclone version (eg output from `rclone -V`)

1.39

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows 7, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)

Onedrive for Business

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone.exe sha1sum OD:Test

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
2018/04/17 18:12:20 DEBUG : Using config file from "C:\\Users\\edk\\.config\\rcl
one\\rclone.conf"
2018/04/17 18:12:20 DEBUG : rclone: Version "v1.39" starting with parameters ["r
clone.exe" "-vv" "sha1sum" "OD:Test"]
2018/04/17 18:12:20 DEBUG : One drive root 'Test': Token expired but no uploads
in progress - doing nothing
2018/04/17 18:12:22 DEBUG : Keeping previous permissions for config file: -rw-rw
-rw-
2018/04/17 18:12:22 DEBUG : OD: Saved new token in config file
2018/04/17 18:12:24 INFO  : One drive root 'Test': Modify window is 1s
                                          GPU-Z.0.6.6.exe
                                          cpuz-readme.txt
                                          cpuz.exe
                                          cpuz.ini
                                          latency.exe
2018/04/17 18:12:25 DEBUG : Go routines at exit 7
2018/04/17 18:12:25 DEBUG : rclone: Version "v1.39" finishing with parameters ["
rclone.exe" "-vv" "sha1sum" "OD:Test"]
```

**Comment by ncw** [comment] 2018-04-19 07:14
According to the [onedrive docs for this](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/resources/hashes#remarks):

> In OneDrive for Business and SharePoint Server 2016, sha1Hash and crc32Hash are not available.
>
> In OneDrive Personal, quickXorHash is not available.

So looks like in OneDrive for Business only [quickXorHash](https://docs.microsoft.com/en-us/onedrive/developer/code-snippets/quickxorhash) is available.

So rclone could implement that.

At the very least we need to document where the hash is available.  We know at runtime whether it is a business Onedrive or not so we can alter the output from `Hashes` and `Hash`.

@edkedk can you do this for me? I need some test vectors for quickXorHash and I don't currently have access to a onedrive for business account :-(

[test_vectors.zip](https://github.com/ncw/rclone/files/1926984/test_vectors.zip)

```
unzip test_vectors.zip
rclone copy test_vectors onedrive:test_vectors
rclone size -vv --dump bodies onedrive:test_vectors --log-file test_vectors.log
```

Then zip `test_vectors.log` and attach the zipped version here.  I only need the last response which will be large and full of JSON if you want to edit it for privacy. If you prefer you can email it to me nick@craig-wood.com - Thanks!

**Comment by ncw** [comment] 2018-04-19 19:56
@edkedk no, I forgot the -R flag on zip :blush: 

Here it is again!

[test_vectors.zip](https://github.com/ncw/rclone/files/1929567/test_vectors.zip)

**Comment by edkedk** [comment] 2018-04-19 20:05
I emailed you the log.

**Comment by ncw** [comment] 2018-04-19 22:26
Thank you very much :-)  I'll have a go at porting the quickXorHash from c# to go.

**Comment by edkedk** [comment] 2018-04-20 19:28
I think it works perfectly!

```
C:\...3cbe4-quickxorhash-windows-amd64>check d:\test OD5006:Test -vv --checksum
2018/04/20 21:25:38 DEBUG : rclone: Version "v1.40-098-gae03cbe4-quickxorhash" s
tarting with parameters ["rclone.exe" "check" "d:\\test" "OD5006:Test" "-vv" "--
checksum"]
2018/04/20 21:25:38 DEBUG : Using config file from "C:\\Users\\edk\\.config\\rcl
one\\rclone.conf"
2018/04/20 21:25:39 INFO  : One drive root 'Test': Modify window is 1s
2018/04/20 21:25:39 INFO  : One drive root 'Test': Waiting for checks to finish
2018/04/20 21:25:40 DEBUG : cpuz-readme.txt: OK
2018/04/20 21:25:40 DEBUG : cpuz.exe: OK
2018/04/20 21:25:40 DEBUG : cpuz.ini: OK
2018/04/20 21:25:40 DEBUG : GPU-Z.0.6.6.exe: OK
2018/04/20 21:25:40 DEBUG : latency.exe: OK
2018/04/20 21:25:40 NOTICE: One drive root 'Test': 0 differences found
2018/04/20 21:25:40 DEBUG : 5 go routines active
2018/04/20 21:25:40 DEBUG : rclone: Version "v1.40-098-gae03cbe4-quickxorhash" f
inishing with parameters ["rclone.exe" "check" "d:\\test" "OD5006:Test" "-vv" "-
-checksum"]
```

If I change a file (but not the modification time), I get
```
2018/04/20 21:22:38 DEBUG : cpuz-readme.txt: OK
2018/04/20 21:22:38 DEBUG : cpuz.exe: OK
2018/04/20 21:22:38 DEBUG : cpuz.ini: QuickXorHash = 54d1f773a0160e52ca1247d1420
8820733f049fc (Local file system at \\?\d:\test)
2018/04/20 21:22:38 DEBUG : cpuz.ini: QuickXorHash = 54d1f773a0160e52ca1247d1420
8820723f049fc (One drive root 'Test')
2018/04/20 21:22:38 ERROR : cpuz.ini: QuickXorHash differ
2018/04/20 21:22:38 DEBUG : GPU-Z.0.6.6.exe: OK
2018/04/20 21:22:38 DEBUG : latency.exe: OK
2018/04/20 21:22:38 NOTICE: One drive root 'Test': 1 differences found
2018/04/20 21:22:38 Failed to check: 1 differences found
```

Many thanks for your quick action!

**Comment by ncw** [comment] 2018-04-20 20:04
Excellent!  Thanks for testing.  It is my favourite kind of coding implementing hash functions and other crypto stuff so I couldn't resist staying up late to do it ;-)

I've merged that here

https://beta.rclone.org/v1.40-102-g1a3fb21a/ (uploaded in 15-30 mins)

and it will be in [the latest beta](https://beta.rclone.org) from now on and in the 1.41 release.

**Closed** 2018-04-20 20:04 UTC
Labels: Remote: One Drive, doc fix, enhancement

**Comment by ccchan234** [comment] 2018-11-30 17:32
Hi~

I use win7+rclone 64b v1.43

I just wanna rclone check g-suite:/folder1 vs onedrive-business:/folder1

And got that "hash could not be checked" for the ondrive-business.

I googled for rclone and read that for onedrive-business, only XXXXhash is available
and the post directed me here.

As I am already using v1.43, isn't 2 posts above said this is implemented?

thanks.

**Comment by Cnly** [comment] 2018-11-30 17:58
@ccchan234 The problem is that QuickXorHash is Microsoft only; GDrive doesn't have it. I think these two lines from the manual may help you:

```
If you supply the --size-only flag, it will only compare the sizes not the hashes as well.  Use this for a quick check.
If you supply the --download flag, it will download the data from both remotes and check them against each other on the fly.
    This can be useful for remotes that don't support hashes or if you really want to check all the data.
```

**Comment by ccchan234** [comment] 2018-12-01 10:51
> @ccchan234 The problem is that QuickXorHash is Microsoft only; GDrive doesn't have it. I think these two lines from the manual may help you:
> 
> ```
> If you supply the --size-only flag, it will only compare the sizes not the hashes as well.  Use this for a quick check.
> If you supply the --download flag, it will download the data from both remotes and check them against each other on the fly.
>     This can be useful for remotes that don't support hashes or if you really want to check all the data.
> ```

Hi~
my problem:
paranoid that gdrive could dead due to terrorist/hardware failure/my admin eror etc.

my solution:
rclone them to onedrive, 5TB by 5TB.

of course after rclone copy, I need to VERIFY the checksum.

problem now:
onedrive dunt support checksum calculation....

solution:
I just learnt to use "rclone mount" to mount onedrive as a drive. (u could use win10 and onedrive on demand, but it's NA for me who using win7).
Then use beyond compare or other software to verify the checksum manually.
Yest that would be terrible because say beyond compare need to dnld both and calculate checksum.

But for this moment, to protect me from google drive failure (seems happen before?).
This is my cheapest and readily solution.

Thanks all. Thanks author of rclone and others.

**Comment by ccchan234** [comment] 2018-12-01 10:57
I must say that,
for many times i THINK 2 folders are the same.

Yet when I use "beyond compare" to check,
there is lot of files missing. (I dunt mean rclone, i mean for some reason, could be my error).

But no matter how it would be good to use a 2nd mean to verify that the file processing is correct.

**Comment by landall** [comment] 2019-10-24 17:22
Onedrive Personal start to provide QuickXorHash now.

**Comment by ncw** [comment] 2019-10-25 12:53
> Onedrive Personal start to provide QuickXorHash now.

As well as SHA1?  SHA1 is a much better hash than QuickXorHash so if it supplies both I'd rather keep using the SHA1.

Do you have a link for the above statement?

**Comment by landall** [comment] 2019-10-25 19:21
> > Onedrive Personal start to provide QuickXorHash now.
> 
> As well as SHA1? SHA1 is a much better hash than QuickXorHash so if it supplies both I'd rather keep using the SHA1.
> 
> Do you have a link for the above statement?

No statement now but I have seen it from the result of Microsoft Graph API Call.
This feature (at least one same hashsum between OD and OD4B) have a high vote in office dev  uservoice. 
I think it may be under way to calculate all the quickxorhash of the exist documents.

**Comment by rpet** [comment] 2023-03-21 21:27
> > Onedrive Personal start to provide QuickXorHash now.
> 
> As well as SHA1? SHA1 is a much better hash than QuickXorHash so if it supplies both I'd rather keep using the SHA1.
> 
> Do you have a link for the above statement?

There's a statement about that in https://learn.microsoft.com/en-us/onedrive/developer/rest-api/resources/hashes#remarks :

> Note starting from July 2023 quickXorHash will be the only available property for both OneDrive for Business and OneDriver Personal. Everything else mentioned below is still valid until that date.
> 
> In OneDrive for Business and SharePoint Server 2016, sha1Hash and crc32Hash are not available.
> 
> In OneDrive Personal, quickXorHash is not available.
>

**Comment by rpet** [comment] 2023-03-21 21:53
Nevermind, I've just realized that quickXorHash is already supported:

```
$ rclone hashsum
Supported hashes are:
  * MD5
  * SHA-1
  * Whirlpool
  * CRC-32
  * DropboxHash
  * MailruHash
  * QuickXorHash
```

```
$ rclone lsf onedrive:temp --format=ph --hash=QuickXorHash
hola.docx;075c21d8305768e88646933d01574b9230a0efed
```

**Comment by landall** [comment] 2023-07-27 17:19
> > Onedrive Personal start to provide QuickXorHash now.
> 
> As well as SHA1? SHA1 is a much better hash than QuickXorHash so if it supplies both I'd rather keep using the SHA1.
> 
> Do you have a link for the above statement?

You have no choice now. QuickXorHash is the only answer.
