### ISSUE TITLE
TCP timeout issue

### ISSUE THREAD

**Issue by pharveybattelle** [ncw/rclone#2057] opened 2018-02-09 16:34 UTC
From https://forum.rclone.org/t/tcp-timeout-issue/4782/2

tested with multiple versions of rclone including 1.39 (current version) and 1.39-125 (current beta)

when tcp read connections stop sending data rclone successfully detects and recovers if --time-out=1m but not with the default setting (5m)

Tested on Dell R7910 workstation running Windows 10 with all current MS updates, latest Intel X540 NIC driver.
Tested against a DellEMC ECS
Attached logs showing the timeout setting at 1m and recovering from a tcp i/o error and with the timeout setting at 5m and not recovering (at about 30 minutes I killed rclone since it was never going to complete)
Interestingly in the 5m file it did detect a few of the dead connections but not all of them.

[rclone1m.log](https://github.com/ncw/rclone/files/1711674/rclone1m.log)
[rclone5m.log](https://github.com/ncw/rclone/files/1711697/rclone5m.log)

**Comment by ncw** [comment] 2018-02-10 16:05
Very interesting logs thanks.  That must be the fastest rclone transfer I've seen so far!

All the files which stalled are big files and so are using chunked uploads in the S3 uploader.  These should be 5 MB chunks by default I think.

So it seems that the problem is probably not the passing of the chunks but the negotiation for the next one.

Can you run `nbtstat -n -o` when rclone has stopped transferring any data?  That should show whether rclone has any open connections or not.

Also if you could run a failing transfer with `-vv --dump headers` this will print a lot of stuff, but will enable me to work out if rclone has failed during the transfer of a block, or after a transfer.

**Comment by pharveybattelle** [comment] 2018-02-12 17:57
as requested:
rclone does have connections open when it gets hung downloads.
880 is the PID of rclone.exe in the below output and the 4 connections correspond to the 4 hung downloads in the attached log.  10.206.21.171 is the IP of the load balancer (HAProxy) in front of the ECS.

I killed rclone after 30 minutes, the last 8 minutes no data was transferred. (or at least nothing measurable, in a packet capture I did I saw a couple of ssl packets that looked like they might be data, but they were only like 1 packet every 2 minutes which didn't make any sense except to possibly explain why it doesn't time out...)

[rclone.log](https://github.com/ncw/rclone/files/1717222/rclone.log)

C:\WINDOWS\system32>netstat -n -o
Active Connections
  Proto  Local Address          Foreign Address        State           PID
  TCP    10.206.51.203:51826    10.206.21.171:443      ESTABLISHED     880
  TCP    10.206.51.203:51833    10.206.21.171:443      ESTABLISHED     880
  TCP    10.206.51.203:51835    10.206.21.171:443      ESTABLISHED     880
  TCP    10.206.51.203:51849    10.206.21.171:443      ESTABLISHED     880

I have managed to reproduce the issue on Server 2016 and on different hardware.

**Comment by ncw** [comment] 2018-02-13 17:43
Thanks for the log.

I'll analyse that and get back to you!

**Comment by ncw** [comment] 2018-02-14 12:41
OK what it looks like to me is that for the 4 stuck files
  * rclone sent a GET request
  * rclone received a response header
  * rclone started streaming the data
  * at some point the data stopped streaming
  * rclone did **not** timeout
  * The 4 open sockets in your nestat are the 4 open files

rclone is definitely supposed to timeout in this scenario so that is a bug!

Why the data stops coming I don't know.

I stared at the code some more and I realised there is a way that the idle timeouts could be defeated - if the Read syscall returned 0 bytes.  It isn't supposed to do that, but it is theoretically allowed and maybe that is what is happening - if it returned after 120s (say) with no data then that would explain why the 1m timeout works but the 5m timeout doesn't.

Anyway, here is a beta with a fix for that in - I'd be grateful if you'd tell me whether it fixes the problem or not!

https://pub.rclone.org/v1.39-142-ga57704aa-fix-2057%CE%B2/

**Comment by pharveybattelle** [comment] 2018-02-14 18:12
Thanks for taking a look and trying this patch.  I re-tested but the result was the same.   Log file attached.

I wonder if the S3 system is sending the occasional packet, which I find somewhat difficult to believe, but from my  limited understanding of reading packet captures seems to be what is happening.  I attached a packet capture during the hung period filtered to the source/destination of the HAProxy in front of the storage system

[hung copies filtered.zip](https://github.com/ncw/rclone/files/1725168/hung.copies.filtered.zip)

[rclone.log](https://github.com/ncw/rclone/files/1725147/rclone.log)

**Comment by ncw** [comment] 2018-02-14 21:29
> Thanks for taking a look and trying this patch. I re-tested but the result was the same. Log file attached.

:-(

I had a look through the capture and the log file thank you.

It is difficult to tell exactly what that network activity is - there are TCP keepalives, and there are quite possibly SSL keepalives as well.  The log file looks very similar.

I've compiled another version of the code for you to test.  It should prints lots of

    2018/02/14 21:19:16 INFO  : 10.2.0.9:55368-77.73.1.210:443: nudgeDeadline(5m0s) n=4125 err=<nil>

If you could run it until it hangs then leave it for a bit (just like you have been doing) hopefully we'll see exactly what is happening!  What I want to see is whether when the transfers hang, we are still getting the nudgeDeadline messages and what they look like....

Thanks for your help :-)

https://pub.rclone.org/v1.39-143-g31db1f82-fix-2057%CE%B2/

**Comment by pharveybattelle** [comment] 2018-02-15 16:49
Thanks again for continuing to look into this.  It does indeed print a lot to the log, so much in fact that if I let rclone output to the console it can't go faster than 2Gbps.  If I write to a log it can achieve 10Gbps though and reproduce the issue.  It looks like a data packet is registered every 2 minutes, and I really can't figure out how this could be possible...???

[log end.zip](https://github.com/ncw/rclone/files/1728545/log.end.zip)
[log start.log](https://github.com/ncw/rclone/files/1728546/log.start.log)

**Comment by ncw** [comment] 2018-02-16 11:01
There is one connection left over at the end.  This seems to be sending 1 ethernet packet worth of data every 2 minutes which explains the 1m vs 5m timeout perfectly.

```
2018/02/15 08:41:04 INFO  : 10.206.51.203:60832-10.206.21.171:443: nudgeDeadline(5m0s) n=1460 err=<nil>
2018/02/15 08:43:04 INFO  : 10.206.51.203:60832-10.206.21.171:443: nudgeDeadline(5m0s) n=1460 err=<nil>
2018/02/15 08:45:05 INFO  : 10.206.51.203:60832-10.206.21.171:443: nudgeDeadline(5m0s) n=1460 err=<nil>
2018/02/15 08:47:05 INFO  : 10.206.51.203:60832-10.206.21.171:443: nudgeDeadline(5m0s) n=1460 err=<nil>
2018/02/15 08:49:05 INFO  : 10.206.51.203:60832-10.206.21.171:443: nudgeDeadline(5m0s) n=1460 err=<nil>
2018/02/15 08:51:06 INFO  : 10.206.51.203:60832-10.206.21.171:443: nudgeDeadline(5m0s) n=1460 err=<nil>
2018/02/15 08:53:06 INFO  : 10.206.51.203:60832-10.206.21.171:443: nudgeDeadline(5m0s) n=1460 err=<nil>
2018/02/15 08:55:06 INFO  : 10.206.51.203:60832-10.206.21.171:443: nudgeDeadline(5m0s) n=1460 err=<nil>
2018/02/15 08:57:07 INFO  : 10.206.51.203:60832-10.206.21.171:443: nudgeDeadline(5m0s) n=1460 err=<nil>
```

So why is this happening.... Here is some speculation...
  1. Some sort of bug in Windows or its drivers
    * Maybe unequal sharing of bandwidth of TCP connections
    * let's say there was a packet lost and a retry, perhaps Windows knocked the estimated speed of the TCP connection right back
    * however 1 packet per 2 minutes is too slow and it should speed up
  2. Some sort of bug in the sending appliance
  3. Some sort of bug in the go runtime
  4. Some sort of bug in rclone

I now think 4 is unlikely.  3 is a possibility though.  I grepped the go source code for anything which looked like a 2 minute timer and I only found one the `forcegcperiod` which is the maximum times between garbage collections.  It seems unlikely to be relevant but I'm not sure!

I compiled the very latest go which is the not quite released `go version go1.10rc2 linux/amd64`.  I then compiled rclone with that, so if there have been any relevant fixes in the go runtime you should have them

https://pub.rclone.org/v1.39-145-ga5c3bcc9%CE%B2/

It should show this when you run it

```
$ ./rclone versionrclone v1.39-145-ga5c3bcc9β
- os/arch: linux/amd64
- go version: go1.10rc2
```

Can you have a go with that please? I took the super excessive logging out BTW!

**Comment by pharveybattelle** [comment] 2018-02-16 17:21
The issue remained the same even after the code change, which leads me to believe that the 1 data packet received every 2 minutes might have a valid data payload, which seems almost unbelievable. We can't figure out how this could be possible.
We did make a break though though, we found that if we switched the kernel on the HAProxy servers that are in front of the ECS S3 alike system from UEK to RH that the issue no longer occurs.  We suspect it might be the Intel NIC driver but can't prove this since the drivers are not interchangeable.   We also found that if we talk straight to the ECS nodes bypassing the HAProxy servers that we can't reproduce the issue.   All this leads combined with the code change to only nudge the timer if valid data is received leads us to think that rclone was behaving correctly in not timing out the connection.  I assume that the change to check the data is valid before nudging the timer is an improvement to the code though.
I'm not sure if it makes sense to add some way to handle the case when the data rate drops below a threshold?   I'm thinking that this issue can be closed since it seems to have been proved to be external to rclone.  What are your thoughts?
Thanks for all your work on this.

**Comment by ncw** [comment] 2018-02-21 08:46
> The issue remained the same even after the code change

Thanks for testing it.

> which leads me to believe that the 1 data packet received every 2 minutes might have a valid data payload, which seems almost unbelievable. We can't figure out how this could be possible.

The logging indicated that it was about one packets worth of real data that was delivered through the TCP stack and through go's SSL layer.

> We did make a break though though, we found that if we switched the kernel on the HAProxy servers that are in front of the ECS S3 alike system from UEK to RH that the issue no longer occurs. We suspect it might be the Intel NIC driver but can't prove this since the drivers are not interchangeable. We also found that if we talk straight to the ECS nodes bypassing the HAProxy servers that we can't reproduce the issue

I would say this is consistent with the above.  Something to do with the network driver holding up packets somehow.

> All this leads combined with the code change to only nudge the timer if valid data is received leads us to think that rclone was behaving correctly in not timing out the connection.

That is my conclusion too.

> I assume that the change to check the data is valid before nudging the timer is an improvement to the code though.

Before the change it would have not timed out if the Read call returned 0 bytes which is allowed but unusual.

> I'm not sure if it makes sense to add some way to handle the case when the data rate drops below a threshold?

I was sure there was a ticket about this already, but I can't find it!  It would be relatively easy to add a `--min-data-rate` flag or something like that which measured the bandwidth on a connection and closed it it it sank to below a certain number.  The complications would be how long you measure the bandwidth over I think...

>  I'm thinking that this issue can be closed since it seems to have been proved to be external to rclone. What are your thoughts?

Yes, I'm happy that rclone's timeouts are working properly now.

> Thanks for all your work on this.

And thank you for testing!

I'll close this now.

**Closed by ncw** 2018-02-21 08:46 UTC
Labels: Remote: S3, bug

**Comment by khayama** [comment] 2018-09-27 05:46
I hava the same issue...

**Comment by ncw** [comment] 2018-09-27 09:48
@khayama can we discuss on [the rclone forum](https://forum.rclone.org/)?  Make a new topic there with more info in and we can talk through it. Thanks.

**Comment by khayama** [comment] 2018-09-27 12:08
Please give us insight at the following page

Cannot download over 300GB file with rclone - rclone forum : https://forum.rclone.org/t/cannot-download-over-300gb-file-with-rclone/6971
