### ISSUE TITLE
Plex Integration - Have to restart rclone if Plex restarts

### ISSUE THREAD

**Issue by animosity22** [ncw/rclone#2205] opened 2018-04-04 14:11 UTC
Version:
```
rclone -V
rclone v1.40-035-g1dea99abβ
```

Logs:
```
Apr  4 09:11:28 gemini rclone[29016]: tnvepu36qiohcun8v84ddhsam0/p7048hm1bicgno3fi9cgheicnm2570rbug72e0ehiakrlbpnf2f0/6qd3a6mt2lqhh1o4keott622tpkerps8bam88evh9mmnde93q180: confirmed reading by external reader
Apr  4 09:11:30 gemini rclone[29016]: tnvepu36qiohcun8v84ddhsam0/p7048hm1bicgno3fi9cgheicnm2570rbug72e0ehiakrlbpnf2f0/6qd3a6mt2lqhh1o4keott622tpkerps8bam88evh9mmnde93q180: confirmed reading by external reader
Apr  4 09:11:34 gemini rclone[29016]: tnvepu36qiohcun8v84ddhsam0/p7048hm1bicgno3fi9cgheicnm2570rbug72e0ehiakrlbpnf2f0/6qd3a6mt2lqhh1o4keott622tpkerps8bam88evh9mmnde93q180: confirmed reading by external reader








Apr  4 09:12:22 gemini rclone[29016]: plex: stopped Plex watcher
Apr  4 09:12:22 gemini rclone[29016]: plex: stopped Plex watcher
Apr  4 09:12:22 gemini rclone[25936]: Serving remote control on http://localhost:5572/
Apr  4 09:12:22 gemini rclone[25936]: gcache: Cache DB path: /home/felix/.cache/rclone/cache-backend/gcache.db
Apr  4 09:12:22 gemini rclone[25936]: gcache: Cache chunk path: /home/felix/.cache/rclone/cache-backend/gcache
Apr  4 09:12:22 gemini rclone[25936]: gcache: Chunk Memory: true
Apr  4 09:12:22 gemini rclone[25936]: gcache: Chunk Size: 10M
Apr  4 09:12:22 gemini rclone[25936]: gcache: Chunk Total Size: 32G
Apr  4 09:12:22 gemini rclone[25936]: gcache: Chunk Clean Interval: 1m0s
Apr  4 09:12:22 gemini rclone[25936]: gcache: Workers: 5
Apr  4 09:12:22 gemini rclone[25936]: gcache: File Age: 168h0m0s
Apr  4 09:12:22 gemini rclone[25936]: gcache: Upload Temp Rest Time: 1h0m0s
Apr  4 09:12:22 gemini rclone[25936]: gcache: Upload Temp FS: /data/rclone_upload
Apr  4 09:12:22 gemini rclone[25936]: gcache: Cache DB path: /home/felix/.cache/rclone/cache-backend/gcache.db
Apr  4 09:12:22 gemini rclone[25936]: gcache: Cache chunk path: /home/felix/.cache/rclone/cache-backend/gcache
Apr  4 09:12:22 gemini rclone[25936]: gcache: Chunk Memory: true
Apr  4 09:12:22 gemini rclone[25936]: gcache: Chunk Size: 10M
Apr  4 09:12:22 gemini rclone[25936]: gcache: Chunk Total Size: 32G
Apr  4 09:12:22 gemini rclone[25936]: gcache: Chunk Clean Interval: 1m0s
Apr  4 09:12:22 gemini rclone[25936]: gcache: Workers: 5
Apr  4 09:12:22 gemini rclone[25936]: gcache: File Age: 168h0m0s
Apr  4 09:12:22 gemini rclone[25936]: gcache: Upload Temp Rest Time: 1h0m0s
Apr  4 09:12:22 gemini rclone[25936]: gcache: Upload Temp FS: /data/rclone_upload
Apr  4 09:12:23 gemini rclone[25936]: Encrypted drive 'gmedia:': Modify window is 1ms
Apr  4 09:12:32 gemini rclone[25936]: tnvepu36qiohcun8v84ddhsam0/p7048hm1bicgno3fi9cgheicnm2570rbug72e0ehiakrlbpnf2f0/6qd3a6mt2lqhh1o4keott622tpkerps8bam88evh9mmnde93q180: confirmed reading by external reader

```

If the Plex Server restarts, the rclone process has to be restarted to reconnect the integration into Plex.

**Comment by bassrock** [comment] 2018-04-20 03:41
This may have to do with #1903 . I noticed that one was fixed by waiting till the first read. Another use case for this is when you use docker, and then also mount rclone with a unionfs mount before you start plex and I think that the unionfs mount command may trigger that first read. 

I would suggest that a new way to go about it is to retry until it can connect plex because there are multiple ways users can start rclone-cache and plex.

**Comment by remusb** [comment] 2018-06-12 20:21
Got this improved in https://github.com/ncw/rclone/commit/339fbf0df56965b8b928d2fcc5174372f8c35d49 
The Plex connection will reconnect itself when it fails.

The problem is, I don't think a build started for it. Seems GIT had some issues. @ncw I was looking at travis for a way to manually trigger a master build but it seems I can't without a dummy commit. Do you have another nicer way?

**Comment by ncw** [comment] 2018-06-13 10:08
@remusb 
> The problem is, I don't think a build started for it. Seems GIT had some issues. @ncw I was looking at travis for a way to manually trigger a master build but it seems I can't without a dummy commit. Do you have another nicer way?

THere are some ways you can find [in here](https://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit) - none ideal!

I had another commit to push which I've done so the beta should be in

https://beta.rclone.org/v1.41-104-gd1892896/ (uploaded in 15-30 mins)

**Comment by remusb** [comment] 2018-06-13 14:30
Here's the working beta: https://beta.rclone.org/v1.41-105-g4df17949/

**Closed** 2018-06-15 07:12 UTC
Labels: Remote: Cache

**Comment by dannymichel** [comment] 2019-06-20 03:15
This hasn't been fixed in the latest beta
