### ISSUE TITLE
B2: authorization token has expired

### ISSUE THREAD

**Issue by jdeluyck** [ncw/rclone#904] opened 2016-11-22 19:56 UTC
Hello,

Rclone 1.34, running on a raspberry pi 3 (with raspbian)

I'm currently in the progress of uploading a ton of data to B2, and unfortunately, issue #310  is still present.
I started rclone at [2016-11-21 19:48] (ah, don't we love logfiles)

After a bit over 24 hours, it started spouting these errors:

2016/11/22 19:59:52 data/5/50045: Failed to copy: Authorization token has expired (401 expired_auth_token)
2016/11/22 19:59:53

**Comment by ncw** [comment] 2016-11-24 16:46
I think this is a duplicate of #825 which I've attempted to fix already - try the latest beta and see if that helps.

Please comment in #825 whether it works for you or not!

I'm going to close this one now.

**Closed by ncw** 2016-11-24 16:46 UTC
