### ISSUE TITLE
is webdav supported?

### ISSUE THREAD

**Issue by jakop345** [ncw/rclone#580] opened 2016-07-12 06:18 UTC
is webdav supported? 

**ncw edit**

There is a go library here which could be helpful: https://github.com/studio-b12/gowebdav

**Comment by ncw** [comment] 2016-07-13 15:14
Not currently.  It might help with #382 also. I'll put it on the list :-)

**Comment by nandhp** [comment] 2016-09-01 02:59
Box also supports WebDAV, so this might help with #97 also. However, I don't know if it would be as efficient as using the Box-specific API.

**Comment by richo67** [comment] 2016-11-08 07:42
Would be great to have WebDAV support. I have Synology NAS and it exports all files system as WebDAV (among other ways). I am sure many other system offers WebDAV access.

**Comment by ardhipoetra** [comment] 2016-11-23 14:19
Seconded webDAV support. This can increase compatibility and reach a large user base. So far I'm happy with rclone especially with the `mount` implementation.

**Comment by jrz** [comment] 2017-01-20 08:27
Using duplicati instead.

**Comment by deurk** [comment] 2017-01-30 22:02
Would that make rclone support OwnCloud then?

**Comment by jrz** [comment] 2017-01-30 22:07
It should. OwnCloud files can be stored and retrieved using webdav

**Comment by drohm** [comment] 2017-02-18 18:57
Would love to see support for this so that owncloud/nextcloud would work.

**Comment by wouterch** [comment] 2017-04-26 17:11
Would be really appreciated!

**Comment by amunhoz** [comment] 2017-05-19 12:16
Since ACD is off now, this will be important.
We can get unlimited space in other services with a cheaper price with that.
https://www.opendrive.com/
https://www.box.com/

**Comment by ajkis** [comment] 2017-05-19 12:22
Open drive looks amazing it would be great for cold storage.

p.s. Did not notice any bandwith or file limitation, now the question is what kind of speed we can achieve.

**Comment by j0hnsen** [comment] 2017-05-27 19:01
What is the status here @ncw ?

**Comment by calisro** [comment] 2017-05-27 23:02
@J0hnsen why don't you do a pull request and finish it off.

**Comment by jstray** [comment] 2017-06-06 19:03
+1 for WebDav, in this case to access Synology

**Comment by crakerjac** [comment] 2017-06-09 19:25
+1

**Comment by SIEEY** [comment] 2017-06-12 21:43
+1

**Comment by bittaurus** [comment] 2017-08-13 14:07
+1 for webdav.  Also, webdav supports partial writes, so you could conceivably rclone mount and have full readwrite random access.

**Comment by SURFsara-e-infra** [comment] 2017-09-04 09:00
+1

**Comment by WinXaito** [comment] 2017-09-07 20:30
+1

**Comment by bhcopeland** [comment] 2017-09-12 16:59
+1

**Comment by magicstone1412** [comment] 2017-09-19 07:36
+1

**Comment by viet2503** [comment] 2017-09-19 17:09
+1

**Comment by WebSpider** [comment] 2017-09-25 20:14
+1 in my case for nextcloud/owncloud as target

**Comment by ncw** [comment] 2017-10-09 15:50
Here is the first version of the webdav remote

https://beta.rclone.org/v1.38-017-g7f3dc9b5/ (uploaded in 15-30 mins)

I've tested it with owncloud and nextcloud but I haven't tested it with any other webdav servers though.

Here are [the docs](https://github.com/ncw/rclone/blob/master/docs/content/webdav.md)

Please report issues here.

**Comment by WebSpider** [comment] 2017-10-09 16:06
Awesome! I'll get to testing later this evening.

**Comment by bhcopeland** [comment] 2017-10-09 16:10
Is there a Linux build?

**Comment by WebSpider** [comment] 2017-10-09 16:16
Its in the same place.

**Comment by bhcopeland** [comment] 2017-10-09 16:17
They just all got uploaded ;)

**Comment by drohm** [comment] 2017-10-09 16:26
What's the easiest way to install this test version over 1.35-1?

**Comment by WebSpider** [comment] 2017-10-09 21:22
Running initial sync now. It seems to work right off the bat (yay!), with some minor quirks:
- It overwrites existing files, even if the content is the same (i know because the source didnt change between my first aborted attempt and second)

> 2017/10/09 23:14:37 INFO  : dns/system/data/0/99: Copied (new)
> 2017/10/09 23:14:37 INFO  : rhye/system/data/0/224: Copied (new)
> 2017/10/09 23:14:40 INFO  : dns/system/data/0/104: Copied (replaced existing)
> 2017/10/09 23:14:40 INFO  : dns/system/data/0/10: Copied (replaced existing)

- It complains about file modification times that differ for some reason.
> 2017/10/09 23:14:33 DEBUG : dns/system/data/0/104: Modification times differ by 142h33m13.240590316s: 2017-10-04 00:36:02.759409684 +0200 CEST, 2017-10-09 21:09:16 +0000 GMT
> 2017/10/09 23:14:33 DEBUG : dns/system/data/0/1: Modification times differ by 142h34m52.669975099s: 2017-10-04 00:34:04.330024901 +0200 CEST, 2017-10-09 21:08:57 +0000 GMT

- Debug logging shows some missing statistics about speed and ETA

> Transferred:
>
>   3.924 GBytes (9.552 MBytes/s)
> Errors:                 0
> Checks:                55
> Transferred:          661
> Elapsed time:      7m0.6s
> Transferring:
> *                        rhye/system/data/0/368: 63% done, 0 Bytes/s, ETA: -
> * rhye/system/data/0/365
> * rhye/system/data/0/366
> * rhye/system/data/0/367

**Comment by ncw** [comment] 2017-10-10 07:51
@WebSpider thanks for testing

Your first two points are likely related...  Which system are you using? nextcloud/owncloud or something else? It looks like the modification times aren't beng preserved properly.  Can you see after an upload if the modification times are correct?

> Debug logging shows some missing statistics about speed and ETA

I think that is probably uploads which haven't started yet - hopefully they sort themselves out.

**Comment by scotta** [comment] 2017-10-11 02:41
Trying pull content from BigCommerce using WebDAV I get the following error:

> 2017/10/11 12:59:54 Failed to create file system for "bigcommerce:product_images": read metadata failed: No 'Authorization: Digest' header found. Either the client didn't send one, or the server is misconfigured

Their HTTP headers contain:
`www-authenticate: Digest realm="SabreDAV",qop="auth",nonce="...",opaque="...."`

Thanks

**Comment by taffareltorres** [comment] 2017-10-11 19:18
@ncw WebDAV works for OpenDrive (3Mb/s). No erros. Thanks!

**Comment by donmega** [comment] 2017-10-12 08:31
Hi,

I use WebDAV (not OpenDrive) with the latest beta, and i keep getting these errors:

2017/10/12 10:30:09 ERROR : MViD/jay-z_-_99_problems_(director's_cut)_(explicit-diamond)_(lpcm-pal-retail).vob: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/10/12 10:30:09 ERROR : MViD/luniz-i_got_5_on_it_(bay_area_remix)_(dd2.0-dvdrip-ntsc-casshy)_(audio_re-edit).vob: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/10/12 10:30:09 ERROR : MViD/luniz_-_i_got_5_on_it_(lpcm-promo-ntsc-danzz).vob: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/10/12 10:30:09 ERROR : MViD/mack_10_-_tight_to_def_(ft_t-boz)_(re-rip)_(dd2.0-etv-ntsc-enigma69).vob: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/10/12 10:30:09 ERROR : MViD/mya_-_free_(lpcm-promo-ntsc-bunni).vob: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/10/12 10:30:09 ERROR : MViD/n.w.a.-100_miles_and_running_(ac3-laserdisc-ntsc).mpg: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/10/12 10:30:09 ERROR : MViD/nina_sky_-_on_some_bullshit_(lpcm-720p-kingadam).mkv: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/10/12 10:30:09 ERROR : MViD/prince - violet the organ grinder (1991) (vhs-clean-lpcm-pal-denic).vob: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/10/12 10:30:09 ERROR : MViD/prince_and_nona_gaye_-_love_sign.VOB: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/10/12 10:30:09 ERROR : MViD/puff_daddy_-_victory_(re-rip)_(dd2.0-etv-ntsc-enigma69).vob: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/10/12 10:30:09 ERROR : MViD/rd59-rc.VOB: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/10/12 10:30:09 ERROR : MViD/redhead kingpin & the fbi - do the right thing (1989) (vhs-disceyes 0989-lpcm-pal-denic).vob: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/10/12 10:30:09 ERROR : MViD/t.w.d.y.-player's_holiday(dd2.0-etv-ntsc-Colt45).VOB: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/10/12 10:30:09 ERROR : MViD/tp.pbd.VOB: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/10/12 10:30:09 ERROR : MViD/warren_g_-_i_want_it_all_(ft_mack_10)_(re-rip)_(lpcm-etv-ntsc-explicit-enigma69).vob: Entry doesn't belong in directory "" (contains subdir) - ignoring

**Comment by WebSpider** [comment] 2017-10-12 10:30
I can report great syncs on OwnCloud 8.7 and NextCloud 11.0.
It does appear that when you include \" in the URL, a strange error 'first path segment in URL cannot contain colon' is returned.

**Comment by bittaurus** [comment] 2017-10-12 22:22
It's great that this is going forward. Are plans to let rclone support
random access writes on webdav?

**Comment by xRmg** [comment] 2017-10-16 10:55
The issue @donmega has seems to be related to path's with spaces in them.

**Comment by WebSpider** [comment] 2017-10-16 12:37
Also, I can report this patch doesnt work with stackstorage.com ... they seem to lack the possibility to find out the mtime, so all syncs are full syncs.

Will grab soms logs in the next run.

**Comment by aquac** [comment] 2017-10-17 06:47
@ncw thanks a lot! 
I ttested 'copy' and 'sync' with owncloud.

While the former works fine, the latter doesn't seem to do anything. Is sync already supported ?

**Comment by ncw** [comment] 2017-10-22 16:02
Here is a roundup of replies - sorry for the my absence from this thread:

@scotta thanks for testing with BigCommerce

Can you check with `-vv --dump-headers` that rclone is sending an `Authorization:` header.  Use `--dump-auth` to see it.

@donmega hmm, that is strange - the code is supposed to be filtering those out.  Can you send me the result of `rclone lsd -vv --dump-bodies remote:a/problem/directory` - preferably a directory with not much in it that shows the problem.

@WebSpider wrote:
> It does appear that when you include " in the URL, a strange error 'first path segment in URL cannot contain colon' is returned.

Do you mean when you put a " in the rclone path, eg `rclone ls \"dir\"` or in the config file?

@WebSpider wrote:
> Also, I can report this patch doesnt work with stackstorage.com ... they seem to lack the possibility to find out the mtime, so all syncs are full syncs.

rclone should still do a partial sync, just testing the size and existence of the file.  If you try a run with `-vv` rclone should log more stuff.

@aquac wrote:
 > I tested 'copy' and 'sync' with owncloud.
> While the former works fine, the latter doesn't seem to do anything. Is sync already supported ?

Both sync and copy should work just fine.  If you did a copy first, then a sync, the sync will do nothing as it has nothing to do.

**Comment by Rick7C2** [comment] 2017-10-22 19:37
@ncw I am having the same problem as @donmega using webdav to connect to put.io webdav server.

I have run the command specified above on a dir with one dir in it and two files in that. However this log shows everything in the webdav, so unfortunately it is very long.

Command issued...

rclone lsd -vv --dump-bodies putio:Default &>rclone-putio.txt

And here are the contents of rclone-putio.txt
https://gist.github.com/Rick7C2/5f0a1867e1022ec8d8d64e164df7ff4a (Truncated)

https://gist.githubusercontent.com/Rick7C2/5f0a1867e1022ec8d8d64e164df7ff4a/raw/fd007c54a5a86c1a2925429fda18e514ab2dad31/rclone-putio.txt (Un-Truncated)

Also when trying to copy or move a whole folder from this webdav to gdrive it doesn't create the subfolders. All of the subfolders are empty files.

command...
rclone copy putio:TV/ gdrive:Incoming/TV/testtv/

However if I try to copy or move a file with direct path it works.
command...
rclone move putio:TV/The.X.Factor.S14E15.Judges.Houses.1.1080p.AMZN.WEBRip.DDP2.0.x264-NTb[rarbg]/The.X.Factor.S14E15.Judges.Houses.1.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb.mkv gdrive:Incoming/TV/The.X.Factor.S14E15.Judges.Houses.1.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb.mkv

**Comment by Rick7C2** [comment] 2017-10-22 20:28
@ncw Also it seems that rclone thinks that the directory's are files.

When I run rclone lsd while it shows all the funky errors as stated above it doesn't show the dirs at the bottom.

But when I run rclone ls it shows the dirs below the error lines.

`rclone lsd putio: &>/root/putio-lsd.txt`
https://gist.github.com/Rick7C2/2a2d95a1a0e702aee84e4759f9015082

`rclone ls putio: &>/root/putio-ls.txt`
https://gist.github.com/Rick7C2/9d0e1ee26c0f40ab0fc6d77bec3e245f

Here is the dirs in the root dir.
>putio:
>>Default
>>Movies
>>TV

**Comment by ncw** [comment] 2017-10-22 21:11
@Rick7C2 I see what is going on.

In the response the name is `/Movies` - whereas rclone is expecting the name to end in a `/`.  The RFC says collections MUST end in `/` so this is non RFC compliant.  But hey, we live in the real world ;-)

The other odd thing about the response is it does a recursive listing of everything - I would expect it to only list the top level directory

Maybe those two facts together mean that it isn't treating each directory as a collection but but there is just one collection.... It does have a resource type of collection though.

I suspect I'm going to need to sign up for a put.io account to fix this unless anyone wants to lend me some credentials?

```xml
<D:response>
  <D:href>/Movies</D:href>
  <D:propstat>
    <D:prop>
      <D:supportedlock>
        <D:lockentry xmlns:D="DAV:">
          <D:lockscope>
            <D:exclusive/>
          </D:lockscope>
          <D:locktype>
            <D:write/>
          </D:locktype>
        </D:lockentry>
      </D:supportedlock>
      <D:getlastmodified>Sat, 14 Oct 2017 21:27:51 GMT</D:getlastmodified>
      <D:resourcetype>
        <D:collection xmlns:D="DAV:"/>
      </D:resourcetype>
      <D:displayname>Movies</D:displayname>
    </D:prop>
    <D:status>HTTP/1.1 200 OK</D:status>
  </D:propstat>
</D:response>
```

Compared to a file

```xml
<D:response>
  <D:href>/Default/dir/file.mkv</D:href>
  <D:propstat>
    <D:prop>
      <D:getcontenttype>video/x-matroska</D:getcontenttype>
      <D:supportedlock>
        <D:lockentry xmlns:D="DAV:">
          <D:lockscope>
            <D:exclusive/>
          </D:lockscope>
          <D:locktype>
            <D:write/>
          </D:locktype>
        </D:lockentry>
      </D:supportedlock>
      <D:getcontentlength>577333002</D:getcontentlength>
      <D:getlastmodified>Sun, 22 Oct 2017 19:16:47 GMT</D:getlastmodified>
      <D:getetag>"14effa7b24ef76002269670a"</D:getetag>
      <D:resourcetype>
      </D:resourcetype>
      <D:displayname>file.mkv</D:displayname>
    </D:prop>
    <D:status>HTTP/1.1 200 OK</D:status>
  </D:propstat>
</D:response>
```

**Comment by Rick7C2** [comment] 2017-10-22 21:21
@ncw I will share my putio account with you so you can fix this.

**Comment by ncw** [comment] 2017-10-23 11:39
Here is a new beta which should work fine with put.io. It should be more compatible in general too :-)

https://beta.rclone.org/v1.38-037-g6df1f6fa/ (uploaded in 15-30 mins)

I updated [the webdav docs](https://github.com/ncw/rclone/blob/master/docs/content/webdav.md) with a section on put.io.

**Comment by Rick7C2** [comment] 2017-10-24 00:13
After limited testing it seems to be working as intended except for one thing.

When I run rclone ls It still lists the files recursively Instead of only listing the files in the current dir. Other than that I haven't found any problems. Tomorrow I will have more time to tinker with it.

Thanks @ncw !

**Comment by scotta** [comment] 2017-10-24 03:56
@ncw Thank you for replying. Here's the dump of connecting to BigCommerce. I went through `config` choosing webdav and other. The username is an email address and the password a BigCommerce generated 64 character string. Apologies if I've misconfigured something, first time user. I've modified the store URL and basic auth value for privacy.

> 2017/10/24 14:45:16 DEBUG : rclone: Version "v1.38-037-g6df1f6faβ" starting with parameters ["./rclone" "-vv" "--dump-headers" "--dump-auth" "lsd" "bigcommerce:"]
> 2017/10/24 14:45:16 INFO  : webdav root '': Modify window not supported
> 2017/10/24 14:45:16 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> 2017/10/24 14:45:16 DEBUG : HTTP REQUEST (req 0xc420103500)
> 2017/10/24 14:45:16 DEBUG : PROPFIND /dav/ HTTP/1.1
> Host: store-redacted.mybigcommerce.com
> User-Agent: rclone/v1.38-037-g6df1f6faβ
> Authorization: Basic RANDOMJnWUY0zY70mkPXtpO6rm=
> Depth: 1
> Accept-Encoding: gzip
> 
> 2017/10/24 14:45:16 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> 2017/10/24 14:45:17 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
> 2017/10/24 14:45:17 DEBUG : HTTP RESPONSE (req 0xc420103500)
> 2017/10/24 14:45:17 DEBUG : HTTP/1.1 401 Unauthorized
> Transfer-Encoding: chunked
> Cache-Control: no-cache
> Connection: keep-alive
> Content-Type: application/xml; charset=utf-8
> Date: Tue, 24 Oct 2017 03:45:17 GMT
> Server: openresty
> Www-Authenticate: Digest realm="SabreDAV",qop="auth",nonce="59eeb74ddb1be",opaque="df58bdff8cf60599c939187d0b5c54de"
> X-Bc-Stapler: 1
> X-Newrelic-App-Data: PxQDVV5bARADUlZUBgEBREgTYVYAMhEDXhFZAUxRW1xvSnoUQhVcDzgZZzMpM356fiBBMUNeRQM4bWRWExMGEUQwVxdMXWhuZABbJVAXEU5UGAdRVlMIHwBKUVEDAQNKSQAaEVZeUVtVB11WCApVAVBQD1ATTVUDCEVSPA==
> 
> 2017/10/24 14:45:17 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
> 2017/10/24 14:45:17 ERROR : : error listing: couldn't list files: No 'Authorization: Digest' header found. Either the client didn't send one, or the server is misconfigured
> 2017/10/24 14:45:17 Failed to lsd: couldn't list files: No 'Authorization: Digest' header found. Either the client didn't send one, or the server is misconfigured

**Comment by ncw** [comment] 2017-10-25 22:11
@Rick7C2 wrote
> When I run rclone ls It still lists the files recursively Instead of only listing the files in the current dir. Other than that I haven't found any problems. Tomorrow I will have more time to tinker with it.

`rclone ls` lists recursively by default.  Use `rclone --max-depth 1 ls` to not do that.

@scotta wrote:
> Thank you for replying. Here's the dump of connecting to BigCommerce. I went through config choosing webdav and other. The username is an email address and the password a BigCommerce generated 64 character string.

I think you configured it right - I see the problem now.  BigCommerce is asking for Digest authentication whereas rclone is only supplying basic authentication.  I'll have to read up on exactly how to implement that...

----

Here is a new beta which has a fix which will probably improve put.io with subdirectories, and a compatiblility fix for server side moves and copies

https://beta.rclone.org/v1.38-043-ge612673e/ (uploaded in 15-30 mins)

**Comment by Nicolaius** [comment] 2017-11-12 18:05
Hello,
I'm using a webdav remote encrypted.
When I try to upload a file with a name greater than 79 chars i have error "method not allowed" while with lower name the upload is ok.
I inform you if it is useful.
Thanks for the useful program.

**Comment by ncw** [comment] 2017-11-15 17:25
@scotta sorry for the delay in responding! If you are still interested in getting webdav fixed with bigcommerce then please make a [new issue on github](https://github.com/ncw/rclone/issues/new) with the details you put in above and I'll take a look for the 1.40 release.

@Nicolaius I think that is probably a limitation of the server you are using, not rclone unfortunately.

Otherwise I think this issue is now done - if there is anything I've missed please open a new issue!

Thanks

**Closed by ncw** 2017-11-15 17:25 UTC
Labels: enhancement: new remote
