### ISSUE TITLE
I want to copy only new files. Why is this action so slow?

### ISSUE THREAD

**Issue by davekr8** [ncw/rclone#581] opened 2016-07-13 06:07 UTC
is:open label:question 

I got a boxcryptor container on google (1,7GB, approx 5k files) and i what to have a dump of the container on my NAS (the idea is to dump it every 30 min) to have a own history using rsnapshot on the local container.

so my idea was to run:
`
rclone copy dave_kr8: /media/dave.kr8@drive.google.com/ --low-level-retries 20 --retries 20
`
with a cronjob every 30 min. unfortunately i got end up with
`
2016/07/13 05:59:18
Transferred:            0Bytes (0Byte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     25m8.8s
`
when i added just one file to the container.

so from my point of view, getting a filelist from the google api is fast, comparing time and size is fast, too.
what is wasting so much time? is it recalculating hashes?

how can i reduce the time for "copying" (the copy command) only a few new files every 30 min?

i appreciate if one can give me a more detailed insight in what is going on behind the rclone command. 

_Edit:_

** hmmm, my nas is running on a ssd, and i use the noatime option to mount my filesystem. maybe this is the problem i am facing???

** but it's the same result if i use  --checksum oder --size-only command. or is the copy command not using the options?

**Comment by ncw** [comment] 2016-07-13 14:11
Getting a filelist from the google api can be slow - especially if you have lots of files.  You can time how long it takes by doing `rclone size dave_kr8:`.  It might be interesting to compare the local speed also with `rclone size /media/dave.kr8@drive.google.com/`.

If you do those two measurements then it will tell you where the problem is.

> hmmm, my nas is running on a ssd, and i use the noatime option to mount my filesystem. maybe this is the problem i am facing???

Unlikely I would have thought

> but it's the same result if i use --checksum oder --size-only command. or is the copy command not using the options?

`copy` does obey those options, yes.

Do the files get their modification time updated when they are placed in the drive?  If so then you can use this which might speed things up

You can use this to see if that looks likely

    rclone --max-age 1d --no-traverse lsl  dave_kr8:

And then this for syncing

    rclone --max-age 1d --no-traverse copy dave_kr8: /media/dave.kr8@drive.google.com/ --low-level-retries 20 --retries 20

Note that you'll need the latest rclone v1.31 (just released) to use the --no-traverse flag.

Note also that you can watch the progress of the directory scanning if you use the `-v` flag.

**Comment by davekr8** [comment] 2016-07-13 15:33
first, thank you for the fast reply. 

i am on the new v1.31.
concerning the speed, i get the following results:
```
rclone size dave_kr8:

Total objects: 5757
Total size: 1.662G (1784556658 bytes)
2016/07/13 14:30:39
Transferred:            0Bytes (0Byte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:    11m40.7s
```
and
```
clone size /media/dave.kr8@drive.google.com/

Total objects: 5756
Total size: 1.662G (1784549394 bytes)
2016/07/13 14:16:35
Transferred:            0Bytes (0Byte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:           0
```
as exspected for the ssd.

> Do the files get their modification time updated when they are placed in the drive?

the changetime is changed, the modification time is fixed, as it makes sense for me.

> Note also that you can watch the progress of the directory scanning if you use the -v flag.

using the verbose mode i see a lot of 

`low level retry */20 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)`

i am still wondering about the slow api-requests for getting the list of files. i tried a bit of hacking on the pyhton interface ([https://developers.google.com/drive/v2/reference/files/list](https://developers.google.com/drive/v2/reference/files/list)) and there i get chunks of filedata (max. 1000) per 1-2 seconds.

is collecting filename, size and getting the hash the limiting factor in rclone ?

**Comment by ncw** [comment] 2016-07-13 15:44
Google seem to be rate limiting rclone at the moment #560 which might be related.  So I think that the speed of the sync is being limited by google rather than anything else....

You are only listing 5k objects - that should take no time at all!

**Comment by davekr8** [comment] 2016-07-13 20:03
finally, using my own credentials for the api i ended up with:

```
Transferred:            0Bytes (0Byte/s)
Errors:                 0
Checks:              5757
Transferred:            0
Elapsed time:     1m21.1s
2016/07/13 19:59:16 Go routines at exit 20
```
this are some reasonable timings. 
thanks. 
to be closed !

**Comment by ncw** [comment] 2016-07-14 10:00
Interesting thanks.

I'll write more about rclone rate limits in #560 which I've seen you've subscribe to and I'll close this one.

**Closed by ncw** 2016-07-14 10:00 UTC
