### ISSUE TITLE
Update stats in place

### ISSUE THREAD

**Issue by 19wolf** [ncw/rclone#2361] opened 2018-06-26 02:44 UTC
#### What is the problem you are having with rclone?
None yet

#### What is your rclone version (eg output from `rclone -V`)
```
rclone v1.42
- os/arch: linux/amd64
- go version: go1.10.1
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 18.04, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone sync /data/ googledrive --stats=1s -v`

My thought was that instead of my terminal scrolling with every update, it would be nice if it could update stats output in place, or even 'live'.

**Comment by ncw** [comment] 2018-06-30 13:42
I think this is a duplicate of #2347 and if you look at that issue you'll see I've been doing some experimentation.

**Closed by ncw** 2018-06-30 13:42 UTC
