### ISSUE TITLE
Daemon mode?

### ISSUE THREAD

**Issue by timofonic** [ncw/rclone#246] opened 2015-12-09 21:18 UTC
Hello.

I see there's [https://github.com/astrada/google-drive-ocamlfuse](google-drive-ocaml-fuse), [https://github.com/joe42/CloudFusion/](CloudFusion) and many others. What's wrong about having more alternatives?

These syncers are only for FUSE, not for Windows...

Kind regards

**Comment by ncw** [comment] 2015-12-10 12:48
I'm not quite sure I understand...

Do you think I should be making a fuse backend with rclone - if so that is an idea I've thought about before!

Or something else which would work on Windows?

**Comment by zeshanb** [comment] 2015-12-10 16:54
@ncw fuse backend might be a tangent since mounting to an OS file system is
different from simply transporting and syncing.

**Comment by ncw** [comment] 2015-12-14 17:35
@timofonic shall I close this one as a duplicate of #249 ? Or is there something else you would like to add?

**Comment by timofonic** [comment] 2015-12-24 20:27
@ncw No problem, as they are mostly the same. 

Just please give us some info about progress or what to do to accelerate it. 

I'm really sick of dealing with a zillion of sync apps that fight each other or are too tricky with exotic environments. A common and extensible one that may work as a syncer would be awesome, specially if being really multiplatform and extensible :D

**Comment by ncw** [comment] 2016-01-02 15:57
OK I'll close this in favour of #249.

As for how to accelerate - send in (or get a developer you know) to send in a pull request and I'll happily work with them to integrate!

**Closed** 2016-01-02 15:58 UTC
