### ISSUE TITLE
panic: close of closed channel

### ISSUE THREAD

**Issue by PiscisSwimeatus** [ncw/rclone#1124] opened 2017-02-12 18:15 UTC
What is your rclone version (eg output from rclone -V)
rclone-v1.35-75-g381b845β
Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 16.04
Which cloud storage system are you using? (eg Google Drive)
Amazon Cloud Drive
The command you were trying to run (eg rclone copy /tmp remote:tmp)
rclone copy --checksum
A log from the command with the -vv flag (eg output from rclone -vv copy /tmp remote:tmp)

```
2017/02/12 19:00:25
Transferred:   629.702 GBytes (23.159 MBytes/s)
Errors:                 2
Checks:                49
Transferred:         1693
Elapsed time:   7h44m2.6s
Transferring:
 * ...- Last Call [WEBRip-480p-x264-2ch-AAC].mkv: 100% done, 458.462 kBytes/s, ETA: 0s
 * ...00 A.M. - 800 A.M. [360p-x264-2ch-AAC].mkv: 100% done, 4.625 MBytes/s, ETA: 0s
 * ...M. - 100 P.M. [HDTV-720p-x264-2ch-AC3].mkv: 100% done, 37.811 kBytes/s, ETA: 0s
 * ...Spot [HDTV-480p-x264-2ch-AAC-W4F-eztv].mkv: 100% done, 2.189 MBytes/s, ETA: 0s

panic: close of closed channel

goroutine 22006 [running]:
panic(0xbcbfe0, 0xc420374470)
        /home/travis/.gimme/versions/go1.7.4.linux.amd64/src/runtime/panic.go:500 +0x1a1
net/http.(*persistConn).closeLocked(0xc420198b00, 0x10d9180, 0xc4200949b0)
        /home/travis/.gimme/versions/go1.7.4.linux.amd64/src/net/http/transport.go:1921 +0xaa
net/http.(*persistConn).close(0xc420198b00, 0x10d9180, 0xc4200949b0)
        /home/travis/.gimme/versions/go1.7.4.linux.amd64/src/net/http/transport.go:1901 +0x85
net/http.(*persistConn).readLoop.func1(0xc420198b00, 0xc420288c50)
        /home/travis/.gimme/versions/go1.7.4.linux.amd64/src/net/http/transport.go:1386 +0x41
net/http.(*persistConn).readLoop(0xc420198b00)
        /home/travis/.gimme/versions/go1.7.4.linux.amd64/src/net/http/transport.go:1564 +0x7f7
created by net/http.(*Transport).dialConn
        /home/travis/.gimme/versions/go1.7.4.linux.amd64/src/net/http/transport.go:1062 +0x4e9
```

**Comment by ncw** [comment] 2017-02-12 21:11
Not sure what is going on here - this is a panic from the go standard library.

A bit of searching suggests maybe cancelling a request twice causes this, though I don't think that is anything that rclone ever does.

Is it reproduceable the bug?

Can you

**Comment by PiscisSwimeatus** [comment] 2017-02-13 15:55
It only happened once, and I'm not able to reproduce this. So unless the log above gives you something to go on, you can close this issue for now. And I'll report back if it happenes again.

**Comment by ncw** [comment] 2017-02-14 09:38
@PiscisSwimeatus 

I had a quick chat about this issue on the go developers list.  This should never happen according to the core developers, and I agree after looking at the code.

It clearly did happen which means there was some kind of memory corruption in rclone.  That can be caused by a race condition, however I tested rclone for a long time uploading things to ACD to try to trigger it with no success.  So if it is a race condition it doesn't happen very often :-(

The other alternative is that there was an actual memory corruption on your computer.  Have you tried memtest86 on it recently?  Or it could be soft error which are [suprisingly common](http://www.zdnet.com/article/dram-error-rates-nightmare-on-dimm-street/).  Anyway that really is clutching at straws.

So I agree with you that we should close this for the moment, but please re-open if it happens again!

**Closed by ncw** 2017-02-14 09:38 UTC
Labels: bug
