### ISSUE TITLE
Detect renaming folders or files

### ISSUE THREAD

**Issue by psmanek** [ncw/rclone#765] opened 2016-10-04 19:40 UTC
Hi,

is there any way to check if folders was only renamed? It would be very useful for large folders. Clone would only rename folder, instead of uploading it again.

thanks

**Comment by ncw** [comment] 2016-10-05 13:52
What you are talking about is detecting renames.  For remotes which support a hash it would possible.

**Comment by eharris** [comment] 2016-12-30 12:33
Although this ticket was opened earlier, is it a duplicate of #888?

**Comment by ncw** [comment] 2017-12-14 11:02
This has now been implemented with the --track-renames flag

**Closed by ncw** 2017-12-14 11:02 UTC
Labels: enhancement
