### ISSUE TITLE
[Feature request] Show full path/ Name during transfer

### ISSUE THREAD

**Issue by Massaguana** [ncw/rclone#1207] opened 2017-03-04 05:31 UTC
Hello,

during transfer the file Name are cut off... is it possible to add an mode to show the complete file Name?

Problem, when you are use long file names you can´t read witch file are in process...

Regards
Massaguana

If you've just got a question or aren't sure if you've found a bug then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)
v1.35
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
MacOS, CentOS7 64Bit
> Which cloud storage system are you using? (eg Google Drive)
GSuite Business
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone -v sync "path" "path"
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

**Comment by ncw** [comment] 2017-03-04 07:15
Do you mean in the stats output? The one which tells you which files are transferring?  Or in the log lines that print what has been copied?

**Comment by ncw** [comment] 2017-03-04 07:20
Is this a duplicate of #1206 ?

**Comment by Massaguana** [comment] 2017-03-04 07:52
I mean the status window.. What i Can see during transfer in Terminal...

**Comment by ncw** [comment] 2017-03-04 08:06
Do you mean the same as #1206 ?

**Comment by Massaguana** [comment] 2017-03-04 10:36
it looks an little bit different but i think it is the same... but not sure because i can see the filename end... something like MovieName.mkv

**Comment by ncw** [comment] 2017-03-04 11:43
Can you attach a screenshot of the output you would like to change?

**Comment by Massaguana** [comment] 2017-03-04 14:42
![bildschirmfoto 2017-03-04 um 06 28 40](https://cloud.githubusercontent.com/assets/15521791/23579609/21e9c086-00f1-11e7-8233-5e347a3d0353.png)

**Comment by ncw** [comment] 2017-03-05 09:56
OK, that is what is being proposed in #1206 so I'll close this one in favour of that one.

Can you subscribe to that issue?

Thanks

**Closed by ncw** 2017-03-05 09:56 UTC
Labels: duplicate
