### ISSUE TITLE
Scripted sync errorr: user: Current not implemented on linux/amd64

### ISSUE THREAD

**Issue by waqark3389** [ncw/rclone#747] opened 2016-09-28 10:27 UTC
> What is your rclone version (eg output from `rclone -V`) **1.33**
> Which OS you are using and how many bits (eg Windows 7, 64 bit) **Linux 64 bit**
> Which cloud storage system are you using? (eg Google Drive) **S3**
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`) 
> **#!/bin/bash
> $(rclone --config /root/scripts/rclone/rclone.conf sync /home/backups/"$1" S3Crypt:"$1" > /var/log/backups/"$1".log 2>&1)**

I am syncing files to AWS S3 via the above script. When I run that command manually i.e. 

**rclone --config /root/scripts/rclone/rclone.conf sync /home/backups/"$1" S3Crypt:"$1" > /var/log/backups/"$1".log 2>&1**
- It works fine. However adding it to a script and executing it (with the same user and permissions) returns the following in the log file. The actual sync worked fine and the files are in S3. What does this mean? 

```
2016/09/28 01:17:57 Couldn't find home directory or read HOME environment variable.
2016/09/28 01:17:57 Defaulting to storing config in current directory.
2016/09/28 01:17:57 Use -config flag to workaround.
2016/09/28 01:17:57 Error was: user: Current not implemented on linux/amd64
```

I have already set the --config flag as above. And if the config flag was not set it would not have found my bucket to sync to and in the directory I execute from doesn't have a rclone.conf. So it must be using --config. 

I dont think this is a problem as far as the syncing is concerned as I can see the latest files in S3...
Should I ignore this or any workaround?

**Comment by ncw** [comment] 2016-09-28 12:02
I'm surprised you are getting that error under linux. You get that error if there is something wrong with the user setup. 

It might be a symptoms of running under cron. 

Exactly which Linux distribution are you using? 

The error is harmless and I should probably disable it if you pass in the --config option.

**Comment by waqark3389** [comment] 2016-09-28 13:12
@ncw Agreed, it is something to do with the fact that I run it this way. Would export of $HOME fix this? I haven't seen the code that checks this but I think its just a "silent" error as everything worked fine. 
I am using CentOS release 6.7 (Final) 64 bit: 

Linux backup1 2.6.32-573.18.1.el6.x86_64 #1 SMP Tue Feb 9 22:46:17 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Is it completely safe to run this even though I get an error?

**Comment by ncw** [comment] 2016-09-28 16:57
Here is the code

```go
// Find the config directory
func configHome() string {
	// Find users home directory
	usr, err := user.Current()
	if err == nil {
		return usr.HomeDir
	}
	// Fall back to reading $HOME - work around user.Current() not
	// working for cross compiled binaries on OSX.
	// https://github.com/golang/go/issues/6376
	home := os.Getenv("HOME")
	if home != "" {
		return home
	}
	ErrorLog(nil, "Couldn't find home directory or read HOME environment variable.")
	ErrorLog(nil, "Defaulting to storing config in current directory.")
	ErrorLog(nil, "Use -config flag to workaround.")
	ErrorLog(nil, "Error was: %v", err)
	return ""
}
```

If you supply `--config` you can ignore the error message.

What user is the crontab running under? 

Exporting HOME will get rid of the error message but it doesn't explain why `user.Current()` didn't work in the first place.

As a normal user, if you `unset HOME` do you get the same error when you run rclone?

**Comment by ncw** [comment] 2017-01-09 17:44
Did you manage to resolve this?

**Comment by waqark3389** [comment] 2017-01-10 12:22
@ncw Apologies, didn't actually see your response. 

As I added --config to the command, I chose to ignore the error as there is no actual problem with syncing. 

Exporting HOME gets rid of the error, though. 

Here is the script, 

```
        echo "$(date) [Using rclone]: $1 Syncing " >> /var/log/trust/rclonemain.log
        $(rclone --config /root/scripts/rclone/rcloneCsw.conf sync /home/csw/"$1" cswCrypt:"$1" > /var/log/trust/"$1".log 2>&1)
        echo $? > /var/log/trust/"$1".exitcode
```

This runs as the root user. 

I'm not sure why I'm getting it to be honest and since no one else has reported it, it must be a special case in my environment with the chain of scripts im using during the backup process. 
I'll play around a little more when I get time to try and unset HOME etc. 
Will keep you posted!

**Comment by ncw** [comment] 2017-01-10 16:02
I should probably not give that error if `--config` is set. That would involve a bit of gymnastics but it could be done.

> I'm not sure why I'm getting it since no one else has reported it, it must be a special case in my environment 

The root cause of the problem is that `user.Current()` didn't work. A quick squint at the go source code tells me that it is never going to work compiled without cgo if $HOME is unset.

```
$ export CGO_ENABLED=0
$ unset HOME
$ go build 
$ ./rclone version
2017/01/10 16:00:44 Couldn't find home directory or read HOME environment variable.
2017/01/10 16:00:44 Defaulting to storing config in current directory.
2017/01/10 16:00:44 Use -config flag to workaround.
2017/01/10 16:00:44 Error was: user: Current not implemented on linux/amd64
2017/01/10 16:00:44 Config file ".rclone.conf" not found - using defaults
rclone v1.35-DEV
```

So setting $HOME is the correct thing to do in this case as I don't plan to start building with CGO_ENABLED=1

**Comment by benamira** [comment] 2017-01-17 16:42
I am om the same boat.
Unable to make the script work in systemd to start at boot and getting same errors. the command included in the script works like a charm, but want to make automatic when boot.

Tried everything.. Could you help on that?

`systemctl start rcloneMount.service

Job for rcloneMount.service failed because the control process exited with error code. See "systemctl status rcloneMount.service" and "journalctl -xe" for details.


# systemctl status rcloneMount.service
● rcloneMount.service - Mount Google Drive
   Loaded: loaded (/etc/systemd/system/rcloneMount.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2017-01-17 17:38:12 CET; 14s ago
  Process: 6967 ExecStop=/bin/fusermount -u /mnt/FOLDER (code=exited, status=1/FAILURE)
  Process: 6957 ExecStart=/bin/bash /root/scripts/rcloneMount.sh (code=exited, status=0/SUCCESS)

Jan 17 17:38:09 CLOUDFER bash[6957]: 2017/01/17 17:38:09 Couldn't find home directory or read HOME environment variable.
Jan 17 17:38:09 CLOUDFER bash[6957]: 2017/01/17 17:38:09 Defaulting to storing config in current directory.
Jan 17 17:38:09 CLOUDFER bash[6957]: 2017/01/17 17:38:09 Use -config flag to workaround.
Jan 17 17:38:09 CLOUDFER bash[6957]: 2017/01/17 17:38:09 Error was: user: Current not implemented on linux/amd64
Jan 17 17:38:09 CLOUDFER bash[6957]: 2017/01/17 17:38:09 Failed to create file system for "secretgoogle:BENAMIRA": didn't find section in config
Jan 17 17:38:12 CLOUDFER fusermount[6967]: /bin/fusermount: failed to unmount /mnt/FOLDER: No such file or directory
Jan 17 17:38:12 CLOUDFER systemd[1]: rcloneMount.service: Control process exited, code=exited status=1
Jan 17 17:38:12 CLOUDFER systemd[1]: Failed to start Mount Google Drive.
Jan 17 17:38:12 CLOUDFER systemd[1]: rcloneMount.service: Unit entered failed state.
Jan 17 17:38:12 CLOUDFER systemd[1]: rcloneMount.service: Failed with result 'exit-code'.`

**Comment by ncw** [comment] 2017-01-17 17:44
@benamira set the `--config` flag for rclone in the script.  Take a look [at this thread](https://forum.rclone.org/t/rclone-mount-on-startup-with-systemd/360/2) on the forum

**Comment by ncw** [comment] 2017-01-17 17:44
I'm going to close this now since the original issue is sorted.

**Closed by ncw** 2017-01-17 17:44 UTC
