### ISSUE TITLE
Add Custom MetaData during a transfer

### ISSUE THREAD

**Issue by nodughere** [ncw/rclone#126] opened 2015-09-08 04:21 UTC
This is similar to the request by Martin to copy Custom Metadata when moving from S3 to Swift or others.  However, I would like a switch where I can add my own headers to each put operation.  This would take a dictionary and just append it to the headers passed to the object storage backend.  It would be up to the user to format correctly for the backend.

Example rclone with Swift
rclone --custom-data={'x-meta-object-my-favorite-car':'ford mustang', 'X-Delete-After': 3600}   copy /home/doug/data/ SwiftCluster:container

This command would add metadata and allow objects to auto delete in 1 hour as an example

Example rclone with S3
rclone --custom-data={'x-amz-meta-my-favorite-car':'ford mustang'}   copy /home/doug/data/ S3Cluster:bucket

Doug

**Comment by ncw** [comment] 2015-09-08 07:54
A great idea, however I think this is mostly a duplicate of #59 - can you add your comments there please and close this ticket!

Thanks

Nick

**Closed** 2015-09-08 14:18 UTC
Labels: duplicate
