### ISSUE TITLE
Windows. How can i exclude System Volume Information for non-administrator

### ISSUE THREAD

**Issue by tagplus5** [ncw/rclone#786] opened 2016-10-13 20:10 UTC
When filing an issue, please include the following information if
possible as well as a description of the problem.  Make sure you test
with the [latest beta of rclone](http://rclone.org/downloads/).

> What is your rclone version (eg output from `rclone -V`)

rclone v1.33

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows 10 1607 14393.321

> Which cloud storage system are you using? (eg Google Drive)

local

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone sync -v d:\ e:\backup --exclude /System Volume Information/** --dry-run`

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

`2016/10/13 23:03:15 Failed to sync: failed to open directory "\\\\?\\d:\\System Volume Information": open \\?\d:\System Volume Information: Access is denied.`

i try 
`--exclude /System?Volume?Information/**`
and
`--exclude /System{ }Volume{ }Information/**`

**Comment by ncw** [comment] 2016-10-17 21:44
I presume you have some quotes around that?

    rclone sync -v d:\ e:\backup --exclude "/System Volume Information/**" --dry-run

I would have thought that should work...

You can test quickly by using `rclone size d:\ --exclude "/System Volume Information/**"`

Trying to reproduce with the latest beta on a Windows VM I'm getting this
```
X:\rclone>rclone ls c:\
2016/10/18 02:09:24 failed to open directory "\\\\?\\c:\\": open \\?\c:\: The system cannot find the path specified.
```

Which looks like it might be a different bug - do you see that?

It would be worth testing with the latest beta of rclone from http://beta.rclone.org

**Comment by ncw** [comment] 2016-10-18 09:45
I submitted a [go bug #17500](https://github.com/golang/go/issues/17500) for the `failed to open directory "\\\\?\\c:\\": open \\?\c:\: The system cannot find the path specified.` problem.

**Comment by ncw** [comment] 2017-04-25 09:33
That go bug has been fixed now, so I'm going to close this issue.

**Closed by ncw** 2017-04-25 09:33 UTC
