### ISSUE TITLE
Support for Box cloud service

### ISSUE THREAD

**Issue by markjamie** [ncw/rclone#797] opened 2016-10-15 22:16 UTC
Would it be possible to support the Box cloud service (http://www.box.com) within rclone? Ideally for both personal and business accounts.

**Comment by ncw** [comment] 2016-10-16 09:56
This is a duplicate of #97 - can you subscribe to that issue please to show interest?

Thanks

Nick

**Closed** 2016-11-03 21:00 UTC
Labels: duplicate
