### ISSUE TITLE
--files-from reads lots of local files - don't recurse into excluded directories

### ISSUE THREAD

**Issue by lickdragon** [ncw/rclone#395] opened 2016-03-17 21:24 UTC
Hello,
  I'm using rclone v1.28 on Debian Jessie 64-bits.
I'm trying to rclone copy using --files-from, something like:

rclone copy -v --config credsfile --files-from=listfiles ./ credname:/test2/

This is to Google Drive.

rclone procedes to build a (in my case) huge list of files found locally which are "Excluded from sync (and deletion)" .

My expectation would be that rclone simply copies the files listed in the files-from without any other hanky panky.

Thanks for a neat-o and fast tool!

.
./adiabatic_data
./adiabatic_data/600_20
./adiabatic_data/600_20/run_53
./adiabatic_data/600_20/run_53/outFile.txt
./adiabatic_data/600_20/run_53/output_file.txt
./adiabatic_data/600_20/run_53/jobScript.py
./adiabatic_data/600_20/run_53/error_file.txt
./adiabatic_data/600_20/run_53/jobsubmit
./adiabatic_data/600_20/run_53/log_file.txt
2016/03/17 16:19:53 Google drive root 'test2': Modify window is 1ms
2016/03/17 16:19:53 Google drive root 'test2': Building file list
2016/03/17 16:19:53 .bashrc: Excluded from sync (and deletion)
2016/03/17 16:19:53 CCA_run_creation/Quist2012/.DS_Store: Excluded from sync (and deletion)
2016/03/17 16:19:53 CCA_run_creation/Quist2012/.hg/00changelog.i: Excluded from sync (and deletion)
2016/03/17 16:19:53 CCA_run_creation/Quist2012/.hg/branch: Excluded from sync (and deletion)
2016/03/17 16:19:53 CCA_run_creation/Quist2012/.hg/cache/branchheads: Excluded from sync (and deletion)
2016/03/17 16:19:53 CCA_run_creation/Quist2012/.hg/cache/tags: Excluded from sync (and deletion)
2016/03/17 16:19:53 CCA_run_creation/Quist2012/.hg/dirstate: Excluded from sync (and deletion)
2016/03/17 16:19:53 CCA_run_creation/Quist2012/.hg/hgrc: Excluded from sync (and deletion)
2016/03/17 16:19:53 CCA_run_creation/Quist2012/.hg/requires: Excluded from sync (and deletion)
2016/03/17 16:19:53 CCA_run_creation/Quist2012/.hg/store/00changelog.i: Excluded from sync (and deletion)
2016/03/17 16:19:53 CCA_run_creation/Quist2012/.hg/store/00manifest.i: Excluded from sync (and deletion)
2016/03/17 16:19:53 CCA_run_creation/Quist2012/.hg/store/data/_samples/_accumulation_dot_samples__2012/_potential_mask.cif.i: Excluded from sync (and deletion)
2016/03/17 16:19:53 CCA_run_creation/Quist2012/.hg/store/data/_samples/_accumulation_dot_samples__2012/_test_accumulation_dot3_d.cif.i: Excluded from sync (and deletion)
2016/03/17 16:19:53 CCA_run_creation/Quist2012/.hg/store/data/_samples/_accumulation_dot_samples__2012/_test_accumulation_dot3_d.qdt.i: Excluded from sync (and deletion)

**Comment by ncw** [comment] 2016-03-18 19:26
Yes you are right, this is the way rclone works right now.

I'm planning to fix this at some point though - after the directory listing refactor that is currently ongoing.

Thanks for the report

Nick

**Comment by lickdragon** [comment] 2016-03-18 21:00
Great!
Happy coding. :)

**Comment by MattBlissett** [comment] 2016-03-30 18:32
Fixing this would also help when the user doesn't have access permission to excluded directories — at the moment, they're still checked and cause errors.

**Comment by ncw** [comment] 2016-05-16 22:06
Here is a beta with a fix for this: let me know how it goes!

http://pub.rclone.org/v1.29-28-g36700d3%CE%B2/

Thanks

Nick

**Closed** 2016-05-16 22:09 UTC
Labels: enhancement

**Comment by dewi-ny-je** [comment] 2017-08-30 08:03
Hi, this issue isn't actually solved in the current release 1.37 (tested on OmniOS/Illumos).
I have a filter "- .zfs/**" but still I get an error message about not being able to read the folder .../.zfs/share/...
I stopped shortly after the message and no .zfs folder was copied to B2, while other folders were.

The issue is very relevant on said platform: the folder .zfs contains snapshots of the whole dataset (think to a partition if you don't know ZFS), meaning that it contains the same files of the rest of the disk, as many times as the number of snapshots taken.
Traversing said (excluded) folder means way slower processing and more memory.

I haven't investigated much why I got that error message, I didn't even have "-v" because I was in a hurry, but it's worth checking the correct implementation of the exclusion filters.

What info do you need from me to understand better the issue? I can provide you with it later today.
