### ISSUE TITLE
corrupted on transfer: QuickXorHash hash differ

### ISSUE THREAD

**Issue by ghost** [ncw/rclone#2753] opened 2018-11-22 07:19 UTC
#### Output of `rclone version`
rclone v1.44-099-g26e2f1a9-beta
- os/arch: linux/386
- go version: go1.11.2

#### Describe the issue
When copying .xlxs files **to** a sharepoint, I get the error:
corrupted on transfer: sizes differ
When adding the --ignore-size arg, I get the error:
corrupted on transfer: QuickXorHash hash differ

**Comment by ncw** [comment] 2018-11-23 20:30
I think this issue is a duplicate of #2599 which we are working on a solution for.

**Closed** 2019-05-27 08:03 UTC
Labels: Remote: One Drive, duplicate
