### ISSUE TITLE
Feature Request: Versioning / Conflict resolution

### ISSUE THREAD

**Issue by dolkensp** [ncw/rclone#670] opened 2016-09-01 10:15 UTC
Can we please get a way to automatically archive old versions of a file, as new versions are uploaded?

At the moment, I'm using a bespoke C# app I wrote which has the following workflow:
1. Upload new file as **_[yyyyMMddHHmm]_-_[filehash]_.tmp**
2. Move existing file to **.archive/_[yyyyMMddHHmm]_-filename.ext**
3. Rename temporary file to **filename.ext**

This provides simple version history for the remote files.

**Comment by ermint** [comment] 2016-09-04 09:11
Some backends support this transparently. See versioning in S3. I think google cloud supports similar.

**Comment by dolkensp** [comment] 2016-09-05 02:45
I'm interested in it for ACD personally, as it will let me store 6TB of photos for free with my prime subscription


Peter Dolkens

**Comment by leocrawford** [comment] 2016-09-07 10:56
Is this a dupe of https://github.com/ncw/rclone/issues/18?

**Comment by dolkensp** [comment] 2016-09-07 12:22
@leocrawford  - Reading through that whole thread, I think #18 would address my needs.

Slightly different implementation, but seems fine to me.

Interestingly, for ACD at least, there are slight improvements that could be made to #18 as ACD lets you reference the same file in multiple "directories" - so you could actually have a complete filesystem in each "revision"

My only question is how well the proposed solution will work for multiple changes in any given timeperiod. Are versions created when rsync is run, or only on-demand, etc.

**Comment by leocrawford** [comment] 2016-09-13 13:59
Does it? That is very neat, so you can do a proper rdiff-backup (http://www.nongnu.org/rdiff-backup/) type of operation, without symlinks. Nice!

I'd suspect that it would be snapshot based

**Comment by ncw** [comment] 2016-09-19 17:21
My plan for this is to implement #98 then implement a seperate higher level `rclone backup` command which would do a backup with ability to see previous backup snapshots up to some limit.

Each time you ran the `rclone backup` command you'd get a new snapshot.

I will spec it out a bit later

**Comment by MourIdri** [comment] 2017-10-05 13:15
@ncw : can you make the rclone backup command not dependant from the underlay technology ? ( We can read S3 previous Version above), but using this is going to complexify the management and would be based on what is under the hood. 
Thanks for this is is Awesome !

**Comment by ncw** [comment] 2017-12-14 10:54
rclone now supports [--backup-dir](https://rclone.org/docs/#backup-dir-dir) which with a tiny amount of scripting gives all the tools necessary for incremental backups.

I do intend to wrap it in a easy to use command at some point.

**Closed by ncw** 2017-12-14 10:54 UTC
Labels: enhancement
