### ISSUE TITLE
No webdav support (NextCloud / OwnCloud)

### ISSUE THREAD

**Issue by laurentdinclaux** [ncw/rclone#1262] opened 2017-03-21 20:34 UTC
The app is missing Webdav support

**Comment by calisro** [comment] 2017-03-22 12:22
https://github.com/ncw/rclone/issues/580

**Comment by ncw** [comment] 2017-03-22 14:34
I'm going to close this as a duplicate of #580 - please add your support there.

**Comment by ncw** [comment] 2017-10-09 15:51
Here is the first version of the webdav remote

https://beta.rclone.org/v1.38-017-g7f3dc9b5/ (uploaded in 15-30 mins)

I've tested it with owncloud and nextcloud but I haven't tested it with any other webdav servers though.

Here are [the docs](https://github.com/ncw/rclone/blob/master/docs/content/webdav.md)

Please report issues with this in #580.

**Closed by ncw** 2017-10-09 15:51 UTC
Labels: duplicate
