### ISSUE TITLE
panic/crash in windows7, 64 bit.

### ISSUE THREAD

**Issue by ljr9600** [ncw/rclone#2572] opened 2018-09-12 15:59 UTC
#### What is the problem you are having with rclone?
panic while trying to copy 3 gb drive contents.  Issue continues to happen after a retries.  

#### What is your rclone version (eg output from `rclone -V`)
v1.42 (reproduceable in 1.39)

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
win7, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
google drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
"./rclone.exe" "--config" "rclone.conf" "-vv" "--transfers=16" "--checkers=32" "copy" "--drive-upload-cutoff=32M" "--drive-chunk-size=32M" "g:\\" "google_drive_encrypted:/j1/2018/mybook/" "--log-file=mybook.txt"

(i tried sizes of 64M, 128M and same issues)

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
panic: runtime error: slice bounds out of range

goroutine 1769 [running]:
github.com/ncw/rclone/lib/readers.(*RepeatableReader).Read(0xc04343e8d0, 0xc04bdd3000, 0x1000, 0x1000, 0xc0420f7a60, 0xc0420f7a50, 0xc046363
aa0)
        C:/gopath/src/github.com/ncw/rclone/lib/readers/repeatable.go:56 +0x267
net/http.transferBodyReader.Read(0xc0421f00a0, 0xc04bdd3000, 0x1000, 0x1000, 0xd86, 0x0, 0xc04207c888)
        C:/go/src/net/http/transfer.go:60 +0x5d
io.(*LimitedReader).Read(0xc0422b2200, 0xc04bdd3000, 0x1000, 0x1000, 0xd86, 0x0, 0x0)
        C:/go/src/io/io.go:446 +0x6a
bufio.(*Writer).ReadFrom(0xc04207c880, 0x1187ae0, 0xc0422b2200, 0x4db00c0, 0xc04207c880, 0x1)
        C:/go/src/bufio/bufio.go:703 +0xd4
io.copyBuffer(0x1186a80, 0xc04207c880, 0x1187ae0, 0xc0422b2200, 0x0, 0x0, 0x0, 0xf5f8c0, 0xc0421a0c01, 0xc0422b2200)
        C:/go/src/io/io.go:386 +0x321
io.Copy(0x1186a80, 0xc04207c880, 0x1187ae0, 0xc0422b2200, 0xc04bdd3268, 0x1073084, 0x2)
        C:/go/src/io/io.go:362 +0x61
net/http.(*transferWriter).WriteBody(0xc0421f00a0, 0x1186a80, 0xc04207c880, 0x2, 0x2)
        C:/go/src/net/http/transfer.go:337 +0x601
net/http.(*Request).write(0xc046330700, 0x1186a80, 0xc04207c880, 0x0, 0xc04343ed50, 0x0, 0x0, 0x0)
        C:/go/src/net/http/request.go:622 +0x6b9
net/http.(*persistConn).writeLoop(0xc0421b2fc0)
        C:/go/src/net/http/transport.go:1825 +0x1f1
created by net/http.(*Transport).dialConn
        C:/go/src/net/http/transport.go:1238 +0x986
```

**Comment by ncw** [comment] 2018-09-12 16:40
Hmm, I think that looks like http transport reading from a finished with handle somehow.

You say it only happens on retries?  So I guess that means that Seek has been called on the repeatable buffer.

Maybe it is `Seek` racing with `Read` somehow.

There is no locking on Seek and Read.

Can you see if you can reproduce with [the latest beta](https://beta.rclone.org) please?  I suspect it will reproduce but it is possible fixes to the go1.11 runtime have fixed this too.

**Comment by ljr9600** [comment] 2018-09-12 21:32
sorry, I meant to say, a retry of the full copy eventually fails as well.  normally around 9gigs gets transferred, then I can try again to see if more files get transferred and so on.  

I'll try latest beta tonight and see.

**Comment by ncw** [comment] 2018-09-14 10:13
@ljr9600 did you mean to close this?  How did the testing with the beta go?

**Comment by ljr9600** [comment] 2018-09-15 03:36
Sorry, i didn't mean to close it.  But the beta does seem to be better,  and no more panics.

**Comment by ncw** [comment] 2018-09-15 09:42
OK, I'll leave this closed then, but let me know if it happens again with the beta - thanks.

**Comment by LingMan** [comment] 2018-11-12 00:54
Looks like I just encountered the same problem. On a subsequent execution of the same command line on the same data everything went fine so this is probably not something I'll be able to reproduce.

Note that the local storage system on my end is known to be flaky. This might simply be a case of missing error handling.


What is your rclone version:
1.44

Which OS you are using and how many bits:
CentOS 7.5 64bit

The command you were trying to run:
`rclone copy -v --transfers=25 /local/path remote:`

```
panic: runtime error: slice bounds out of range

goroutine 1337 [running]:
github.com/ncw/rclone/lib/readers.(*RepeatableReader).Read(0xc0002c0810, 0xc027062000, 0x1000, 0x1000, 0x0, 0xc02700a1e0, 0xc02700a1d0)
        /home/travis/gopath/src/github.com/ncw/rclone/lib/readers/repeatable.go:56 +0x255
net/http.transferBodyReader.Read(0xc02706bcc0, 0xc027062000, 0x1000, 0x1000, 0x1000, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/transfer.go:62 +0x56
io.(*LimitedReader).Read(0xc000718440, 0xc027062000, 0x1000, 0x1000, 0x1000, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/io/io.go:448 +0x63
bufio.(*Writer).ReadFrom(0xc000a04d00, 0x1327ac0, 0xc000718440, 0x7fc0d8bfb0a8, 0xc000a04d00, 0xc0000dfc01)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/bufio/bufio.go:707 +0xe4
io.copyBuffer(0x1326180, 0xc000a04d00, 0x1327ac0, 0xc000718440, 0x0, 0x0, 0x0, 0x106a5a0, 0xc02700a101, 0xc000718440)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/io/io.go:388 +0x303
io.Copy(0x1326180, 0xc000a04d00, 0x1327ac0, 0xc000718440, 0x270, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/io/io.go:364 +0x5a
net/http.(*transferWriter).writeBody(0xc02706bcc0, 0x1326180, 0xc000a04d00, 0x2, 0x2)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/transfer.go:362 +0x5b8
net/http.(*Request).write(0xc01a859800, 0x1326180, 0xc000a04d00, 0x0, 0xc0210563c0, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/request.go:645 +0x6e8
net/http.(*persistConn).writeLoop(0xc026fea000)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/transport.go:1888 +0x1b8
created by net/http.(*Transport).dialConn
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/transport.go:1339 +0x966
```

**Comment by ncw** [comment] 2018-11-12 12:03
Hmm, I'll re-open this.

It looks very much like Read() and Seek() are being called concurrently so what I'll do is add a mutex which should fix the issue.

**Closed** 2018-11-12 14:33 UTC
Labels: bug

**Comment by ncw** [comment] 2018-11-12 14:56
I merged the fix to master - it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and in v1.45.

Please let me know if it happens again!

**Comment by LingMan** [comment] 2018-11-12 16:59
I've updated to v1.44-080-g16f797a7 and will let you know if it happens again.

**Comment by ncw** [comment] 2018-11-13 10:57
> I've updated to v1.44-080-g16f797a7 and will let you know if it happens again.

Thanks :-)
