### ISSUE TITLE
mount --daemon does not work with encrypted config

### ISSUE THREAD

**Issue by Cnly** [ncw/rclone#2442] opened 2018-08-05 12:51 UTC
#### What is the problem you are having with rclone?
`rclone mount` does not work when the config is encrypted. It seems that during the daemonization, neither the password or the decrypted config is passed from the parent to the child process. Maybe there can be a mechanism to pass either of them through pipe or environment variables.

#### What is your rclone version (eg output from `rclone -V`)
`v1.42-062-gf72eade7`

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 18.04

####  Which cloud storage system are you using? (eg Google Drive)
This problem should be there regardless of backend type.

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone mount remote: /mountpoint --daemon`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
Aug 01 16:46:47 <hidden> rclone[23920]: rclone: Version "v1.42-062-gf72eade7" starting with parameters ["./rclone" "-vv" "mount" "remote:" "/mountpoint" "--daemon" "--debug-fuse" "--syslog"]
Aug 01 16:46:52 <hidden> rclone[23920]: Using config file from "/home/<hidden>/.config/rclone/rclone.conf"
Aug 01 16:46:54 <hidden> rclone[23920]: remote: Saved new token in config file
Aug 01 16:46:56 <hidden> rclone[23920]: rclone: Version "v1.42-062-gf72eade7" finishing with parameters ["./rclone" "-vv" "mount" "remote:" "/mountpoint" "--daemon" "--debug-fuse" "--syslog"]
Aug 01 16:46:56 <hidden> rclone[23936]: rclone: Version "v1.42-062-gf72eade7" starting with parameters ["./rclone" "-vv" "mount" "remote:" "/mountpoint" "--daemon" "--debug-fuse" "--syslog"]
Aug 01 16:46:56 <hidden> rclone[23936]: Couldn't decrypt configuration, most likely wrong password.
Aug 01 16:46:56 <hidden> rclone[23936]: Failed to read line: EOF
```

**Comment by ncw** [comment] 2018-08-05 16:56
Thanks for reporting this - I've confirmed that it is a problem.

Do you fancy working on a fix?

**Comment by Cnly** [comment] 2018-08-05 17:51
Thanks for replying. Would like to work on this but I think we need to talk about the solution a bit.

I would propose adding an environment variable `RCLONE_CONFIG_KEY` (or maybe a better name) and passing the `configKey` through that variable when daemonizing. This way we don't have to store or pass plain text passwords if users don't want to set `RCLONE_CONFIG_PASS`. And passing the `configKey` rather than the decrypted config itself also allows the child process to write back to the file (E.g., when saving a checkpoint for Amazon Cloud Drive).

But of course, the best way to do this should be using a pipe, which is not supported by go-daemon (See https://github.com/sevlyar/go-daemon/issues/19). :(

Would like to hear your opinion on this.

**Comment by ncw** [comment] 2018-08-07 20:51
I've had to solve this sort of problem before and an environment variable is a good solution here.

I think we should probably use a variable which won't conflict with normal use, say `_RCLONE_CONFIG_PASS` or something like that.  The `fs/config` could export SavePassToEnv and LoadPassFromEnv which manages it.  For security we should delete the var from the environment once it is loaded.

**Comment by Cnly** [comment] 2018-08-08 16:06
Okay, I've pushed a first commit for this issue. `configKey` is passed to the child now and `--daemon` is working with encrypted config. But we may be having some problems with unsetting the environment variable: It seems that calls like `os.Unsetenv("_RCLONE_CONFIG_KEY")` can't remove the variable from a user's easy reach, for example `/proc/$PID/environ`.

**Comment by ncw** [comment] 2018-08-11 14:42
> Okay, I've pushed a first commit for this issue. configKey is passed to the child now and --daemon is working with encrypted config.

Nice

>  But we may be having some problems with unsetting the environment variable: It seems that calls like os.Unsetenv("_RCLONE_CONFIG_KEY") can't remove the variable from a user's easy reach, for example /proc/$PID/environ.

You are right - that is unexpected by me, but seems to be the way it works.

It is [posssible to change /proc/PID/environ](https://unix.stackexchange.com/questions/302948/change-proc-pid-environ-after-process-start) but not particularly easy from Go in a cross platform way.

We could use `config.Obscure` and `config.Reveal` to mask the password in the environment which would be better than nothing...

Pipes would be nice here wouldn't they!

**Comment by Cnly** [comment] 2018-08-14 08:10
I have changed to `obscure.Obscure` now. It is almost no better than base64, though. :(

Have also commented in the go-daemon repo to see if it's possible that pipes can be supported soon.

**Comment by Cnly** [comment] 2018-08-17 07:07
Maybe we can make use of a temporary file. This can be removed more easily.

**Comment by ncw** [comment] 2018-08-17 17:31
A temporary file is a good idea - we can pass the name of it in the environment then delete it straight away.  Not 100% secure but better than before I think.  Need to be careful with the perms on the temporary file but `ioutil.TempFile` does the correct thing.

**Comment by ncw** [comment] 2018-08-21 08:42
This is now merged - thank you for your contributino @Cnly :-)

**Closed by ncw** 2018-08-21 08:42 UTC
Labels: VFS / mount, bug
