### ISSUE TITLE
rclone Keeps Failing to Copy File with "corrupted on transfer" (Google Drive)

### ISSUE THREAD

**Issue by reubendb** [ncw/rclone#981] opened 2017-01-03 02:58 UTC
> What is your rclone version (eg output from `rclone -V`)

rclone 1.35

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux AMD64

> Which cloud storage system are you using? (eg Google Drive)

Google Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone -v copy "GDrive:/Google Photos/VID_20161129_141853510.mp4" /tmp/

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

2017/01/02 21:41:47 rclone: Version "v1.35" starting with parameters ["rclone" "-v" "copy" "GDrive:/Google Photos/VID_20161129_141853510.mp4" "/tmp/"]
2017/01/02 21:41:47 Local file system at /tmp: Modify window is 1ms
2017/01/02 21:41:48 Local file system at /tmp: Waiting for checks to finish
2017/01/02 21:41:48 Local file system at /tmp: Waiting for transfers to finish
2017/01/02 21:41:53 VID_20161129_141853510.mp4: corrupted on transfer: MD5 hash differ "53a0e5a5db26301f97d390a51155cae7" vs "cd6c3d2dc4e91101b5000357dfd96e73"
2017/01/02 21:41:53 VID_20161129_141853510.mp4: Removing failed copy
2017/01/02 21:41:53 Attempt 1/3 failed with 1 errors and: corrupted on transfer: MD5 hash differ "53a0e5a5db26301f97d390a51155cae7" vs "cd6c3d2dc4e91101b5000357dfd96e73"

(Two more attempts failed with the same error) 

Hello,
First of all, thank you for this wonderful program. 

I am trying to download all of my files in Google Photos to my local machine using 'rclone copy', with the destination is a completely empty (local) directory initially. Out of about ~3500 files, 90 of them says that they are "corrupted on transfer: MD5 hash differ". These are mostly .mp4 files, but there are also a handful of JPEG files.

I then tried to manually download a few of the corrupted files one at a time (as shown in the form above) and I kept getting the same error.  I checked the using the web interface and there is no duplicate of the file. 

I then downloaded the file using the web interface and manually run md5sum on it and got: cd6c3d2dc4e91101b5000357dfd96e73
I then also tried using [https://github.com/prasmussen/gdrive] to download the entire 'Google Photos' folder and was able to do so. The md5sum of the downloaded file (via gdrive) is also the same as the version downloaded via web interface.

What can I do to help troubleshoot this issue? It is also curious that from multiple attempts rclone always end up with the same corrupted MD5 hash. 

The files in my Google Photos are mostly from automatic upload from an Android phone and I wanted to use rclone as an automated way to also keep a backup of those on my local machine.

Thanks.

**Comment by ncw** [comment] 2017-01-03 18:02
I just had a look at the code.  The corrupted hashes are in order src, dst so from

    2017/01/02 21:41:53 Attempt 1/3 failed with 1 errors and: corrupted on transfer: MD5 hash differ "53a0e5a5db26301f97d390a51155cae7" vs "cd6c3d2dc4e91101b5000357dfd96e73"

"53a0e5a5db26301f97d390a51155cae7" is the hash that google thinks it is

"cd6c3d2dc4e91101b5000357dfd96e73" is the hash that we get when downloading - which agrees the web interface.

So for some reason google has the checksum wrong on these objects.

`--ignore-checksum` which I'm implementing in #793 would help you here.

**Comment by reubendb** [comment] 2017-01-05 05:01
Thanks, I will give that a try once implemented. I wonder if the issue is on Google's side for not keeping the correct hash. #863 seems to have similar issue except the destination is remote, I wonder if it's related (a symptom of the same problem somehow).

**Comment by ncw** [comment] 2017-01-05 11:44
#863  is the same problem.

I'll try to get #793 done soon!

**Comment by ncw** [comment] 2017-01-05 17:52
Can you try this which implements the --ignore-checksum command?

http://pub.rclone.org/v1.35-15-g82742f5-ignore-checksum%CE%B2/

**Comment by ncw** [comment] 2017-02-03 08:12
I've merged this to master for the 1.36 release

Here is the beta - http://beta.rclone.org/v1.35-62-g9d331ce/ (uploaded in 15-30 mins)

**Closed** 2017-02-03 08:14 UTC
Labels: enhancement

**Comment by BenoitDuffez** [comment] 2017-05-10 07:43
Thanks for this workaround, it's awesome.
Would it be possible though to `touch` the files remotely, or do something that will make Google Drive recompute the hash?

**Comment by jtenniswood** [comment] 2017-05-10 16:21
I've run into the same problem, tried the --ignore-checksum switch, it does make it upload but the file is corrupt when I try to download it again.

In my case, the same script and setup on two machines running the same OS and rclone release, one machine throws errors and the others work perfectly.

Not sure what to try next, any ideas?

**Comment by jtenniswood** [comment] 2017-05-10 17:03
Sorry, turns out it was just me being incredibly dim, I had left a cron job running every minute to test this backup, but the new job overwrote the old backup, which rclone was trying to update, which caused the errors.  Doh!

**Comment by BenoitDuffez** [comment] 2017-05-15 12:13
Would it be possible to disable checksum on specific files?

**Comment by vitor-alves** [comment] 2017-08-15 14:59
+1 
Ignoring the checksum in specific folders/files would be perfect. In my machine it seems that only a single file is having this problem.

**Comment by djsmiley2k** [comment] 2018-03-03 16:27
I'm seeing this problem, going to try the ignore checksum fix... However I've noticed for all the photos I've had it having an issue with, they seem to be duplicates which google has 'fiddled' with - i.e. it's added effects, animations, rotations etc.

Maybe google isn't recomputing the hashes after it makes these changes?

**Comment by ncw** [comment] 2018-03-05 21:17
@djsmiley2k this is an old issue now!  If you can reproduce the problem then open a new issue and I'll investigate - thanks!

**Comment by srd424** [comment] 2018-11-10 16:42
Suspicion confirmed: looking at one of these movies that raised a checksum error, it turns out my copy was one I had accidentally downloaded from someone else's shared album. I had previously backed up that shared album using the "download all" feature in Photos. The version from the previous backup had a much higher bitrate, and a checksum that matched the one that rclone was expecting. So something at Google is transcoding movies (fair enough) but then getting confused about the hash, or exposing the wrong one, or something..

**Comment by pongnguy** [comment] 2018-11-26 02:57
I recently downloaded rclone and am very new to it.  In running some test cases, I successfully copied a local folder to Amazon S3 using the --ignore-checksum flag.  However I am getting "Failed to copy: corrupted on transfer: MD5 crypted hash differ" errors when I try to copy the same files to a crypt remote.  Not sure what else to do!

**Comment by ncw** [comment] 2018-11-26 08:51
> I recently downloaded rclone and am very new to it. In running some test cases, I successfully copied a local folder to Amazon S3 using the --ignore-checksum flag. However I am getting "Failed to copy: corrupted on transfer: MD5 crypted hash differ" errors when I try to copy the same files to a crypt remote. Not sure what else to do!

Can you post the command line for which you are getting the error please?

**Comment by pongnguy** [comment] 2018-11-27 02:52
Sure.  I am trying to upload from a local directory (i.e. 'Vacation Pictures') to an encrypted remote (i.e. amazon_s3_crypt).  The encrypted remote has a ":" in its location (i.e. I made a separate bucket for the encrypted files).

`Name                 Type
====                 ====
amazon_s3_crypt      crypt
amazon_s3_dropbox_personal s3`

Using this command:

`rclone sync ./'Vacation Pictures'/ "amazon_s3_crypt:Vacation Pictures/" --ignore-checksum`

**Comment by ncw** [comment] 2018-11-27 11:12
@pongnguy thanks.  I think this is a different issue to this one.  What you are doing shouldn't require `--ignore-checksum` - why are you using that?

The message `Failed to copy: corrupted on transfer: MD5 crypted hash differ` is from the crypt layer stating that the hash for the upload wasn't what it expected.

It would probably be best if you please make a [new issue on github](https://github.com/ncw/rclone/issues/new/choose) - can you fill out the issue template details with rclone version, os version, logs etc and make a way for me to reproduce the issue ideally - thanks :-)

**Comment by blackgnezdo** [comment] 2023-12-31 18:29
FWIW, this is still an issue, possibly with old files in Google Drive. I hit it a couple of time with some videos from 2018.

**Comment by ahmar20** [comment] 2024-01-19 11:52
> FWIW, this is still an issue, possibly with old files in Google Drive. I hit it a couple of time with some videos from 2018.

I can confirm I/m having the same issue while trying to sync a folder from Google Drive to Nextcloud. Error is:
```
Failed to calculate src hash: hash type not supported
corrupted on transfer: sha1 hash differ "" vs "85a539281f8c4e132af944b623a7ef4b666987d1"
```

**Comment by ncw** [comment] 2024-01-19 17:32
@ahmar20 can you make a new issue about this please with details of exactly what you did - thank you.
