### ISSUE TITLE
Issue #586 is gone?

### ISSUE THREAD

**Issue by robbat2** [ncw/rclone#806] opened 2016-10-19 20:18 UTC
A user reported an issue using rclone on DreamHost, to rclone, which was in issue #586.

I was trying to narrow down if it was definitely a Ceph bug (Rather than an rclone bug), but it seems you've deleted or locked issue #586, so I can't access it anymore.

**Comment by ncw** [comment] 2016-10-19 21:46
I haven't deliberately done anything to that issue. It does seem to have disappeared though :-(

I'll ask github support about it. 

I'll see if I can dig up the problem and post it here in a moment.

**Comment by ncw** [comment] 2016-10-19 22:06
Here is a reconstruction of what the problem is...

First upload a file with a UTF-8 character to a bucket

```
$ rclone -q ls dreamhost:utf8-test
        6 complex character £100.txt
```

Now try a server side copy

```
$ rclone copy dreamhost:utf8-test dreamhost:utf8-test2 --retries 1
2016/10/19 22:55:29 S3 bucket utf8-test2: Waiting for checks to finish
2016/10/19 22:55:29 S3 bucket utf8-test2: Waiting for transfers to finish
2016/10/19 22:55:29 complex character £100.txt: Failed to copy: NoSuchKey: 
	status code: 404, request id: tx000000000000003b63946-005807ebd1-10bb00c9-default
2016/10/19 22:55:29 Attempt 1/1 failed with 1 errors and: NoSuchKey: 
	status code: 404, request id: tx000000000000003b63946-005807ebd1-10bb00c9-default
2016/10/19 22:55:29 Failed to copy: NoSuchKey: 
	status code: 404, request id: tx000000000000003b63946-005807ebd1-10bb00c9-default
```

Now with http debug

```
$ rclone copy -v --dump-bodies dreamhost:utf8-test dreamhost:utf8-test2 --retries 1
```

The relevant transaction is

```
2016/10/19 22:56:40 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2016/10/19 22:56:40 HTTP REQUEST
2016/10/19 22:56:40 PUT /utf8-test2/complex%20character%20%C2%A3100.txt HTTP/1.1
Host: objects-us-west-1.dream.io
User-Agent: rclone/v1.33-DEV
Content-Length: 0
Authorization: SNIP
Date: Wed, 19 Oct 2016 21:56:40 UTC
X-Amz-Copy-Source: utf8-test%2Fcomplex+character+%C2%A3100.txt
X-Amz-Metadata-Directive: COPY
Accept-Encoding: gzip

2016/10/19 22:56:40 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2016/10/19 22:56:40 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2016/10/19 22:56:40 HTTP RESPONSE
2016/10/19 22:56:40 HTTP/1.1 404 Not Found
Content-Length: 225
Accept-Ranges: bytes
Content-Type: application/xml
Date: Wed, 19 Oct 2016 21:56:40 GMT
X-Amz-Request-Id: tx000000000000003b51cb0-005807ec18-10b45ddf-default

<?xml version="1.0" encoding="UTF-8"?><Error><Code>NoSuchKey</Code><BucketName>utf8-test2</BucketName><RequestId>tx000000000000003b51cb0-005807ec18-10b45ddf-default</RequestId><HostId>10b45ddf-default-default</HostId></Error>
2016/10/19 22:56:40 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
```

However if you try the exact same thing against S3 it works just fine.

```
2016/10/19 23:03:01 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2016/10/19 23:03:01 HTTP REQUEST
2016/10/19 23:03:01 PUT http://s3.amazonaws.com/utf8-test2/complex%20character%20%C2%A3100.txt HTTP/1.1
Host: s3.amazonaws.com
User-Agent: rclone/v1.33-DEV
Content-Length: 0
Authorization: snip
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Copy-Source: utf8-test%2Fcomplex+character+%C2%A3100.txt
X-Amz-Date: 20161019T220301Z
X-Amz-Metadata-Directive: COPY
Accept-Encoding: gzip

2016/10/19 23:03:01 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2016/10/19 23:03:01 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2016/10/19 23:03:01 HTTP RESPONSE
2016/10/19 23:03:01 HTTP/1.1 200 OK
Content-Length: 234
Content-Type: application/xml
Date: Wed, 19 Oct 2016 22:03:02 GMT
Server: AmazonS3
X-Amz-Id-2: SAkNeGyzpGulA++DE6QqVHAaHqzn2tpwVyjqBa2rL/jO3ZigeG3jGihiLLkEXQ816g0MVYIjwqc=
X-Amz-Request-Id: 0D8ECC97657B88F4

<?xml version="1.0" encoding="UTF-8"?>
<CopyObjectResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><LastModified>2016-10-19T22:03:02.000Z</LastModified><ETag>&quot;b1946ac92492d2347c6235b4d2611184&quot;</ETag></CopyObjectResult>
2016/10/19 23:03:01 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
```

I think the problem is the `X-Amz-Copy-Source` which according to the [AWS copy docs](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectCOPY.html) is supposed to be URL encoded, however I conjecture that CEPH isn't decoding it as such - hence the key not found error.

> x-amz-copy-source
>
> The name of the source bucket and key name of the source object, separated by a slash (/).
> 
> Type: String
> 
> Default: None
> 
> Constraints:
> 
> This string must be URL-encoded. Additionally, the source bucket must be valid and you must have READ access to the valid source object.
> 
> If the source object is archived in Amazon Glacier (storage class of the object is GLACIER), you must first restore a temporary copy using the POST Object restore. Otherwise, Amazon S3 returns the 403 ObjectNotInActiveTierError error response.
>

**Comment by ncw** [comment] 2016-10-19 22:11
Just noticed that #586 is still in the milestone: https://github.com/ncw/rclone/milestone/18 so looks like some sort of data corruption at github :-(

**Comment by ncw** [comment] 2016-10-20 13:18
Issue #586 is back.  Github support restored it for me.  They didn't explain what happened or why it went away though!

**Comment by ncw** [comment] 2016-10-23 17:07
I'm going to close this now #586 is back

**Closed by ncw** 2016-10-23 17:07 UTC
