### ISSUE TITLE
feature request: support for cloud@mail.ru

### ISSUE THREAD

**Issue by Dees7** [ncw/rclone#1696] opened 2017-09-21 11:31 UTC
Please, make [cloud@mail.ru](https://cloud.mail.ru) support.

It may be [helpful](https://github.com/yar229/WebDavMailRuCloud)

**Comment by timofonic** [comment] 2017-09-27 15:28
@Dees7 There's [CloudCross](/MasterSoft24/CloudCross), a russian project that's somewhat similar to Rclone but done in C++ (but it uses Qt, welcome to bloatland...). It supports far fewer protocols, but Cloud.Mail.Ru is one of them.

**Comment by dmak** [comment] 2019-03-17 20:08
Can be used as a reference: [MailRu C++ implementation in CloudCross](https://github.com/MasterSoft24/CloudCross/tree/master/ccross-app/src/MailRu).

**Comment by ivandeex** [comment] 2019-07-02 21:04
duplicate of #591

**Comment by ncw** [comment] 2019-07-03 11:34
Please see #591 - development is underway there thanks to @ivandeex 

I'll close this so we don't get confused!

**Closed by ncw** 2019-07-03 11:34 UTC
Labels: duplicate, enhancement: new remote
