### ISSUE TITLE
Onedrive Issue: files/directories ending with word "drive" getting quota error

### ISSUE THREAD

**Issue by JRman** [ncw/rclone#2720] opened 2018-11-03 17:40 UTC
#### Output of `rclone version`
 ./rclone --version
rclone v1.44
- os/arch: windows/amd64
- go version: go1.11

#### Describe the issue

Details to reproduce, etc:

https://forum.rclone.org/t/onedrive-could-not-find-a-property-named-quota-on-type-onedrive-item/7403

**Comment by ncw** [comment] 2018-11-03 17:45
Here is a minimal reproduction.  @Cnly what do you think?

```
  mkdir -p /tmp/odtest/adrive
  echo hello > odtest/adrive/test.txt
  rclone copy -vv --dump bodies /tmp/odtest onedriveg:test --retries 1 2>&1 | tee /tmp/onedrive.log
```

With the relevant log being

```
2018/11/03 16:49:46 DEBUG : HTTP REQUEST (req 0xc0004a2200)
2018/11/03 16:49:46 DEBUG : GET /v1.0/drives/71a96798e7b1d253/root:/test/adrive HTTP/1.1
Host: graph.microsoft.com
User-Agent: rclone/v1.44-036-g1f05d5bf-beta
Authorization: XXXX
Accept-Encoding: gzip

2018/11/03 16:49:46 DEBUG : HTTP RESPONSE (req 0xc0004a2200)
2018/11/03 16:49:46 DEBUG : HTTP/1.1 400 Bad Request
Transfer-Encoding: chunked
Cache-Control: private
Client-Request-Id: 7001728a-4c8d-48d6-96cc-3dfc31de0d18
Content-Type: application/json
Date: Sat, 03 Nov 2018 16:49:46 GMT
Duration: 195.3003
Request-Id: 7001728a-4c8d-48d6-96cc-3dfc31de0d18
Strict-Transport-Security: max-age=31536000
X-Ms-Ags-Diagnostic: {"ServerInfo":{"DataCenter":"UK South","Slice":"SliceC","Ring":"5","ScaleUnit":"002","Host":"AGSFE_IN_3","ADSiteName":"UKS"}}

10a
{
  "error": {
    "code": "generalException",
    "message": "Could not find a property named 'quota' on type 'oneDrive.item'.",
    "innerError": {
      "request-id": "7001728a-4c8d-48d6-96cc-3dfc31de0d18",
      "date": "2018-11-03T16:49:46"
    }
  }
}
0
```

**Comment by Cnly** [comment] 2018-11-04 13:38
Just got some time to look into this problem... I did some test and could confirm this. This problem only seems to happen with OneDrive Personal. I was unable to reproduce it on OD for Business and from @JRman your Drive ID format included in your log I suppose you're using OD for Personal as well. Am I correct?

I remembered we could use both `/root:/path/to/file` and `/root:/path/to/file:` to address an item by path, although the [docs](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/driveitem) seem to mention the latter only when there's some suffix, e.g. `/root:/path/to/file:/createUploadSession`. I tried adding the trailing colon and that fixed the problem.

I've created a test version [here](https://beta.rclone.org/branch/v1.44-037-g638cea21-onedrive-path-workaround-2720-beta/). Could you help test it? Thanks!

**Comment by JRman** [comment] 2018-11-04 18:03
Yes, I am using OD Personal.  I tried the patched version and everything is now working correctly.

My syncs are all running clean now (windows version FYI)

Thanks!

**Comment by Cnly** [comment] 2018-11-08 03:12
I have created an upstream issue and let's see if this can be fixed by OneDrive.

**Comment by gabriellluz** [comment] 2018-11-24 09:35
This happens to me, too. Exactly the same.

**Comment by ajuitar** [comment] 2018-12-24 10:48
A similar thing happened to me. The name of a folder on OneDrive Personal "Old_drive" gave me the same "Could not find a property named 'quota' on type 'oneDrive.item'." error, and no files would sync. I changed the name of the remote folder to "Old_drv", and the sync went without errors.

**Comment by Aquarian-Age** [comment] 2019-01-27 04:05
rclone -V
rclone v1.45
- os/arch: linux/amd64
- go version: go1.11.2

----

Create a onedrive.md file in the /home/username/doc/xxx/ directory. Run rclone sync /home/username/doc/ onedrive:doc

Create a directory called onedrive in the /home/username/doc/xxx/ directory and move onedrive.md to the home/username/doc/xxx/onedrive/ directory.

Executing rclone sync /home/username/doc/ onedrive:doc will reproduce this problem

I just tried to delete the /home/username/doc/xxx/onedrive directory and re-create a /home/username/doc/OneDrive-cli directory.
Perform synchronization
The problem is solved

**Comment by Cnly** [comment] 2019-03-13 03:50
I've merged the workaround into master. Please feel free to re-open if you're still seeing problems.

**Closed by Cnly** 2019-03-13 03:50 UTC
Labels: Remote: One Drive, bug
