### ISSUE TITLE
b2: file segmentation must be no

### ISSUE THREAD

**Issue by marrie** [ncw/rclone#884] opened 2016-11-15 17:51 UTC
Service: b2
rclone version: rclone v1.33-79-g77b975dβ
mac os version: 
ProductName:	Mac OS X
ProductVersion:	10.12.2
BuildVersion:	16C41b

When I did a backup I got a message that file name segment must be no. I have 10 retries so all of them should have failed but here is the log file indicating as such.

Thanks.
[output log here](https://github.com/ncw/rclone/files/592735/output.logaa.zip)

**Comment by marrie** [comment] 2016-11-16 05:25
Well, thinking a reboot would fix this I rebooted, it didn't fix. I'm still getting similar errors. Did b2 brake? Also I noticed rclone used all of my I think it was 25 hundred class c transactions. Is here a way to disable that so it's not trying to get the file list every time? I've not seen this inbehavior by the way.
[output log here](https://github.com/ncw/rclone/files/593812/outputsa.logaa.zip)

**Comment by ncw** [comment] 2017-03-01 16:47
I'm going to close this as a duplicate of #965

**Closed by ncw** 2017-03-01 16:47 UTC
Labels: duplicate
