### ISSUE TITLE
rclone couldn't sync between two onedrive.

### ISSUE THREAD

**Issue by guoxiangke** [ncw/rclone#2684] opened 2018-10-22 10:46 UTC
#### What is the problem you are having with rclone?

both rclone ls 1drive:/  && rclone ls 2drive:/  works on my pi.
but rclone -vvv sync 1drive:/ 2drive:/ give errors unauthenticated

2018/10/22 18:43:07 ERROR : backup: error reading source directory: couldn't list files: unauthenticated: invalidAudienceUri: Invalid audience Uri 'https://****-my.sharepoint.com/'.

#### What is your rclone version (output from `rclone version`)

pi@raspberrypi:~ $ rclone version
rclone v1.43.1
- os/arch: linux/arm
- go version: go1.11

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
pi@raspberrypi:~ $ arch
armv7l

####  Which cloud storage system are you using? (eg Google Drive)

onedrive

**Comment by Cnly** [comment] 2018-10-24 13:08
Hi, since rclone v1.43 and v1.44 actually use different versions of API for OneDrive, could you please try again with v1.44 and see if the problem is still there? Future code changes will probably be based on v1.44. Thanks!

**Comment by Cnly** [comment] 2019-02-05 18:09
I'm closing this issue for now because it's for an old version of rclone. Please feel free to re-open if you have any updates.

**Closed by Cnly** 2019-02-05 18:09 UTC
Labels: Remote: One Drive
