### ISSUE TITLE
Slice bounds out of range

### ISSUE THREAD

**Issue by pmow** [ncw/rclone#2020] opened 2018-01-26 23:16 UTC
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the latest beta of rclone.

    https://beta.rclone.org/
    https://rclone.org/downloads/

If you've just got a question or aren't sure if you've found a bug then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)
1.39 and I also attempted on rclone v1.39-045-ga80d8a21β

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu Linux 64

> Which cloud storage system are you using? (eg Google Drive)
Google Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone lsd volume:dir

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
~/rclone-v1.39-045-ga80d8a21β-linux-amd64$ rclone lsd gdrivevol:tv/ -vv
2018/01/26 18:15:37 DEBUG : Using config file from "/home/pmow/.config/rclone/rclone.conf"
2018/01/26 18:15:37 DEBUG : rclone: Version "v1.39-045-ga80d8a21β" starting with parameters ["rclone" "lsd" "gdrivevol:tv/" "-vv"]
2018/01/26 18:15:39 DEBUG : gdcache: wrapped gdrive:rclone-dontsync/ukn5hhvkk2s4leshm7hsskjbi0 at root /ukn5hhvkk2s4leshm7hsskjbi0
2018/01/26 18:15:39 INFO  : gdcache: Cache DB path: /home/pmow/.cache/rclone/cache-backend/gdcache.db
2018/01/26 18:15:39 INFO  : gdcache: Cache chunk path: /home/pmow/.cache/rclone/cache-backend/gdcache
2018/01/26 18:15:39 INFO  : gdcache: Chunk Memory: true
2018/01/26 18:15:39 INFO  : gdcache: Chunk Size: 5M
2018/01/26 18:15:39 INFO  : gdcache: Chunk Total Size: 10G
2018/01/26 18:15:39 INFO  : gdcache: Chunk Clean Interval: 1m0s
2018/01/26 18:15:39 INFO  : gdcache: Workers: 4
2018/01/26 18:15:39 INFO  : gdcache: File Age: 24h0m0s
2018/01/26 18:15:39 INFO  : gdcache: Cache Writes: false
2018/01/26 18:15:39 INFO  : cache: deleted (0) chunks
2018/01/26 18:15:40 DEBUG : gdcache: wrapped gdrive:rclone-dontsync/ukn5hhvkk2s4leshm7hsskjbi0 at root /ukn5hhvkk2s4leshm7hsskjbi0
2018/01/26 18:15:40 INFO  : gdcache: Cache DB path: /home/pmow/.cache/rclone/cache-backend/gdcache.db
2018/01/26 18:15:40 INFO  : gdcache: Cache chunk path: /home/pmow/.cache/rclone/cache-backend/gdcache
2018/01/26 18:15:40 INFO  : gdcache: Chunk Memory: true
2018/01/26 18:15:40 INFO  : gdcache: Chunk Size: 5M
2018/01/26 18:15:40 INFO  : gdcache: Chunk Total Size: 10G
2018/01/26 18:15:40 INFO  : gdcache: Chunk Clean Interval: 1m0s
2018/01/26 18:15:40 INFO  : gdcache: Workers: 4
2018/01/26 18:15:40 INFO  : gdcache: File Age: 24h0m0s
2018/01/26 18:15:40 INFO  : gdcache: Cache Writes: false
2018/01/26 18:15:40 INFO  : Encrypted drive 'gdrivevol:tv/': Modify window is 1ms
panic: runtime error: slice bounds out of range

goroutine 61 [running]:
github.com/ncw/rclone/backend/cache.(*Directory).Remote(0xc42010a3f0, 0x34, 0x34)
        /home/travis/gopath/src/github.com/ncw/rclone/backend/cache/directory.go:98 +0x117
github.com/ncw/rclone/backend/cache.(*Persistent).GetDirEntries.func1(0xc420187420, 0x101bcb0, 0xc420187420)
        /home/travis/gopath/src/github.com/ncw/rclone/backend/cache/storage_persistent.go:204 +0x2d5
github.com/ncw/rclone/vendor/github.com/coreos/bbolt.(*DB).View(0xc42009e3c0, 0xc420453a88, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/coreos/bbolt/db.go:698 +0x9a
github.com/ncw/rclone/backend/cache.(*Persistent).GetDirEntries(0xc4212f6500, 0xc42010a3f0, 0x0, 0xc42010a3f0, 0x8, 0x10, 0xc420159210)
        /home/travis/gopath/src/github.com/ncw/rclone/backend/cache/storage_persistent.go:182 +0x7d
github.com/ncw/rclone/backend/cache.(*Fs).List(0xc4201541a0, 0x0, 0x0, 0x0, 0x0, 0x2, 0x2, 0xc420453f68)
        /home/travis/gopath/src/github.com/ncw/rclone/backend/cache/cache.go:466 +0xb3
github.com/ncw/rclone/backend/crypt.(*Fs).List(0xc42008adc0, 0x0, 0x0, 0xc4200f27c0, 0xc420025300, 0xc4200f2800, 0xc4200f2820, 0xc4200f2840)
        /home/travis/gopath/src/github.com/ncw/rclone/backend/crypt/crypt.go:240 +0x76
github.com/ncw/rclone/fs/list.DirSorted(0x15ddc60, 0xc42008adc0, 0x0, 0x0, 0x0, 0xc4200f2ac0, 0xc4200f2ae0, 0xc4200f2b00, 0xc4200f2b20, 0xc4200f2b40)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/list/list.go:23 +0x63
github.com/ncw/rclone/fs/walk.walk.func2(0xc420308ea0, 0xc4203167e0, 0x101b930, 0x15ddc60, 0xc42008adc0, 0x0, 0xc420308ee0, 0xc4203156c0, 0xc420308eb0, 0xc420223f50, ...)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/walk/walk.go:122 +0x1e3
created by github.com/ncw/rclone/fs/walk.walk
        /home/travis/gopath/src/github.com/ncw/rclone/fs/walk/walk.go:114 +0x265

```

**Comment by B4dM4n** [comment] 2018-01-27 14:35
I was able to reproduce the issue using this remotes:
```
[TestDrive]
type = drive
client_id = ...
client_secret = ...
service_account_file = 
token = ...

[TestDriveCache]
type = cache
remote = TestDrive:cache
plex_url = 
plex_username = 
plex_password = 
chunk_size = 1m
info_age = 1h
chunk_total_size = 500M

[TestDriveCacheEnc]
type = crypt
remote = TestDriveCache:
filename_encryption = standard
directory_name_encryption = true
password = ...
password2 = ...
```
Running `rclone mkdir -vv TestDriveCacheEnc:tv` will result in a panic `runtime error: slice bounds out of range`

The issue is using the plain remote `TestDriveCache:` as the crypt remote.
[backend/crypt/crypt.go#110](https://github.com/ncw/rclone/blob/master/backend/crypt/crypt.go#L110) will produce a `remotePath = "TestDriveCache:/0ohpbtuvsv3o1m0c6bo69gia6k"`.

In [backend/cache/directory.go#96](https://github.com/ncw/rclone/blob/master/backend/cache/directory.go#L96) the result of `p := cleanPath(path.Join(d.Dir, d.Name))` will be `"0ohpbtuvsv3o1m0c6bo69gia6k"` while `d.CacheFs.Root()` is `"/0ohpbtuvsv3o1m0c6bo69gia6k"`.

A possible fix would be
```
diff --git a/fs/fs.go b/fs/fs.go
index b743ffb9..a5f79850 100644
--- a/fs/fs.go
+++ b/fs/fs.go
@@ -715,7 +715,7 @@ func ParseRemote(path string) (fsInfo *RegInfo, configName, fsPath string, err e
        var fsName string
        fsName, configName, fsPath = "local", "local", path
        if parts != nil && !driveletter.IsDriveLetter(parts[1]) {
-               configName, fsPath = parts[1], parts[2]
+               configName, fsPath = parts[1], strings.TrimLeft(parts[2], "/")
                fsName = ConfigFileGet(configName, "type")
                if fsName == "" {
                        return nil, "", "", ErrorNotFoundInConfigFile
```

**Comment by B4dM4n** [comment] 2018-01-29 10:36
This is the same as #1945

**Comment by pmow** [comment] 2018-01-29 15:22
Just to clarify, I tried with and without trailing slash.  Incidentally I made use of purge cache switch, which worked around the issue.

**Comment by B4dM4n** [comment] 2018-01-29 15:50
It's not the trailing `/` that's causing the problem.
There is a leading `/` passed to the `cache` backend.

Using my config above, the remote passed from the `crypt` to the `cache` backend will look like this: `TestDriveCache:/0ohpbtuvsv3o1m0c6bo69gia6k`

**Comment by B4dM4n** [comment] 2018-01-30 18:38
The issue should be fixed in https://beta.rclone.org/v1.39-098-ged2d4ef4/

If it doesn't work, please re-open the issue.

**Closed by B4dM4n** 2018-01-30 18:38 UTC
