### ISSUE TITLE
backblaze b2 large file endless loop

### ISSUE THREAD

**Issue by wizzard0** [ncw/rclone#597] opened 2016-07-25 09:33 UTC
Trying to transfer 100 gb file, speed is fine but it has no chance to complete. Infinite exponential backoff on error 500/503 maybe?
Also minimum sleep timer probably should be 5sec, and timeout 5min, backblaze is SLOW.

> What is your rclone version (eg output from `rclone -V`)
rclone v1.32

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Win10 64bit

> Which cloud storage system are you using? (eg Google Drive)
Backblaze B2

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy -v archive.rar b2:wizzard/containers

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

```
2016/07/25 12:20:06 archive.rar: Sending chunk 48 length 100663296
2016/07/25 12:20:13 archive.rar: Done sending chunk 44
2016/07/25 12:20:13 archive.rar: Sending chunk 49 length 100663296
2016/07/25 12:20:37
Transferred:   11.906 GBytes (3.692 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     55m1.9s
Transferring:
 *                                archive.rar:  4% done. avg: 8061.9, cur: 2680.1 kByte/s. ETA: 10h21m30s

2016/07/25 12:20:41 archive.rar: Clearing part upload URL because of error: Not enough members for write of 4_z5d310083bc06005156640f1e_f31036e1573ae1966_d20160725_m091938_c001_v0001013_t0037: class org.apache.http.conn.ConnectTimeoutException - Connect to member-15.vault:8180 [member-15.vault/192.168.243.25] failed: connect timed out; class org.apache.http.conn.ConnectTimeoutException - Connect to member-17.vault:8180 [member-17.vault/192.168.243.27] failed: connect timed out (500 internal_error)
2016/07/25 12:20:41 pacer: Rate limited, increasing sleep to 20ms
2016/07/25 12:20:41 pacer: low level retry 1/10 (error Not enough members for write of 4_z5d310083bc06005156640f1e_f31036e1573ae1966_d20160725_m091938_c001_v0001013_t0037: class org.apache.http.conn.ConnectTimeoutException - Connect to member-15.vault:8180 [member-15.vault/192.168.243.25] failed: connect timed out; class org.apache.http.conn.ConnectTimeoutException - Connect to member-17.vault:8180 [member-17.vault/192.168.243.27] failed: connect timed out (500 internal_error))
2016/07/25 12:20:41 archive.rar: Sending chunk 46 length 100663296
2016/07/25 12:20:42 B2 bucket wizzard path containers/: Setting sleep to 1s after error: No uploads available in vault 0001013 (503 service_unavailable)
2016/07/25 12:20:42 pacer: Rate limited, increasing sleep to 1s
2016/07/25 12:20:42 pacer: low level retry 1/10 (error No uploads available in vault 0001013 (503 service_unavailable))
2016/07/25 12:20:43 pacer: Rate limited, increasing sleep to 2s
2016/07/25 12:20:43 pacer: low level retry 2/10 (error No uploads available in vault 0001013 (503 service_unavailable))
2016/07/25 12:20:44 pacer: low level retry 3/10 (error No uploads available in vault 0001013 (503 service_unavailable))
2016/07/25 12:20:46 pacer: low level retry 4/10 (error No uploads available in vault 0001013 (503 service_unavailable))
2016/07/25 12:20:48 pacer: low level retry 5/10 (error No uploads available in vault 0001013 (503 service_unavailable))
2016/07/25 12:20:50 pacer: low level retry 6/10 (error No uploads available in vault 0001013 (503 service_unavailable))
2016/07/25 12:20:52 pacer: low level retry 7/10 (error No uploads available in vault 0001013 (503 service_unavailable))
2016/07/25 12:20:54 pacer: low level retry 8/10 (error No uploads available in vault 0001013 (503 service_unavailable))
2016/07/25 12:20:56 pacer: low level retry 9/10 (error No uploads available in vault 0001013 (503 service_unavailable))
2016/07/25 12:20:58 pacer: low level retry 10/10 (error No uploads available in vault 0001013 (503 service_unavailable))
2016/07/25 12:20:58 pacer: Reducing sleep to 1s
2016/07/25 12:20:58 archive.rar: Error sending chunk 46: failed to get upload URL: No uploads available in vault 0001013 (503 service_unavailable)
2016/07/25 12:20:58 pacer: Reducing sleep to 500ms
2016/07/25 12:20:58 archive.rar: Done sending chunk 49
2016/07/25 12:20:58 pacer: Reducing sleep to 250ms
2016/07/25 12:20:58 archive.rar: Done sending chunk 47
2016/07/25 12:20:58 pacer: Reducing sleep to 125ms
2016/07/25 12:20:58 archive.rar: Done sending chunk 48
2016/07/25 12:20:59 archive.rar: Sending chunk 50 length 100663296
2016/07/25 12:21:37
Transferred:   11.906 GBytes (3.627 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     56m1.9s
Transferring:
 *                                archive.rar:  4% done. avg: 7339.6, cur:   49.0 kByte/s. ETA: 566h23m46s

2016/07/25 12:21:56 pacer: Reducing sleep to 62.5ms
2016/07/25 12:21:56 archive.rar: Done sending chunk 50
```

>>> WTF

```
2016/07/25 12:21:56 archive.rar: Cancelling large file upload due to error: failed to get upload URL: No uploads available in vault 0001013 (503 service_unavailable)
```

>>> WTF

```
2016/07/25 12:21:58 pacer: Reducing sleep to 31.25ms
2016/07/25 12:21:58 archive.rar: Received error: failed to get upload URL: No uploads available in vault 0001013 (503 service_unavailable) - low level retry 2/10
2016/07/25 12:21:58 archive.rar: Removing failed copy
2016/07/25 12:21:58 pacer: Reducing sleep to 15.625ms
2016/07/25 12:21:58 archive.rar: Failed to remove failed copy: failed to delete file: File not present: containers/archive.rar (400 no_such_file)
2016/07/25 12:21:59 pacer: Reducing sleep to 10ms
2016/07/25 12:21:59 archive.rar: Starting upload of large file in 1067 chunks (id "4_z5d310083bc06005156640f1e_f201af4d1d5887eb7_d20160725_m092157_c001_v0001001_t0025")
2016/07/25 12:22:00 archive.rar: Sending chunk 1 length 100663296
2016/07/25 12:22:02 archive.rar: Sending chunk 2 length 100663296
2016/07/25 12:22:03 archive.rar: Sending chunk 3 length 100663296
2016/07/25 12:22:04 archive.rar: Sending chunk 4 length 100663296
2016/07/25 12:22:34 archive.rar: Done sending chunk 3
2016/07/25 12:22:34 archive.rar: Sending chunk 5 length 100663296
2016/07/25 12:22:37
Transferred:   12.469 GBytes (3.731 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     57m1.9s
Transferring:
 *                                archive.rar:  0% done. avg: 15541.6, cur: 11507.2 kByte/s. ETA: 2h31m1s

2016/07/25 12:23:00 archive.rar: Done sending chunk 5
2016/07/25 12:23:00 archive.rar: Sending chunk 6 length 100663296
2016/07/25 12:23:02 archive.rar: Done sending chunk 2
2016/07/25 12:23:02 archive.rar: Sending chunk 7 length 100663296
2016/07/25 12:23:29 archive.rar: Done sending chunk 6
2016/07/25 12:23:29 archive.rar: Sending chunk 8 length 100663296
2016/07/25 12:23:37
Transferred:   12.750 GBytes (3.750 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     58m1.9s
Transferring:
 *                                archive.rar:  0% done. avg: 9032.4, cur: 5658.3 kByte/s. ETA: 5h6m15s

2016/07/25 12:23:38 archive.rar: Done sending chunk 7
2016/07/25 12:23:38 archive.rar: Sending chunk 9 length 100663296
2016/07/25 12:23:50 archive.rar: Done sending chunk 8
2016/07/25 12:23:50 archive.rar: Sending chunk 10 length 100663296
2016/07/25 12:24:33 archive.rar: Done sending chunk 10
```

**Comment by ncw** [comment] 2016-08-01 21:56
Sorry I missed this issue when you posted it.

I've not seen the `No uploads available in vault 0001013 (503 service_unavailable)` error which seems to be the root cause of your problem.  It looks like backblaze is too busy.

I can see I've made a mistake and capped the retry time to 2 seconds - if rclone had been backing off exponentially there then hopefully it would have got an upload URL.

I'll set the max time to 5 minutes and post a beta for you to try.

You can also try increasing `--low-level-retries`

**Comment by ncw** [comment] 2016-08-01 22:04
Here is a beta with the upper pause time set to 5 minutes from 2 seconds.

http://pub.rclone.org/v1.32-4-g57f8f1e%CE%B2/

**Comment by wizzard0** [comment] 2016-08-02 06:01
Thanks, I will try the beta.

Regarding 5 minutes... the support finally responded and said "when receiving errors 500 or 503 you should try exponential backoff starting from 1 second up to 1 hour, because individual vaults may be taken down up to 30 minutes for maintenance". So I guess 5 minutes may still not be enough :)

**Comment by wizzard0** [comment] 2016-08-03 16:02
Well, it seems to work :)

**Comment by ncw** [comment] 2016-08-22 17:43
I'm going to close this now as it seems to work :-)

You would need to set `--low-level-retries=20` to make sure of waiting an hour (checking every 5 minutes). `--low-level-retries=10` will only wait just under 15 minutes.

**Closed by ncw** 2016-08-22 17:43 UTC
Labels: bug
