### ISSUE TITLE
Frequent seeking causes "failed to authenticate decrypted block - bad password?" on encrypted ACD

### ISSUE THREAD

**Issue by Coornail** [ncw/rclone#828] opened 2016-10-27 15:55 UTC
> What is your rclone version (eg output from `rclone -V`)
> rclone v1.33-83-g8710741β

Plex scanning on an encrypted Amazon Cloud Drive mount throws _ReadFileHandle.Read io.Seeker failed: failed to authenticate decrypted block - bad password?_ errors.

The file is always different, and reading them from the beginning to the end is working without any problem.

Here is an example with only the relevant file:

```
file1: Dir.Lookup
file1: Dir.Lookup OK
file1: File.Attr
file1: File.Open
file1: ReadFileHandle.Read size 4096 offset 25944064
file1: ReadFileHandle.seek from 0 to 25944064 (io.Seeker)
file1: ReadFileHandle.Read OK
file1: ReadFileHandle.Read size 16384 offset 0
file1: ReadFileHandle.seek from 25945952 to 0 (io.Seeker)
file1: ReadFileHandle.Read OK
file1: ReadFileHandle.Read size 4096 offset 45056
file1: ReadFileHandle.seek from 16384 to 45056 (io.Seeker)
file1: ReadFileHandle.Read OK
file1: ReadFileHandle.Read size 4096 offset 77824
file1: ReadFileHandle.seek from 49152 to 77824 (io.Seeker)
file1: ReadFileHandle.Read io.Seeker failed: failed to authenticate decrypted block - bad password?
file1: ReadFileHandle.Read size 4096 offset 77824
file1: ReadFileHandle.seek from 49152 to 77824 (io.Seeker)
file1: ReadFileHandle.Read io.Seeker failed: failed to authenticate decrypted block - bad password?
file1: ReadFileHandle.Read size 4096 offset 77824
file1: ReadFileHandle.seek from 49152 to 77824 (io.Seeker)
file1: ReadFileHandle.Read io.Seeker failed: failed to authenticate decrypted block - bad password?
file1: ReadFileHandle.Read size 4096 offset 77824
file1: ReadFileHandle.seek from 49152 to 77824 (io.Seeker)
file1: ReadFileHandle.Read io.Seeker failed: failed to authenticate decrypted block - bad password?
file1: ReadFileHandle.Read size 4096 offset 77824
file1: ReadFileHandle.seek from 49152 to 77824 (io.Seeker)
file1: ReadFileHandle.Read io.Seeker failed: failed to authenticate decrypted block - bad password?
file1: ReadFileHandle.Flush
file1: ReadFileHandle.Flush OK
file1: ReadFileHandle.Release closing
file1: ReadFileHandle.Release OK
```

I believe the issue is related to the frequent seeking in the file, possibly a missing lock.

**Comment by Coornail** [comment] 2016-10-27 15:58
As of reproducing it, I'm not entirely sure.

I would upload a moderate sized file (100 megabytes?) to an encrypted amazon cloud folder and try to seek to different positions in it.

**Comment by ncw** [comment] 2016-10-27 16:47
Exactly how big is file1 in your log above?

@Coornail 
> As of reproducing it, I'm not entirely sure.
> 
> I would upload a moderate sized file (100 megabytes?) to an encrypted amazon cloud folder and try to seek to different positions in it.

I uploaded a 2 GB file to acd+crypt and ran a seek testing program I wrote which did a random seek, read a random amount of data and compared it against a local copy of the file.  That didn't find any errors 200 times in a row :-(

Can send a complete unmodified log please?  Email it to me at nick@craig-wood.com if you don't want it to be public.

Thanks

Nick

**Comment by Coornail** [comment] 2016-10-27 17:01
Sent you an email with the log file.
The file in question is 25 megabytes (25945952 bytes).

**Comment by ncw** [comment] 2016-10-27 17:46
Thanks for the log.

Can you send one with `--debug-fuse` too please?

> Edit: I'm not sure, but it's possible that multiple processes opened the file to read. Could that be an issue?

It might be something like that.  How do the multiple processes open the file? Is one forked from the other?

**Comment by Coornail** [comment] 2016-10-27 18:01
I'll email you a logfile with `--debug-fuse`.

They are forked from the same process. This is how pstree looks like:
```
start.sh---start_pms---Plex Media Serv-+-Plex Media Scan---3*[{Plex Media Scan}]
                                       |-Plex Script Hos---12*[{Plex Script Hos}]
                                       |-Plex Script Hos---17*[{Plex Script Hos}]
                                       |-6*[Plex Script Hos---9*[{Plex Script Hos}]]
                                       |-Plex Script Hos---10*[{Plex Script Hos}]
                                       `-26*[{Plex Media Serv}]
```
Sadly Plex is closed source, so the things I can find out are limited.

My setup is running in a docker container (which is an another things to consider).

**Comment by ncw** [comment] 2016-10-28 12:38
@Coornail thanks for the log - I have spent some time studying that but haven't come to a conclusion yet.

Can you send me a log with `-v --debug-fuse --dump-headers` in please?  This will be quite big and have `Authorization:` headers in you should strip out before sending eg `grep -v Authorization: <dirty-log >clean-log`.

I've also posted a version of rclone with the race detector built in.  rclone runs a bit slower like that, but it will produce a traceback if it detects any races which would indicate more missing locking.  If you can run that with `-v --debug-fuse` and send me the log I would be grateful (the race detector will write to stderr I think so make sure you capture that).

http://pub.rclone.org/rclone-v1.33-85-g6846a1c-linux-amd64-race.gz

Thanks for your help and hopefully we'll get to the bottom of this shortly!

**Comment by Coornail** [comment] 2016-10-28 13:17
Thanks @ncw!

I'll get to it in a few hours and email you the log.

**Comment by ncw** [comment] 2016-10-31 14:34
Thanks for the log.  It looks like there are no races which is good :-)

What appears to be happening is every now and again rclone does a `Range:` request, but acd replies with a normal `200 OK` instead of a `206 Partial Content`
```
2016/10/28 20:51:04 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2016/10/28 20:51:04 HTTP REQUEST
2016/10/28 20:51:04 GET /cdproxy/nodes/XXXX/content HTTP/1.1
Host: content-na.drive.amazonaws.com
User-Agent: rclone/v1.33-DEV
Range: bytes=786165168-

2016/10/28 20:51:04 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
```

and the response was

```
2016/10/28 20:51:06 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2016/10/28 20:51:06 HTTP RESPONSE
2016/10/28 20:51:06 HTTP/1.1 200 OK
Content-Length: 359274160
Cache-Control: public, max-age=7200
Connection: keep-alive
Content-Disposition: attachment;   	filename=XXXXX
Content-Type: application/octet-stream
Date: Fri, 28 Oct 2016 20:51:06 GMT
Etag: "3aa5a31aeeca48405be931b18aa754dd-69"
Server: Amazon-Cloud-Drive
X-Amzn-Requestid: 550bfe99-860d-4794-b650-44b0fa256b1c

2016/10/28 20:51:06 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
```

So reading from the start of the file not seeked like rclone asked for.

I've put in a work-around for this in this beta.

http://pub.rclone.org/v1.33-92-g881740e-acd-range-fix%CE%B2/

Ideally what I'd like to see is `Error expecting HTTP response 206 but got 200 - retrying` in the logs and it all works properly :-)

Have a go and see what happens - I suggest recording the full log with `-v --debug-fuse --dump-headers` and sending it to me.

Cross fingers!

**Comment by Coornail** [comment] 2016-10-31 15:35
Sounds awesome, thank you!
I'll check it out in a few hours and get back to you.

**Comment by ncw** [comment] 2016-11-01 22:57
With the hints in your logs I managed to reproduce the problem with a program which did lots of simultaneous seeking.  I managed to get the race detector to fire using go tip and it showed me where the problem was.  Here is the commit message.

    crypt: Fix data corruption caused by seeking
    
    The corruption was caused when the file was read to the end thus
    setting io.EOF and returning the buffers to the pool.  Seek reset the
    EOF and carried on using the buffers that had been returned to the
    pool thus causing corruption when other goroutines claimed the buffers
    simultaneously.
    
    Fix by resetting the buffer pointers to nil when released and claiming
    new ones when seek resets EOF.  Also added locking for Read and Seek
    which shouldn't be run concurrently.

I've committed this to a branch and made a beta from it - can you have a go with it please?

http://pub.rclone.org/v1.33-92-g4bcea27-seek-race-fix%CE%B2/

If it works for you too I'll merge it to master.

This turned out to be a complicated problem to debug - that is the danger with highly concurrent programs like rclone, but once I could reproduce it locally I knew I'd crack it!

The ACD 200 vs 206 fix was a complete red-herring, alas caused by my mis-reading of the logs!  I made a change to help with this in the future 5c967810ed15def4f5235cef7d58f26516f8bc5d

Thank you for your help debugging this, and I really hope this fixes it for you!

PS You were spot on with your original comment: `I believe the issue is related to the frequent seeking in the file, possibly a missing lock.` :-)

**Comment by Coornail** [comment] 2016-11-02 00:13
Thank you, we are very close now!
This fix solved 90% of the errors, which is great news, but it also means that there is still a bug that's 10x harder to find.

I'll email you a log tomorrow, and I'm sure we can figure it out!

**Comment by ncw** [comment] 2016-11-03 23:00
OK I've merged the above in: http://beta.rclone.org/v1.33-101-g154e91b/ (ready in 15-30 mins)

I didn't see the logs yet so look forward to seeing them :-)

**Comment by ncw** [comment] 2016-11-04 22:00
Thanks for the logs.

I see the problem - looks straight forward for once!

rclone attempted to seek 20 bytes beyond the end of the file to 371155456 however the file was only 371155436 bytes long.  Amazon responsed with 200 OK and the whole file from the beginning (which is technically an error - it should have given an error here).

The decrypted file is 371064828 bytes long

FUSE asked rclone to seek to position 371068928 in the decrypted stream which is 4100 bytes beyond the end of the stream.

This is a legit thing for fuse/plex to do - rclone needs to check it isn't being asked to seek beyond the end of a file.  I'll have to lookup the exact behaviour required though.

I think that is the problem - I'll double check in the morning!

**Comment by ncw** [comment] 2016-11-05 10:05
I've fixed this now in: http://beta.rclone.org/v1.33-105-gd1080d5/ (uploaded in 15-30 mins) in changeset 64b5a76bec1a49cf74355f8bc939988649424b91

Can you give this a test please and if it still isn't working re-open the ticket!

Thanks for all your testing

**Closed** 2016-11-05 10:05 UTC
Labels: bug, Remote: Amazon Cloud Drive
