### ISSUE TITLE
cache: sometimes failing test

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#1844] opened 2017-11-20 11:06 UTC
Sometimes one of the [cache tests fails](https://travis-ci.org/ncw/rclone/jobs/304311868)

```
2017/11/19 13:53:15 NOTICE: Config file "/notfound" not found - using defaults
--- FAIL: TestInternalLargeWrittenContentMatches (1.39s)
	Error Trace:	cache_internal_test.go:584
			cache_internal_test.go:255
	Error:      	Received unexpected error:
	            	unexpected EOF
2017/11/19 13:54:33 NOTICE: Config file "/notfound" not found - using defaults
FAIL
FAIL	github.com/ncw/rclone/cache	77.922s
```

It would be nice to make this 100% reliable.

**Comment by remusb** [comment] 2017-11-20 12:16
So it's still happening. I'll need to do some troubleshooting on Travis then cause it wasn't reproducible locally (even with various flags).

@ncw Assign this to me and in the meantime would you think that by disabling the internal tests of cache to not interfere with other PRs would be better?

**Comment by ncw** [comment] 2017-11-20 14:20
It doesn't fail very often and I've seen it fail on Windows and Linux.

If it annoys me too much I'll disable the test :-)

**Comment by remusb** [comment] 2017-12-09 21:57
A bunch of these should have disappeared.

It seems to be related to time-based tests and I'm making assumption based on the performances of my machine which I imagine is quite different from the test environments. I still have one more test skipped but I'll make sure to not include these types of tests and do them differently from now on.

**Comment by remusb** [comment] 2018-01-30 20:19
Closing this as I've left only a couple of basic tests to run by default which will likely never fail. The full suite will be executed offline as I'm mostly interested in cloud remotes + mounted runs anyway, less in local caching.

**Closed by remusb** 2018-01-30 20:19 UTC
Labels: Remote: Cache, maintenance
