### ISSUE TITLE
Rclone always finding new files to copy

### ISSUE THREAD

**Issue by jonas2295** [ncw/rclone#1570] opened 2017-07-31 14:19 UTC
So I have two gdrives that I am keeping mirrored. I have run it a handful of times now since I stopped uploading to the source gdrive and everytime I re-run the command it finds new files to copy even though there was absolutely no change to the files in the source.

It correctly finds existing files and skips those but finds files that have apparently been missed out before even though the outputs do no indicate any errors (-v)

Some examples of the outputs I am getting.

> 2017/07/30 18:20:56 DEBUG : 2016/02-14-16 full backup Sony -gopro/GoPro/117GOPRO/GOPR5074.THM: Unchanged skipping
2017/07/30 18:20:58 DEBUG : 2016/01-24-16 keikis aerial und gopro/gopro/GOPR5013.MP4: Sending chunk 67108864 length 8388608
2017/07/30 18:21:00 DEBUG : 2016/01-10-16 West side/aerial/DJI_0031.MOV: Sending chunk 92274688 length 8388608

Some more:
>/07/30 18:23:21 DEBUG : 2017/01-29-17 Spitting cave whales and more x5s/x5s/A079_C025_20170129_P1/A079_C025_20170129_P0007.mov: Size and modification time the same (differ by 0s, within tolerance 1ms)
2017/07/30 18:23:21 DEBUG : 2017/01-29-17 Spitting cave whales and more x5s/x5s/A079_C025_20170129_P1/A079_C025_20170129_P0007.mov: Unchanged skipping
2017/07/30 18:23:21 DEBUG : 2017/01-29-17 Spitting cave whales and more x5s/x5s/A079_C025_20170129_P1/A079_C025_20170129_P0003.mov: Size and modification time the same (differ by 0s, within tolerance 1ms)
2017/07/30 18:23:21 DEBUG : 2017/01-29-17 Spitting cave whales and more x5s/x5s/A079_C025_20170129_P1/A079_C025_20170129_P0003.mov: Unchanged skipping
2017/07/30 18:23:22 DEBUG : pacer: Rate limited, sleeping for 16.336848143s (5 consecutive low level retries)
2017/07/30 18:23:22 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2017/07/30 18:23:22 DEBUG : 2016/01-10-16 West side/aerial/DJI_0031.MOV: Sending chunk 134217728 length 8388608
2017/07/30 18:23:22 DEBUG : 2016/03-11-16 waikiki plus firework sony/bilder/DSC05128.ARW: Sending chunk 0 length 8388608
2017/07/30 18:23:22 DEBUG : pacer: Resetting sleep to minimum 10ms on success
2017/07/30 18:23:22 DEBUG : 2017/03-28-17 koko arch makapuu lighthouse x5s/sd/DJI_0174.MP4: Sending chunk 58720256 length 8388608
2017/07/30 18:23:23 DEBUG : 2017/03-26-17 Westside x5s gopro/gopro/GOPR3039.MP4: Sending chunk 25165824 length 8388608
2017/07/30 18:23:23 DEBUG : 2017/03-28-17 koko arch makapuu lighthouse x5s/sd/DJI_0170.MP4: Sending chunk 8388608 length 8388608
2017/07/30 18:23:23 DEBUG : 2017/02-05-17 Spitting caves dan x5s/x5s/A081_C016_20170205_B1/A081_C016_20170205_B00043.dng: Sending chunk 16777216 length 4977420
2017/07/30 18:23:24 DEBUG : 2016/01-24-16 keikis aerial und gopro/gopro/GOPR5013.MP4: Sending chunk 109051904 length 8388608`

I tried lowering the transfer count, checking -vv for any errors and --ignore-existing flag with no change.

> What is your rclone version (eg output from `rclone -V`)
1.37
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu, VPS, x86
> Which cloud storage system are you using? (eg Google Drive)
Gdrive 
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone -v --transfers=64 copy "source":/VideoBackup "dest":/VideoBackup

**Comment by ncw** [comment] 2017-07-31 15:54
Check the source and destination for duplicates with `rclone dedupe` - that could be the cause of the problem.

**Comment by jonas2295** [comment] 2017-07-31 21:55
Tried that in --dry-run but there seem to be only about 5 files on each side that are duplicates however there are far more files that rclone copies on a rerun of the copy command.

**Comment by ncw** [comment] 2017-08-01 21:08
Can you send me a complete log with `-vv` please?  With `--dry-run` is fine.

Also can you do `rclone ls2 -R source: > source-list.txt` and `rclone ls2 -R dest: > dest-list.txt` and attach those.

If those have file names you don't want to be public then email them to me at nick@craig-wood.com otherwise attach them all to the issue.

Thanks

**Comment by jonas2295** [comment] 2017-08-01 21:53
I will send you the logs you requested via email in a bit!

**Comment by ncw** [comment] 2017-08-02 13:55
> I will send you the logs you requested via email in a bit!

I've received those thanks.  I think I see what the problem might be - duplicate directories.

Can you send me a log of the sync with -vv too please?  With --dry-run is fine.

**Comment by ncw** [comment] 2017-08-02 21:22
Here is an experimental version of dedupe which will merge duplicated directories which I think will fix your problem.

https://pub.rclone.org/v1.37-045-g3f98978c-dedupedir%CE%B2/

I can see you have duplicated directories here

`grep '/$' < source-list.txt | sort  | uniq -c | sort -n | egrep -v '^ +1 '`

```
      2 2016/Canada 2016/Day 4 DJI sunshine valley/
      2 2017/03-26-17 Westside x5s gopro/Neuer Ordner/
      2 2017/03-28-17 koko arch makapuu lighthouse x5s/Neuer Ordner/
      4 2017/Neuer Ordner/
```

If you want to give it a try, try `rclone dedupe -v --dry-run remote:path` to start with.  `2016/Canada 2016` might be a good directory to start with. When you think the output looks sensible try without the `--dry-run`.  This will merge the contents of the duplicated directories and trash (not delete) the empty directory at the end.  It is brand new code so may have bugs.

**Comment by jonas2295** [comment] 2017-08-03 11:01
Okay awesome! The folder is basically structured by Year - Day - Camera so the camera folders certainly exist several times however in different subfolders etc. Not sure if that is the issue.
I will run the experimental version in a bit, do you still want the sync -vv log of the copy command?

**Comment by jonas2295** [comment] 2017-08-03 11:28
Just tested the experimental and yes it does indeed find a handful of duplicate files to remove in -dry-run. I will let it dedupe both the source and the dest folder after checking that those files were indeed duplicates. After that I will see if the copy command finds new files to copy again or not, right?

**Comment by jonas2295** [comment] 2017-08-03 14:37
`2017/08/03 14:20:06 INFO  :
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:            115750
Transferred:            0
Elapsed time:    12m21.1s
`
Rclone doesn´t find any new files to copy so it seems to be all good with the experimental version!

**Comment by ncw** [comment] 2017-08-07 13:44
Excellent - thanks for testing :-)

I'll merge that into master shortly

**Comment by ncw** [comment] 2017-08-11 13:33
I'm going to close this now as I think the issue has been dealt with.

**Closed by ncw** 2017-08-11 13:33 UTC
