### ISSUE TITLE
b2: rclone eventually fails to respect the specified --transfers value

### ISSUE THREAD

**Issue by dpedu** [ncw/rclone#731] opened 2016-09-14 15:34 UTC
When syncing a large filesystem to B2, rclone eventually transfers only a few files at a time, instead of the requested number of parallel transfers.

When it first starts, everything is good. We see nearly all the transfers running in parallel:

```
Transferred:   51.971 MBytes (882.298 kBytes/s)
Errors:                 0
Checks:              5631
Transferred:           29
Elapsed time:      1m0.3s
Transferring:
 * ...some/unique/file/path: 15% done. avg:   57.4, cur:   36.8 kByte/s. ETA: 6m18s
 * ...some/unique/file/path: 13% done. avg:   25.7, cur:   21.6 kByte/s. ETA: 5m27s
 * ...some/unique/file/path: 13% done. avg:   47.1, cur:   41.5 kByte/s. ETA: 5m43s
 * ...some/unique/file/path: 75% done. avg:   18.9, cur:   17.4 kByte/s. ETA: 17s
 * ...some/unique/file/path: 14% done. avg:   25.6, cur:   31.1 kByte/s. ETA: 3m44s
 * ...some/unique/file/path:  0% done. avg:    0.0, cur:    0.0 kByte/s. ETA: -
 * ...some/unique/file/path: 14% done. avg:   50.9, cur:   47.9 kByte/s. ETA: 5m18s
 * ...some/unique/file/path: 42% done. avg:   19.3, cur:   23.9 kByte/s. ETA: 54s
 * ...some/unique/file/path: 68% done. avg:   27.8, cur:   29.1 kByte/s. ETA: 21s
 * ...some/unique/file/path: 20% done. avg:   17.6, cur:   18.1 kByte/s. ETA: 3m7s
 * ...some/unique/file/path: 23% done. avg:   20.9, cur:   21.1 kByte/s. ETA: 2m28s
 * ...some/unique/file/path:  0% done. avg:    0.0, cur:    0.0 kByte/s. ETA: -
 * ...some/unique/file/path: 11% done. avg:   63.0, cur:  171.4 kByte/s. ETA: 42s
 * ...some/unique/file/path:  9% done. avg:   18.8, cur:   23.7 kByte/s. ETA: 5m12s
 * ...some/unique/file/path:  0% done. avg:    0.0, cur:    0.0 kByte/s. ETA: -
 * ...some/unique/file/path: 51% done. avg:   23.4, cur:   19.7 kByte/s. ETA: 54s
 * ...some/unique/file/path:  0% done. avg:    0.0, cur:    0.0 kByte/s. ETA: -
 * ...some/unique/file/path:  0% done. avg:    0.0, cur:    0.0 kByte/s. ETA: -
 * ...some/unique/file/path:  0% done. avg:    0.0, cur:    0.0 kByte/s. ETA: -
 * ...some/unique/file/path: 40% done. avg:   21.1, cur:   15.0 kByte/s. ETA: 1m40s
 * ...some/unique/file/path:  0% done. avg:    0.0, cur:    0.0 kByte/s. ETA: -
 * ...some/unique/file/path:  0% done. avg:    0.0, cur:    0.0 kByte/s. ETA: -
 * ...some/unique/file/path:  0% done. avg:    0.0, cur:    0.0 kByte/s. ETA: -
 * ...some/unique/file/path: 21% done. avg:   19.5, cur:   24.9 kByte/s. ETA: 2m8s
 * ...some/unique/file/path:  4% done. avg:   32.1, cur:   31.5 kByte/s. ETA: 16m34s
 * ...some/unique/file/path:  0% done. avg:    0.0, cur:    0.0 kByte/s. ETA: -
 * ...some/unique/file/path: 21% done. avg:   22.4, cur:   32.5 kByte/s. ETA: 1m38s
 * ...some/unique/file/path:  1% done. avg:  204.1, cur:  209.0 kByte/s. ETA: 49m3s
 * ...some/unique/file/path:  1% done. avg:  218.2, cur:  240.9 kByte/s. ETA: 42m36s
 * ...some/unique/file/path: 36% done. avg:   32.6, cur:   36.3 kByte/s. ETA: 1m11s
 * ...some/unique/file/path:  4% done. avg:   33.0, cur:   34.8 kByte/s. ETA: 14m57s
 * ...some/unique/file/path: 11% done. avg:   34.3, cur:   37.8 kByte/s. ETA: 5m36s
```

However, after a few hours of syncing many files, most files in the periodically outputted list above will look like:

```
 * ...some/unique/file/path:  0% done. avg:    0.0, cur:    0.0 kByte/s. ETA: -
```

And maybe only 3-5 will still be making progress. The files not making progress will sit that way for some time before eventually being removed and the error counter incremented. The error printed is something along the lines of API token expired, which is not surprising. I will paste the exact error here later today when run with `-v` finishes.

These are generally all plain files with sizes varying between zero bytes and hundreds of GBs.

> What is your rclone version (eg output from `rclone -V`)

rclone v1.33

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 14.04 64 bit

> Which cloud storage system are you using? (eg Google Drive)

B2

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone --config /root/.rclone.conf --transfers 32 --bwlimit 1M --filter-from exclude.txt --delete-excluded sync /local/path remotename:bucket-name

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

http://davepedu.com/files/rclonelog.txt

**Comment by ncw** [comment] 2016-09-14 22:29
Big files upload their parts in parallel and take more than one upload slot which may well explain why some files make no progress for a while - their upload slots are being used by big files uploading.  I should probably have a separate pool for the big file upload chunks then they wouldn't starve the incoming files.

It might be better to have a separate flag for controlling the concurrency of the large file uploads, as each chunk will take 96MB of memory.  If not set it could default to the number of transfers.  This means that by default B2 might transfer twice `transfers` things at once.

I need to see that error message to work out exactly what is going on - I'm not expecting any sort of timeout - and a full log with `-v` would be very helpful.  Attach it here, or if you are worried about the contents email it privately to nick@craig-wood.com .  Put the issue number in the title would be helpful if you do email it.

**Comment by dpedu** [comment] 2016-09-15 01:31
I've updated my original post with a link to the log (4MB+ over 10 hours).

Your theory sounds like it fits in with what I've observed - at the very end of that log, 5 of the 7 files transferring are large, 50-100GB+ files

**Comment by marrie** [comment] 2016-09-15 05:38
I believe I'm also having the same problem wiht the same service. I can't pin it down though as I'm normally asleep  when all of this happens, and I can't normally log dive in my sleep. Waht I normally do is rerun knowing that it won't copy the stuff already there hoping that the larger stuff I do have will copy over.

**Comment by ncw** [comment] 2016-09-15 07:39
@dpedu I've had a look through the log you posted.  I can see clearly the problem you mean.  I think if I do a fix similar to my first comment then it will fix the issues.

I think the issue is mostly cosmetic though - the files not being transferred - the ones you see at 0% will get done eventually.

The errors I see in your log seems to be all backblaze being overloaded at various points in the transfer - `Failed to copy: c001_v0001000_t0021 is too busy (503 service_unavailable)`.  There isn't a lot rclone can do about that except retry the uploads which it will do eventually (see the `--retries` flag).  The log you sent didn't show a retry so I guess it hadn't quite finished yet.

So on a retry rclone should retry those 18 files, hopefully successfully.

@marrie 
> Waht I normally do is rerun knowing that it won't copy the stuff already there hoping that the larger stuff I do have will copy over.
I'd like to see a log with `-v` if possible.

It might be that you need to increase the value of `--low-level-retries` if big files are failing to upload - that will mean rclone will try harder - the log will show you though.

**Comment by ncw** [comment] 2016-10-17 16:09
I've implemented this here: http://beta.rclone.org/v1.33-67-gb7875fc/ (may take 15 mins to be uploaded)

**Closed** 2016-10-17 16:09 UTC
Labels: bug, Remote: Backblaze B2
