### ISSUE TITLE
support for onedrive for business?

### ISSUE THREAD

**Issue by ksne3k2h** [ncw/rclone#900] opened 2016-11-21 07:52 UTC
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the [latest beta of rclone](http://rclone.org/downloads/).

If you've just got a question then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)
v1.34-DEV
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Centos6 64bit
> Which cloud storage system are you using? (eg Google Drive)
onedrive & onedrive for business
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync /home/backup remote:backup
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

**Comment by ncw** [comment] 2016-11-21 11:20
I think this is a duplicate of #254

Can you subscribe to that one please.

Thanks

Nick

**Closed by ncw** 2016-11-21 11:20 UTC
Labels: duplicate
