### ISSUE TITLE
onedrive: SharePoint: Failed to cancel multipart upload: itemNotFound

### ISSUE THREAD

**Issue by xunilog** [ncw/rclone#2661] opened 2018-10-17 07:46 UTC
Rclone Version: 1.44 on Ubuntu 18.04
Storage: OneDrive (Sharepoint library)

I first copied files from Sharepoint to my local drive without any issue (copy command). Then I did some modifications to my files, and tried to do a sync (sync command) from local file system to remote Sharepoint library (Sharepoint Online).

2018/10/17 09:32:41 DEBUG : C/61st C/fitout_info.xlsx: Uploading segment 0/10069 size 10069
2018/10/17 09:32:42 DEBUG : C/61st C/fitout_info.xlsx: Cancelling multipart upload: itemNotFound: The resource could not be found.

2018/10/17 09:32:41 DEBUG : C/tests/20181012 - C test results.xlsx: Uploading segment 0/1842984 size 1842984
2018/10/17 09:32:48 ERROR : C/tests/20181012 - C test results.xlsx: corrupted on transfer: sizes differ 1842984 vs 1851060
2018/10/17 09:32:48 INFO  : C/tests/20181012 - C 360 test results.xlsx: Removing failed copy

**Comment by Cnly** [comment] 2018-10-17 08:58
Hi @xunilog, it seems that this is a duplicate of #2599. Can you confirm that? It's a known problem with SharePoint - it modifies uploaded Office files silently. You may want the flags `--ignore-checksum` and `--ignore-size`. :)

**Comment by xunilog** [comment] 2018-10-18 07:37
Thanks, the flags fixed the checksum issue, but ItemNotFound error is still present:

2018/10/18 09:27:30 NOTICE: C/6 S/fitout_info.xlsx: Failed to cancel multipart upload: itemNotFound: The resource could not be found.
2018/10/18 09:27:30 ERROR : C/6 S/ffitout_info.xlsx: Failed to copy: itemNotFound: The resource could not be found.
2018/10/18 09:27:30 ERROR : One drive root '': not deleting files as there were IO errors
2018/10/18 09:27:30 ERROR : One drive root '': not deleting directories as there were IO errors

**Comment by Cnly** [comment] 2018-10-18 10:09
@xunilog I see from your log that rclone is trying to cancel an upload. Could you post the complete log so we can see why rclone is trying to do that? It would be really helpful. Thanks!

**Comment by Cnly** [comment] 2018-10-21 03:59
@xunilog I hope you don't mind my renaming this issue to "onedrive: SharePoint: Failed to cancel multipart upload: itemNotFound" because the size difference is a known problem. :)

**Comment by xunilog** [comment] 2018-10-21 19:40
Sorry for the delay. I created a test Sharepoint site not to mess with my work files.

I first created a file in Sharepoint called "hello world - now". Then I used rclone config and rclone copy to copy files locally on my laptop.

I modified the file, and ran rclone sync to sync local files back to Sharepoint. I added the "-vv" argument, and below is the result and error I am getting.

2018/10/21 21:35:48 DEBUG : hello world - now (copy).docx: Size and modification time the same (differ by -855.535ms, within tolerance 1s)
2018/10/21 21:35:48 DEBUG : hello world - now (copy).docx: Unchanged skipping
2018/10/21 21:35:48 DEBUG : hello world - now.docx: Modification times differ by 3m1.144464086s: 2018-10-21 21:32:43.855535914 +0200 CEST, 2018-10-21 19:35:45 +0000 UTC
2018/10/21 21:35:48 DEBUG : hello world - now.docx: QuickXorHash = cbaf4c928ab3ccaf41eec603fbff433fee7259cf (Local file system at /home/yann/Sharepoint/Test)
2018/10/21 21:35:48 DEBUG : hello world - now.docx: QuickXorHash = b18dca7f1ccebb7095ac879f0e1a554909844cfc (One drive root &apos;&apos;)
2018/10/21 21:35:48 DEBUG : hello world - now.docx: QuickXorHash differ
2018/10/21 21:35:48 DEBUG : hello world - now.docx: Starting multipart upload
2018/10/21 21:35:48 INFO  : One drive root &apos;&apos;: Waiting for checks to finish
2018/10/21 21:35:48 INFO  : One drive root &apos;&apos;: Waiting for transfers to finish
2018/10/21 21:35:50 DEBUG : hello world - now.docx: Uploading segment 0/13208 size 13208
2018/10/21 21:35:50 DEBUG : hello world - now.docx: Cancelling multipart upload: itemNotFound: The resource could not be found.
2018/10/21 21:35:51 NOTICE: hello world - now.docx: Failed to cancel multipart upload: itemNotFound: The resource could not be found.
2018/10/21 21:35:51 ERROR : hello world - now.docx: Failed to copy: itemNotFound: The resource could not be found.
2018/10/21 21:35:51 DEBUG : One drive root &apos;&apos;: failed to copy 1 directories
2018/10/21 21:35:51 DEBUG : One drive root &apos;&apos;: copied 1 directories
2018/10/21 21:35:51 ERROR : One drive root &apos;&apos;: not deleting files as there were IO errors
2018/10/21 21:35:51 ERROR : One drive root &apos;&apos;: not deleting directories as there were IO errors
2018/10/21 21:35:51 ERROR : Attempt 3/3 failed with 1 errors and: itemNotFound: The resource could not be found.
2018/10/21 21:35:51 Failed to sync: itemNotFound: The resource could not be found.

**Comment by Cnly** [comment] 2018-10-24 11:52
@xunilog I had a look at your log, and this seems like the same bug as https://forum.rclone.org/t/onedrive-error-on-changed-file/6853/7. Can you confirm that? There's also a [workaround](https://forum.rclone.org/t/onedrive-error-on-changed-file/6853/14) in that forum thread.

**Comment by Cnly** [comment] 2019-05-21 19:26
Closing due to inactivity. Please move over to #3212.

**Closed by Cnly** 2019-05-21 19:26 UTC
Labels: Remote: One Drive, bug
