### ISSUE TITLE
UnionFS Crashing

### ISSUE THREAD

**Issue by toomuchio** [ncw/rclone#823] opened 2016-10-26 11:50 UTC
Running the latest beta, Ubuntu x64, Amazon Cloud Storage.

rclone mount acde: /home/*/aws_test --allow-other --no-modtime --dir-cache-time=2m &
unionfs-fuse -o allow_other,cow /home/*/local_test=RW:/home/*/aws_test=RO /home/*/crash

Works fine not in a UnionFS but when in a UnionFS:

2016/10/26 13:42:23 fuse: panic in handler for Read [ID=0x1a2 Node=0x3 Uid=1000 Gid=1000 Pid=29089] 0x2 131072 @0x40000 dir=false fl=0 lock=0 ffl=OpenReadOnly: runtime error: invalid memory address or nil pointer dereference
goroutine 562 [running]:
bazil.org/fuse/fs.(*Server).serve.func2(0xdf7900, 0xc420160770, 0xc420461eb8, 0xc420461e0f)
        /home/travis/gopath/src/bazil.org/fuse/fs/serve.go:857 +0x1d9
panic(0xa2f7a0, 0xc420010090)
        /home/travis/.gimme/versions/go1.7.3.linux.amd64/src/runtime/panic.go:458 +0x243
io.ReadAtLeast(0x0, 0x0, 0xc420400000, 0x10010, 0x10010, 0x10010, 0x5, 0x6, 0x0)
        /home/travis/.gimme/versions/go1.7.3.linux.amd64/src/io/io.go:307 +0x85
io.ReadFull(0x0, 0x0, 0xc420400000, 0x10010, 0x10010, 0xc42121c6f8, 0xc41ffe227a, 0xc42121c770)
        /home/travis/.gimme/versions/go1.7.3.linux.amd64/src/io/io.go:325 +0x58
github.com/ncw/rclone/crypt.(*decrypter).Read(0xc42126a960, 0xc420518000, 0x20000, 0x20000, 0x0, 0x0, 0x44fe10)
        /home/travis/gopath/src/github.com/ncw/rclone/crypt/cipher.go:563 +0x18f
io.ReadAtLeast(0xdf1340, 0xc42126a960, 0xc420518000, 0x20000, 0x20000, 0x20000, 0xa656c0, 0xc4202d4700, 0xdf1340)
        /home/travis/.gimme/versions/go1.7.3.linux.amd64/src/io/io.go:307 +0xa4
io.ReadFull(0xdf1340, 0xc42126a960, 0xc420518000, 0x20000, 0x20000, 0x20000, 0x2, 0x0)
        /home/travis/.gimme/versions/go1.7.3.linux.amd64/src/io/io.go:325 +0x58
github.com/ncw/rclone/cmd/mount.(*ReadFileHandle).Read(0xc4200a2240, 0x7fce2dec2a60, 0xc4212c4300, 0xc420160770, 0xc4202f7ae0, 0x20000, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/cmd/mount/read.go:95 +0x22d
bazil.org/fuse/fs.(*Server).handleRequest(0xc420138900, 0x7fce2dec2a60, 0xc4212c4300, 0xdf1300, 0xc4202a8e40, 0xc4202a8ec0, 0xdf7900, 0xc420160770, 0xc420461eb8, 0x0, ...)
        /home/travis/gopath/src/bazil.org/fuse/fs/serve.go:1249 +0x98c
bazil.org/fuse/fs.(*Server).serve(0xc420138900, 0xdf7900, 0xc420160770)
        /home/travis/gopath/src/bazil.org/fuse/fs/serve.go:878 +0x4a3
bazil.org/fuse/fs.(*Server).Serve.func1(0xc420138900, 0xdf7900, 0xc420160770)
        /home/travis/gopath/src/bazil.org/fuse/fs/serve.go:425 +0x6e
created by bazil.org/fuse/fs.(*Server).Serve
        /home/travis/gopath/src/bazil.org/fuse/fs/serve.go:426 +0x3e4
2016/10/26 13:42:23 fuse: panic in handler for Read [ID=0x1a3 Node=0x3 Uid=1000 Gid=1000 Pid=29089] 0x2 4096 @0x20000 dir=false fl=0 lock=0 ffl=OpenReadOnly: runtime error: invalid memory address or nil pointer dereference
goroutine 563 [running]:
bazil.org/fuse/fs.(*Server).serve.func2(0xdf7900, 0xc420160850, 0xc42037eec8, 0xc42037ee1f)
        /home/travis/gopath/src/bazil.org/fuse/fs/serve.go:857 +0x1d9
panic(0xa2f7a0, 0xc420010090)
        /home/travis/.gimme/versions/go1.7.3.linux.amd64/src/runtime/panic.go:458 +0x243
github.com/ncw/rclone/crypt.(*decrypter).Seek(0xc42126a960, 0x20000, 0x0, 0x2d, 0xc42037e7c8, 0x2)
        /home/travis/gopath/src/github.com/ncw/rclone/crypt/cipher.go:626 +0x28e
github.com/ncw/rclone/cmd/mount.(*ReadFileHandle).seek(0xc4200a2240, 0x20000, 0xb0bfef, 0x25)
        /home/travis/gopath/src/github.com/ncw/rclone/cmd/mount/read.go:47 +0x211
github.com/ncw/rclone/cmd/mount.(*ReadFileHandle).Read(0xc4200a2240, 0x7fce2dec2a60, 0xc420202400, 0xc420160850, 0xc4202c2260, 0x1000, 0xa5ee45aaf5cd)
        /home/travis/gopath/src/github.com/ncw/rclone/cmd/mount/read.go:78 +0x4c9
bazil.org/fuse/fs.(*Server).handleRequest(0xc420138900, 0x7fce2dec2a60, 0xc420202400, 0xdf1300, 0xc4202a8e40, 0xc4202a8ec0, 0xdf7900, 0xc420160850, 0xc42037eec8, 0x0, ...)
        /home/travis/gopath/src/bazil.org/fuse/fs/serve.go:1249 +0x98c
bazil.org/fuse/fs.(*Server).serve(0xc420138900, 0xdf7900, 0xc420160850)
        /home/travis/gopath/src/bazil.org/fuse/fs/serve.go:878 +0x4a3
bazil.org/fuse/fs.(*Server).Serve.func1(0xc420138900, 0xdf7900, 0xc420160850)
        /home/travis/gopath/src/bazil.org/fuse/fs/serve.go:425 +0x6e
created by bazil.org/fuse/fs.(*Server).Serve
        /home/travis/gopath/src/bazil.org/fuse/fs/serve.go:426 +0x3e4
2016/10/26 13:42:24 *: ReadFileHandle.Read error: failed to authenticate decrypted block - bad password?
2016/10/26 13:42:24 *: ReadFileHandle.Read error: failed to authenticate decrypted block - bad password?
2016/10/26 13:42:27 *: ReadFileHandle.Read error: read tcp *: use of closed network connection
2016/10/26 13:42:27 *: ReadFileHandle.Read error: read tcp *: use of closed network connection
2016/10/26 13:42:49 *: ReadFileHandle.Read error: http: read on closed response body
2016/10/26 13:42:49 *: ReadFileHandle.Read error: http: read on closed response body

**Comment by calisro** [comment] 2016-10-26 14:46
Issue #802 seems related.

**Comment by ncw** [comment] 2016-10-26 20:49
How exactly did you cause the crash?  Were you playing a video?  If so with which player?

Can you reliably cause this crash?  If so can you post the whole log please?

Note to self: the crash was caused by the reader being nil in crypt.Decrypter.Read. How did it get to be nil is the question?  Perhaps a race between Read and Seek.

**Comment by completion** [comment] 2016-10-26 21:22
I am having the same issue. I am using the latest version of rclone from github. I mount rclone and unionfs using the same flags and options as OP just different directories. I then try to play the video in plex or copy it:
`$ cp acd/test.mkv ~/`
`cp: error reading 'acd/test.mkv': Input/output error`
The file is 300MB. This errors happens reliably everytime I try to read the file from the unionfs mount. I can read the file perfectly fine directly from the rclone mount. 

logs
[rclone-errors.txt](https://github.com/ncw/rclone/files/554457/rclone-errors.txt)
[rclone-log.txt](https://github.com/ncw/rclone/files/554456/rclone-log.txt)

**Comment by calisro** [comment] 2016-10-26 21:31
@ncw In my case, unionfs doesn't crash at all.  I do get errors with the rclone fuse mount that I can attach but it looks similar to the one above.    I can reliably recreate it with vlc or KODI.  
[out.gz](https://github.com/ncw/rclone/files/554478/out.gz)

**Comment by toomuchio** [comment] 2016-10-26 22:45
@ncw My mistake I should have been more clear, it crashes the mediaplayer. Plex in this case. I even tried AUFS and the more native OverlayFS. Same problem.

**Comment by toomuchio** [comment] 2016-10-27 03:14
Does anybody have a workaround in the mean time?

**Comment by ncw** [comment] 2016-10-27 09:02
Thanks for the logs.

Examining them closely I can see that reads are being issued from mutiple threads simultaneously.  Which lead me to a bit of missing locking in the FUSE module.

Here is a beta with the fix - let me know if it works: http://beta.rclone.org/v1.33-83-g8710741/ (will be uploaded in 15-30 mins)

**Comment by toomuchio** [comment] 2016-10-27 09:22
Confirmed fixed the issue unionfs works now! Thanks for the speedy fix can close this issue off :)

**Comment by ncw** [comment] 2016-10-27 10:05
@toomuchio excellent news - thanks for testing

**Comment by ncw** [comment] 2016-10-27 10:47
@calisro does that fix your issue too?

**Comment by calisro** [comment] 2016-10-27 12:43
@ncw Sure does.  I verified with unionfs and then also verified its working through my nginx setup down through unionfs.  Thanks.

**Comment by ncw** [comment] 2016-10-27 16:48
Excellent - I'm going to close this now

**Closed by ncw** 2016-10-27 16:48 UTC
Labels: bug, FUSE
