### ISSUE TITLE
Is it possible to rename crypt files on a remote?

### ISSUE THREAD

**Issue by jahands** [ncw/rclone#795] opened 2016-10-15 13:58 UTC
I have setup a crypt remote mapped to a folder on Amazon Cloud Drive.
Crypt remote: `sec:acd/Files`
ACD remote: `acd:`
I have both file and filename encryption turned on for the `sec` remote.
Is it possible to rename files? I can't seem to make move work. Should I just not be using filename encryption?

> What is your rclone version (eg output from `rclone -V`)
> v1.33
> 
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
> Windows 10, 64bit, Ubuntu 16.04 64bit
> 
> Which cloud storage system are you using? (eg Google Drive)
> Amazon Cloud Drive
> 
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
> `rclone move sec:test/maps.tar.gz.crdownload sec:test/maps.tar.gz`
> 
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
> `2016/10/15 08:56:33 Failed to move: can't move files on overlapping remotes`

This error is saying I can't do this. So is there no way to organize/rename files on a remote without downloading and re-uploading them? I'm asking because I have multi-GB files I'm trying to store.

**Comment by ncw** [comment] 2016-10-16 10:00
I'm going to fix this in #227

In the mean time you can use the steps that durval made in the forum to find the encrypted name then do the rename in the web interface.

https://forum.rclone.org/t/how-to-efficiently-move-dir1-dir1-to-dir1-amazon-cloud-drive-encrypted/54/4

**Comment by jahands** [comment] 2016-10-16 12:19
Awesome! Will we be able to rename/move both files and folders?

I really appreciate your work, thank you.

**Comment by ncw** [comment] 2016-10-25 18:16
Some time in the future yes!

**Comment by pedrosimao** [comment] 2016-12-04 02:20
I was testing the move command today (with encrypted Amazon Cloud Drive), and I did try to move from Amazon Cloud inside Amazon Cloud itself. I tried to changed the folder name, only. But rclone started downloading and uploading everything all over.
So I realized two things:
1 - The move command is not working. If rclone was smarter it would simply rename the folder instead of trying to re-download everything.
2 - We are missing a rename command. This is especially useful for the encrypted backups, because of the encrypted filenames. Otherwise we could simply use the cloud interface,given by the service provider, to rename each file and folder. But with encrypted version it is not possible since we don't know what name means what, and we don't know how to manually create encrypted names.

**Comment by ncw** [comment] 2016-12-04 20:38
@pedrosimao you should find both of those things are fixed in the latest beta.  In particular server side moves are now supported on acd, and there is the `moveto` command which can be used to rename stuff.

**Comment by jahands** [comment] 2016-12-04 22:05
Awesome, thanks!

**Comment by pedrosimao** [comment] 2016-12-07 12:37
Hello @ncw, I gave it a try on the new move and moveto commands (beta releases), and I am getting errors on both commands:

2016/12/07 13:34:24 Attempt 1/3 failed with 1 errors and: directory not found
2016/12/07 13:34:25 Encrypted amazon drive root 'RCLONE/i80s1nh3c7kb6sd885du23j5b4/cuuo1ld70j689ad5cmkqheubc0/3eqqmb9jmge1u5bo11cg52bpec': Server side directory move failed: directory not found

I am pretty sure the directories do exists. The move and moveto work when I try to move files to a local folder for example. But moving from one encrypted folder to another will result in errors.

**Comment by ncw** [comment] 2016-12-07 14:30
@pedrosimao I can confirm server side directory moves on acd+crypt seem to be broken...

Will fix and post a beta for you to try

**Comment by pedrosimao** [comment] 2016-12-07 17:21
Ok, thanks a lot for that! I am impressed with your speed.

**Comment by ncw** [comment] 2016-12-09 17:36
@pedrosimao try this http://beta.rclone.org/v1.34-60-g2656a0e/ (uploaded in 15-30 mins)

that should fix it hopefully!

**Comment by pedrosimao** [comment] 2016-12-10 08:37
@ncw I will check it out on sunday night. If I find any remaining bugs I will let you know. Thanks a lot!

**Comment by ncw** [comment] 2017-01-09 17:53
Hopefully that is all fixed!  Please re-open if not.

**Closed by ncw** 2017-01-09 17:53 UTC

**Comment by mikeferr** [comment] 2017-01-28 15:16
This isn't working for me on windows (v1.35):

C:\Apps\rclone>rclone.exe moveto encrypt:"Series\Agents Of S.H.I.E.L.D" encrypt:"Series\Marvel's Agents Of S.H.I.E.L.D"

2017/01/28 10:12:39 Encrypted amazon drive root 'rclone/vhm40phu7l34cq5o72dt3pgrjo/kqe0e1bi0khm92ien0ri5lfhum293ug453nv7i9gjcufjtqjemsg': Waiting for checks to finish
2017/01/28 10:12:39 Encrypted amazon drive root 'rclone/vhm40phu7l34cq5o72dt3pgrjo/kqe0e1bi0khm92ien0ri5lfhum293ug453nv7i9gjcufjtqjemsg': Waiting for transfers to finish
2017/01/28 10:12:39 Attempt 1/3 failed with 0 errors and: error listing source: Encrypted amazon drive root 'rclone/vhm40phu7l34cq5o72dt3pgrjo/77tishgnlqagujtsivuj72355l8gan9vijoq6hmvh4lhmt2lqgh0': directory not found
2017/01/28 10:12:40 Encrypted amazon drive root 'rclone/vhm40phu7l34cq5o72dt3pgrjo/kqe0e1bi0khm92ien0ri5lfhum293ug453nv7i9gjcufjtqjemsg': Waiting for checks to finish
2017/01/28 10:12:40 Encrypted amazon drive root 'rclone/vhm40phu7l34cq5o72dt3pgrjo/kqe0e1bi0khm92ien0ri5lfhum293ug453nv7i9gjcufjtqjemsg': Waiting for transfers to finish
2017/01/28 10:12:40 Attempt 2/3 failed with 0 errors and: error listing source: Encrypted amazon drive root 'rclone/vhm40phu7l34cq5o72dt3pgrjo/77tishgnlqagujtsivuj72355l8gan9vijoq6hmvh4lhmt2lqgh0': directory not found
2017/01/28 10:12:40 Encrypted amazon drive root 'rclone/vhm40phu7l34cq5o72dt3pgrjo/kqe0e1bi0khm92ien0ri5lfhum293ug453nv7i9gjcufjtqjemsg': Waiting for checks to finish
2017/01/28 10:12:40 Encrypted amazon drive root 'rclone/vhm40phu7l34cq5o72dt3pgrjo/kqe0e1bi0khm92ien0ri5lfhum293ug453nv7i9gjcufjtqjemsg': Waiting for transfers to finish
2017/01/28 10:12:40 Attempt 3/3 failed with 0 errors and: error listing source: Encrypted amazon drive root 'rclone/vhm40phu7l34cq5o72dt3pgrjo/77tishgnlqagujtsivuj72355l8gan9vijoq6hmvh4lhmt2lqgh0': directory not found
2017/01/28 10:12:40 Failed to moveto: error listing source: Encrypted amazon drive root 'rclone/vhm40phu7l34cq5o72dt3pgrjo/77tishgnlqagujtsivuj72355l8gan9vijoq6hmvh4lhmt2lqgh0': directory not found
