### ISSUE TITLE
Rclone - Google Drive and own client_id

### ISSUE THREAD

**Issue by townsmcp** [ncw/rclone#1220] opened 2017-03-07 20:22 UTC
I have tried following the instructions to make my own client_id (including doing the OAUTH). I have gone back to edit the clone config and selected my Google Drive config, added my settings etc however when I now run the command to seat clone I get an error message:

 ./rclone -v --config rclone.conf sync /data/Media/TV GDrive:/Media/TV
2017/03/07 20:15:15 rclone: Version "v1.34" starting with parameters ["./rclone" "-v" "--config" "rclone.conf" "sync" "/data/Media/TV" "GDrive:/Media/TV"]
2017/03/07 20:15:16 Failed to create file system for "GDrive:/Media/TV": couldn't read info about Drive: Get https://www.googleapis.com/drive/v2/about?alt=json: oauth2: cannot fetch token: 401 Unauthorized
Response: {
  "error" : "unauthorized_client"
}

Any suggestions please? This worked before I generated my own codes.
This is on a NetGear Ready NAS

**Comment by calisro** [comment] 2017-03-07 23:13
Just re-edit your remote and refresh the re-authorize now that you have it under the under ID.

**Comment by calisro** [comment] 2017-03-07 23:16
└─> rclone config
Current remotes:

Name                 Type
====                 ====
xxxxxx

e) Edit existing remote
n) New remote
d) Delete remote
r) Rename remote
c) Copy remote
s) Set configuration password
q) Quit config
e/n/d/r/c/s/q> e
Choose a number from below, or type in an existing value
xxxxxxx
remote> 2
--------------------
xxxxxxx
--------------------
Edit remote
Value "client_id" = "xxxxxxx"
Edit? (y/n)>
y) Yes
n) No
y/n> n
Value "client_secret" = "xxxxxxxxx"
Edit? (y/n)>
y) Yes
n) No
y/n> n
Remote config
**Already have a token - refresh?
y) Yes
n) No
y/n> Y**

**Comment by townsmcp** [comment] 2017-03-07 23:23
Thanks - unfortunately this is what I did for the error message to appear above :(

**Comment by calisro** [comment] 2017-03-07 23:38
check to make sure you have the client id set in your rcline.conf.  I had a problem where it wouldn't save if you tried to refresh your token immediately after you added the clientid.  I had to not refresh it the first time through and then go back in and refresh it.

**Comment by wtangerine** [comment] 2017-04-09 17:12
I had the same issue. Created my own client_id in Google API Manager, authorized - it worked with rclone and shortly after that it didn't work anymore. Tried to refresh it and again the same story. Indeed the client_id and the secret were not saved to the rclone.conf file. After adding them manually to the file, working properly again (didn't even need to refresh).

Overall this looks like a bug?

**Comment by calisro** [comment] 2017-04-09 17:18
Yep. It's got to be a bug.  I had the same issue too. I had to quickly save my Comp file and then replace it shortly thereafter again

**Comment by ncw** [comment] 2017-04-10 11:07
@calisro A bug in rclone or drive?  If rclone what do you think the problem is?

**Comment by calisro** [comment] 2017-04-10 12:12
Rclone...  It seems to be either two rclone process clobbering the config file or the order to which a single rclone process writes to the config.  In my case I found that when adding a client id to an existing remote that when I walked through the config setup and added the client Id that if refreshed the auth in that same work flow it would succeed but not write the client id!  I found I had to go through the setup without refreshing the auth and exit then go back in and refresh and test the auth.

It is entirely possible I had other rclone process that wrote to the config in between though.

**Comment by calisro** [comment] 2017-04-10 12:15
Perhaps it would make sense to separate transient auth tokens from the config so that there would be less clobbering? That would also help with losing the config data when space was at zero in the filesystem.

**Comment by vb0** [comment] 2017-04-28 04:19
I think there's a bug in saving the config. I had an already existing "drive" type config. I went and edited it to use my own client_id and saved the config (I did not do multiple edits, I did not have multiple rclone config started, etc). It worked for a short while then I started getting unauthorized_client. Although I don't have logs I am pretty confident it worked with my own client_id for that session (I guess using a token generated during the config) because I was throttled on the default one.

Looking inside config file I see that I have empty client_id and client_secret.

rclone v1.36-22-gbc25190β, win64

**Comment by victor21813** [comment] 2017-06-13 06:03
Have the same problem with my own client_id and client_secret.
Is there any news or update for this problem?
Thanks for the hard work.

**Comment by rsimplicio** [comment] 2017-06-16 18:48
I, too, have my own API client_id and client_secret, and after about 27 minutes of uploading just fine with those credentials, I suddenly got a ton of 401 oauth2 errors as in the original issue. I've had this happen to me twice now, after reconfiguring. I am using a headless machine so I have to copy/paste the URL, etc. 

Since reading this I am going to look at the config file and make sure my info is there, which I suspect at this point it is not.

**Comment by ajthemacboy** [comment] 2017-07-04 00:41
Just tried as well, I am also getting "unauthorized_client". I followed the instructions exactly and tried re-creating the token a couple times, the token appears in my rclone config, not sure what to do.

**Comment by syaifulnizamyahya** [comment] 2017-07-06 13:05
I had this issue multiple times. Heres how I worked around it.
1. delete .rclone.conf file in C:\Users\<user>\
2. run rclone config
3. configure rclone as usual

Problem seems to be rclone unable to update .rclone.conf file.

**Comment by DragonFury24** [comment] 2017-08-07 05:37
Yep. Same here. Editing the config through cli doesn't save the client_id and client_secret in the config file for some reason. I was only running one rclone process, so I'm not sure why. It worked when I manually added it in.

**Comment by ncw** [comment] 2017-08-07 14:17
@DragonFury24 If you were running rclone on the same remote, then it will have overwritten your changes when it saved the token

The other issues in this ticket have been fixed now I think by
  * only changing the remote that rclone is running on
  * doing a two step save so it can't ever eave an empty config file

**Comment by CottonEaster** [comment] 2017-08-28 17:15
I had this problem, in that after use `rclone config` to change my account id and 'secret', rclone worked for a while with Gdrive and then generated 401 authorization errors. I repeated the `rclone config` procedure and now things are working - for longer than last time - but we'll see. And, ah, I find that my `rclone.config` file has blank entries for `client_id` and `client_secret`. Should I just paste the relevant data into there? But in what format? The `token` field has a syntax that involves braces . .

**Comment by DragonFury24** [comment] 2017-08-28 17:25
Nothing wrong with editing the config file. Paste in your key and secret. I had to do that to get my own API to work.

**Comment by CottonEaster** [comment] 2017-08-28 17:28
@DragonFury24

Ah, well, if it works (despite what the page I linked says) then it works. But, as I wondered in my previous post, what's the syntax? Plain text? Text in quotation marks? Something else?

**Comment by DragonFury24** [comment] 2017-08-28 17:29
No quotes. Plain text.

**Comment by CottonEaster** [comment] 2017-08-28 17:31
OK, thanks - I'll do it if I have a breakage. Actually, I suppose I should do it now, because quite possibly rclone/Gdrive is using the wrong credentials at the moment, namely the generic ones.

**Comment by CottonEaster** [comment] 2017-08-28 17:35
While I have your ear, and if I may: do you know if it a good idea to impose [TPS limits](https://rclone.org/docs/#tpslimit-float) on rclone to Gdrive?

Looking at the Google API dashboard thing, it seems that, with *no* limiting, the number of requests from my computer does not go much above the 10 per second (and that the daily limit for requests would allow much more than I'll ever use in a day). *Still*, might things go faster if I imposed limits. I thought you might know the answer. Thanks for your help so far.

**Comment by DragonFury24** [comment] 2017-08-28 19:10
It's not gonna do much. The default limit is 100/sec. And it's only 1 API
request per file. You can just leave it as is.

**Comment by CottonEaster** [comment] 2017-08-28 23:21
Thank you for that information. It is helpful.

**Comment by valentine** [comment] 2017-11-22 15:18
I'm facing a similar issue with Google Drive where I'd get:
```
Response: {
"error" : "unauthorized_client"
}
```

if I use my own `client_id` and `client_secret`, but do not add them back into the configuration file after the initial OAuth login.

**Comment by ncw** [comment] 2017-11-22 17:29
I've had lots of reports of the client_id disappearing but I haven't managed to replicate it :-(

Here is my attempt to replicate it.  If you can replicate it please provide similar instructions!

Thanks

```
$ rclone config
Current remotes:

Name                 Type
====                 ====
TestAmazonCloudDrive amazon cloud drive
[snip]
yandex               yandex

e) Edit existing remote
n) New remote
d) Delete remote
r) Rename remote
c) Copy remote
s) Set configuration password
q) Quit config
e/n/d/r/c/s/q> n
name> drive-test
Type of storage to configure.
Choose a number from below, or type in your own value
 1 / Amazon Drive
   \ "amazon cloud drive"
[snip]
21 / http Connection
   \ "http"
Storage> drive
Google Application Client Id - leave blank normally.
client_id> XXXX.apps.googleusercontent.com
Google Application Client Secret - leave blank normally.
client_secret> XXXX
Remote config
Make sure your Redirect URL is set to "urn:ietf:wg:oauth:2.0:oob" in your custom config.
Use auto config?
 * Say Y if not sure
 * Say N if you are working on a remote or headless machine or Y didn't work
y) Yes
n) No
y/n> y
If your browser doesn't open automatically go to the following link: http://127.0.0.1:53682/auth
Log in and authorize rclone for access
Waiting for code...
Got code
Configure this as a team drive?
y) Yes
n) No
y/n> n
--------------------
[drive-test]
client_id = XXXX.apps.googleusercontent.com
client_secret = XXXX
token = {"access_token":"XXXX","token_type":"Bearer","refresh_token":"XXXX","expiry":"2017-11-22T18:21:32.337372528Z"}
--------------------
y) Yes this is OK
e) Edit this remote
d) Delete this remote
y/e/d> y
Current remotes:

Name                 Type
====                 ====
TestAmazonCloudDrive amazon cloud drive
[snip]
yandex               yandex

e) Edit existing remote
n) New remote
d) Delete remote
r) Rename remote
c) Copy remote
s) Set configuration password
q) Quit config
e/n/d/r/c/s/q> q
```

Now test it and see if the client_id and client_secret disappear

```
$ rclone config show drive-test
--------------------
[drive-test]
type = drive
client_id = XXXX.apps.googleusercontent.com
client_secret = XXXX
token = {"access_token":"XXXX","token_type":"Bearer","refresh_token":"XXXX","expiry":"2017-11-22T18:21:32.337372528Z"}
--------------------
$ rclone lsd drive-test:
[snip]
          -1 2016-10-17 16:41:52        -1 test
$ rclone config show drive-test
--------------------
[drive-test]
type = drive
client_id = XXXX.apps.googleusercontent.com
client_secret = XXXX
token = {"access_token":"XXXX","token_type":"Bearer","refresh_token":"XXXX","expiry":"2017-11-22T18:21:32.337372528Z"}
--------------------
```

**Comment by valentine** [comment] 2017-11-22 18:02
I've managed to replicate it 100% of the time by first adding Google Drive as a remote without the `client_id` and `client_secret` (so using the default ones), and then trying to edit the remote after to use my own, and answering `y` to the token refresh question.

I've gotten an error with `rclone config -vv` twice now:
> y/n> 2017/11/23 02:00:33 DEBUG : Closed auth server with error: http: Server closed

And it always ends up with the `client_id` and `client_secret` disappearing after.

I hope this helps!

**Comment by ncw** [comment] 2017-11-23 13:50
@valentine **BINGO** thank you very much, I've managed to replicate that!

I'll work out what is happening now...

**Comment by ncw** [comment] 2017-11-23 14:04
I've fixed this now - thanks for working out what was happening @valentine 

https://beta.rclone.org/v1.38-183-g02ffd435/ (uploaded in 15-30 mins)

**Closed** 2017-11-23 14:04 UTC
