### ISSUE TITLE
oauth crash if expiry missing

### ISSUE THREAD

**Issue by justmwa** [ncw/rclone#1442] opened 2017-05-25 07:58 UTC
v1.36
if the token's expiry entry is missing:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x7eab29]

goroutine 1 [running]:
github.com/ncw/rclone/oauthutil.(*Renew).Invalidate(0x0)
        /home/ncw/go/src/github.com/ncw/rclone/oauthutil/renew.go:68 +0x29
github.com/ncw/rclone/amazonclouddrive.(*Fs).shouldRetry(0xc042204360, 0xc0421bee10, 0x1162580, 0xc0421b7950, 0xc0421b7950, 0x7ec441, 0xc042177868)
        /home/ncw/go/src/github.com/ncw/rclone/amazonclouddrive/amazonclouddrive.go:159 +0x1a4
github.com/ncw/rclone/amazonclouddrive.NewFs.func1(0xc0422042a0, 0x116f8a0, 0xc042204360)
        /home/ncw/go/src/github.com/ncw/rclone/amazonclouddrive/amazonclouddrive.go:196 +0xc4
github.com/ncw/rclone/pacer.(*Pacer).call(0xc0422042a0, 0xc042208320, 0xa, 0xc9f5e0, 0xc0421b7601)
        /home/ncw/go/src/github.com/ncw/rclone/pacer/pacer.go:334 +0x78
github.com/ncw/rclone/pacer.(*Pacer).Call(0xc0422042a0, 0xc042208320, 0xc042204360, 0xc0421dc820)
        /home/ncw/go/src/github.com/ncw/rclone/pacer/pacer.go:357 +0x6d
github.com/ncw/rclone/amazonclouddrive.NewFs(0xc042008220, 0x3, 0xc042008224, 0x5, 0x3, 0xc042008224, 0x5, 0x0)
        /home/ncw/go/src/github.com/ncw/rclone/amazonclouddrive/amazonclouddrive.go:197 +0x3c5
github.com/ncw/rclone/cmd.newFsFile(0xc042008220, 0x9, 0x0, 0x0, 0x0, 0x0)
        /home/ncw/go/src/github.com/ncw/rclone/cmd/cmd.go:110 +0xc5
github.com/ncw/rclone/cmd.newFsSrc(0xc042008220, 0x9, 0x0, 0xc042177cb8, 0x5ae6d3, 0xc0421beb40)
        /home/ncw/go/src/github.com/ncw/rclone/cmd/cmd.go:129 +0x54
github.com/ncw/rclone/cmd.NewFsSrc(0xc0421b7290, 0x1, 0x1, 0xc0421b7290, 0x1)
        /home/ncw/go/src/github.com/ncw/rclone/cmd/cmd.go:213 +0x50
github.com/ncw/rclone/cmd/ls.glob..func1(0x11b16a0, 0xc0421b7290, 0x1, 0x1)
        /home/ncw/go/src/github.com/ncw/rclone/cmd/ls/ls.go:20 +0x88
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).execute(0x11b16a0, 0xc0421b7250, 0x1, 0x1, 0x11b16a0, 0xc0421b7250)
        /home/ncw/go/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:648 +0x238
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x11af8e0, 0xc0421dc640, 0x0, 0x0)
        /home/ncw/go/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:735 +0x340
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).Execute(0x11af8e0, 0x0, 0x20)
        /home/ncw/go/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:693 +0x32
main.main()
        /home/ncw/go/src/github.com/ncw/rclone/rclone.go:15 +0x38

**Comment by tynor88** [comment] 2017-05-25 07:59
I experienced this as well without the expiry entry.

**Comment by ncw** [comment] 2017-05-25 09:22
What was the sequence of events leading up to that?

**Comment by justmwa** [comment] 2017-05-25 09:28
Your guess is as good as mine.

**Comment by tynor88** [comment] 2017-05-25 09:35
@ncw I pasted something like this when setting up ACD:

```json
{"access_token":"xxx","refresh_token":"xxx","token_type":"bearer","expires_in":3600}
```

With real tokens of course. Notice the **"expires_in"** rather than **"expiry"**

Not sure if this is a bug.

**Comment by ncw** [comment] 2017-05-25 12:14
@tynor88 thanks  - that is something to go on :-)

**Comment by Qwatuz** [comment] 2017-05-26 13:40
Just started getting this last night, transferring from ACD encrypted to Gdrive unencrypted. It was working all week (using a different auth token) until last night. It seems a problem with ACD>Gdrive as I can still upload Server to ACD(unencrypted).


`mishmash2@lw806:~$ rclone copy "backup:/TV Shows" "google-4:/TV Shows" --transfers=40 --checkers 20 --stats=5s --no-update-modtime -v
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x809462]

goroutine 1 [running]:
github.com/ncw/rclone/oauthutil.(*Renew).Invalidate(0x0)
        /home/ncw/go/src/github.com/ncw/rclone/oauthutil/renew.go:68 +0x22
github.com/ncw/rclone/amazonclouddrive.(*Fs).shouldRetry(0xc42009e4e0, 0xc420332090, 0x11a6440, 0xc4201e8170, 0xc4201e8170, 0x80acaa, 0xc4212d5668)
        /home/ncw/go/src/github.com/ncw/rclone/amazonclouddrive/amazonclouddrive.go:159 +0x19d
github.com/ncw/rclone/amazonclouddrive.NewFs.func1(0xc42009e420, 0x11b46a0, 0xc42009e4e0)
        /home/ncw/go/src/github.com/ncw/rclone/amazonclouddrive/amazonclouddrive.go:196 +0xbd
github.com/ncw/rclone/pacer.(*Pacer).call(0xc42009e420, 0xc4201068c0, 0xa, 0xcbfe60, 0xc420013001)
        /home/ncw/go/src/github.com/ncw/rclone/pacer/pacer.go:334 +0x71
github.com/ncw/rclone/pacer.(*Pacer).Call(0xc42009e420, 0xc4201068c0, 0xc42009e4e0, 0xc4200801e0)
        /home/ncw/go/src/github.com/ncw/rclone/pacer/pacer.go:357 +0x66
github.com/ncw/rclone/amazonclouddrive.NewFs(0xc4200a0f00, 0x6, 0xc4200a0f08, 0x1e, 0x6, 0xc4200a0f07, 0x1f, 0x0)
        /home/ncw/go/src/github.com/ncw/rclone/amazonclouddrive/amazonclouddrive.go:197 +0x3be
github.com/ncw/rclone/fs.NewFs(0xc4200a0f00, 0x26, 0x2, 0xc4200a0f00, 0x26, 0xc4212d5940)
        /home/ncw/go/src/github.com/ncw/rclone/fs/fs.go:613 +0xa9
github.com/ncw/rclone/crypt.NewFs(0x7ffec72667f4, 0x6, 0x7ffec72667fb, 0x9, 0x6, 0x7ffec72667fb, 0x9, 0x0)
        /home/ncw/go/src/github.com/ncw/rclone/crypt/crypt.go:86 +0x415
github.com/ncw/rclone/cmd.newFsFile(0x7ffec72667f4, 0x10, 0x4, 0xc420233540, 0x4, 0x4)
        /home/ncw/go/src/github.com/ncw/rclone/cmd/cmd.go:110 +0xbe
github.com/ncw/rclone/cmd.newFsSrc(0x7ffec72667f4, 0x10, 0xe, 0xd55c4a, 0x5, 0xc4201f1c01)
        /home/ncw/go/src/github.com/ncw/rclone/cmd/cmd.go:129 +0x4d
github.com/ncw/rclone/cmd.NewFsSrcDst(0xc42026c180, 0x2, 0x8, 0xc42026c180, 0x2, 0x8, 0xc420233480)
        /home/ncw/go/src/github.com/ncw/rclone/cmd/cmd.go:161 +0x4f
github.com/ncw/rclone/cmd/copy.glob..func1(0x11f5e60, 0xc42026c180, 0x2, 0x8)
        /home/ncw/go/src/github.com/ncw/rclone/cmd/copy/copy.go:58 +0x8d
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).execute(0x11f5e60, 0xc42026c100, 0x8, 0x8, 0x11f5e60, 0xc42026c100)
        /home/ncw/go/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:648 +0x231
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x11f51a0, 0xc42026a320, 0x0, 0x0)
        /home/ncw/go/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:735 +0x339
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).Execute(0x11f51a0, 0x0, 0x20)
        /home/ncw/go/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:693 +0x2b
main.main()
        /home/ncw/go/src/github.com/ncw/rclone/rclone.go:15 +0x31`

**Comment by JanHellwig** [comment] 2017-05-26 19:54
I get the same error with a token that looks similar to the one that @tynor88 used (**expires_in** instead of **expiry**).
It happens every time I try to interact with my ACD remote so I can't reproduce what @Qwatuz mentioned in regards to still being able to upload to ACD.

```panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x7eab29]

goroutine 1 [running]:
github.com/ncw/rclone/oauthutil.(*Renew).Invalidate(0x0)
/home/ncw/go/src/github.com/ncw/rclone/oauthutil/renew.go:68 +0x29
github.com/ncw/rclone/amazonclouddrive.(*Fs).shouldRetry(0xc04200c8a0, 0xc0421c47e0, 0x1162580, 0xc0420ce110, 0xc0420ce110, 0x7ec441, 0xc043271748)
/home/ncw/go/src/github.com/ncw/rclone/amazonclouddrive/amazonclouddrive.go:159 +0x1a4
github.com/ncw/rclone/amazonclouddrive.NewFs.func1(0xc04200c7e0, 0x116f8a0, 0xc04200c8a0)
/home/ncw/go/src/github.com/ncw/rclone/amazonclouddrive/amazonclouddrive.go:196 +0xc4
github.com/ncw/rclone/pacer.(*Pacer).call(0xc04200c7e0, 0xc0420acea0, 0xa, 0xc9f5e0, 0xc042008401)
/home/ncw/go/src/github.com/ncw/rclone/pacer/pacer.go:334 +0x78
github.com/ncw/rclone/pacer.(*Pacer).Call(0xc04200c7e0, 0xc0420acea0, 0xc04200c8a0, 0xc04200a460)
/home/ncw/go/src/github.com/ncw/rclone/pacer/pacer.go:357 +0x6d
github.com/ncw/rclone/amazonclouddrive.NewFs(0xc0420024c0, 0x12, 0xc0420024d3, 0x7, 0x12, 0xc0420024d3, 0x7, 0x0)
/home/ncw/go/src/github.com/ncw/rclone/amazonclouddrive/amazonclouddrive.go:197 +0x3c5
github.com/ncw/rclone/fs.NewFs(0xc0420024c0, 0x1a, 0x2, 0xc0420024c0, 0x1a, 0xc043271a20)
/home/ncw/go/src/github.com/ncw/rclone/fs/fs.go:613 +0xb0
github.com/ncw/rclone/crypt.NewFs(0xc0420026a0, 0x16, 0xc0420026a0, 0x0, 0x16, 0xc0420026a0, 0x0, 0x0)
/home/ncw/go/src/github.com/ncw/rclone/crypt/crypt.go:86 +0x41c
github.com/ncw/rclone/fs.NewFs(0xc0420026a0, 0x17, 0x116ff20, 0xc0421e57a0, 0x0, 0x0)
/home/ncw/go/src/github.com/ncw/rclone/fs/fs.go:613 +0xb0
github.com/ncw/rclone/cmd.newFsDst(0xc0420026a0, 0x17, 0x116ff20, 0xc0421e57a0)
/home/ncw/go/src/github.com/ncw/rclone/cmd/cmd.go:151 +0x54
github.com/ncw/rclone/cmd.NewFsSrcDst(0xc0421bc900, 0x2, 0x12, 0xc0421bc900, 0x2, 0x12, 0xc04220a540)
/home/ncw/go/src/github.com/ncw/rclone/cmd/cmd.go:162 +0x9a
github.com/ncw/rclone/cmd/copy.glob..func1(0x11b05a0, 0xc0421bc900, 0x2, 0x12)
/home/ncw/go/src/github.com/ncw/rclone/cmd/copy/copy.go:58 +0x94
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).execute(0x11b05a0, 0xc0421bc7e0, 0x12, 0x12, 0x11b05a0, 0xc0421bc7e0)
/home/ncw/go/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:648 +0x238
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x11af8e0, 0xc0421c6730, 0x0, 0x0)
/home/ncw/go/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:735 +0x340
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).Execute(0x11af8e0, 0x0, 0x20)
/home/ncw/go/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:693 +0x32
main.main()
/home/ncw/go/src/github.com/ncw/rclone/rclone.go:15 +0x38```

**Comment by ncw** [comment] 2017-06-27 21:21
I have fixed this in https://beta.rclone.org/v1.36-222-gf3c7e1a9/ (uploaded in 15-30 mins)

**Closed** 2017-06-27 21:21 UTC
Labels: bug
