### ISSUE TITLE
v1.27 Serious bug - rclone recursive algorithm missing some files/directories on Google drive source

### ISSUE THREAD

**Issue by TimJWatts** [ncw/rclone#355] opened 2016-02-15 15:51 UTC
I have a Drive on Google Apps for Education - and sync is not catching all the files.

Investigating further, I noticed:

rclone@phoenix:/vol/kdldata/GoogleDriveBackup$ /usr/local/bin/rclone --stats=0 ls 'twatts_kdl:/Shared Drive/' | grep 'Non Pay'
=========================================
   180534 KDL Group Share/KDL Admin/Finances/2015-2016/KDL Non Pay Finances 2015-2016.xlsx

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       29.5s
=========================================
which is correct:

BUT

rclone@phoenix:/vol/kdldata/GoogleDriveBackup$ /usr/local/bin/rclone --stats=0 ls 'twatts_kdl:/' | grep 'Non Pay'
=========================================
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       59.8s
=========================================

Starting a recursive listing from one level higher in the drive tree is causing certain files AND folders lower down to disappear from the source listing. The missing files/folders are consistent with what is not on the local target after a sync operation.

This suggests a problem with the recursion algorithm.

NB - files are owned by various people but I have access to all.

To see how many missing files there are:

/usr/local/bin/rclone --stats=0 ls 'twatts_kdl:/Shared Drive/' | wc -l
===========================
220
===========================

/usr/local/bin/rclone --stats=0 ls 'twatts_kdl:/' | grep 'Shared Drive' | wc -l
===========================
157
===========================

So it is missing 63 files!

Investigating further, I produced a list of the missing files.

Every single missing file is a Google Doc. Many of them were created or imported by me and reside in a tree where I created every node, so that seems to rule out it getting confused over permissions.

If I select my whole Google Drive in Chrome, do a "Download", unpack the zipfile and look in the "Shared Drive" directory and run "find -type f | wc -l" I get 220 files, the expected number, which is a further verification that I have permissions. My account is also the GA4Education admin account.

Happy to help debug this -

Cheers, Tim Watts

**Comment by ncw** [comment] 2016-02-15 17:08
This sounds like a duplicate of #336

If so then this beta should fix it

http://pub.rclone.org/v1.27-11-g1cd0d9a%CE%B2/

**Comment by TimJWatts** [comment] 2016-02-15 19:01
Cool - I did search for duplicates, but I do not feel too bad about missing that one.

I can try the beta for you tomorrow and will let you know how it fares.

Super tool by the way - very elegant - thanks to all who contributed to rclone :)

**Comment by TimJWatts** [comment] 2016-02-16 16:41
Hi @ncw I can confirm that this has fixed the issue. Thank you ever so much for this :)

The only discrepancy were 2 files that bore *identical* names to another file in their respective folders. I've told my users not to do that (because it's insane even if GDrive lets you do it).

It's a small point - I might investigate that later and reproduce a test case if I can. But this is very good news - rclone is working very well.

Can I assume this fix will be in the next stable? All the best, Tim

**Comment by ncw** [comment] 2016-02-16 17:44
Great glad that has fixed it. Duplicate file names are a known gotcha in drive - I agree it wasn't a sensible design choice! 

The fix is committed to master and will be in the next release.

**Comment by TimJWatts** [comment] 2016-02-16 18:31
Super - thank you @ncw - I'll be monitoring (I have a cron job sync-ing GDrive down to my linux server) and every now and then I do a sanity check,

One "interesting" thing is comparing GDrives ZIP download to rclone's sync'd copy - all file sizes the same, but odd variation in MD5 sums. I assumed the export algorithm would be the same in whichever way it was exported, but it seems not. Unless it's something to do with the metadata at the time of export (perhaps to do with slight variation of export filename???) Not an rclone issue of course, but curious...

Cheers,

Tim

**Comment by ncw** [comment] 2016-02-16 22:19
I've noticed that drive exports seem to vary slightly. I don't know why - maybe a timestamp or something like that. It is a little frustrating but I don't think there is anything I can do about it.

**Comment by ncw** [comment] 2016-02-19 13:56
I'm going to close this now - thanks for the report.

**Closed by ncw** 2016-02-19 13:56 UTC
