### ISSUE TITLE
Upload hangs/stalls when using --bwlimit

### ISSUE THREAD

**Issue by Ferni7** [ncw/rclone#170] opened 2015-10-09 10:00 UTC
I'm trying to use rclone to sync/copy up to my dreamhost s3 (ceph) account. It seems to get stuck/stall when I have --bwlimit in the command, without it, it seems fine (but hammers my upload so makes my connection unusable).

Attaching a debug log of the --bwlimit flag in use and you can see it stall, i killed it after about an hour...

Here is the command I'm using...

rclone --transfers 1 --checksum --bwlimit 10k --exclude-from exclude-file.txt --config .rclone.conf -v sync "Z:\Photos" "DreamObjects:xxxxxxx/Photos/"

**Comment by Ferni7** [comment] 2015-10-09 10:01
Can't seem to get the upload working in here, keeps giving me an error so just put my log on dropbox:

https://dl.dropboxusercontent.com/u/6961522/output_bwlimit.txt

**Comment by klauspost** [comment] 2015-10-09 10:05
Does it also happen if you use more than 1 transfers?

**Comment by Ferni7** [comment] 2015-10-09 10:07
Yes it does, that's why i reduced to 1 transfer to see if that would help...

Here is the log without bwlimit that worked, same command otherwise
rclone --transfers 1 --checksum --exclude-from exclude-file.txt --config .rclone.conf -v sync "Z:\Photos" "DreamObjects:xxxxxxx/Photos/"

https://dl.dropboxusercontent.com/u/6961522/output_nobwlimit.txt

**Comment by ncw** [comment] 2015-10-09 11:03
Can you try varying the `--bwlimit` upwards? Try doubling it until it works... I suspect that the pauses introduced by the limiting are causing the server to misbehave.

I don't currently have access to a s3/ceph server. Looks like I could sign up for a free trial to see for myself though!

**Comment by klauspost** [comment] 2015-10-09 11:21
At least I cannot reproduce with ACD on Windows, so it could be an S3/ceph-specific issue.

I looked for some possible races/deadlocks in "Account", but I couldn't immediately find one. The [only place the bandwidth limiter waits](https://github.com/ncw/rclone/blob/master/fs/accounting.go#L322) shouldn't have any side-effects, even though we hold the "file.mu" lock while it is running.

**Comment by ncw** [comment] 2015-10-09 14:04
I managed to replicate this both with S3 and with dreamhost (s3/ceph).  It doesn't seem to be a problem with any of the other providers.

It might be a problem in the https://github.com/aws/aws-sdk-go library but I haven't had a chance to look yet.

**Comment by Ferni7** [comment] 2015-10-09 21:27
Thanks guys... I tried --bwlimit 50k which is about half my upload (my upload is only ~1mbit) and same problem... 

Good to know it's not just me.. let me know if I can do anything to help but since you've reproduced it I suspect it's in your capable hands :)

**Comment by klauspost** [comment] 2015-10-11 10:21
@ncw - I have done some digging in the S3 library.

It seems like the library [buffers up to "Partsize"](https://github.com/aws/aws-sdk-go/blob/master/service/s3/s3manager/upload.go#L329) before sending any data. That is obviously bad for the bandwidth limiter, since it will only limit the read into the buffer, not the actual upload.

Also, there is fairly silent automatic retries on the [request handler](https://github.com/aws/aws-sdk-go/blob/master/aws/request/request.go#L200). I think it has at least 3 retries before failing. This can be adjusted in the [*s3.S3](https://github.com/aws/aws-sdk-go/blob/master/service/s3/service.go#L17) that contains a [*service.Service object](https://github.com/aws/aws-sdk-go/blob/master/aws/service/service.go#L22).

**Comment by ncw** [comment] 2015-11-15 16:02
I've eventually tracked the problem down to the token bucket library rclone uses.

I've sent in a fix for it tsenart/tb#7

This fixes the stalling problem, but doesn't address the problems @klauspost states above (which need a re-design of the limiter - putting it into the transport probably).

**Comment by ncw** [comment] 2015-11-16 23:20
This has now been fixed upstream and the fix will be in the next release.

There are still issues with the smoothness of the transfer, but I think that is a job for another ticket #222

@Ferni7 thanks for reporting the bug and sorry it has taken a while to track it down!

**Closed by ncw** 2015-11-16 23:20 UTC
Labels: bug
