### ISSUE TITLE
Make FUSE mount support seek

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#707] opened 2016-09-08 21:46 UTC
This should be possible for read only files and would likely make the fs a lot more compatible

**Comment by justusiv** [comment] 2016-09-09 17:33
If i understand this properly. The FUSE mount currently doesn't support reading from he middle of the file. So for example if i have a mount and it has a 5GB video file. I play this file with any media player, try to jump to the middle of the file this is not supported currently?

**Comment by calisro** [comment] 2016-09-09 17:52
That is correct but it goes a bit further I believe.  Currently vlc, for example, can't even play a file on the fuse mounts because of lack of seek without even advancing the file.  The way most of these players read from files is via offset and when it tries to do that, it doesn't get data.

**Comment by justusiv** [comment] 2016-09-09 17:58
Interesting... Hope to there is an easy fix for this. I know most cloud drives support seeking from files. acd_cli supports this.

**Comment by ncw** [comment] 2016-09-09 19:36
As far as I know all the underlying cloud storage systems support http range requests which could be used to build seeking on. It would be quite a lot of work to add it though (rclone supports lots of cloud storage systems!). 

I'd probably make an Object.OpenRange(start, end) which has would return an io.ReadCloser. This could maybe be built on an Object.OpenWithHttpHeaders which could come in useful for other things... 

Another alternative is to buffer the file to disk and use that to support seeking which would have some advantages but the major disadvantage that seeking to the end would require downloading the whole file.

**Comment by justusiv** [comment] 2016-09-09 19:42
I am not smart enough to look at the code. But how is it done in https://github.com/yadayada/acd_cli?

**Comment by calisro** [comment] 2016-09-09 19:50
I would think no matter what we'd need seeking on the http stream.  I do like the buffering but there are also lots of clients that wouldn't have the storage space to buffer a whole file.

**Comment by ncw** [comment] 2016-09-10 21:48
Have a go with this beta which implements http seeking: http://pub.rclone.org/v1.33-17-g7b80335-fuse-seek%CE%B2/

I can now play and skip around videos with rclone mount.

Note that seeking doesn't work over crypt yet (it will eventually just need a bit more brainpower than I have right now to work out how to do it!).  It does work over all the other remotes though.

**Comment by calisro** [comment] 2016-09-10 23:25
Seems to work good.  I've tested it with VLC and it worked great.  I want to test it with movies on xbmc next.

**Comment by calisro** [comment] 2016-09-11 01:56
It worked kind of with xbmc.  It was a bit slow though and the mount was throwing errors.I can get a better debug tomorrow. 

2016/09/10 21:44:28 kitchen/20160908/20160908-115316-1607.avi: ReadFileHandle.Read e
rror: set tcp 10.100.1.195:39305: use of closed network connection
2016/09/10 21:44:30 kitchen/20160908/20160908-115316-1607.avi: ReadFileHandle.Read e
rror: set tcp 10.100.1.195:41263: use of closed network connection
2016/09/10 21:44:41 kitchen/20160908/20160908-115316-1607.avi: ReadFileHandle.Read e
rror: set tcp 10.100.1.195:42346: use of closed network connection
2016/09/10 21:44:54 kitchen/20160908/20160908-115316-1607.avi: ReadFileHandle.Read e
rror: set tcp 10.100.1.195:42386: use of closed network connection
2016/09/10 21:45:13 kitchen/20160908/20160908-115459-1608.avi: ReadFileHandle.Read e
rror: set tcp 10.100.1.195:33035: use of closed network connection

**Comment by calisro** [comment] 2016-09-11 02:47
This is with -v.  I can turn on further debugging if that helps.  These are pretty small bitrate files but it is still really slow to play after a seek.  Might just be the latency with acd.  Not sure. 

[r.log.gz](https://github.com/ncw/rclone/files/465734/r.log.gz)

**Comment by ncw** [comment] 2016-09-11 08:55
Thanks for testing.  Note that seeks will be slow as they have to re-open the connection to the server.  Will examine your log a bit later!

**Comment by calisro** [comment] 2016-09-11 12:19
Yes. I did some wall clock timing and the time to initially start the stream is equal or similar to the time to seek to the middle which is what I would expect.  

I did, however, do some benchmarking using acdcli under the same setup.  The rclone mount tool ~15-17 seconds to open the stream and them about the same time to seek.  The acdcli took under a second to open and under a second to seek.  It is interesting because rclone gives my full bandwidth on copies (acdcli gives maybe 2MB/s)...

**Comment by calisro** [comment] 2016-09-11 12:48
One more test.  I have a http server pointed to the rclone mount and when I download a file with curl, I get 40k/s speed.  The http server will download in chunks (seek) so it simulates a stream but will download at full speed where a movie stream will only download what it needs to play the stream based on bitrate.  This explains why kodi was stuttering when streaming with a low bitrate avi

**Comment by justusiv** [comment] 2016-09-11 20:01
Just throwing in my own observations. First i am using the http://pub.rclone.org/v1.33-17-g7b80335-fuse-seek%CE%B2/ I don't have great internet 30/5. I am not able to seek but i am actually not even able play videos from the beginning of the fuse mount. They start but just turns blocky gray and freezes. When i watch traffic while trying i am getting like 10mbit however if i copy a file down from the mount i max my bandwidth at 30mbit.
So yeah big difference between downloading the file and actually playing it live. Am happy to test anything.

**Comment by ncw** [comment] 2016-09-11 20:21
Lots to think about thanks for your useful tests. Looks like I probably need to increase some buffering in fuse. Will examine the source if the competition some more!

**Comment by justusiv** [comment] 2016-09-11 20:30
I will test this but does anyone have some insight? would setting up a share and reading from the share make it more of a linear read for rclone?

**Comment by justusiv** [comment] 2016-09-11 20:53
Tested. From my windows box playing a video from the start it would stutter and only transfer 6mbit. copy the file over would max my 30mbit connection.
So much for tricking it :P

**Comment by justusiv** [comment] 2016-09-14 12:54
I did some testing with speeds on seeking/playing with rclone vs acd_cli with encfs. Are you interested in seeing any of this info? If you are i can wipe up something semi structured.

**Comment by ncw** [comment] 2016-09-14 20:30
@justusiv That would be the interesting if it isn't too much bother, thanks.

**Comment by jkaberg** [comment] 2016-09-16 13:23
I'd love to see this working with the crypt storage :-) Keep up the good work!

**Comment by justusiv** [comment] 2016-09-21 21:13
I meant to mention this earlier... but i don't think you will like my data.... My connection is to slow to even matter. I can stream crap reliably even maxing out my connection.

Any progress on seek using crypt?

**Comment by captainswain** [comment] 2016-09-22 01:42
@justusiv I've got quite a bit of encrypted media uploaded. I'll try and mount/play the content when I get home to see if I can reproduce the slow speeds that you are experiencing. What are you using to playback the media?

**Comment by justusiv** [comment] 2016-09-22 01:58
@captainswain I just meant my internet is actually pretty slow right now... i cant stream 1080p content currently.. Just got a new provider and speeds are pretty whack. 
Also the encrypted stuff does not support seeking yet.... so unless you watch from the beginning it wont work.

**Closed** 2016-10-05 20:09 UTC
Labels: enhancement, FUSE

**Comment by ncw** [comment] 2016-10-05 20:18
I've committed the seek stuff to master now - see http://beta.rclone.org/v1.33-49-gde for a beta with it in.

**Comment by jkaberg** [comment] 2016-10-05 20:19
@ncw Very nice! Did this include crypt support? (I can't tell from the commit)

**Comment by ncw** [comment] 2016-10-05 21:14
Yes it does include crypt support as you discovered. And thanks for updating the URL!

**Comment by Trentflix** [comment] 2016-10-05 23:02
Love the new Crypt feature and Mount + Seeking! Testing on my Linux VM I get about 1MB/s transfer when streaming video from a Crypt mount (both Encrypted Google Drive and Encrypted ACD) although when I use the Copy function through the command line I get 60MB/s with Encrypted Google Drive and 40MB/s with Encrypted ACD.

**Comment by spencercharest** [comment] 2016-10-05 23:19
@Trentflix I'm having the same issue. What OS are you using?

**Comment by Trentflix** [comment] 2016-10-05 23:35
Ubuntu x64 14.04

**Comment by calisro** [comment] 2016-10-06 13:45
This is with and without crypt.  Seek works now which is a step in the right direction.  Perhaps another issue should be opened to try to improve performance.  It isn't really usable for streaming content at this point.  I average 20-40k where-as I can download a file at 100MB/s without seek.


`
└─> curl --insecure -u xxxxx:xxxxx https://xxxxxxxx/xxx/xxxxxxxxx.mkv > /dev/null

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 4481M    0 1727k    0     0  32532      0 40:07:39  0:00:54 40:06:45 27176
`

**Comment by captainswain** [comment] 2016-10-14 05:03
It seems that the newest seek build's performance is very lackluster, I tried to pair it with plex and couldn't get any content to start streaming. Once switching back to rclone-v1.33-13-g7be4c3a-fuse-flagsβ everything seems to function fun with significantly more consistent network performance

**Comment by ncw** [comment] 2016-10-25 18:11
Try: http://beta.rclone.org/v1.33-81-g9d2dd2c/ which has a number of significant fixed for seeking in, especially with crypt.

**Comment by calisro** [comment] 2016-10-25 18:48
I'm still unable to even stream a single 720p movie with seek enabled.

**Comment by jkaberg** [comment] 2016-10-25 19:40
For the ```ReadFileHandle.Read error: failed to authenticate decrypted block - bad password?``` you can see this issue: https://github.com/ncw/rclone/issues/802

**Comment by calisro** [comment] 2016-10-25 20:20
Thanks.  If I try with smaller files (per that issue), I also get an error but different.

2016/10/25 16:20:10 somefile.mp4: ReadFileHandle.Read error: http: read on closed response body
2016/10/25 16:20:11 somefile.mp4: ReadFileHandle.Read error: http: read on closed response body

**Comment by calisro** [comment] 2016-10-25 20:31
The performance is actually pretty impressive using VLC as a simple test case to stream files (smaller 2 Gig ones).  Im currently streaming 12 streams.  They are HD content.  and seeking is still pretty quick considering.

**Comment by KyleSanderson** [comment] 2021-04-02 22:27
@ncw https://github.com/rclone/rclone/issues/707#issuecomment-251787169 has link rotted - do you have the latest link?

**Comment by ncw** [comment] 2021-04-03 12:41
This code is all in the master branch so you should be able to use [the latest release](https://rclone.org/downloads/)

**Comment by KyleSanderson** [comment] 2021-04-03 18:56
In actually looking for the code, I have a similar bug in my FS. Was hoping to take a bit from here 😸

**Comment by ncw** [comment] 2021-04-05 19:27
@KyleSanderson 
> In actually looking for the code, I have a similar bug in my FS. Was hoping to take a bit from here

If you want more help open up a thread in [the rclone forum](https://forum.rclone.org/) in the dev section and we'll try to help more!
