### ISSUE TITLE
WriteFileHandle.Flush error for Amazon Cloud Drive write attempts 

### ISSUE THREAD

**Issue by thechile** [ncw/rclone#874] opened 2016-11-13 08:51 UTC
Hi,

I was trying to write to a acd mount point and kept getting the following type of errors `WriteFileHandle.Flush error: Post https://content-eu.drive.amazonaws.com/cdproxy/nodes?suppress=deduplication: http: ContentLength=486 with Body length 57546611`. I found https://github.com/ncw/rclone/issues/813 which explained the problem as 

> This is because Amazon need to know the size of the file in advance for the upload, but we don't know it until the end.

Can you explain this problem in some more detail please because i also read https://github.com/ncw/rclone/issues/669 which seems to suggest that the file size isn't required in advance. 

Looking through the acd API documentation it does mention [here](https://developer.amazon.com/public/apis/experience/cloud-drive/content/restful-api-getting-started) that the size **is** required.

> Content-Length	Specifies the length of the message in the body; without the headers. This is a required parameter when the body of the request in not empty.

Fingers crossed that write support is possible on `mount` to allow use of common tools/scripts to shift data into acd like `cp` or `rsync` etc..

Out of curiosity... in the fuse code when you receive the request would it not be possible to use the target file name that your about to create/write via rclone and scan the associated local source path for the matching file and stat the file size to fulfill acd requirement to specify size on upload ? Or is that a bit willy wonka thinking ?

Great project, thanks for all your hard work.

**Comment by thechile** [comment] 2016-11-13 09:19
Just some more info which i noticed and seems odd

If i try to cp the below local file to rclone mount point

```
$ stat .viminfo 

File: ‘.viminfo’
Size: 5895      	Blocks: 16         IO Block: 4096   regular file
Device: fc01h/64513d	Inode: 441488      Links: 1
```
I get the below error which seems to suggest it detects the file size correctly as `5895` and then fails because of a miss-match between the actual size and the one send in http header `Error: http: ContentLength=430 with Body length 6325`

```
2016/11/13 17:12:27 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2016/11/13 17:12:27 .viminfo: WriteFileHandle.Write len=5895
2016/11/13 17:12:28 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2016/11/13 17:12:28 HTTP RESPONSE (req 0xc4200d05a0)
2016/11/13 17:12:28 HTTP/1.1 200 OK
Cache-Control: no-store
Connection: keep-alive
Content-Type: application/json
Date: Sun, 13 Nov 2016 09:12:28 GMT
Pragma: no-cache
Server: Server
Vary: User-Agent
X-Amzn-Requestid: 4cf3a4e1-a981-11e6-8878-XXXXXXXXXXXX

2016/11/13 17:12:28 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2016/11/13 17:12:28 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2016/11/13 17:12:29 HTTP REQUEST (req 0xc4200d0b40)
2016/11/13 17:12:29 POST /cdproxy/nodes?suppress=deduplication HTTP/1.1
Host: content-eu.drive.amazonaws.com
User-Agent: rclone/v1.34-DEV
Content-Length: 430
Authorization: XXXX
Content-Type: multipart/form-data; boundary=231ee268c16bb03cde80501ecc73f18e585163d95af8e8a48c3ae0a38b4b
Accept-Encoding: gzip

2016/11/13 17:12:29 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2016/11/13 17:12:30 .viminfo: WriteFileHandle.Write OK (5895 bytes written)
2016/11/13 17:12:30 .viminfo: WriteFileHandle.Flush
2016/11/13 17:12:30 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2016/11/13 17:12:30 HTTP RESPONSE (req 0xc4200d0b40)
2016/11/13 17:12:30 Error: http: ContentLength=430 with Body length 6325
2016/11/13 17:12:30 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2016/11/13 17:12:30 .viminfo: Error detected after finished upload - waiting to see if object was uploaded correctly: Post https://content-eu.drive.amazonaws.com/cdproxy/nodes?suppress=deduplication: http: ContentLength=430 with Body length 6325 ("HTTP status UNKNOWN")
2016/11/13 17:12:30 .viminfo: Giving up waiting for object - returning original error: Post https://content-eu.drive.amazonaws.com/cdproxy/nodes?suppress=deduplication: http: ContentLength=430 with Body length 6325 ("HTTP status UNKNOWN")
2016/11/13 17:12:30 .viminfo: WriteFileHandle.Flush error: Post https://content-eu.drive.amazonaws.com/cdproxy/nodes?suppress=deduplication: http: ContentLength=430 with Body length 6325
2016/11/13 17:12:30 .viminfo: WriteFileHandle.Release nothing to do
```

**Comment by breunigs** [comment] 2016-11-13 11:17
> Can you explain this problem in some more detail please because i also read #669 which seems to suggest that the file size isn't required in advance.

This is how the fuse API works. It doesn't tell you "here's a file with 6 kB, please store it", but rather `open file x`, `store 4kB at position 0 in handle for file x`, `store 2kB at position 4k in handle for file x`, `close handle`. It also works the same way when reading files; see http://engineering.facile.it/blog/eng/write-filesystem-fuse/ for a nice tutorial. 

Regardless if it's actually possible to somehow figure out the "source file" for regular copy operations, there are a lot of cases where the file size is not known in advance. Think `cat somefile > acd/someotherfile` or when there is no source file to begin with, say when you directly save to the file system.

> Looking through the acd API documentation it does mention here that the size is required.

Interesting, I didn't read that before. Anyway, I presume they just accept [chunked transfer encoding](https://en.wikipedia.org/wiki/Chunked_transfer_encoding ) since they most likely speak HTTP 1.1. I didn't actually check that, though, but I would be surprised if it works differently. Case in point, this is how acd_cli handles uploads (cmp. http://docs.python-requests.org/en/master/user/advanced/#streaming-uploads and following section). I didn't read enough code in `go-acd` which rclone uses, though, and am now wondering if it keeps everything in memory instead of streaming it. Will have to check that!

> Fingers crossed that write support is possible on mount to allow use of common tools/scripts to shift data into acd like cp or rsync etc..

cp yes, but rsync is a totally different beast: it relies on modification time (#371) among other attributes. There is a pull request to acd_cli that stores these in the extended attributes, but that is non-standard. I.e. at least in the case of AmazonDrive, any rsync support would be non-standard. 


As for your 2nd comment: I am a bit surprised it actually figured out the file size in one go. I guess this must be the read buffer being used. I would expect it to print `.viminfo: WriteFileHandle.Write`  multiple times when the file size exceeds the buffer though. The mismatch you observed is probably caused by these lines:
https://github.com/ncw/rclone/blob/master/amazonclouddrive/amazonclouddrive.go#L593-L597
`src.Size()` is `0` here, because it doesn't actually get set and this default stays. You can see what happens now: it tries to write the file with a length of 0, even though it isn't. The `Content-Length: 430` is coming from all the metadata (which filename, which parent, etc) and the incorrectly assumed length. The actual file is then still added to the request, which leads to the mismatch.

Makes sense?

**Comment by ncw** [comment] 2016-11-13 17:41
Nice explanation @breunigs 

I note that the [bit of code you linked to](https://github.com/ncw/rclone/blob/master/amazonclouddrive/amazonclouddrive.go#L593-L597) is a work around for uploading 0 length files.  If the Put() method could be changed so it could upload 0 length files then uploading would work via FUSE.

The `Put` method in go-acd was written by me and it seems very complicated - perhaps there is a better way...

**Comment by breunigs** [comment] 2016-11-13 20:13
You will always have an if/else to some extent, because ACD does *not* support creating 0 byte files using chunked transfer encoding¹. And of course, for streaming upload the file size is not known in advance. So regardless of how you put it, there will always be two cases.

But that's not a big issue, because you can just try to read a byte and then act appropriately (or maybe use `bufio`'s `Peek`). Long story short, @ncw implicitly answered [my question from the other issue](https://github.com/ncw/rclone/issues/669#issuecomment-260124145) and I will make the hack I posted there into a decent patch. Incoming write support \o/

¹ I checked this ~6 months ago for acd_cli for a related issue, I guess this didn't change.

**Comment by thechile** [comment] 2016-11-14 04:14
OK many thanks for the helpful info.. helped me understand. 

@breunigs Looking forward to testing the write support when it drops :) 

For rsync i'd try something like this, just for file transfer functionality. Using `--size-only` should work around the time stamp issue and be accurate enough for my requirements. 

`rsync -v --inplace --size-only --whole-file --info=progress2 /path/to/src_files rclone_fuse_mnt/`

**Comment by ncw** [comment] 2016-11-19 10:57
This should be fixed in http://beta.rclone.org/v1.34-22-g0b562bc/ (will be uploaded in 15-30 mins)

Please re-open if it doesn't work for you.

**Closed** 2016-11-19 10:58 UTC
Labels: enhancement, FUSE, Remote: Amazon Cloud Drive
