### ISSUE TITLE
Bug in the "Obfuscation" method of encrypting filenames ?

### ISSUE THREAD

**Issue by drsmithy** [ncw/rclone#1315] opened 2017-04-07 05:50 UTC
I think I may have found a bug in the "Obfuscation" method of encrypting filenames.  I am using rclone v1.36-20-g2fd86c9β and Amazon Cloud Drive.

When I try to name a folder on a crypted remote to "Avatar The Last Airbender", I get a garbled result.

Eg:

```
MyUserName@MyServer:~/files/acd-MyUserName@gmail.com/local/TV$ ~/bin/rclone lsd acd-MyUserName-gmail-com-crypt:TV/ | grep asdf
          -1 2017-04-07 04:51:49        -1 asdf
MyUserName@MyServer:~/files/acd-MyUserName@gmail.com/local/TV$ ~/bin/rclone moveto  "acd-MyUserName-gmail-com-crypt:TV/asdf" "acd-MyUserName-gmail-com-crypt:TV/Avatar The Last Airbender"
MyUserName@MyServer:~/files/acd-MyUserName@gmail.com/local/TV$ ~/bin/rclone lsd acd-MyUserName-gmail-com-crypt:TV/ | grep Ava
MyUserName@MyServer:~/files/acd-MyUserName@gmail.com/local/TV$ ~/bin/rclone lsd acd-MyUserName-gmail-com-crypt:TV/ | grep Bwb
          -1 2017-04-07 04:53:21        -1 Bwbubs Uif Mbtu Bjscfoefs
MyUserName@MyServer:~/files/acd-MyUserName@gmail.com/local/TV$
```

(Note: I know which garbled filename to look for in the example above after trying to figure out what was happening - I don't know if it is predictable, but it is consistent.)

Interestingly, it can still be referred to by the name it "should" be:

```
MyUserName@MyServer:~/files/acd-MyUserName@gmail.com/local/TV$ ~/bin/rclone size "acd-MyUserName-gmail-com-crypt:TV/Avatar The Last Airbender"
Total objects: 59
Total size: 10.236 GBytes (10991065480 Bytes)
MyUserName@MyServer:~/files/acd-MyUserName@gmail.com/local/TV$

```

And changing just a single letter makes it act "normally" ('T' to 't' in 'The'):

```
MyUserName@MyServer:~/bin/rclone moveto "acd-MyUserName-gmail-com-crypt:TV/Avatar The Last Airbender" "acd-MyUserName-gmail-com-crypt:TV/Avatar the Last Airbender"
MyUserName@MyServer:~/bin/rclone lsd acd-MyUserName-gmail-com-crypt:TV | grep Ava
          -1 2017-04-07 04:58:24        -1 Avatar the Last Airbender
MyUserName@MyServer:~/files/acd-MyUserName@gmail.com/local/TV$

```

Behind the scenes it looks like this (when "broken"):

```
MyUserName@MyServer:~/bin/rclone lsd --crypt-show-mapping acd-MyUserName-gmail-com-crypt:TV
[...]
2017/04/07 07:01:33 NOTICE: Bwbubs Uif Mbtu Bjscfoefs: Encrypts to "0.Bwbubs Uif Mbtu Bjscfoefs"

MyUserName@MyServer:~$ ~/bin/rclone lsd --crypt-show-mapping acd-MyUserName-gmail-com:crypt/170.oq | grep Bwb
          -1 2017-04-07 05:01:28        -1 0.Bwbubs Uif Mbtu Bjscfoefs
MyUserName@MyServer:~$

```

I also seem to be seeing the same bug with the folder name "Fullmetal Alchemist Brotherhood":

```
MyUserName@MyServer:~/files/acd-MyUserName@gmail.com/local/TV$ ~/bin/rclone lsd  acd-MyUserName-gmail-com-crypt:TV  
[...]
          -1 2017-04-07 05:13:22        -1 F
MyUserName@MyServer:~/files/acd-MyUserName@gmail.com/local/TV$ ~/bin/rclone moveto  "acd-MyUserName-gmail-com-crypt:TV/F" "acd-MyUserName-gmail-com-crypt:TV/Fullmetal Alchemist Brotherhood"
MyUserName@MyServer:~/files/acd-MyUserName@gmail.com/local/TV$ ~/bin/rclone lsd  acd-MyUserName-gmail-com-crypt:TV  | grep Full
          -1 2017-04-06 07:06:01        -1 Fullmetal Alchemist
MyUserName@MyServer:~/files/acd-MyUserName@gmail.com/local/TV$ ~/bin/rclone lsd  acd-MyUserName-gmail-com-crypt:TV
[...]

          -1 2017-04-07 05:37:17        -1 Gvmmnfubm Bmdifnjtu Cspuifsippe
MyUserName@MyServer:~/files/acd-MyUserName@gmail.com/local/TV$ ~/bin/rclone lsd --crypt-show-mapping acd-MyUserName-gmail-com-crypt:TV
2017/04/07 07:38:52 NOTICE: Gvmmnfubm Bmdifnjtu Cspuifsippe: Encrypts to "0.Gvmmnfubm Bmdifnjtu Cspuifsippe"
          -1 2017-04-07 05:37:17        -1 Gvmmnfubm Bmdifnjtu Cspuifsippe
MyUserName@MyServer:~/files/acd-MyUserName@gmail.com/local/TV$ ~/bin/rclone lsd --crypt-show-mapping acd-MyUserName-gmail-com:crypt/170.oq | grep Gvm
          -1 2017-04-07 05:37:17        -1 0.Gvmmnfubm Bmdifnjtu Cspuifsippe
MyUserName@MyServer:~/files/acd-MyUserName@gmail.com/local/TV$ ~/bin/rclone moveto  "acd-MyUserName-gmail-com-crypt:TV/Fullmetal Alchemist Brotherhood" "acd-MyUserName-gmail-com-crypt:TV/Fullmetal Alchemist brotherhood"
MyUserName@MyServer:~/files/acd-MyUserName@gmail.com/local/TV$ ~/bin/rclone lsd  acd-MyUserName-gmail-com-crypt:TV  | grep Full
          -1 2017-04-07 05:40:21        -1 Fullmetal Alchemist brotherhood
MyUserName@MyServer:~/files/acd-MyUserName@gmail.com/local/TV$

```

**Comment by drsmithy** [comment] 2017-04-07 05:54
And with added -vv

```
MyUserName@MyServer:~/files/acd-MyUserName@gmail.com/local/TV$ ~/bin/rclone moveto  -vv "acd-MyUserName-gmail-com-crypt:TV/Avatar" "acd-MyUserName-gmail-com-crypt:TV/Avatar The Last Airbender"
2017/04/07 07:52:07 DEBUG : rclone: Version "v1.36-20-g2fd86c9β" starting with parameters ["/home7/MyUserName/bin/rclone" "moveto" "-vv" "acd-MyUserName-gmail-com-crypt:TV/Avatar" "acd-MyUserName-gmail-com-crypt:TV/Avatar The Last Airbender"]
2017/04/07 07:52:12 INFO  : Encrypted amazon drive root 'crypt/170.oq/0.Bwbubs Uif Mbtu Bjscfoefs': Modify window not supported
2017/04/07 07:52:12 DEBUG : Encrypted amazon drive root 'crypt/170.oq/0.Bwbubs Uif Mbtu Bjscfoefs': Using server side directory move
2017/04/07 07:52:13 INFO  : Encrypted amazon drive root 'crypt/170.oq/0.Bwbubs Uif Mbtu Bjscfoefs': Server side directory move succeeded
2017/04/07 07:52:13 INFO  :
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        5.1s
2017/04/07 07:52:13 DEBUG : Go routines at exit 11
2017/04/07 07:52:13 DEBUG : rclone: Version "v1.36-20-g2fd86c9β" finishing with parameters ["/home7/MyUserName/bin/rclone" "moveto" "-vv" "acd-MyUserName-gmail-com-crypt:TV/Avatar" "acd-MyUserName-gmail-com-crypt:TV/Avatar The Last Airbender"]
MyUserName@MyServer:~/files/acd-MyUserName@gmail.com/local/TV$

```

**Comment by Rootax** [comment] 2017-04-09 13:23
Hello.

I think I have a similar bug. rclone v1.36-20-g2fd86c9β and Amazon Cloud Drive too.

So, I was synching some music stuff, and notice one file showed up the same way on the crypted, and encrypted "side". With the encrypted name. Here some screenshots : 
![rclonebug1](https://cloud.githubusercontent.com/assets/22431162/24837609/39918102-1d38-11e7-8a76-4293db45e53d.jpg)

![rclonebug2](https://cloud.githubusercontent.com/assets/22431162/24837610/3fe1aeba-1d38-11e7-9dea-e667f227bf32.jpg)


The jobs log are : 
`2017/04/09 15:14:07 INFO  : Encrypted amazon drive root '114.fGBpxntr nHGEr/16.BE6/104.Kls Krs/24.XQJLPMEBOB/233.HAtvzwolyl - ZlClu'z ayhClsz (YlAhps) (6447) [MUa]': Modify window not supported
2017/04/09 15:14:07 INFO  : Encrypted amazon drive root '114.fGBpxntr nHGEr/16.BE6/104.Kls Krs/24.XQJLPMEBOB/233.HAtvzwolyl - ZlClu'z ayhClsz (YlAhps) (6447) [MUa]': Waiting for checks to finish
2017/04/09 15:14:07 INFO  : Encrypted amazon drive root '114.fGBpxntr nHGEr/16.BE6/104.Kls Krs/24.XQJLPMEBOB/233.HAtvzwolyl - ZlClu'z ayhClsz (YlAhps) (6447) [MUa]': Waiting for transfers to finish
2017/04/09 15:14:08 INFO  :
Transferred:   2.111 MBytes (923.063 kBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        2.3s
Transferring:
*                   13-atmosphere-shoes-fnt.wma: 100% done, 0 Bytes/s, ETA: 0s

2017/04/09 15:14:09 INFO  : 13-atmosphere-shoes-fnt.wma: Copied (new)
2017/04/09 15:14:09 INFO  :
Transferred:   2.111 MBytes (707.278 kBytes/s)
Errors:                 0
Checks:                 0
Transferred:            1
Elapsed time:          3s`


After it's uploaded, I can't delete or do anything with the file with rclone. I have to delete it with the ACD website... I just uploaded about 5to of data. That the one I notice "by accident", but of 72k files, I guess there is other bug like this...

**Comment by ncw** [comment] 2017-04-10 11:10
@sweharris fancy having a look at this?

**Comment by sweharris** [comment] 2017-04-10 13:04
Oh!  That's... annoying.

I can replicate:
```
$ rclone copy asdf foo:TV/asdf
$ rclone ls foo:TV
        0 asdf/x1
$ rclone moveto foo:TV/asdf foo:"TV/Avatar The Last Airbender"
$ rclone ls foo:TV                                            
        0 JEjCjA cqn UjBC JrAknwmnA/x1
$ rclone ls Amazon:foo 
       32 170.XZ/0.JEjCjA cqn UjBC JrAknwmnA/169.A5
```

We can see the "0.JEj..." part.  That 0 means that the calculated rotate distance was zero, and the _deobfuscate_ routine takes the zero to mean "no rotation" (which should normally only happen when the string isn't a valid runeString).  

Changing one character - eg "Avatar the Last Airbender" caused a different rotate distance to be calculated which didn't suffer the problem.

I'll take a look today, but it may not be until after work (depending on how busy I get).  I have some guesses...

**Comment by sweharris** [comment] 2017-04-10 13:33
OK, yes, the problem is what I thought; the filename calculated distance is 0(mod 256).  Approximately 1 in 256 files would be expected to hit this problem.  (Even though the sum is zero, the actual rotation isn't zero because we add the nameKey afterwards to get the real rotation distance).

Now there's some ways I can fix this:
1) Change the calculation  (eg "(dir mod 255 ) + 1").
2) Change what we store in the filename (eg "dir+1" as the prefix)
3) kludge things; if the sum is calculated as 0 then make it 1
4) Change the "invalid string" flag (eg use a "!" instead of a "0" as the first character).

Options 1 and 2 will incompatible with existing obfuscated filenames because the filenames generated won't match.  All existing obfuscated files will need to be uploaded.  Sure, it's a beta version, but it may hurt a number of people.  Option 3 will keep compatibility with approx 99.6% of all files; the existing "0" files will need to be re-uploaded.  Option 4 will break any current "invalid unicode" files but everything else should work correctly.  I expect (but can't prove) this to be a small number.

I think this is a decision for @ncw as to how he would like to see it done... each option will have some impact!

**Comment by Rootax** [comment] 2017-04-10 13:49
Thx for the explanations . Can you confirm that drsmithy problem and mine is the same ?

Thx again.

**Comment by sweharris** [comment] 2017-04-10 13:55
@Rootax - if you look at the files on the ACD site (or do an `rclone ls` of the underlying ACD filesystem) do the bad names all begin with `0.` ?  If so, then it's the same problem.

I _think_ it is, based on my test:

```
$ rclone copy 13-atmosphere-shoes-fnt.wma foo:
$ rclone ls Amazon:foo
       32 0.79-jCvxByqnAn-BqxnB-owC.Fvj
```
We can see the name begins with "0".

**Comment by Rootax** [comment] 2017-04-10 14:01
Ah yes, it always start with 0 indeed.

For the record I'm fine with every solution, even 1 and 2. Like you said, it's a beta, and we know the risks. If re-uploading everything is the way to go for a "cleaner" solution, then I'm all for it.

**Comment by sweharris** [comment] 2017-04-10 14:07
FWIW, here's a quick "option 4" patch:

```
--- a/crypt/cipher.go
+++ b/crypt/cipher.go
@@ -298,9 +298,9 @@ func (c *cipher) obfuscateSegment(plaintext string) string {
        }
 
        // If the string isn't valid UTF8 then don't rotate; just
-       // prepend a 0.
+       // prepend a !.
        if !utf8.ValidString(plaintext) {
-               return "0." + plaintext
+               return "!." + plaintext
        }
 
        // Calculate a simple rotation based on the filename and
@@ -388,7 +388,7 @@ func (c *cipher) deobfuscateSegment(ciphertext string) (string, error) {
                return "", ErrorNotAnEncryptedFile
        } // No .
        num := ciphertext[:pos]
-       if num == "0" {
+       if num == "!" {
                // No rotation; probably original was not valid unicode
                return ciphertext[pos+1:], nil
        }
diff --git a/crypt/cipher_test.go b/crypt/cipher_test.go
index edeb360..56639bf 100644
--- a/crypt/cipher_test.go
+++ b/crypt/cipher_test.go
@@ -243,7 +243,7 @@ func TestDecryptFileName(t *testing.T) {
                {NameEncryptionOff, "1/12/123.bin", "1/12/123", nil},
                {NameEncryptionOff, "1/12/123.bix", "", ErrorNotAnEncryptedFile},
                {NameEncryptionOff, ".bin", "", ErrorNotAnEncryptedFile},
-               {NameEncryptionObfuscated, "0.hello", "hello", nil},
+               {NameEncryptionObfuscated, "!.hello", "hello", nil},
                {NameEncryptionObfuscated, "hello", "", ErrorNotAnEncryptedFile},
                {NameEncryptionObfuscated, "161.\u00e4", "\u00a1", nil},
                {NameEncryptionObfuscated, "160.\u03c2", "\u03a0", nil},
```

**Comment by calisro** [comment] 2017-04-10 16:35
which beta was this problem introduced in?

**Comment by sweharris** [comment] 2017-04-10 16:47
It's been in the obfuscate code since that function was introduced; change 6e003934fc1e8fb1fd4b6a549dcda0d964c1a4e4, and which was merged in on March 29th; https://github.com/ncw/rclone/pull/1235

(It wasn't in 1.36; it'll be new in 1.37)

**Comment by naeloob** [comment] 2017-04-10 16:53
@sweharris 
It will probably be silly but if you add "0." in front of the plaintext : 
`               return "0." + plaintext`

why not check too "0." instead of simply "0"?
`       if num == "0" {`

That way the number of upped files afected will be reduced.

**Comment by sweharris** [comment] 2017-04-10 17:02
There's a test for the "." before that, and the num variable is set to everything before the "."
```
        pos := strings.Index(ciphertext, ".")
        if pos == -1 {
                return "", ErrorNotAnEncryptedFile
        } // No .
        num := ciphertext[:pos]
        if num == "0" {
```
So we are, effectively, testing for `0.`

**Comment by naeloob** [comment] 2017-04-10 17:05
Ok, sorry.
I talked just with the information on the message, i had have to check all the source.
It cannot be so easy :(

Sorry mate.

**Comment by drsmithy** [comment] 2017-04-11 01:51
Thanks for looking at this everyone.

That 1 in 256 files is a bit scary.  Having put ~10T of stuff up into ACD over the last couple of weeks it'd be great if there was some way of programmatically identifying which files/folders have been affected. :)

**Comment by sweharris** [comment] 2017-04-11 02:08
@drsmithy if you look at the raw filenames from the unencrypted store (eg "rclone ls Amazon:base_dir") then any filename beginning "0." is impacted.  To compare that to a local tree you'd need to do an "rclone ls acd-my-user-encrypted" and then compare the results to a local "find . -type f" (with sorting and filtering; it's a simple script).  Directory misnames (as in your "Airbender" example) are the most annoying, because every file in that directory is good, but the directory name is bad.

Of course only obfuscated files are impacted; if you use "none" or "standard" for filename_encryption then you're not impacted.

For the "obfuscated" case, option 4 from my list of fixes would make these files work again without any change, as long as the original filename was valid unicode (so if the filenames were pure ASCII then you'd be fine).  Any files with broken unicode names would need to be re-uploaded.   I expect that to be the least impactful solution (and is my preferred option), but since all options have impact I'm deferring to @ncw as to what fix he'd like to see.

There are some kludges you can do for immediate relief, but they may not be compatible, going forward.  For example, from the ACD web UI, any "0.randomstuff" entry you see, you could rename to "0.good_name".  Now the current rclone interface will show it as "good_name".  If we pick option 4 as the go-forward solution then you'll later need to rename it to "!.good_name", so this _is_ just a kludge and not recommended...

**Comment by drsmithy** [comment] 2017-04-12 05:17
Thanks, that was incredibly obvious in hindsight and I feel a bit silly for asking. :)

A few runs of 'find' shows 49 out of 11,826 objects are busted..

Unfortunately there's been some renaming going along with my uploading, so a straight compare isn't easy, but they are conveniently showing up in Sickrage as missing episodes, making them reasonably easy to find. :)

**Comment by Rootax** [comment] 2017-04-12 06:42
If you sync the source and the encrypted destination, the files with the "bad name" are considered different and uped again, so, no need to "search" them. Now, I just wait 1.37 :) (or the first beta with the solution)

**Comment by samukas** [comment] 2017-04-13 14:59
Ouch. Glad I stumbled upon this issue.
As I am "copy"-ing files (and most of the times locally deleting) files instead of using sync, I'll be watching this issue and looking forward to 1.37 to see how I should deal with the affected files

**Comment by ncw** [comment] 2017-04-14 09:47
@sweharris Are you going to send a PR for the fix?

Option 4 seems like a reasonable choice to me.

Can you make sure you include a test which fails on "Avatar The Last Airbender" and is fixed by your patch?

As for existing data that has been uploaded, a short python script should be able to rename things shouldn't it?

**Comment by sweharris** [comment] 2017-04-14 14:46
PR just made.  I made a bit of mess on my repo trying to keep this PR separate from the "report encrypted name" PR, but I think it's resulted in a clean PR!

I added a test in `TestEncDecMatches` which failed before the test, but succeeds now.

**Comment by Rootax** [comment] 2017-04-21 18:34
Sorry to be this guy, but any news about a new beta with this commit ?

**Comment by sweharris** [comment] 2017-04-21 18:36
In the PR, @ncw writes "This looks good. Will merge in a bit! (Sorry have been a bit overloaded after my return from vacation!)"

**Comment by Rootax** [comment] 2017-04-21 20:10
Ah yes sorry, didn't saw that.

Thx !

**Comment by ncw** [comment] 2017-04-22 08:19
This has been merged and will be in this beta

https://beta.rclone.org/v1.36-23-ge1647a5/ (uploaded in 15-30 mins)

**Closed by ncw** 2017-04-22 08:19 UTC
Labels: bug, Remote: Crypt
