### ISSUE TITLE
Find a better way to resume long-running rclones

### ISSUE THREAD

**Issue by filmil** [ncw/rclone#174] opened 2015-10-16 06:51 UTC
I started this rclone process about 1 month ago.  About 260GB and 100.000 files later, the machine that did the copying had to be reset, for reasons I don't understand just yet, and rclone was stopped.  Now I have 260GB to resume and about 3 times that to transfer in total.  

I understand that rclone is able to compare the file lists and sync only files that need syncing, and this is good. However, at this point I sort of wish that there was a way for rclone to write a periodic 'state of the world' that could be used to resume interrupted long-haul transfers.

**Comment by klauspost** [comment] 2015-10-16 08:25
@filmil - could you explain your use case a bit more in depth?

What are you copying to/from? 
How much time is spent before actual copying starts?

I have uploaded several TB to Amazon Cloud Drive, and resume time has never been an issue. I think the optimal way is to see if there is a way to speed up the current method, before throwing in "magic".

**Comment by filmil** [comment] 2015-10-16 15:17
On Fri, Oct 16, 2015 at 1:25 AM Klaus Post <notifications@github.com> wrote:

> @filmil <https://github.com/filmil> - could you explain your use case a
> bit more in depth?
>
Sure. I'm moving my backups from local hard drives to Google Drive.  I have
a 1Mbit/s upload pipe at home, and about 1T of data to upload.

> What are you copying to/from?
>
Local hard disks (at home) to Google Drive.

> How much time is spent before actual copying starts?
>
It took about 8 hours to read initial contents from Google Drive.  Right
now, about 2 hours in, rclone is comparing contents and skipping a bunch of
files that it had already copied over.


> I have uploaded several TB to Amazon Cloud Drive, and resume time has
> never been an issue. I think the optimal way is to see if there is a way to
> speed up the current method, before throwing in "magic".
>
Got it.  And depending on how long it takes for the upload to recover,
maybe there isn't an actual need to do anything here: if my upload is
slated to run for 3 months total, then a few hours here and there don't
make much of a difference.  The only thing here is, the longer the transfer
lasts, the more likely it is that something will go wrong.  And hence
recovery becomes more useful.  Feel free to figure out if doing anything
here makes sense for rclone.  I am inclined to think that as cloud grows,
it may become more important than it is now but not sure how much relative
to all the other, non-long-haul uses.

F

**Comment by ncw** [comment] 2015-11-07 16:52
Thanks for reporting this.  I'm going to close this it seems rclone is working as intended - maybe not quite as fast as possible though. Rest assured we will continue to try to make the resumes as fast as possible!

Thanks for the report

Nick

**Closed by ncw** 2015-11-07 16:52 UTC

**Comment by filmil** [comment] 2016-03-08 18:06
Thought you may like to know: the copy finished a few days ago, having transferred just short of 3 million files and logging 67 errors in the process. rclone FTW.

**Comment by ncw** [comment] 2016-03-09 08:01
Great! You should find the next version of rclone is much faster with drive. You can try a beta at pub.rclone.org if you want (choose the latest).
