### ISSUE TITLE
Symlinked directories aren't getting copied

### ISSUE THREAD

**Issue by yurivict** [ncw/rclone#257] opened 2015-12-20 15:22 UTC
When some directory is a symlink (/my/symlink -> /some/real/dir), rclone ignores its contents.

This command does nothing:
```
rclone copy /my/symlink remote:backup
```

rclone should see the same files that 'ls' sees.

**Comment by ncw** [comment] 2015-12-23 11:14
This by design.  Cloud storage systems can't store symlinks and following symlinks is fraught with peril (think recursive symlinks)

However rsync has some options which rclone could implement

```
        -l, --links                 copy symlinks as symlinks
        -L, --copy-links            transform symlink into referent file/dir
            --copy-unsafe-links     only "unsafe" symlinks are transformed
            --safe-links            ignore symlinks that point outside the tree
            --munge-links           munge symlinks to make them safer
        -k, --copy-dirlinks         transform symlink to dir into referent dir
        -K, --keep-dirlinks         treat symlinked dir on receiver as dir
```

I think the `-L` or `--copy-links` is probably the one to implement.  Rclone can't implement `-l` as cloud storage systems can't hold symlinks.

```
       -L, --copy-links
              When  symlinks are encountered, the item that they point to (the
              referent) is copied, rather than the symlink.
```

What do you think?

**Comment by yurivict** [comment] 2015-12-24 09:26
I was thinking in terms of how cp behaves when given a symlink.
$ cp -R sym-link-to-dir copy
- creates another symbolic link.
But
$ cp -R sym-link-to-dir/ copy
copies the directory. Slash makes a difference.

Most people will expect this behavior when they immediately supply the specific directory.

I also like the keys you suggest to have. They refer to how symlinks are treated in general.

**Comment by yurivict** [comment] 2015-12-24 09:27
Sorry, closed it by accident.

**Comment by klauspost** [comment] 2016-01-04 15:30
Duplicate of #40?

**Comment by ncw** [comment] 2016-02-10 18:33
Yes this is a duplicate of #40 so I'm going to close this

**Closed by ncw** 2016-02-10 18:33 UTC
Labels: enhancement
