### ISSUE TITLE
ACD - Odd behavior with move/rename

### ISSUE THREAD

**Issue by toomuchio** [ncw/rclone#830] opened 2016-10-28 06:52 UTC
Running the latest beta, Ubuntu x64, Amazon Cloud Storage.

For example if I do this

This is an encrypted mount.
touch atestfile
rclone copy atestfile acde:
rclone move acde:atestfile acde:hrm

A new folder called hrm is created and atestfile is put in there, instead of just renaming the file to hrm.
Is that intended? Seems quite odd. 

Also just wondering how far in the roadmap is moving/renaming in mounts? Would make organizing a lot easier.

Unfortunately since move isn't behaving the way I thought it would it doesn't seem possible to rename crypted files/folders at all. Since you can't really go to the amazon web ui and do that that way either as the file names are all encrypted.

**Comment by calisro** [comment] 2016-10-28 14:19
rclone ls robacd-crypt:/xbmc.log
  1694674 xbmc.log

 rclone move robacd-crypt:/xbmc.log robacd-crypt:/xbmc.txt
2016/10/28 10:14:00 
Transferred:   1.616 MBytes (409.677 kBytes/s)
Errors:                 0
Checks:                 1
Transferred:            1
Elapsed time:          4s

 rclone ls robacd-crypt:/xbmc.**txt**
  1694674 xbmc**.log**

 rclone ls robacd-crypt:/xbmc.log
2016/10/28 10:14:27 directory not found

If I check though on my fuse mounted volume of that same crypt drive, it is renamed correctly.  Looks like metadata is not updated though which is wierd! 
  ls xbmc*
xbmc.log

**Comment by toomuchio** [comment] 2016-10-28 14:41
Yeah it's really weird, I know getting writing to work via the mounts is a large task but since we have deleting it would be really cool to have moving/renaming working as well and/or rclone move fixed :)

Pretty much impossible to rename any crypted on ACD stuff at the moment without downloading renaming then reuploading :'(

**Comment by toomuchio** [comment] 2016-10-29 00:51
I see, you can't move files or dirs with server side operations currently so it's downloading and reuploading. https://github.com/ncw/rclone/issues/721

**Comment by calisro** [comment] 2016-10-29 00:55
Yes but it should handle it implicitly

**Comment by toomuchio** [comment] 2016-10-29 02:24
Fair.... @ncw just from what I've gathered in order to add server side move support would one just need to add relevant Move() and DirMove() functions to amazonclouddrive.go? If you wont be adding support any time soon I might have some time add it. Just need to get a better grasp on the code base first.

**Comment by toomuchio** [comment] 2016-10-30 01:53
@ncw There seems to be a bug with FindPath in dircache even when turning off the create flag it still attempts to make the directory after a few recursions.

I was able to add most of the logic for server side moves with ACD and it does indeed work in some cases, it's not ready for me to send you a pull request though due to the weird behaviors I'm getting from FindPath.

I can't explain this either, overlapping remotes error on the non-crypted, but not on the crypted.
./../../../../bin/rclone move acde:anothertest2 acde:testme/notareal2 -v
2016/10/30 02:31:24 rclone: Version "v1.33-DEV" starting with parameters ["./../../../../bin/rclone" "move" "acde:anothertest2" "acde:testme/notareal2" "-v"]
Move: create = false
_findDir: create = true
_findDir: create = true
2016/10/30 02:31:33 anothertest2: Moved

./../../../../bin/rclone move acd:anothertest2 acd:testme/notareal2 -v
2016/10/30 02:46:07 rclone: Version "v1.33-DEV" starting with parameters ["./../../../../bin/rclone" "move" "acd:anothertest" "acd:testme/notareal2" "-v"]
Move: create = false
_findDir: create = true
2016/10/30 02:46:11 amazon drive root 'testme/notareal2': Modify window not supported
2016/10/30 02:46:11 amazon drive root 'testme/notareal2': can't move files on overlapping remotes
2016/10/30 02:46:11 Attempt 1/3 failed with 0 errors and: can't move files on overlapping remotes
2016/10/30 02:46:11 amazon drive root 'testme/notareal2': can't move files on overlapping remotes
2016/10/30 02:46:11 Attempt 2/3 failed with 0 errors and: can't move files on overlapping remotes
2016/10/30 02:46:11 amazon drive root 'testme/notareal2': can't move files on overlapping remotes
2016/10/30 02:46:11 Attempt 3/3 failed with 0 errors and: can't move files on overlapping remotes
2016/10/30 02:46:11 Failed to move: can't move files on overlapping remotes

**Comment by toomuchio** [comment] 2016-10-30 10:06
Send a pull request adding support for moving/renaming using server side requests for ACD. 
https://github.com/ncw/rclone/pull/835

I was going to add directory support as well but it would have ended up being a total mess to test, since the mount option doesn't seem to use MoveDir and I can't call rclone move acd:a/ acd:b/

I think the is directory empty check on renames can go away as well, not sure why that's there.

**Comment by ncw** [comment] 2016-11-03 21:57
To answer your initial question

> rclone move acde:atestfile acde:hrm
> 
> A new folder called hrm is created and atestfile is put in there, instead of just renaming the file to hrm.
> Is that intended? Seems quite odd.

That is intended behaviour.  I agree it is a bit odd!  I'm going to make new rclone commands `cp` and `mv` which will work more like people expect. See #227

@toomuchio thanks for your PR - I'm a bit behind with rclone stuff, but I'll get to it soon!

I'm going to close this issue as I think the remaining things are represented well elsewhere.

**Closed by ncw** 2016-11-03 21:57 UTC
