### ISSUE TITLE
Split large files

### ISSUE THREAD

**Issue by mb300sd** [ncw/rclone#625] opened 2016-08-18 15:46 UTC
It would be nice to have a feature where large files could be split into multiple parts during upload. I'm using rclone to do offsite copying of my virtual machine backups and some of the files are >2TB.

I'm currently running this as a workaround, but it'd be nice to have the functionality built in and avoid many TBs of copying.
```
$ cat split.sh
#!/bin/bash

for f in *.vbk; do
        if [ $(stat -c %s $f) -gt 53687091200 ]; then
                if [ ! -f "$f!" ]; then
                        split -d -b 50G $f $f.
                        touch "$f!"
                fi
        fi
done
```

It could also be combined with --size-only so that it checks the sum of the sizes of the uploaded files against the size of the local file.

**Comment by ncw** [comment] 2016-08-18 15:50
This is a good idea, but it is a duplicate of #497 which I've renamed to be easier to find!

Can you subscribe to that ticket please?

**Closed** 2016-08-25 18:46 UTC
Labels: duplicate
