### ISSUE TITLE
Unable to copy to OneDrive for Business

### ISSUE THREAD

**Issue by Fade2Gray2** [ncw/rclone#2248] opened 2018-04-14 01:15 UTC
#### What is the problem you are having with rclone?
Not able to upload to OneDrive for Business however uploading to OneDrive personal works

#### What is your rclone version (eg output from `rclone -V`)
rclone v1.40
- os/arch: windows/amd64
- go version: go1.10

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10

####  Which cloud storage system are you using? (eg Google Drive)
OneDrive for Business

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone -v copy c:/temp/jack.jpg remote:Backup

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
C:\Temp\rclone-v1.40-windows-amd64>rclone -vv copy c:/temp/jack.jpg remote:Backup
2018/04/14 11:08:11 DEBUG : rclone: Version "v1.40" starting with parameters ["rclone" "-vv" "copy" "c:/temp/jack.jpg" "remote:Backup"]
2018/04/14 11:08:11 DEBUG : Using config file from "C:\\Users\\David\\.config\\rclone\\rclone.conf"
2018/04/14 11:08:12 INFO  : One drive root 'Backup': Modify window is 1s
2018/04/14 11:08:12 DEBUG : rclone-v1.40-windows-amd64: Excluded from sync (and deletion)
2018/04/14 11:08:12 DEBUG : test: Excluded from sync (and deletion)
2018/04/14 11:08:12 INFO  : One drive root 'Backup': Waiting for checks to finish
2018/04/14 11:08:12 INFO  : One drive root 'Backup': Waiting for transfers to finish
2018/04/14 11:08:12 DEBUG : jack.jpg: Starting multipart upload
2018/04/14 11:08:12 DEBUG : pacer: Rate limited, increasing sleep to 20ms
2018/04/14 11:08:12 DEBUG : pacer: low level retry 1/10 (error generalException: An unspecified error has occurred.)
2018/04/14 11:08:13 DEBUG : pacer: Rate limited, increasing sleep to 40ms
2018/04/14 11:08:13 DEBUG : pacer: low level retry 2/10 (error generalException: An unspecified error has occurred.)
2018/04/14 11:08:13 DEBUG : pacer: Rate limited, increasing sleep to 80ms
2018/04/14 11:08:13 DEBUG : pacer: low level retry 3/10 (error generalException: An unspecified error has occurred.)
2018/04/14 11:08:13 DEBUG : pacer: Rate limited, increasing sleep to 160ms
2018/04/14 11:08:13 DEBUG : pacer: low level retry 4/10 (error generalException: An unspecified error has occurred.)
2018/04/14 11:08:13 DEBUG : pacer: Rate limited, increasing sleep to 320ms
2018/04/14 11:08:13 DEBUG : pacer: low level retry 5/10 (error generalException: An unspecified error has occurred.)
2018/04/14 11:08:13 DEBUG : pacer: Rate limited, increasing sleep to 640ms
2018/04/14 11:08:13 DEBUG : pacer: low level retry 6/10 (error generalException: An unspecified error has occurred.)
2018/04/14 11:08:14 DEBUG : pacer: Rate limited, increasing sleep to 1.28s
2018/04/14 11:08:14 DEBUG : pacer: low level retry 7/10 (error generalException: An unspecified error has occurred.)
2018/04/14 11:08:14 DEBUG : pacer: Rate limited, increasing sleep to 2s
2018/04/14 11:08:14 DEBUG : pacer: low level retry 8/10 (error generalException: An unspecified error has occurred.)
2018/04/14 11:08:16 DEBUG : pacer: low level retry 9/10 (error generalException: An unspecified error has occurred.)
2018/04/14 11:08:18 DEBUG : pacer: low level retry 10/10 (error generalException: An unspecified error has occurred.)
2018/04/14 11:08:18 DEBUG : jack.jpg: Received error: generalException: An unspecified error has occurred. - low level retry 1/10
2018/04/14 11:08:18 DEBUG : jack.jpg: Starting multipart upload
2018/04/14 11:08:20 DEBUG : pacer: low level retry 1/10 (error generalException: An unspecified error has occurred.)
2018/04/14 11:08:22 DEBUG : pacer: low level retry 2/10 (error generalException: An unspecified error has occurred.)
2018/04/14 11:08:24 DEBUG : pacer: low level retry 3/10 (error generalException: An unspecified error has occurred.)
2018/04/14 11:08:26 DEBUG : pacer: low level retry 4/10 (error generalException: An unspecified error has occurred.)
2018/04/14 11:08:28 DEBUG : pacer: low level retry 5/10 (error generalException: An unspecified error has occurred.)
2018/04/14 11:08:30 DEBUG : pacer: low level retry 6/10 (error generalException: An unspecified error has occurred.)
2018/04/14 11:08:32 DEBUG : pacer: low level retry 7/10 (error generalException: An unspecified error has occurred.)
2018/04/14 11:08:34 DEBUG : pacer: low level retry 8/10 (error generalException: An unspecified error has occurred.)

**Comment by ndbeals** [comment] 2018-04-14 16:11
I'm getting these exact same errors, it only started happening to me some time between yesterday and today. 

Maybe MS changed something on their end?

**Comment by nsymms** [comment] 2018-04-14 20:55
I've been getting this also in my OneDrive business (academic) accounts, for a couple of days now. I ran rclone with the `--dump headers,auth,bodies` option and the server is returning 500 in response to the `createSession` request. The response body is
```
54
{"error":{"code":"generalException","message":"An unspecified error has occurred."}}
0
```

Everything else looks good to me, including credentials, URL construction, other data, etc. It's been working well for months now and all of a sudden it dies. The only difference I see so far between rclone and some "other" cloud client that works is the POST data during createSession. Rclone sends something like
```
{"item":{"fileSystemInfo":{"createdDateTime":"2018-04-11T00:22:51Z",
 "lastModifiedDateTime":"2018-04-11T00:22:51Z"}} }
```
and the other client simply sends:
`{"item":{"@name.conflictBehavior":"rename"}}`

And, if it helps, all the other things still work: `ls, delete, mount`. You just can't write anything to OneDrive. I'm going to keep doing tests on my own to see what else I can discover.

**Comment by nsymms** [comment] 2018-04-14 21:52
Ha. That was it.

I know nothing about the GO language but I managed to hack up the OneDrive `api/types.go` and `onedrive.go` files to implement the changes I mentioned above, and it worked!

It took me awhile to figure out how to compile and re-compile after changes, but it works. Now hopefully @ncw can work his magic and make a release. It was a 5-line change for me; hopefully he can do it properly.

I did notice another difference between rclone and the other client. They use a different URL. Where rclone uses `/_api/v2.0/drives/me/root:/..... etc` they use `/_api/v2.0/me/drive/items/root:/...`. I didn't change that since it seems to work either way.

**Comment by Fade2Gray2** [comment] 2018-04-14 23:58
Thanks nsymms, you've make some great progress!!
For a real newbie like myself, in simple terms could be please provide a simple step by step instructions on how to get this fixed OR would be better to simply wait for an updated version of rclone that addresses this issue?
Thanks again !!

**Comment by nsymms** [comment] 2018-04-15 01:46
Probably be better to wait for @ncw if you're not used to editing source code and compiling. It's getting late at night where I live, so if Nick doesn't respond in 12 hours or so, I can list more detailed steps and post a linux binary somewhere. Not sure if I can create a Windows binary but I could try.

**Comment by sandersonb** [comment] 2018-04-15 07:06
Reading https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession it seems to agree with @nsymms that the request body to createSession should be either empty or have a `"@microsoft.graph.conflictBehavior": "<behavior">` in it. My theory right now is that the `FileSystemInfo` structure is no longer supported in this call. But -- can `FileSystemInfo` be passed to the fragment upload? If not then we've lost functionality.

**Comment by wegood9** [comment] 2018-04-15 14:26
I have the same problem,too.

**Comment by ncw** [comment] 2018-04-15 17:46
@nsymms thanks for your investigations :-)  

Unfortunately I don't have a working onedrive for business login any more - all the ones I've been lent in the past are no longer working :-(

Is it the addition of the `"@name.conflictBehavior"` which fixes the problem, or is it the removal of the `"fileSystemInfo"` which fixes the problem.

If the latter, then rclone objects will no longer have the correct modification date which will break syncing.

Also I think "replace" would be a better value for `@name.conflictBehavior` (which should be the default).

Can you try this which just sets the conflictBehaviour?  This does pass the integration tests for onedrive personal.

https://beta.rclone.org/v1.40-085-g1b78dc75-fix-2248-onedrive/ (uploaded in 15-30 mins)

PS for next time, please send a unified diff `diff -u` - old style diffs confuse `patch` and me!

Sending up the bat signal for @olihey :-)

**Comment by olihey** [comment] 2018-04-15 18:28
Please stay calm, no changes needed for now.
It seems the OneDrive API has an issue: https://github.com/OneDrive/onedrive-api-docs/issues/832

@sandersonb It's not stated anywhere in the docs that `conflictBehavior` is needed. It's just used in all examples, so that might be a bit misleading.
@ncw I agree, that the default should be `replace` which is actually the 'default' setting if it's missing 😄 
@nsymms Without the `FileSystemInfo `structure we will loose the ability to set the last modification date, so 🤞 that Microsoft fixes that, also rclone is not yet using the new Microsoft Graph API for accessing your data, so that's might why the URLs doesn't match with other client that might use the Graph API

**Comment by nsymms** [comment] 2018-04-15 19:28
I've run a couple of tests, and indeed it appears to be the addition of the fileSystemInfo object that causes the 500 response. This is exactly what is stated in the OneDrive API issue mentioned by @olihey. So by simply passing an empty body (just "{}") to the createSession request, things work. But I that's not really a fix, since the problem is on Microsoft's side and we lose the file timestamps which rclone needs in place.

I also noticed that the "move" command no longer works because it also passes a fileSystemInfo object to the api.

So I guess we shouldn't make any changes; just wait for the Microsoft team to fix this? Unless of course they take FOREVER in which case a workaround might be required.

**Comment by olihey** [comment] 2018-04-15 19:31
@nsymms That's the big question, and from previous experience I know it will take some time for Microsoft to fix this. But there are also some bugs reported that never got any response 😞

**Comment by ncw** [comment] 2018-04-15 22:05
@olihey 

We could do a workaround and set the modtime after, however that will reintroduce the doubling the revisions problem won't it?

**Comment by nsymms** [comment] 2018-04-15 22:48
That's what I was thinking....

So I tried it; no joy. Rclone's modtime() method sets the fileSystemInfo via a PATCH and that's broken on the Microsoft side also. It's the 2nd example listed in https://github.com/OneDrive/onedrive-api-docs/issues/832 and you can see the 500 response they get.

**Comment by olihey** [comment] 2018-04-16 05:37
@nsymms @ncw Well, workaround for now is using an older version of rclone before the fix for the double versions was added? Not sure which one this is, as I mostly run master 😄? And if Microsoft does not react, which I don't think they will as using the FileSystemInfo is there preferred way of uploading files with metadata, we have to revert back.

**Comment by wjansenw** [comment] 2018-04-16 06:33
Could it be this started working OK again? I didn't upgrade rclone but the issue is gone...

**Comment by Fade2Gray2** [comment] 2018-04-16 07:10
Upon wjansenw's update, l have re-tested and are happy to advise it is now working using the current/latest version of rclone 👍 at my side

**Comment by ncw** [comment] 2018-04-16 07:44
This was posted on the onedrive issue just now: https://github.com/OneDrive/onedrive-api-docs/issues/832

> Just a quick update to report that things are back to normal on both OneDrive Bussiness and Sharepoint when using our in-house Office365 account but a couple of our app's users were still complaining about it. We've advised them to give it a rest and try a day later with the hope it restores itself till then.

**Comment by ncw** [comment] 2018-04-16 16:43
It looks like Microsoft have fixed the issue at their end.

> There unfortunately was a regression with the handling of those timestamps, but as you've observed the issue was patched over the weekend. I haven't checked deployment status today, but it's possible the patch is still rolling to a few tenants so waiting will probably help.

So I'm going to close this issue now :-)

**Closed by ncw** 2018-04-16 16:43 UTC
Labels: Remote: One Drive, bug
