### ISSUE TITLE
Upload failed, file removed, but retry continuing

### ISSUE THREAD

**Issue by isaiah36** [ncw/rclone#605] opened 2016-08-05 04:33 UTC
When filing an issue, please include the following information if
possible as well as a description of the problem.  Make sure you are
using the [latest version of rclone](http://rclone.org/downloads/).

> What is your rclone version (eg output from `rclone -V`) 1.32

> Which OS you are using and how many bits (eg Windows 7, 64 bit) Ubuntu 16 64 bit

> Which cloud storage system are you using? (eg Google Drive) Amazon 

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`) sync

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

I am syncing a directory with many large video files, 25 altogether.  After 13 files completed successfully 1 file of 6.6 Gb size reached 100% and then started over from 0% again.  I removed the file from the directory completely but the retry is carrying on merrily on its way!  Does rclone cache the whole file before uploading?  It is too large to be in memory, besides there are 3 other files running too.

I have experienced failed upload before, and solved it by using the Amazon desktop app for Windows.  So, I am doing that in this case.  I don't want to interrupt the rclone process because other files are in an advanced stage of upload, but I want it to stop the retry of the failed file and move on to another file.  Is there a command modification that will tell rclone not to retry failed uploads?

Thanks.

**Comment by isaiah36** [comment] 2016-08-05 04:41
A 2nd file reached 100% and then started over from 0% again.  I killed the process and started it fresh.

**Comment by ncw** [comment] 2016-08-05 09:43
I suspect this is the same problem as #601 which unfortunately is an Amazon problem which I can't fix :-(

If you supply a log with `-v` I can confirm.

> I removed the file from the directory completely but the retry is carrying on merrily on its way! Does rclone cache the whole file before uploading? 

No rclone doesn't cache the file.  On unix you can delete an open file and the processes which have it open will carry on just fine.  Windows prevents you from deleting open files at all.

> Is there a command modification that will tell rclone not to retry failed uploads?

Checkout the `--retries` flag and also the `--low-level-retries` flag.

**Comment by isaiah36** [comment] 2016-08-05 15:41
The unreliability of the server side APIs is unfathomable.  How hard can it be to support a venerable old protocol like rsync?  Amazon is affordable, that's about what one can say.

2 other files started over from 0% while I was monitoring the progress, one at 4% and the other at 10% before I went to bed.  11 files were completed in the first 24 hours, and only 4 more have completed in the second 24 hours.  The desktop app is still running the upload of the file started about 10 hours ago.  it does not output any speed or estimated time left.

I should have logged it to file.  If I run it again I will create a log file.

**Comment by ncw** [comment] 2016-08-05 23:11
I posted a potential fix for this in #606 if you fancy giving it a go.

**Comment by isaiah36** [comment] 2016-08-08 00:36
I have the latest beta installed.  Since that time I have had one file trip up repeatedly at 37% and start over.  I tried the same file with the Amazon desktop app for 4 hours and 45 minutes, about twice as long as it should have taken, before cancelling the upload.

**Comment by ncw** [comment] 2016-08-08 18:13
Here is a new attempt at a fix.  Note that it only stands a chance if your file gets to nearly 100% - if it is cut off much less then that then the only hope is to retry it.

http://pub.rclone.org/v1.32-18-gaffc483%CE%B2/

**Comment by ncw** [comment] 2016-08-08 21:45
OK here is another attempt, a bit better tested:

http://pub.rclone.org/v1.32-18-gaffc483%CE%B2/

**Comment by ncw** [comment] 2016-08-08 21:54
With correct URL this time: http://pub.rclone.org/v1.32-18-g29ab7ea%CE%B2/

**Comment by isaiah36** [comment] 2016-08-09 00:43
Thank you for all your efforts.  I do not have a long batch to run, but I will in a day or two.  I'll be sure to run it -v with log file.

The tripping file did finally get uploaded by the Amazon desktop app, in one swing judging by the time it took.  This Windows 7 laptop is connected by ethernet cord, not wifi.  The other one where the upload failed is on wifi.

**Comment by ncw** [comment] 2016-08-09 17:04
I've reworked the patch again with the following changes.  On a failed upload we
  * detect if we uploaded the file to 100% - if we didn't do nothing
  * do this for any upload error (so might get round the 500 error)
  * increase timeout to 2 minutes - timeout might need to vary with file size?
  * made timeout configurable with `--acd-upload-wait-time` - perhaps set it large when uploading huge files?

Here is the beta: http://pub.rclone.org/v1.32-18-gf7562dc%CE%B2/

**Comment by isaiah36** [comment] 2016-08-09 17:15
Thanks.  So, the argument would be --acd-upload-wait-time="5" for a 5 minute wait?

I am running a batch upload right now with the previous beta, and a verbose text file log.  I'll post the results.

**Comment by ncw** [comment] 2016-08-09 20:06
You want --acd-upload-wait-time="5m"

**Comment by isaiah36** [comment] 2016-08-09 23:13
Thank you.

**Comment by isaiah36** [comment] 2016-08-10 14:14
Here is the log from the last backup.  From a quick scan I see one 504 timeout but it appears to have been handled successfully on the first retry.  I did not notice a restart in there.
[rclone-log.txt](https://github.com/ncw/rclone/files/411283/rclone-log.txt)

**Comment by ncw** [comment] 2016-08-10 20:23
I've had a look at that thanks.  It looks like the token refreshing is working, but rclone didn't wait long enough for objects to appear.

Can you try the latest beta (see above)?

Thanks for testing - Nick

**Comment by isaiah36** [comment] 2016-08-10 21:52
I thought I had the latest beta.  I re installed it to make sure.  I don't have a long batch to run manually so the next available log will be from the cron job that runs at night.  I will post it in the morning.

**Comment by isaiah36** [comment] 2016-08-11 12:57
Looks like a flawless log.
[rclone-log.txt](https://github.com/ncw/rclone/files/413215/rclone-log.txt)

**Comment by isaiah36** [comment] 2016-08-13 22:19
While doing a copy of 3 files 1 reached 100% and started over.  It is 1.4 Gb in size.  So maybe the timeout is not what it is.

**Comment by isaiah36** [comment] 2016-08-13 22:42
Completed it on the 2nd attempt.

**Comment by ncw** [comment] 2016-08-18 16:50
I've merged this to master and it will be in the v1.33 release - thanks for your help testing.

Please re-open if you see any problems.

Here is a beta with the latest code in: http://pub.rclone.org/v1.32-20-g2ebeed6%CE%B2/

**Closed by ncw** 2016-08-18 16:50 UTC
Labels: bug
