### ISSUE TITLE
Sync google documents

### ISSUE THREAD

**Issue by mullenkamp** [ncw/rclone#123] opened 2015-09-07 14:34 UTC
Hi again,

This is not as immediately necessary as some other issues that you may have (e.g. folder time stamps and removal, "include/exclude" options, duplicate files, etc), but I thought I'd bring it up for completeness.

Implementing the option to download converted google documents and have them recognized as such on a reverse sync would be a great option (especially for backing up google docs). 
Google already has an API for Drive that allows you to specify a file type to download the various google documents:
https://developers.google.com/drive/web/manage-downloads#downloading_google_documents

This has already been implemented in an open source google drive mounting program:
https://github.com/astrada/google-drive-ocamlfuse/wiki/Exportable-formats

I hope this helps...Thanks again for a nice copy program.

**Comment by ncw** [comment] 2015-09-07 16:41
This is a duplicate of #49

**Comment by mullenkamp** [comment] 2015-09-07 17:32
Oh, sorry. It wasn't obvious from the title (or even the initial comment).

**Closed** 2015-09-07 17:34 UTC
Labels: duplicate

**Comment by ncw** [comment] 2015-09-07 18:35
@mullenkamp No worries! Unfortunately there are a lot of open tickets - so many features to add and not enough time!

**Comment by mullenkamp** [comment] 2015-09-07 19:05
You've done a great job so far. This is a fairly minor issue, that's why I
made the disclaimer at the beginning. The most important part of copy
programs is that the transfers are reliable and consistent. This has been a
major issue with other similar programs I've used. Everything else is a
bonus.
I always feel bad that I'm not a real programmer and still ask for free
things like this. That's why I thank people like you ;)

**Comment by ncw** [comment] 2015-09-07 19:06
@mullenkamp thanks and you are welcome!
