### ISSUE TITLE
fuse: panic in handler for Rename

### ISSUE THREAD

**Issue by PiscisSwimeatus** [ncw/rclone#973] opened 2016-12-26 22:29 UTC
> What is your rclone version (eg output from `rclone -V`)
rclone v1.34-75-gcbfec0dβ
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 16.04.1 LTS
> Which cloud storage system are you using? (eg Google Drive)
Amazon Cloud Drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
Mount - Rename
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

2016/12/26 23:25:17 fuse: panic in handler for Rename [ID=0x1c9e Node=0x2 Uid=1000 Gid=1000 Pid=6854] from "M2jj2l5mjvQjAbumThW4bB,kYqrcuktJB2wSmXk,5USH3UwlYRG0Zt89fUa9omhsZiZGHFCjzWUrwwywqndbErBFvUi9s7frkzL8Eo2c9sfo60" to dirnode 0xe "TiOJYSeRij0jIFCrR0AYpyMEs1rO4n74kGwdgajY59pGaY3hdgkRLJv2ZIGbs4xOfLFgloTpuNCWp7d3D2jXpR2d-Wh9dzqZphR3-ZprsdzYZ1": runtime error: invalid memory address or nil pointer dereference
goroutine 9076 [running]:
github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).serve.func2(0xfccc40, 0xc4207e4180, 0xc4208a3eb8, 0xc4208a3e0f)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:857 +0x1d9
panic(0xb250a0, 0xc420010090)
        /home/travis/.gimme/versions/go1.7.4.linux.amd64/src/runtime/panic.go:458 +0x243
github.com/ncw/rclone/vendor/github.com/ncw/go-acd.(*Node).Rename(0xc4207e41e0, 0xc420ed494b, 0x6e, 0x0, 0xc4208a3220, 0xc4208a3228, 0xc4208a3218)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/ncw/go-acd/nodes.go:310 +0x57
github.com/ncw/rclone/amazonclouddrive.(*Fs).renameNode.func1(0xc4200598c0, 0xc420c35f20, 0xc212ec)
        /home/travis/gopath/src/github.com/ncw/rclone/amazonclouddrive/amazonclouddrive.go:1026 +0x63
github.com/ncw/rclone/pacer.(*Pacer).call(0xc4200598c0, 0xc4207e0180, 0xa, 0xba78e0, 0x40b801)
        /home/travis/gopath/src/github.com/ncw/rclone/pacer/pacer.go:334 +0x89
github.com/ncw/rclone/pacer.(*Pacer).Call(0xc4200598c0, 0xc4207e0180, 0x0, 0x481639)
        /home/travis/gopath/src/github.com/ncw/rclone/pacer/pacer.go:357 +0x66
github.com/ncw/rclone/amazonclouddrive.(*Fs).renameNode(0xc420059980, 0xc420d26300, 0xc420ed494b, 0x6e, 0x100000000000000, 0x100000000000000, 0x16)
        /home/travis/gopath/src/github.com/ncw/rclone/amazonclouddrive/amazonclouddrive.go:1028 +0x15f
github.com/ncw/rclone/amazonclouddrive.(*Fs).moveNode(0xc420059980, 0xc4208afc20, 0x87, 0xc420ed494b, 0x6e, 0xc4207f2500, 0x16, 0xc420d26300, 0xc4208afc39, 0x6e, ...)
        /home/travis/gopath/src/github.com/ncw/rclone/amazonclouddrive/amazonclouddrive.go:1074 +0x1d9
github.com/ncw/rclone/amazonclouddrive.(*Fs).Move(0xc420059980, 0xfd1a20, 0xc4208e26a0, 0xc420ed4900, 0xb9, 0x0, 0x1, 0x7f770573d4b0, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/amazonclouddrive/amazonclouddrive.go:654 +0x1e9
github.com/ncw/rclone/cmd/mount.(*Dir).Rename(0xc420238070, 0x7f77056f62b0, 0xc4207e0140, 0xc4207e4180, 0xfc5180, 0xc4207c0310, 0x0, 0xfc76c0)
        /home/travis/gopath/src/github.com/ncw/rclone/cmd/mount/dir.go:365 +0xaf3
github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).handleRequest(0xc4201f80c0, 0x7f77056f62b0, 0xc4207e0140, 0xfc5180, 0xc420238070, 0xc4203c63c0, 0xfccc40, 0xc4207e4180, 0xc4208a3eb8, 0x0, ...)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:1335 +0x27e0
github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).serve(0xc4201f80c0, 0xfccc40, 0xc4207e4180)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:878 +0x4a3
github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).Serve.func1(0xc4201f80c0, 0xfccc40, 0xc4207e4180)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:425 +0x6e
created by github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).Serve
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:426 +0x3e4

**Comment by ncw** [comment] 2016-12-31 12:11
This appears to have been caused by an acd.Node without an Id...

What sequence of operations lead to this - can you provide a sequence which I can use to reproduce?

**Comment by PiscisSwimeatus** [comment] 2017-01-02 10:57
I've seen this while moving/renaming files with both nautilus and filebot. I don't have any concrete step-by step guide to reproduce this issue since it only happens once in a while. It does look like it only happens when I do a lot of files at once. And maybe this error pops up on 1/20 maybe. If I try again it works. Is there any logging/actions you want me to do/send you which would give you more information?

**Comment by PiscisSwimeatus** [comment] 2017-01-06 16:36
Same issue with 1.35

**Comment by ncw** [comment] 2017-01-14 09:51
I've figured this one out - it should be fixed in this beta

http://beta.rclone.org/v1.35-26-gaa62e93/ (uploaded in 15-30 mins)

**Closed** 2017-01-14 09:52 UTC
Labels: bug, Remote: Amazon Cloud Drive

**Comment by PiscisSwimeatus** [comment] 2017-01-19 07:27
Thank you, not been able to reproduce this error after your fix.

**Comment by ncw** [comment] 2017-01-20 17:54
@PiscisSwimeatus thanks for testing.
