### ISSUE TITLE
Fix and document move

### ISSUE THREAD

**Issue by dav1303** [ncw/rclone#334] opened 2016-02-01 20:29 UTC
Hi

Is it possible to activate the option "deleting files after" but on the source file ?

Thanks Regards

**Comment by ncw** [comment] 2016-02-01 22:49
I'm not sure I understand what you mean. The source files are never deleted?

**Comment by dav1303** [comment] 2016-02-02 18:55
Hi

Is it possible to had an optionnal parameter to delete the source file
after migration success or an option to move

Regards
Le 1 févr. 2016 11:49 PM, "Nick Craig-Wood" <notifications@github.com> a
écrit :

**Comment by ncw** [comment] 2016-02-05 16:49
There is an `rclone move` command which might do what you want?

I've just noticed this is missing from the docs!

**Comment by dav1303** [comment] 2016-02-05 17:03
Yes but I've got this error when moving from Disk to GDrive

2016/02/05 18:01:39 Google drive root '': Waiting for checks to finish
2016/02/05 18:01:39 Couldn't move: Can't copy object - incompatible remotes
2016/02/05 18:01:39 Couldn't move: Can't copy object - incompatible remotes
2016/02/05 18:01:39 Couldn't move: Can't copy object - incompatible remotes
2016/02/05 18:01:39 Couldn't move: Can't copy object - incompatible remotes
2016/02/05 18:01:39 Google drive root '': Waiting for transfers to finish
2016/02/05 18:01:39 Google drive root '': Not deleting files as there were IO er
rors
2016/02/05 18:01:39 Attempt 3/3 failed with 4 errors

**Comment by ncw** [comment] 2016-02-06 16:42
I can confirm that! I'll make a fix and put a beta here for you to try

**Comment by dav1303** [comment] 2016-02-19 21:56
Thanks Nick

**Comment by ncw** [comment] 2016-02-25 22:16
This is fixed now and will be in the next release.

Here is a beta for you to try with the fix.

http://pub.rclone.org/v1.27-33-g3890105%CE%B2/

Thanks for reporting the bug

Nick

**Closed** 2016-02-25 22:15 UTC
Labels: bug, doc fix

**Comment by dav1303** [comment] 2016-02-26 22:30
Hi Nick

Thanks it seems perfect now

Regards

**Comment by mdeboer** [comment] 2016-05-13 15:50
It would be nice to have an option that skips the rmdir of the source directory. Say if I move /backup, it tries to delete /backup, which might be mounted and give errors.

1. Upload files
2. Remove all contents of the source dir (eg. /backup)
3. Done, quit. (skip the rmdir part)

I managed to fix this myself by creating a filter/excludes file in /backup and excluding that file. This way /backup is not considered empty and will not be removed while all tranfered files still are removed.

**Comment by ncw** [comment] 2016-05-16 11:06
rclone `move` works like it does because it can invoke a server side operation to move the whole directory tree if available.

I see where you are coming from though - I'll have a think!

**Comment by reuu** [comment] 2016-11-01 12:44
Hi. Im using move. It copy all but don't delete from source... i need to compare one on one and see if it copied, after review, delete manually from source... move does not delete.. anyone know what's happend with move command? thanks..

**Comment by ncw** [comment] 2016-11-03 22:12
@reuu check that there weren't any errors copying.  If there were then rclone doesn't do deletions.
