### ISSUE TITLE
Gogle Docs not showing in Google Drive

### ISSUE THREAD

**Issue by jacobfarkas** [ncw/rclone#339] opened 2016-02-03 13:54 UTC
rclone is only seeing the regular files I store in Google Drive. I'm not able to see or sync any of the native google docs, sheets, etc,

**Comment by mafm** [comment] 2016-02-04 01:41
Are you missing files from the root directory only? In issue #49 somebody mentioned that specifying
  drive-full-list=false
might be needed to get google docs in root directory.

That solved the problem for me - using v1.27.

**Comment by jacobfarkas** [comment] 2016-02-04 01:49
Matthew,

Thanks for the input.

Sadly, I'm not not getting native google docs in any directory. All other
files are there.

--Jacob

**Comment by ncw** [comment] 2016-02-04 10:09
@jacobfarkas can you make sure you are using rclone 1.27 and using the `drive-full-list=false` (until I fix #336).

Also can you check you can download the docs from the web interface?  Try right clicking on them in the drive web interface and selecting download - it might be that you don't have permissions to export the documents.

What happens when you run `rclone -v ls drive:path` - does rclone mention the docs at all in the debug output?

**Comment by ncw** [comment] 2016-02-04 10:16
Another thought - are these files shared with you? See #48

**Comment by jacobfarkas** [comment] 2016-02-04 14:37
Nick,

It does work when I'm using the  --drive-full-list=false

Thanks,
--Jacob

**Comment by ncw** [comment] 2016-02-05 16:45
Great.  I'll mark this as a duplicate of #336 then.

**Closed by ncw** 2016-02-05 16:45 UTC
Labels: duplicate

**Comment by jacobfarkas** [comment] 2016-02-05 16:47
Nick,

I noticed it even when in "root" of Google Drive

--Jacob

**Comment by ncw** [comment] 2016-02-05 16:50
Yes that is expected.  If `--drive-full-list=false` then it has the same cause as #336

**Comment by jacobfarkas** [comment] 2016-02-05 17:09
Fair point.
