### ISSUE TITLE
Fails to upload to ceph backed juno/swift HTTP 411

### ISSUE THREAD

**Issue by stuartbfox** [ncw/rclone#117] opened 2015-08-29 16:28 UTC
Hi 

Attempting to create an apt mirror on swift with rclone, I can't upload any files. The container is set to private and auth is working, I can ls/lsd and view the contents. Output is

ubuntu@1404-package-builder:~/git/Diamond/build$ rclone --verbose=true copy diamond_4.0.211_all.deb gva1:repos/TEST
2015/08/29 16:27:08 Swift container repos path TEST/: Modify window is 1ns
2015/08/29 16:27:08 Swift container repos path TEST/: Building file list
2015/08/29 16:27:08 Swift container repos path TEST/: Waiting for checks to finish
2015/08/29 16:27:08 Swift container repos path TEST/: Waiting for transfers to finish
2015/08/29 16:27:08 diamond_4.0.211_all.deb: Failed to copy: HTTP Error: 411: 411 Length Required
2015/08/29 16:27:08 diamond_4.0.211_all.deb: Removing failed copy
2015/08/29 16:27:08 diamond_4.0.211_all.deb: Failed to remove failed copy: Object Not Found
2015/08/29 16:27:08 Attempt 1/3 failed with 1 errors
2015/08/29 16:27:08 Swift container repos path TEST/: Building file list
2015/08/29 16:27:08 Swift container repos path TEST/: Waiting for checks to finish
2015/08/29 16:27:08 Swift container repos path TEST/: Waiting for transfers to finish
2015/08/29 16:27:08 diamond_4.0.211_all.deb: Failed to copy: HTTP Error: 411: 411 Length Required
2015/08/29 16:27:08 diamond_4.0.211_all.deb: Removing failed copy
2015/08/29 16:27:08 diamond_4.0.211_all.deb: Failed to remove failed copy: Object Not Found
2015/08/29 16:27:08 Attempt 2/3 failed with 1 errors
2015/08/29 16:27:08 Swift container repos path TEST/: Building file list
2015/08/29 16:27:09 Swift container repos path TEST/: Waiting for checks to finish
2015/08/29 16:27:09 Swift container repos path TEST/: Waiting for transfers to finish
2015/08/29 16:27:09 diamond_4.0.211_all.deb: Failed to copy: HTTP Error: 411: 411 Length Required
2015/08/29 16:27:09 diamond_4.0.211_all.deb: Removing failed copy
2015/08/29 16:27:09 diamond_4.0.211_all.deb: Failed to remove failed copy: Object Not Found
2015/08/29 16:27:09 Attempt 3/3 failed with 1 errors

Transferred:       494550 Bytes ( 695.40 kByte/s)
Errors:                 1
Checks:                 0
Transferred:            3
Elapsed time:  694.506827ms

2015/08/29 16:27:09 Go routines at exit 9

**Comment by ncw** [comment] 2015-08-29 18:27
That is a puzzle!

I've done quite a bit of searching about this error from Ceph, and it seems that Ceph requires either `Transfer-Encoding: chunked`, or a `Content-Length`.

I've double checked using the debug facilities in the AWS SDK and I believe rclone is sending a `Content-Length`  for all PUT and POST uploads.

rclone is working with my test ceph (unfortunately I don't know which version as I'm using a donated account) and also with S3.

Some questions for you:
  * is there a proxy between you and the ceph node
  * how have you got RadosGW set up - are you using the recommended way with the patched apache?
  * is there anything else unusual about your setup?

Hopefully we can get to the bottom of this!

Thanks

Nick

**Comment by ncw** [comment] 2015-09-02 09:18
@stuartbfox did you have any ideas on the above?  Thanks -- Nick

**Comment by j-vizcaino** [comment] 2015-09-22 14:32
Hi,

I'm facing a similar issue. I guess why you can't reproduce the problem is because it is caused by the global configuration.
I am using Rados running behing an Apache fastcgi and can't get the PUT commands to go through. In my case, Apache is simply discarding the PUT requests (possibly because the `Content-Length` is missing from headers).

Issuing a simple
```
rclone --retries=1 --dump-headers=true copy myfile.zip target:container
```
shows four requests (excluding the first GET, part of the auth/token step, URL simplified)

* PUT container → 202
* GET container → 200 (lists container)
* PUT myfile.zip → 411 (no `Content-Length` or `Transfer-Encoding` header here)
* DELETE myfile.zip → 404

Looking at the rados log, I can see the PUT/202, GET/200, DELETE/404: the PUT command is missing.
For more information regarding the Apache configuration: http://docs.ceph.com/docs/hammer/radosgw/config/

As a side note: targeting Rados directly works perfectly.

Versions used:

* Ceph 0.94.3
* rclone 1.20

Thanks

**Comment by ncw** [comment] 2016-02-10 18:23
When I try this with rclone 1.27 I can see a `Content-Length` header in the PUT so I conjecture this is fixed now.

If not then please re-open or make another issue.

Thanks

Nick

**Closed by ncw** 2016-02-10 18:23 UTC
Labels: can't reproduce
