### ISSUE TITLE
Failed to create new OS thread

### ISSUE THREAD

**Issue by tcf909** [ncw/rclone#1264] opened 2017-03-21 23:59 UTC
Spawned from #1231 

Running the rclone using a process manager that runs the following command:
```
/usr/local/bin/rclone mount ACD_VAULT:/Media /data/.Vault --config /etc/rclone/rclone.conf -v --max-read-ahead 200M --buffer-size 200M --allow-other &
wait $!
```

Using version 174 I get this output:
```
/usr/local/bin/rclone mount ACD_VAULT:/Media /data/.Vault --config /etc/rclone/rclone.conf -v --max-read-ahead 200M --buffer-size 200M --allow-other
runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc

runtime stack:
runtime.throw(0x814023, 0x9)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/panic.go:596 +0x70
runtime.newosproc(0x1442002a000, 0x1442003a000)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/os_linux.go:163 +0x164
runtime.newm(0x848e20, 0x0)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/proc.go:1628 +0x110
runtime.main.func1()
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/proc.go:126 +0x28
runtime.systemstack(0xccdd00)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/asm_arm64.s:241 +0x90
runtime.mstart()
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/proc.go:1132

goroutine 1 [running]:
runtime.systemstack_switch()
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/asm_arm64.s:190 +0x8 fp=0x14420026780 sp=0x14420026770
runtime.main()
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/proc.go:127 +0x58 fp=0x144200267d0 sp=0x14420026780
runtime.goexit()
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/asm_arm64.s:981 +0x4 fp=0x144200267d0 sp=0x144200267d0
```

Rolling back to version 164 eliminated  the issue.

This is in a docker container based on Ubuntu.

**Comment by ncw** [comment] 2017-03-22 14:51
Could you make me a container which reproduces this issue that I can get from the docker hub?  With some instructions on how to fetch, run and reproduce please?

I've done quite a bit of searching and while I see lots of reports of this issue, I don't see a definitive fix.  If you can make it reproducible then I can investigate, and send it upstream to the go developers if appropriate.

Thanks

Nick

**Comment by tcf909** [comment] 2017-04-25 05:46
Haven't been able to reproduce it in the last couple of weeks. Maybe close until it resurfaces?

**Comment by ncw** [comment] 2017-06-28 09:17
I'm going to close this until we see it again :-)

**Closed by ncw** 2017-06-28 09:17 UTC
Labels: bug

**Comment by Dave3o3** [comment] 2017-09-15 09:25
Here it is – with latest macOS beta (`rclone-v1.37-139-g798502b2β-osx-amd64`):

I transferred from Dropbox remote to Google Drive:

```
rclone copy -c -v dropbox:Folder\ Name gdrive:Folder\ Name
```

Got this after 4 hours:

```
runtime: failed to create new OS thread (have 2049 already; errno=12)
fatal error: runtime.newosproc

runtime stack:
runtime.throw(0x1a55b36, 0x11)
	/home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/panic.go:605 +0x95
runtime.newosproc(0xc423140000, 0xc42b94a000)
	/home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/os_darwin.go:127 +0x16b
runtime.newm(0x1a8c678, 0xc42001c000)
	/home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/proc.go:1647 +0x156
runtime.startm(0x0, 0xc42b911f01)
	/home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/proc.go:1718 +0x13f
runtime.wakep()
	/home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/proc.go:1799 +0x48
runtime.resetspinning()
	/home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/proc.go:2164 +0x71
runtime.schedule()
	/home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/proc.go:2252 +0x116
runtime.goexit0(0xc42b177980)
	/home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/proc.go:2396 +0x236
runtime.mcall(0xc4247f3a80)
	/home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/asm_amd64.s:286 +0x5b
```

The stack is quite longer. If you need it, please let me know.

**Comment by ncw** [comment] 2017-09-15 10:42
@Dave3o3 I suspect this is a different bug - it looks like something is leaking threads given that you have 2049 active!  I suspect the relatively new dropbox v2 backend. Can you make please make a [new issue on github](https://github.com/ncw/rclone/issues/new) please and if you do have the full backtrace can you attach it (I expect it to be massive).

Thanks

**Comment by Dave3o3** [comment] 2017-09-15 15:00
#1683
