### ISSUE TITLE
Backblaze: Implement CopyFile

### ISSUE THREAD

**Issue by dquintela** [ncw/rclone#3215] opened 2019-05-21 17:03 UTC
#### What is your current rclone version (output from `rclone version`)?

rclone v1.46
- os/arch: windows/amd64
- go version: go1.11

#### What problem are you are trying to solve?

rclone's "backblaze" backend doesn't implement CopyFile. Per #2539, this inhibits the possibility of file and folder renames/moves, specially when using "rclone mount"

#### How do you think rclone should be changed to solve that?

The "backend" should implement the operation using the APIs announced today [Backblaze B2 Copy File Beta is Now Public](https://www.backblaze.com/blog/backblaze-b2-copy-file-beta-is-now-public/), and in particular to #2539, permit "Call Copy then Delete on each file if available" as described in @ncw comment https://github.com/ncw/rclone/issues/2539#issuecomment-425704600

**Comment by dquintela** [comment] 2019-05-21 17:10
Relates / Duplicates #3184

**Comment by coltonrb** [comment] 2019-05-21 17:10
Duplicate of #3210

**Comment by dquintela** [comment] 2019-05-21 17:13
> Duplicate of #3210 ?

Seems soo.. And almost finished :)

**Comment by ncw** [comment] 2019-05-21 19:37
Yes this is a dupe.  Can you use the other issue - I'll close this one now, thanks.

**Closed by ncw** 2019-05-21 19:37 UTC
