### ISSUE TITLE
Idea to improve media playing performance from ACD (maybe useful in other clouds too)

### ISSUE THREAD

**Issue by NeoPhyTe-x360** [ncw/rclone#1043] opened 2017-01-17 20:00 UTC
We are some people that we use cloud storage to save some media files and bluray backups, and use plex (or other) to play our media BD. I've noticed the bad performance on plex _direct play_ (specially when we use acd), but the "good performance" when plex creates a "buffer" of X minutes when _transcode/direct stream_. (no freezes and fast start)

I don't know if it's possible because maybe apps do requests that can't be cached, but I'm gonna try to explain it.

There is possible to create a "read-buffer" when media is played in mount options? 
Don't know if this will affect to other type of file read/analyze media method, so I leave the experts to decide if it's viable to implement. (maybe we could limit buffers only to some media types mkv,avi....)

I suggest to create 3 values in **mounting** options to improve media playing and avoid freezes when play media:

1. **initial-read-buffer**   (in megabytes.....etc. this will be the initial buffer, until this buffer is full, the media won't play media files (mkv, avi, mp4, mpeg, etc), when initial buffer is full, the media will start the play)
2. **total-read-buffer** (the total buffer to use when a media is read, so you will be using this buffer, and while it will be fulfilled downloading from cloud)
3. **file-size-usebuffer**  (use read buffer when the file is >= tan 2G per example)

This maybe could be useful to people who use plex, emby, or direct play from the mount

Regards

**Comment by ncw** [comment] 2017-01-18 14:37
Thanks for your ideas.

I have experimented with buffering and it does make a difference, but it severely affects the seek performance.

rclone streams the data from acd so provided you don't seek, having lots of buffering works well.

However if you do seek, then rclone has to throw all the buffering away and re-open the https connection using a range request.  If you do lots of seeks (like some media players do at the start) rclone ends up downloading a lot of stuff that is thrown away which kills the performance.

What I should probably do is put the buffer option back and set a flag to control it.  2) and 3) of your list would be easy to do.  Not sure about 1) - that would be very detrimental to seeking.

**Comment by NeoPhyTe-x360** [comment] 2017-01-18 16:57
Nice, I hope to try it soon.

Thanks for your hard work

**Comment by scoopydude2002** [comment] 2017-01-19 08:08
@ncw Another possibility is the libfuse feature auto_cache. I currently use this with unionfs-fuse sitting on top of rclone mount. With this enabled, if there is no change to the file then the cache will not be flushed. When I play a file with Plex and then stop, and then resume, that portion of the video will not need to be downloaded again and will stream from the memory cache.

**Comment by endiz** [comment] 2017-01-19 13:25
@scoopydude2002 do you mind posting your unionfs mount command?

**Comment by ncw** [comment] 2017-01-19 13:30
@scoopydude2002 auto_cache sounds like a really good idea.

Looks like this is implemented in libfuse (which rclone doesn't use) rather than the kernel, so rclone can't use it directly :-(

**Comment by flixajki** [comment] 2017-01-19 13:33
Streaming wise the major improvement would be to cache whole file on disk, described here: https://github.com/ncw/rclone/issues/1050#issuecomment-273774075

As for above flags I dont really see the use of **initial-read-buffer** as if you dont have enough bandwith even if its precache let say 5 minutes you would eventually get stuck again and need to wait. 

The problem with storing some custom amounts of buffer in memory is you could end up without it quite soon. Iam having like 10 to 15 concurrent streams and using /dev/shm (50% of ram) as temp transcoder folder so I dont get any I/O problems, since most of videos are 8 to 20GB let say i would want at least 10% of average file to be precashed that would mean 1GB at least, so 10 users 10GB. 

With precashing the whole file on disk you dont have those kind of limits and the streaming would be much better. Since a lot of people have their Plex servers on fast connections the whole 8GB movie would be already precached within first 3 to 10 minutes. 

Sorry for offtopic its discussion for this topic: https://github.com/ncw/rclone/issues/1050#issuecomment-273774075

**Comment by NeoPhyTe-x360** [comment] 2017-01-19 13:55
Pleople like us have plex servers on fast connections but, ACD doesn't take the whole bandwidth to download a file, not at reading startup

I consider initial buffer is important only on ACD (slower init than drive). 

when you play media from acd, the initial connection never goes above 20-22mbps (I have 300/300), in the first 30 segs, so I always have a freeze at init of playing

**Comment by ncw** [comment] 2017-01-20 17:38
@NeoPhyTe-x360 re requests / second.  Can you make another issue about that please?  Link it to #485 which is a related idea.  It would be relatively easy to implement I think by limiting it in the http transport...

**Comment by scoopydude2002** [comment] 2017-01-22 07:21
@endiz My unionfs mount is fairly simple:
    uninofs-fuse mount -o cow,allow_other,**auto_cache**,statfs_omit_ro /media/local=rw:/media/acd=ro /media/union

**Comment by scoopydude2002** [comment] 2017-02-01 00:22
I think this idea is good, but there are multiple ways this can be done. I believe how [node-gdrive-fuse](https://github.com/thejinx0r/node-gdrive-fuse) implements it works well. It doesn't do whole-file caching, which I think is a waste of bandwidth and HD space. Instead it caches files in "chunks".

1. **chunkSize** - Size of each chunk to cache (8MB is a good starting point).
2. **advancedChunks** - Number of chunks ahead to cache (5 is a good start)
3. **maxCacheSize** - Max total of HD space using for file caching. This is used for all files. When the cache is full, the chunks that are oldest are deleted first.

When read file from a mount, rclone should try to see if that chunk exists locally first and only download chunks that are required but missing from local cache.

node-gdrive-fuse stores the files as in a folder with filename: filename-chunkXXX-ZZZZ (not quite sure where it stores the directory info). The chunk informations should probably have to be stored in a DB.

**Comment by endiz** [comment] 2017-02-01 03:31
Thanks @scoopydude2002 i've added the auto-cache option to my unionfs mount.

I agree, the chunking method above seems efficient. I'm assuming the chunk info could be stored locally in an sqlite database similar to acdcli.

**Comment by ncw** [comment] 2017-02-14 23:15
OK, try this beta.  You can control the size of the buffer for each transfer with `--buffer-size`.  It may be a disaster for seeking - let me know!

    http://beta.rclone.org/v1.35-98-g9a9d098/ (uploaded in 15-30 mins)

**Comment by jjmares** [comment] 2017-02-15 10:02
--buffer-size works for mount?

how we must use it? --buffer-size 1024 for example? Its 1024 bits, bytes...?

THANKS!

**Comment by ncw** [comment] 2017-02-15 21:07
For those in doubt, `--buffer-size` takes a number followed by `k`, `M`, or `G`.  IIf you leave the number out it is in `k`.  This is the same as all the other [SIZE parameters](http://rclone.org/docs/#options)

**Comment by ncw** [comment] 2017-02-15 23:01
I've just realised that I wasn't re-applying the buffer after a seek...

So can you try this beta please

http://beta.rclone.org/v1.35-101-gf15c6b6/ (uploaded in 15-30 mins)

**Comment by ajkis** [comment] 2017-02-16 20:08
@ncw Does the buffer-size for mount applied per file or overall ?

**Comment by ncw** [comment] 2017-02-17 09:21
OK here is what I hope is a final tweak (for 1.36 at least) on buffer sizes.

This does a soft start, which greatly improves seeking, and fixes the mis-use of the seek interface.  Together those changes bring it back to 1.35 performance, but with buffering.

http://beta.rclone.org/v1.35-113-g033d1eb/ (uploaded in 15-30 mins)

**Comment by ajkis** [comment] 2017-02-17 13:48
Iam testing atm with latest version 116 and its working far better with 0 buffer.

**Comment by NeoPhyTe-x360** [comment] 2017-02-17 19:55
@ncw latest beta link doesn't work, so I can't try v1.35-113 release. Can you reupload?

**Comment by NeoPhyTe-x360** [comment] 2017-02-17 20:39
117 release tested a bit. For the moment direct play is freezing after a 10 seconds from play, and not restarting (plex), I don't know if it's working because sometimes it's not playing anything after a minute (loading but not playing).

mount:
rclone mount amazon: /media/amazon --allow-non-empty --allow-other --no-check-certificate --buffer-size 128M --max-read-ahead 128M --transfers 4 --dir-cache-time 30m --checkers 12 --uid 128 --gid 135 --umask 000 &

**Comment by endiz** [comment] 2017-02-17 20:48
@NeoPhyTe-x360 have you tried without the mount options? I know @ncw tweaked the acd mount in 1.35 so we didn't have to include most of those flags.

i recommend simply trying "rclone mount amazon: /media/amazon --allow-non-empty --allow-other --uid 128 --gid 135 --umask 000 &"

I would love to try the beta but unfortunately i'm out of the country for a few weeks =/

**Comment by NeoPhyTe-x360** [comment] 2017-02-17 20:53
@endiz  tested without these other flags but the same happens.

I see connection downloading at 36MB/s but the play sometimes doesn't start (128mb buffer at 300mbps doesn't take more than a few seconds to fill). When it start (maybe 5/10 times), it freezes after 10-30 segs, and won't play anymore

**Comment by endiz** [comment] 2017-02-17 21:01
Try a 500MB buffer?

**Comment by NeoPhyTe-x360** [comment] 2017-02-17 21:04
@endiz tried 384M but the same happens (now I'm trying 98 release, and it takes more time to became frozen (2-3min) in the first play, in the second play freeze happens at 10 seconds. Not play after the freezes

**Comment by NeoPhyTe-x360** [comment] 2017-02-18 08:25
@ncw , noticing the rclone is maintaining in memory the buffer for about 1-2min, so maybe the problems comes from there. 
If you start to read a file, buffer fills in memory and play fast, you stop the file copy/read, and the buffer stills there for about 1-2minutes, so, if you play the second one in the first 5minutes, the play starts very very slow. The problem is that's not ocurring every time, only sometimes.

Could be a problem related with IO writting? It is possible to writte buffer in disk (/tmp or somewhere) instead on kernel buffer? (I don't know where is written now, but I don't see anything new in /tmp)

**Comment by ncw** [comment] 2017-02-18 12:40
@NeoPhyTe-x360 - thanks for all your testing.

> I'm seeing that on the first play after mount, the performance is almost perfect, but the rest of the plays after that, are very very slow to load, and sometimes not loading anything

Playing the same file or a different one?

Can you do some tests with the latest beta? http://beta.rclone.org/v1.35-123-g6e0e1ad/

I'd like to see -123 with `--buffer-size 128M` (say) and `--buffer-size 0` and also a comparison with 1.35.

I think one of the problems with testing with ACD is that it is very variable in performance.  Sometimes it doesn't even deliver enough bandwidth for streaming so if you could repeat each test as many times as possible that would be useful.

**Comment by NeoPhyTe-x360** [comment] 2017-02-18 13:04
@ncw 
> Playing the same file or a different one?
Different ones (to avoid if buffer is saved somewhere)

Gonna test new version, later I'll edit the post

**Comment by ncw** [comment] 2017-02-20 16:20
@NeoPhyTe-x360 thanks for testing.  That is a huge amount of variability :-(  I suspect ACD is introducing the variability, so testing with Google Drive would be very interesting.

Are you using the `--no-seek` flag?  I would hope that it would work well without the `--no-seek` flag. Using the `--no-seek` flag might be the cause of some of the freezing but not restarting if the player can't rewind the stream.  Not sure how the player will respond to the errors it gets back when it tries to seek.

**Comment by ncw** [comment] 2017-03-01 17:07
I'm going to close this issue now as I think the general consensus is that the changes work reasonably well.

There is undoubtedly more work to do though with buffering!

**Closed by ncw** 2017-03-01 17:07 UTC
Labels: enhancement

**Comment by NeoPhyTe-x360** [comment] 2017-03-03 16:31
@ncw thanks for your hard work. I was very busy this weeks, so I could't try more than I tried that day. I will try more once I have a bit time, so I haven't used plex neither.

Thanks
