### ISSUE TITLE
Max Transfer

### ISSUE THREAD

**Issue by ColeMundus** [ncw/rclone#1940] opened 2017-12-24 02:57 UTC
It would be very useful if there was a `--max-transfer` flag for specifying the max amount to transfer. I can think of things like:

- Scripting remote switching
- Avoiding quota (Transfer 500GB to allow 250GB for uploading other things)
- Knowing when transfer is done (Instead of leaving it to sit for hours transferring at 0 B/s)

I know I can use bw limit but that does not serve the same purpose something like a `--max-transfer` flag would

**Comment by zenjabba** [comment] 2017-12-24 03:24
Max transfers within what period though? The issue with this options is it needs to keep track of each endpoint and then timeframe against each endpoint.

**Comment by ColeMundus** [comment] 2017-12-24 03:51
Just for that session. No need to keep track of it or anything, just stop rclone once it's transferred the specified amount of data

**Comment by ncw** [comment] 2018-01-05 15:38
That would be relatively easy to implement I think..

**Comment by ncw** [comment] 2018-01-05 15:41
Actaully this is a duplicate of #1599 - so I'm going to close this one - please add any comments to that issue - thanks.

**Closed by ncw** 2018-01-05 15:41 UTC
Labels: enhancement
