### ISSUE TITLE
SFTP Upload does not work with synology diskstation

### ISSUE THREAD

**Issue by mineyannik** [ncw/rclone#1474] opened 2017-06-11 09:11 UTC
> What is your rclone version (eg output from `rclone -V`)
1.36

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 64 bit

> Which cloud storage system are you using? (eg Google Drive)
SFTP

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`mineyannik@s4:~/backup$ /usr/sbin/rclone copy minecraft.zip remote:SemperCraft/Backup/S4/1 -vv`

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
2017/06/11 11:09:11 DEBUG : rclone: Version "v1.36" starting with parameters ["/usr/sbin/rclone" "copy" "minecraft.zip" "remote:SemperCraft/Backup/S4/1" "-vv"]
2017/06/11 11:09:12 INFO  : sftp://sempercraft@**:22/SemperCraft/Backup/S4/1: Modify window is 1s
2017/06/11 11:09:12 ERROR : Attempt 1/3 failed with 1 errors and: mkdir dirExists failed: dirExists stat failed: EOF
2017/06/11 11:09:12 ERROR : Attempt 2/3 failed with 1 errors and: mkdir dirExists failed: dirExists stat failed: failed to send packet header: EOF
2017/06/11 11:09:12 ERROR : Attempt 3/3 failed with 1 errors and: mkdir dirExists failed: dirExists stat failed: failed to send packet header: EOF
2017/06/11 11:09:12 Failed to copy: mkdir dirExists failed: dirExists stat failed: failed to send packet header: EOF
```

**Comment by ncw** [comment] 2017-06-11 10:27
Which SFTP server are you using?  It looks like it is having a problem with something rclone is doing.

Can you also try with the latest beta from https://beta.rclone.org please?

**Comment by mineyannik** [comment] 2017-06-11 10:28
It is the default sftp server of my synology diskstation.

**Comment by mineyannik** [comment] 2017-06-11 10:31
It's the same error with the latest beta.
```
2017/06/11 12:30:38 DEBUG : rclone: Version "v1.36-170-g2ca477c5β" starting with parameters ["/usr/sbin/rclone" "copy" "minecraft.zip" "remote:SemperCraft/Backup/S4/1" "-vv"]
2017/06/11 12:30:40 INFO  : sftp://sempercraft@**:22/SemperCraft/Backup/S4/1: Modify window is 1s
2017/06/11 12:30:40 ERROR : Attempt 1/3 failed with 1 errors and: mkdir dirExists failed: dirExists stat failed: EOF
2017/06/11 12:30:40 ERROR : Attempt 2/3 failed with 1 errors and: mkdir dirExists failed: dirExists stat failed: failed to send packet header: EOF
2017/06/11 12:30:40 ERROR : Attempt 3/3 failed with 1 errors and: mkdir dirExists failed: dirExists stat failed: failed to send packet header: EOF
2017/06/11 12:30:40 Failed to copy: mkdir dirExists failed: dirExists stat failed: failed to send packet header: EOF
```

**Comment by piotrekoo** [comment] 2017-07-05 13:56
I'm having the same problem not only when uploading, but also when downloading via SFTP from Synology. Transfering using WinSCP is flawless though.
Synology DSM runs internal-sftp of OpenSSH.

**Comment by Ossssip** [comment] 2017-11-13 14:36
Hi, I am not a user of rclone, but I had the same problem with a Synology NAS sftp and [duplicacy](https://github.com/gilbertchen/duplicacy), an open source backup tool. I have found out that duplicacy works just fine if absolute path is provided (with double slash between the hostname and  the directory, like sftp://user@server:port//directory).

**Comment by ncw** [comment] 2017-11-15 12:22
@Ossssip - good tip.  Can @mineyannik and @piotrekoo give that a go?

So in rclone speak you would try transferring with `remote:/full/path/to/file` rather than `remote:file`

**Comment by mineyannik** [comment] 2017-11-15 16:36
Sorry but i do not use this combination anymore

Nick Craig-Wood <notifications@github.com> schrieb am Mi., 15. Nov. 2017,
13:22:

**Comment by blevins321** [comment] 2018-04-15 04:58
I was having this problem with the current regular release and stumbled upon this thread. It wouldn't happen every time, but after a dozen or so successful transfers, one would trigger this error and cause all the other running threads to stop transferring.

Extremely simple fix: Just put a / at the beginning of the path. Not the entire root path, just a slash at the beginning.

sftp:Plex/TV Shows   becomes sftp:/Plex/TV Shows and all is well.

**Comment by ncw** [comment] 2018-04-15 22:09
@blevins321 thanks for the analysis.

That kind of implies a bug in rclone.

Can you try to get a reproducible way of getting the error? If you can do that I can probably fix it!

What SFTP server are you using?

**Comment by piotrekoo** [comment] 2018-04-18 13:06
I can reproduce it on my Synology running an OpenSSH server.
Putting a / at the beginning of the path fixes file transfer but breaks checksum calculation. I'll check this evening if it's by any chance related to the config file.

**Comment by piotrekoo** [comment] 2018-04-18 19:25
The directory tree in Synology is not the same for SSH and SFTP.
SFTP lists only _Shared Folders_ in `/` and doesn't start in user's home directory. When SSHing to Synology those folders can be found in `/volume[1,2,..]/`. That's why the checksum calculation breaks I suppose.
The log: [issue1474-1.log.gz](https://github.com/ncw/rclone/files/1925518/issue1474-1.log.gz)

**Comment by ncw** [comment] 2018-04-19 10:12
Oops that build failed - try this one:

https://beta.rclone.org/v1.40-095-g350b3c03-fix-1474-sftp-hash/ (uploaded in 15-30 mins)

**Comment by ncw** [comment] 2018-04-21 08:04
I've merged this to master in

https://beta.rclone.org/v1.40-111-g870c58f7/ (uploaded in 15-30 mins)

which will be in [the latest beta](https://beta.rclone.org) and 1.41

**Closed** 2018-04-21 08:04 UTC
Labels: Remote SFTP, bug, doc fix

**Comment by piotrekoo** [comment] 2018-04-25 11:15
@ncw Tested, but forgot to send the log. Sorry. [issue1474-2.log.gz](https://github.com/ncw/rclone/files/1946681/issue1474-2.log.gz)

I think the only way to make hash calc working for synology boxes is to introduce an option allowing user to specify a ssh path
I'll try coding it this week. My go skills are rather non-existent but the code doesn't look complicated

**Comment by ncw** [comment] 2018-04-25 14:01
@piotrekoo thanks for the log.  The error does look sensible :-)

> I think the only way to make hash calc working for synology boxes is to introduce an option allowing user to specify a ssh path

That is a good idea.  So a new config variable for the whole path for the ssh commands.

> I'll try coding it this week. My go skills are rather non-existent but the code doesn't look complicated

If you've ever programmed in C or a descendant language (Java, C# etc) go is really pretty easy!

**Comment by ncw** [comment] 2018-04-30 16:31
The --ssh-path-override will be here

https://beta.rclone.org/v1.41-006-g31162496/ (uploaded in 15-30 mins)

and in [the latest beta](https://beta.rclone.org) from now on and in [the latest beta](https://beta.rclone.org).

**Comment by curious-jim** [comment] 2018-11-04 06:12
was this option removed in new version? I was using 1.42 for a while and it worked, but today I needed to setup another backup and I downloaded the latest 1.44 and I got:

> Fatal error: unknown flag: --ssh-path-override
> Error: unknown flag: --ssh-path-override

downgrade to 1.42 fixed the issue

**Comment by ncw** [comment] 2018-11-04 12:17
The parameter is this

      --sftp-path-override string   Override path used by SSH connection.

It got renamed in the backend config unification - sorry I missed that out the changelog.  However you can now store it in the config file too (config with the advanced options) which you should find useful as `path_override`.

**Comment by KrLx1994roller** [comment] 2019-11-16 00:03
> Hi, I am not a user of rclone, but I had the same problem with a Synology NAS sftp and [duplicacy](https://github.com/gilbertchen/duplicacy), an open source backup tool. I have found out that duplicacy works just fine if absolute path is provided (with double slash between the hostname and the directory, like sftp://user@server:port//directory).

I've been having disconnection, EOF, dirExists stat failed issues nonstop when trying to sync files to a Synology NAS. I found this thread and tried using `--sftp-path-override string` and I could not make it work.

After carefully reading every single comment, I started trying everything and this has been the only solution. Just adding an extra `/` right after the port. The remote, when pointing to the user's home directory, should look like this `serversandboxcrypt:/home/`. The `/` right after the colon made the magic!

Thank you very much @Ossssip !!! <3

**Comment by ncw** [comment] 2019-11-16 16:51
@KrLx1994roller I'm sorry this took you a while to work out.  It does say this [in the docs](https://rclone.org/sftp/) though!

> “Note that some SFTP servers will need the leading / - Synology is a good example of this. rsync.net, on the other hand, requires users to OMIT the leading /.

**Comment by KrLx1994roller** [comment] 2019-11-16 18:14
@ncw No problem! There's a lot of information everywhere and it was actually my fault as I was using an encrypted remote and I focused on the encrypt documentation, I didn't think about the STFP one :( I guess working late in the evening is not good for clear thinking hahah. Thanks for the effort and the awesome tool :)
