### ISSUE TITLE
Unable to add OneDrive account information.

### ISSUE THREAD

**Issue by zixinglovecn** [ncw/rclone#687] opened 2016-09-06 16:31 UTC
Suspected "Redirect URIs" set error.

When the "Redirect URIs" is set to "http://localhost.rclone.org:53682/",
Browser tip: `No code found returned by remote server.`

When the "Redirect URIs" is set to "http://localhost:53682"
Browser display success, but the program shows that to configure token: 

```
Failed to configure token: failed to get token: oauth2: cannot fetch token: 400 Bad Request
Response:“ {"error":"invalid_grant","error_description":"The provided value for the 'redirect_uri' is not valid. The value must exactly match the redirect URI used to obtain the authorization code."}
```

I was a rookie, I really do not know how to solve, and I hope to get help.

Program generated URLs:
`https://login.live.com/oauth20_authorize.srf?client_id=c6080499-42e8-42d8-b0bf-40ef0bf7b02a&redirect_uri=http%3A%2F%2Flocalhost.rclone.org%3A53682%2F&response_type=code&scope=wl.signin+wl.offline_access+onedrive.readwrite&state=b3b8a74b517a8dc1f3dbb4d8a19ca36e`

**Comment by zixinglovecn** [comment] 2016-09-07 14:13
anybody help me?

**Comment by ncw** [comment] 2016-09-07 21:59
localhost.rclone.org is set to resolve to 127.0.0.1

what do you see if you do this (assuming you are using Windows, if using Linux/OS X then use `ping6` instead of `ping -6`)

    ping localhost.rclone.org
    ping -6 localhost.rclone.org

Which really should work, unless maybe your computer is IPv6 only?

I added an IPv6 address to localhost.rclone.org of `::1` too.

Does that help?

**Comment by ncw** [comment] 2016-09-07 22:00
Also it might be that you don't have the localhost interface set up.  You'll need to tell me which OS you are using if you want help with that!

**Comment by zixinglovecn** [comment] 2016-09-08 00:50
I test `ping localhost.rclone.org`
Can be Ping to 127.0.0.1
May be the problem of my machine settings。
OS: `Windows Server 2003; Windows Server 2008; Windows 10`

**Comment by ncw** [comment] 2017-01-09 17:31
Did you make this work?

**Comment by ncw** [comment] 2017-04-25 09:28
I've changed the onedrive code to use  "http://localhost:53682" so this should be fixed now.

Please try https://beta.rclone.org/v1.36-41-gb651784/ and re-open if the issue is still present.

**Closed by ncw** 2017-04-25 09:28 UTC

**Comment by rvkooten** [comment] 2017-09-24 17:59
When using rclone v1.37 i see with the onedrive config in the browser this URL with an error

https://login.live.com/err.srf?lc=1033#error=invalid_request&error_description=The+provided+value+for+the+input+parameter+%27redirect_uri%27+is+not+valid.+The+expected+value+is+%27https://login.live.com/oauth20_desktop.srf%27+or+a+URL+which+matches+the+redirect+URI+registered+for+this+client+application
