### ISSUE TITLE
How "crypt" folder handle non-repeating errors (e.g. network timeout)

### ISSUE THREAD

**Issue by lsching17** [ncw/rclone#702] opened 2016-09-08 11:35 UTC
rclone v1.33, Windows 7 x64. Amazon cloud drive

i have a "crypt" folder (standard encryption) on Amazon cloud drive.

I uploaded and then download (both by "sync" command) for verification

several files failed with message "Failed to copy: failed to authenicate decrypted block - bad password?"

When i restart the download process, the files can be successfully downloaded.

Do "crypt" folder retried automatically like other cloud drive for non-repeating errors (e.g. network timeout)?

**Comment by ncw** [comment] 2016-09-08 14:26
Yes crypt should retry files under control of the `--retries` and `--low-level-retries` flags as normal.

That particular error `Failed to copy: failed to authenicate decrypted block - bad password?` I think is caused by a broken network connection rather than an actual corruption.

**Comment by lsching17** [comment] 2016-09-08 20:03
Does checksum error belong to high-level retries or low level retries?

Could this be fixed? actually Checksum error<>network error, and it is very misleading.

**Comment by ncw** [comment] 2016-09-08 20:30
That error will probably be a high level retry. 

Yes I will fix the misleading error.

**Comment by ncw** [comment] 2017-01-09 17:29
The misleading error has now been fixed so I'm going to close this.

**Closed by ncw** 2017-01-09 17:29 UTC
