### ISSUE TITLE
ACD "Only one auth mechanism allowed" errors

### ISSUE THREAD

**Issue by dzg** [ncw/rclone#1501] opened 2017-06-25 09:38 UTC
> What is your rclone version (eg output from `rclone -V`)

v1.36-209-gb44d0ea0 

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows Server 2016 

> Which cloud storage system are you using? (eg Google Drive)

acd, Google drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone copy acd: gd:

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Using the proxy method from https://forum.rclone.org/t/proxy-for-amazon-cloud-drive/2848/52

-vv shows:

`DEBUG : pacer: low level retry 2/10 (error HTTP code 400: "400 Bad Request": response body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidArgument</Code><Message>Only one auth mechanism allowed; only the X-Amz-Algorithm query parameter, Signature query string parameter or the Authorization header should be specified</Message><ArgumentName>Authorization</ArgumentName><ArgumentValue>Bearer Atza|...</ArgumentValue><RequestId>...</RequestId><HostId>...</HostId></Error>")`

And no transfer occurs.

**Comment by giacomofabbri** [comment] 2017-06-25 16:34
I have the same error! I'm using the latest beta and Ubuntu 64-bit, mounting acd it works for some time then it became unresponsive. But if I try rclone lsd acd:/ it shows me the root folder!! Thanks and I hope that you can help us

**Comment by ncw** [comment] 2017-06-25 16:35
I thought I'd fixed that issue... I think it is caused by transferring big files greater than the temp link threshold.

I wonder it is was reintroduced by go 1.8 which changed something in that area.

So what size are the files that give the error?

**Comment by qw3rty2017** [comment] 2017-06-25 18:29
It seems to be related to filesize indeed. I tested a 2GB file and it worked, while a 5 GB file gave me the error mentioned before.

**Comment by giacomofabbri** [comment] 2017-06-25 18:39
In my case actually after sometimes the mount option stop working, but looking at the log I got the same error as OP! Please help me

**Comment by ncw** [comment] 2017-06-26 09:16
I have an idea what is happening here - can you try using `--acd-templink-threshold 0` and see if that works around the problem?

What I think is happening is that files above a certain size are being redirected - but rclone is supplying the `Authorization` header on redirect.  I fixed this problem for the templink case already so the above might be a work around.  If it does work around the problem I know how to fix it properly.

**Comment by qw3rty2017** [comment] 2017-06-26 09:44
Nice! `--acd-templink-threshold 0` fixed it.

**Comment by dzg** [comment] 2017-06-26 09:53
OMG thank you! You just saved me days of work!

**Comment by ncw** [comment] 2017-06-27 18:50
I'm going to re-open this as I need to fix it properly!

**Comment by meiskam** [comment] 2017-10-08 23:58
having the same problem, copying files from acd to gdrive, version: rclone v1.38 linux/amd64 .. `--acd-templink-threshold 0` workaround seems to have helped

**Comment by ncw** [comment] 2017-11-24 10:12
I've now fixed this here

https://beta.rclone.org/v1.38-186-g6448c445/

**Closed** 2017-11-24 10:11 UTC
Labels: bug, IMPORTANT

**Comment by valentine** [comment] 2017-11-29 12:32
Encountered this problem with the stable version too; it's working in practice and returning:
> DEBUG : Removing Authorization: header after redirect to S3

I'm guessing that's all good?

**Comment by ncw** [comment] 2017-11-29 18:17
@valentine yes that is working now. Thanks for testing.
