### ISSUE TITLE
Unable to login into mega

### ISSUE THREAD

**Issue by yiiTT** [ncw/rclone#2771] opened 2018-11-25 21:54 UTC
#### What is the problem you are having with rclone?
Unable to login into mega

#### What is your rclone version (output from `rclone version`)
v1.45

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10 64bit

####  Which cloud storage system are you using? (eg Google Drive)
Mega

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone ls mega1:`
`rclone ls :mega: --mega-user username --mega-pass obscure_pass` has the same issue
(account works with the official MEGAcmd)

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
2018/11/25 15:45:26 DEBUG : rclone: Version "v1.45" starting with parameters ["rclone" "ls" "mega1:" "--mega-debug" "-vv" "--dump" "bodies"]
2018/11/25 15:45:26 DEBUG : Using config file from "C:\\Users\\hidden\\.config\\rclone\\rclone.conf"
2018/11/25 15:45:26 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2018/11/25 15:45:26 DEBUG : HTTP REQUEST (req 0xc000474b00)
2018/11/25 15:45:26 DEBUG : POST /cs?id=hidden HTTP/1.1
Host: g.api.mega.co.nz
User-Agent: rclone/v1.45
Content-Length: 73
Content-Type: application/json
Accept-Encoding: gzip

[{"a":"us","user":"hidden","uh":"hidden"}]
2018/11/25 15:45:26 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2018/11/25 15:45:27 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2018/11/25 15:45:27 DEBUG : HTTP RESPONSE (req 0xc000474b00)
2018/11/25 15:45:27 DEBUG : HTTP/1.1 200 OK
Content-Length: 4
Access-Control-Allow-Headers: Content-Type, MEGA-Chrome-Antileak
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Original-Content-Length
Access-Control-Max-Age: 86400
Connection: keep-alive
Content-Type: application/json
Original-Content-Length: 4

[-8]
2018/11/25 15:45:27 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2018/11/25 15:45:27 Failed to create file system for "mega1:": couldn't login: The upload target URL you are trying to access has expired. Please request a fresh one
```

**Comment by ncw** [comment] 2018-11-29 12:45
Thanks for making an issue about this.  The underlying library needs fixing.

This is due to a change in the way logins are done for new mega accounts.

This is the corresponding change in the mega code
https://github.com/meganz/sdk/pull/1278

And here are some helpful discussions https://github.com/meganz/MEGAcmd/issues/121

I hope to have time to look at this at the weekend.

**Comment by gyunter** [comment] 2019-01-11 14:19
I can confirm it's currently impossible to use Mega.nz from within `rclone` on MacOS aswell:
```
$ rclone -vv lsd mega-gyunter:
2019/01/11 17:17:32 DEBUG : rclone: Version "v1.45" starting with parameters ["rclone" "-vv" "lsd" "mega-gyunter:"]
2019/01/11 17:17:32 DEBUG : Using config file from "/Users/gyunter/.config/rclone/rclone.conf"
2019/01/11 17:17:32 Failed to create file system for "mega-gyunter:": couldn't login: Unknown mega error -26
```

**Comment by star191** [comment] 2019-01-19 19:36
Same

`
Failed to create file system for "mega:": couldn't login: The upload target URL you are trying to access has expired. Please request a fresh one
`

I hope this bug will be fixed after all

**Comment by c-edw** [comment] 2019-01-20 03:47
Disabling 2FA did not fix this for me. I read something about MEGA changing it's APIs. I will look into fixing this tomorrow morning.

**Comment by star191** [comment] 2019-01-21 08:20
@c-edw 
Is there any progress? :3

**Comment by ncw** [comment] 2019-01-21 17:54
@c-edw I'd love to have some help with this!  I keep not having enough time :-(

Here is what I wrote above

> The underlying library needs fixing.
> 
> This is due to a change in the way logins are done for new mega accounts.
> 
> This is the corresponding change in the mega code
> [meganz/sdk#1278](https://github.com/meganz/sdk/pull/1278)
> 
> And here are some helpful discussions [meganz/MEGAcmd#121](https://github.com/meganz/MEGAcmd/issues/121)

Note it is likely that the fix will need to be in this library https://github.com/t3rm1n4l/go-mega (which I am also a maintainer of).

**Comment by c-edw** [comment] 2019-01-21 18:02
Sorry, I completely forgot. The issue seems to be with the `Login` function in go-mega (see [here](https://github.com/t3rm1n4l/go-mega/blob/854bf31d998b151cf5f94529c815bc4c67322949/mega.go#L461)). The computed `Handle` is different to what MEGA expects so the login fails and it throws EEXPIRED for some reason. 
I will try to reverse engineer the MEGA client JavaScript code a bit, but it's an absolute mess and isn't well documented.
@t3rm1n4l.

**Comment by ncw** [comment] 2019-01-22 09:49
@c-edw wrote: 
> Sorry, I completely forgot. The issue seems to be with the `Login` function in go-mega (see [here](https://github.com/t3rm1n4l/go-mega/blob/854bf31d998b151cf5f94529c815bc4c67322949/mega.go#L461)). The computed `Handle` is different to what MEGA expects so the login fails and it throws EEXPIRED for some reason.
> I will try to reverse engineer the MEGA client JavaScript code a bit, but it's an absolute mess and isn't well documented.

Indeed!  I found the C++ SDK slightly easier to read but that might just be me...

https://github.com/meganz/sdk

**Comment by barrio** [comment] 2019-01-26 21:33
I have one mega account that throws this error and another that works just fine one the very same machine...

**Comment by ncw** [comment] 2019-01-27 12:08
> I have one mega account that throws this error and another that works just fine one the very same machine...

I think it is all mega accounts created after a certain date that have the problem.

**Comment by gyunter** [comment] 2019-01-31 18:34
https://github.com/ncw/rclone/issues/2771#issuecomment-453531051

If this info somehow useful: my account was created in 2013.

**Comment by star191** [comment] 2019-02-03 10:52
Ah, are there any good news?

**Comment by ncw** [comment] 2019-02-04 17:36
I've had a go at fixing this.  It works for my old account and a new one I created.

Please give this a go and report back - thanks!

https://beta.rclone.org/branch/v1.45-172-g7d5d6c04-fix-2771-mega-login-beta/ (uploaded in 15-30 mins)

**Comment by HaydenKow** [comment] 2019-02-05 01:12
> I've had a go at fixing this. It works for my old account and a new one I created.
> 
> Please give this a go and report back - thanks!
> 
> https://beta.rclone.org/branch/v1.45-172-g7d5d6c04-fix-2771-mega-login-beta/ (uploaded in 15-30 mins)

did not work on the windows x64 build. same error

```
2019/02/04 20:11:16 Failed to create file system for "mega2:": couldn't login: Object (typically, node or user) not found
```

**Comment by ncw** [comment] 2019-02-05 08:07
@HaydenKow this fix fixes this error
> couldn't login: The upload target URL you are trying to access has expired. Please request a fresh one

You are getting a different error `Object (typically, node or user) not found`.  That kind of indicates that your email address / password is wrong somehow.

**Comment by mrkingmidas** [comment] 2019-02-05 11:38
> I've had a go at fixing this. It works for my old account and a new one I created.
> 
> Please give this a go and report back - thanks!
> 
> https://beta.rclone.org/branch/v1.45-172-g7d5d6c04-fix-2771-mega-login-beta/ (uploaded in 15-30 mins)

Hi! I am test now - my account "1 month age" work's!

**Comment by ncw** [comment] 2019-02-05 13:53
Thanks for testing :-)

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.46

**Closed** 2019-02-05 13:53 UTC
Labels: Remote: Mega, bug

**Comment by agent0404** [comment] 2019-02-05 14:57
still aint working for my mega account from 2014. i've just started using rclone and it's working great with all my other accounts

```
rclone-v1.45-172-g7d5d6c04-fix-2771-mega-login-beta-linux-amd64 ./rclone lsd mega:
2019/02/05 09:38:31 Failed to create file system for "mega:": couldn't login: Unknown mega error -26

rclone-v1.45-172-g7d5d6c04-fix-2771-mega-login-beta-linux-amd64 ./rclone version  
rclone v1.45-172-g7d5d6c04-fix-2771-mega-login-beta
- os/arch: linux/amd64
- go version: go1.11.5
```

**Comment by ncw** [comment] 2019-02-05 17:11
@agent0404 I think that error is "Multi-factor authentication required" - rclone doesn't support multi factor auth yet.

**Comment by ncw** [comment] 2019-02-05 17:23
> @agent0404 I think that error is "Multi-factor authentication required" - rclone doesn't support multi factor auth yet.

I just updated the error codes in the mega backend so that will say something a bit more sensible!

**Comment by barrio** [comment] 2019-02-05 19:18
I can confirm the patch works for my approx. 6 month old mega account.
TNX a lot for fixing this quickly!

**Comment by dev-techmoe** [comment] 2019-02-07 11:07
> I've had a go at fixing this. It works for my old account and a new one I created.
> 
> Please give this a go and report back - thanks!
> 
> https://beta.rclone.org/branch/v1.45-172-g7d5d6c04-fix-2771-mega-login-beta/ (uploaded in 15-30 mins)

stable version has the same problem in my environment
and this work perfectly, thx

**Comment by star191** [comment] 2019-02-07 11:27
> 
> 
> I've had a go at fixing this. It works for my old account and a new one I created.
> 
> Please give this a go and report back - thanks!
> 
> https://beta.rclone.org/branch/v1.45-172-g7d5d6c04-fix-2771-mega-login-beta/ (uploaded in 15-30 mins)

Thanx! <3

**Comment by trejo08** [comment] 2019-02-10 06:57
> I've had a go at fixing this. It works for my old account and a new one I created.
> 
> Please give this a go and report back - thanks!
> 
> https://beta.rclone.org/branch/v1.45-172-g7d5d6c04-fix-2771-mega-login-beta/ (uploaded in 15-30 mins)

I updated my version and works for me, Thanks

**Comment by ncw** [comment] 2019-02-10 21:16
This fix went into 1.46 which has just been released

**Comment by Anagastes** [comment] 2019-05-02 15:31
I also have a lot of problems registering.

- rclone v1.47.0
- os/arch: linux/amd64 (debian)
- go version: go1.12.4

 rclone lsd HOST: --mega-debug -vv                                                                                                                                                                                                         1 ↵  5673  17:19:46  
2019/05/02 17:23:52 DEBUG : rclone: Version "v1.47.0" starting with parameters ["rclone" "lsd" "HOST:" "--mega-debug" "-vv"]
2019/05/02 17:23:52 DEBUG : Using config file from "/home/USER/.config/rclone/rclone.conf"
2019/05/02 17:23:52 DEBUG : *go-mega*: Retry API request 1/10: Try again
2019/05/02 17:23:52 DEBUG : *go-mega*: Retry API request 2/10: Try again
2019/05/02 17:23:52 DEBUG : *go-mega*: Retry API request 3/10: Try again
2019/05/02 17:23:52 DEBUG : *go-mega*: Retry API request 4/10: Try again
2019/05/02 17:23:52 DEBUG : *go-mega*: Retry API request 5/10: Try again
2019/05/02 17:23:52 DEBUG : *go-mega*: Retry API request 6/10: Try again
2019/05/02 17:23:53 DEBUG : *go-mega*: Retry API request 7/10: Try again
2019/05/02 17:23:53 DEBUG : *go-mega*: Retry API request 8/10: Try again
2019/05/02 17:23:55 DEBUG : *go-mega*: Retry API request 9/10: Try again
2019/05/02 17:23:57 DEBUG : *go-mega*: Retry API request 10/10: Try again
2019/05/02 17:24:02 Failed to create file system for "HOST:": couldn't login: Try again

Normal login via the client works fine. Also on the website.

Any idea?

**Comment by bingoxo** [comment] 2019-05-03 22:32
> @agent0404 I think that error is "Multi-factor authentication required" - rclone doesn't support multi factor auth yet.

any eta for this :) ?

**Comment by imnotender** [comment] 2020-05-25 21:58
Hi, new here.
It's been more than a year since the last message here so sorry for the necroing.
Are there any plans to fixing the "Multi-factor authentication required" problem?
Thanks in advance

**Comment by GiganticThirstyHerald** [comment] 2021-03-23 01:52
It's been almost a year since mentioning this problem last time, but it's still unresolved

**Comment by ncw** [comment] 2021-03-23 08:16
I need to find someone to work on this - are you interested @GiganticThirstyHerald ?

**Comment by Llewellynvdm** [comment] 2021-03-27 00:28
We just today had this issue re-survived:
```
ubuntu@ip-xxx-xx-x-xx:~$ rclone lsd --mega-debug mega: -vv
2021/03/27 00:14:27 DEBUG : rclone: Version "v1.54.1" starting with parameters ["rclone" "lsd" "--mega-debug" "mega:" "-vv"]
Enter configuration password:
password:
2021/03/27 00:14:33 DEBUG : Using config file from "/home/ubuntu/.config/rclone/rclone.conf"
2021/03/27 00:14:33 DEBUG : Creating backend with remote "mega:"
2021/03/27 00:14:35 DEBUG : *go-mega*: Retry API request 1/10: Try again
2021/03/27 00:14:35 DEBUG : *go-mega*: Retry API request 2/10: Try again
2021/03/27 00:14:35 DEBUG : *go-mega*: Retry API request 3/10: Try again
2021/03/27 00:14:36 DEBUG : *go-mega*: Retry API request 4/10: Try again
2021/03/27 00:14:36 DEBUG : *go-mega*: Retry API request 5/10: Try again
2021/03/27 00:14:37 DEBUG : *go-mega*: Retry API request 6/10: Try again
2021/03/27 00:14:37 DEBUG : *go-mega*: Retry API request 7/10: Try again
2021/03/27 00:14:38 DEBUG : *go-mega*: Retry API request 8/10: Try again
2021/03/27 00:14:40 DEBUG : *go-mega*: Retry API request 9/10: Try again
2021/03/27 00:14:43 DEBUG : *go-mega*: Retry API request 10/10: Try again
2021/03/27 00:14:48 Failed to create file system for "mega:": couldn't login: Try again
``` 
What is weird is it worked just a day ago and I could move 400GB of data. Then it got to this... so I dumped the server I was using... moved to new a server, new IP and yet this error continues.

I have read over most of these threads, but do not understand where to start. I have a payed account with MAGA, and it is far from being full.

**Comment by Llewellynvdm** [comment] 2021-03-27 00:34
Just found this... https://github.com/rclone/rclone/commit/cff85f0b9551881be535a4847b56742451e6b476

Makes sense, clearly I must have hit that limit..

> Just as a note: I used `rclone sync` to move data from dropbox to mega, and got blocked.

**Comment by ivandeex** [comment] 2021-03-28 22:31
Guys! The original requested issue was resolved years ago.
Please open new tickets, don't post on this stale thread!
