### ISSUE TITLE
issue with upload to onedrive for business

### ISSUE THREAD

**Issue by putiyeb** [ncw/rclone#1676] opened 2017-09-13 02:24 UTC
> What is your rclone version (eg output from `rclone -V`)

rclone-v1.37-130-gf91f89d4β

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu amd64

> Which cloud storage system are you using? (eg Google Drive)

onedrive for business

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

./rclone copy *.zip od:

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
2017/09/13 00:57:31 DEBUG : rclone: Version "v1.37-130-gf91f89d4β" starting with parameters ["./rclone" "-vv" "copy" "rclone-v1.37-130-gf91f89d4β-linux-amd64.zip" "od:"]
2017/09/13 00:57:32 Failed to create file system for "od:": failed to get root: unauthenticated: Must be authenticated to use '/drive' syntax
```

**Comment by ncw** [comment] 2017-09-13 08:25
What does your config file look like?  Can you paste the `od` section (without the token please).  Does it have a `resource_url` set it in?  Eg

```
[onedrive-dm]
type = onedrive
client_id = 
client_secret = 
token = XXX
resource_url = https://XXX-my.sharepoint.com/
```

Can you make a new remote with `rclone config` to reproduce the problem please?  Then paste the `rclone config` session here (redact the token)

@olihey any other ideas?

**Comment by olihey** [comment] 2017-09-13 08:33
Well, OneDrive for Business should actually not use a endpoint with `/drive`. It should use `*_api/v2.0/drives/me`.

@putiyeb : Have you selected "Business" (b) when you created the FS using rclone config

**Comment by zenjabba** [comment] 2017-09-14 23:13
I've not had this problem at all, we moved 5tb into OneDrive before it filled up.

**Comment by putiyeb** [comment] 2017-09-15 12:20
Yeah, Testing in VPS , the config file will miss the `**resource_url**`. The authentication process:
```
Use auto config?
 * Say Y if not sure
 * Say N if you are working on a remote or headless machine
y) Yes
n) No
y/n> n
For this to work, you will need rclone available on a machine that has a web browser available.
Execute the following on your machine:
        rclone authorize "onedrive"
Then paste the result below:
result> {"access_token":"*******,"expiry":"2017-09-15T20:58:06.5255906+08:00"}
```
Can it just paste the `refresh_token`, that can receive in response url in the browser, to authenticate?

**Comment by olihey** [comment] 2017-09-15 12:37
Can you post the entire log when setting up the remote using the "-v -v"?

**Comment by ncw** [comment] 2017-09-15 13:03
@olihey the user is using [rclone authorize](https://rclone.org/remote_setup/#configuring-using-rclone-authorize) -  I don't think that is going to work because it doesn't pass the `resource_url`.

A work-around is to use the [copying the config method](https://rclone.org/remote_setup/#configuring-by-copying-the-config-file)

We could document that it doesn't work, or think about upgrading `rclone authorize` a bit.

What we need to do is add a `--resource-url` parameter to the authorize command, and get the oauthutil code to add that to the suggested command line.

I note that it should really put client_id and client_secret in the command line too.

**Comment by olihey** [comment] 2017-09-15 13:18
The resource_url is queried AFTER the authorization:
```Storage> 13
Microsoft App Client Id - leave blank normally.
client_id>
Microsoft App Client Secret - leave blank normally.
client_secret>
Remote config
Choose OneDrive account type?
 * Say b for a OneDrive business account
 * Say p for a personal OneDrive account
b) Business
p) Personal
b/p> b
Use auto config?
 * Say Y if not sure
 * Say N if you are working on a remote or headless machine
y) Yes
n) No
y/n> N
For this to work, you will need rclone available on a machine that has a web browser available.
Execute the following on your machine:
        rclone authorize "onedrive"
Then paste the result below:
result> {"access_token":"XXXXXX","token_type":"Bearer","refresh_token":"XXXXX","expiry":"2017-09-15T16:15:00.2628413+02:00"}
2017/09/15 15:15:15 ERROR : Failed to save new token in config file: section 'odb' not found
2017/09/15 15:15:17 INFO  : Skipping API v1.0 endpoint https://raygina-my.sharepoint.com/_api/v1.0/me
2017/09/15 15:15:17 NOTICE: Found API v2.0 endpoint https://raygina-my.sharepoint.com/_api/v2.0/me
2017/09/15 15:15:17 DEBUG : odb: Added new token to config, still needs to be saved
--------------------
[odb]
client_id =
client_secret =
token = {"access_token":"XXXXX","token_type":"Bearer","refresh_token":"XXXXXX","expiry":"2017-09-15T16:15:00.2628413+02:00"}
resource_url = https://raygina-my.sharepoint.com/
```

You can see that the "Found API 2.0 endpoint" happens after the authorization.
It's just very important to select **b** for Business in **both cases** `config` and `authorize`

**Comment by putiyeb** [comment] 2017-09-15 13:58
```
2017/09/15 13:47:14 ERROR : Failed to save new token in config file: section 'od' not found
2017/09/15 13:47:15 ERROR : Failed to query available services: HTTP error 401 (401 Unauthorized) returned body: "{\"error\":{\"code\":\"-2147024891, System.UnauthorizedAccessException\",\"message\":\"Access denied. You do not have permission to perform this action or access this resource.\"}}"
```
I use the token to vps testing from my pc that can login and authorize with a web browser. I think rclone cannot be authorized in vps because the token used by my pc.

**Comment by olihey** [comment] 2017-09-15 14:11
I quickly fired up a mini Google compute instance and I could paste in the token from my Windows PC into the Linux instance and browse my files.
Please post a FULL log.

**Comment by putiyeb** [comment] 2017-09-15 14:35
In my PC 
```
.\rclone.exe config -v -v
2017/09/15 22:29:01 DEBUG : rclone: Version "v1.37-130-gf91f89d4" starting with parameters ["C:\\Users\\rworl\\Desktop\\rclone-v1.37-130-gf91f89d4-windows-amd64\\rclone.exe" "config" "-v" "-v"]
No remotes found - make a new one
n) New remote
s) Set configuration password
q) Quit config
n/s/q> n
name> od
Type of storage to configure.
Choose a number from below, or type in your own value
 1 / Amazon Drive
   \ "amazon cloud drive"
 2 / Amazon S3 (also Dreamhost, Ceph, Minio)
   \ "s3"
 3 / Backblaze B2
   \ "b2"
 4 / Box
   \ "box"
 5 / Dropbox
   \ "dropbox"
 6 / Encrypt/Decrypt a remote
   \ "crypt"
 7 / FTP Connection
   \ "ftp"
 8 / Google Cloud Storage (this is not Google Drive)
   \ "google cloud storage"
 9 / Google Drive
   \ "drive"
10 / Hubic
   \ "hubic"
11 / Local Disk
   \ "local"
12 / Microsoft Azure Blob Storage
   \ "azureblob"
13 / Microsoft OneDrive
   \ "onedrive"
14 / Openstack Swift (Rackspace Cloud Files, Memset Memstore, OVH)
   \ "swift"
15 / QingClound Object Storage
   \ "qingstor"
16 / SSH/SFTP Connection
   \ "sftp"
17 / Yandex Disk
   \ "yandex"
18 / http Connection
   \ "http"
Storage> 13
Microsoft App Client Id - leave blank normally.
client_id>
Microsoft App Client Secret - leave blank normally.
client_secret>
Remote config
Choose OneDrive account type?
 * Say b for a OneDrive business account
 * Say p for a personal OneDrive account
b) Business
p) Personal
b/p> b
Use auto config?
 * Say Y if not sure
 * Say N if you are working on a remote or headless machine
y) Yes
n) No
y/n> y
2017/09/15 22:29:19 DEBUG : Starting auth server on 127.0.0.1:53682
If your browser doesn't open automatically go to the following link: http://127.0.0.1:53682/auth
Log in and authorize rclone for access
Waiting for code...
2017/09/15 22:30:17 DEBUG : Received request on auth server
2017/09/15 22:30:17 DEBUG : Successfully got code
Got code
2017/09/15 22:30:21 DEBUG : od: Added new token to config, still needs to be saved
2017/09/15 22:30:21 DEBUG : Closing auth server
2017/09/15 22:30:21 DEBUG : Closed auth server with error: http: Server closed
2017/09/15 22:30:24 INFO  : Skipping API v1.0 endpoint https://qweictschoolnz-my.sharepoint.com/_api/v1.0/me
2017/09/15 22:30:24 NOTICE: Found API v2.0 endpoint https://qweictschoolnz-my.sharepoint.com/_api/v2.0/me
2017/09/15 22:30:27 DEBUG : od: Added new token to config, still needs to be saved
--------------------
[od]
client_id =
client_secret =
token = {"access_token":"eyJ*****OvLXT81w","token_type":"Bearer","refresh_token":"AQABAAAAAAA****AA","expiry":"2017-09-15T23:30:20.5484754+08:00"}
resource_url = https://****-my.sharepoint.com/
--------------------
```

In VPS
```
./rclone config -v -v
2017/09/15 14:27:43 DEBUG : rclone: Version "v1.37-130-gf91f89d4β" starting with parameters ["./rclone" "config" "-v" "-v"]
No remotes found - make a new one
n) New remote
s) Set configuration password
q) Quit config
n/s/q> n
name> od
Type of storage to configure.
Choose a number from below, or type in your own value
 1 / Amazon Drive
   \ "amazon cloud drive"
 2 / Amazon S3 (also Dreamhost, Ceph, Minio)
   \ "s3"
 3 / Backblaze B2
   \ "b2"
 4 / Box
   \ "box"
 5 / Dropbox
   \ "dropbox"
 6 / Encrypt/Decrypt a remote
   \ "crypt"
 7 / FTP Connection
   \ "ftp"
 8 / Google Cloud Storage (this is not Google Drive)
   \ "google cloud storage"
 9 / Google Drive
   \ "drive"
10 / Hubic
   \ "hubic"
11 / Local Disk
   \ "local"
12 / Microsoft Azure Blob Storage
   \ "azureblob"
13 / Microsoft OneDrive
   \ "onedrive"
14 / Openstack Swift (Rackspace Cloud Files, Memset Memstore, OVH)
   \ "swift"
15 / QingClound Object Storage
   \ "qingstor"
16 / SSH/SFTP Connection
   \ "sftp"
17 / Yandex Disk
   \ "yandex"
18 / http Connection
   \ "http"
Storage> 13
Microsoft App Client Id - leave blank normally.
client_id> 
Microsoft App Client Secret - leave blank normally.
client_secret> 
Remote config
Choose OneDrive account type?
 * Say b for a OneDrive business account
 * Say p for a personal OneDrive account
b) Business
p) Personal
b/p> b
Use auto config?
 * Say Y if not sure
 * Say N if you are working on a remote or headless machine
y) Yes
n) No
y/n> n
For this to work, you will need rclone available on a machine that has a web browser available.
Execute the following on your machine:
        rclone authorize "onedrive"
Then paste the result below:
result> {"access_token":"eyJ*****OvLXT81w","token_type":"Bearer","refresh_token":"AQABAAAAAAA****AA","expiry":"2017-09-15T23:30:20.5484754+08:00"}
2017/09/15 14:30:49 ERROR : Failed to save new token in config file: section 'od' not found
2017/09/15 14:30:50 ERROR : Failed to query available services: HTTP error 401 (401 Unauthorized) returned body: "{\"error\":{\"code\":\"-2147024891, System.UnauthorizedAccessException\",\"message\":\"Access denied. You do not have permission to perform this action or access this resource.\"}}"
--------------------
[od]
client_id = 
client_secret = 
token = {"access_token":"eyJ*****OvLXT81w","token_type":"Bearer","refresh_token":"AQABAAAAAAA****AA","expiry":"2017-09-15T23:30:20.5484754+08:00"}
--------------------
y) Yes this is OK
e) Edit this remote
d) Delete this remote
```

**Comment by olihey** [comment] 2017-09-15 14:44
You can't do it that way. If you want to copy the remote from one machine to another, just copy the section directly from the `~/.rclone.conf`.

The token that is displayed at the end of the first config is the token for your specific resource (resource_url) and can only be used with that resource. When you use this in the VPS as you do it fails when querying the resource.

**Comment by putiyeb** [comment] 2017-09-15 15:07
Yeah, Is it possible to just use the `refresh_token` to finish authorizing?
This project(https://github.com/fkalis/bash-onedrive-upload) can authorize by using `refresh_token`. 
The `refresh_token` is easy to use for vps.

**Comment by olihey** [comment] 2017-09-15 15:15
Nope, the refresh token is as the access token only for the resource.
You use `rclone authorize "onedrive"` on your NON-VPS to get the initial token to setup the remote on the VPS.

**Comment by ncw** [comment] 2017-09-15 16:16
@olihey wrote:
> The resource_url is queried AFTER the authorization

I should have tried that for myself! That will teach me just to read the code ;-)  Sorry for the noise.

**Comment by ncw** [comment] 2017-09-17 09:13
I'm going to close this now as I think we've got to the bottom of the problem.

**Closed by ncw** 2017-09-17 09:13 UTC

**Comment by hi2u** [comment] 2017-10-24 06:58
This seems to be the only place I see people mentioning resource_url...

I'm trying to connect to a SharePoint team site, such as: https://orgname.sharepoint.com/sites/Site-Name

Does anyone know if this is possible?  I've tried changed rclone.conf in a number of different ways, and reauthorizing etc.  But I can't get it to connect to anything aside from the default https://orgname-my.sharepoint.com/

Any other resource_url settings give me the error:

`Failed to create file system for "sptest:": failed to get root: 401 Unauthorized:`

**Comment by luisfavila** [comment] 2018-05-12 22:33
@hi2u Did you get it working with another resource_url?
